
SET ROOTDEV=C:
SET ROOTDIR=\Apache\GSoC-2012

SET XERCESCROOT=%ROOTDEV%%ROOTDIR%\XERCESCPKG-31-VC100

SET XALANCROOT=%ROOTDEV%%ROOTDIR%\XALANCPKG-11-31-VC100

SET XERCESCSRC=%ROOTDEV%ROOTDIR%\xerces-src-31\src

SET XALANCSRC=%ROOTDEV%%ROOTDIR%\xalan-src-11\c\src

SET INCLUDE=%INCLUDE%;%XERCESCROOT%\include;%XALANCROOT%\include
SET LIB=%LIB%;%XERCESCROOT%\lib;%XALANCROOT%\lib;$(SolutionDir)..\..\lib
SET PATH=%PATH%;%XERCESCROOT%\bin;%XALANCROOT%\bin;$(SolutionDir)..\..\bin

CALL "%VS100COMNTOOLS%\vsvars32.bat"

devenv -useenv VC10\GSOC-2.sln


