#if !defined(XALAN_DOM_DEFINITIONS)
#define XALAN_DOM_DEFINITIONS



#include <Include/PlatformDefinitions.hpp>



#if defined(XALAN_DOM_BUILD_DLL)

#define XALAN_DOM_EXPORT XALAN_PLATFORM_EXPORT

#define XALAN_DOM_EXPORT_FUNCTION(T) XALAN_PLATFORM_EXPORT_FUNCTION(T)

#else

#define XALAN_DOM_EXPORT XALAN_PLATFORM_IMPORT

#define XALAN_DOM_EXPORT_FUNCTION(T) XALAN_PLATFORM_IMPORT_FUNCTION(T)

#endif



#endif
