Xalan-C++ API Reference: xalanc::XalanDeque< Type, ConstructionTraits > Class Template Reference
xalanc::XalanDeque< Type, ConstructionTraits > Class Template Reference
Xalan implementation of deque.
#include <xalanc/Include/XalanDeque.hpp>
Public Types
typedef size_t size_type
typedef Type value_type
typedef Type & reference
typedef XalanVector< Type, ConstructionTraits > BlockType
typedef XalanVector< BlockType * > BlockIndexType
typedef XalanDeque< Type, ConstructionTraits > ThisType
typedef XalanDequeIterator< XalanDequeIteratorTraits< value_type >, ThisType > iterator
typedef XalanDequeIterator< XalanDequeConstIteratorTraits< value_type >, ThisType > const_iterator
typedef std::reverse_iterator< iterator > reverse_iterator_
typedef std::reverse_iterator< const_iterator > const_reverse_iterator_
typedef reverse_iterator_ reverse_iterator
typedef const_reverse_iterator_ const_reverse_iterator
typedef ConstructionTraits::Constructor Constructor
typedef Constructor::ConstructableType ConstructableType
Public Member Functions
XalanDeque (MemoryManager &memoryManager, size_type initialSize=0, size_type blockSize=10)
XalanDeque (const XalanDeque &theRHS, MemoryManager &theMemoryManager)
~XalanDeque ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
const_reverse_iterator rbegin () const
const_reverse_iterator rend () const
bool empty () const
size_type size () const
value_type & back ()
value_type & operator[] (size_type index)
const value_type & operator[] (size_type index) const
void clear ()
void push_back (const value_type &value)
void pop_back ()
void resize (size_type newSize)
void swap (XalanDeque &theRHS)
XalanDeque & operator= (const XalanDeque &theRHS)
MemoryManager & getMemoryManager ()
Static Public Member Functions
static XalanDeque * create (MemoryManager &theManager, size_type initialSize=0, size_type blockSize=10)
Public Attributes
const typedef Type & const_reference
Detailed Description
template<class Type, class ConstructionTraits = MemoryManagedConstructionTraits<Type>>
class xalanc::XalanDeque< Type, ConstructionTraits >
Xalan implementation of deque.
Definition at line 200 of file XalanDeque.hpp.
Member Typedef Documentation
BlockIndexType
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef XalanVector<BlockType*> xalanc::XalanDeque< Type, ConstructionTraits >::BlockIndexType
Definition at line 211 of file XalanDeque.hpp.
BlockType
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef XalanVector<Type, ConstructionTraits> xalanc::XalanDeque< Type, ConstructionTraits >::BlockType
Definition at line 210 of file XalanDeque.hpp.
const_iterator
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef XalanDequeIterator<XalanDequeConstIteratorTraits<value_type>, ThisType> xalanc::XalanDeque< Type, ConstructionTraits >::const_iterator
Definition at line 216 of file XalanDeque.hpp.
const_reverse_iterator
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef const_reverse_iterator_ xalanc::XalanDeque< Type, ConstructionTraits >::const_reverse_iterator
Definition at line 222 of file XalanDeque.hpp.
const_reverse_iterator_
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef std::reverse_iterator<const_iterator> xalanc::XalanDeque< Type, ConstructionTraits >::const_reverse_iterator_
Definition at line 219 of file XalanDeque.hpp.
ConstructableType
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef Constructor::ConstructableType xalanc::XalanDeque< Type, ConstructionTraits >::ConstructableType
Definition at line 225 of file XalanDeque.hpp.
Constructor
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef ConstructionTraits::Constructor xalanc::XalanDeque< Type, ConstructionTraits >::Constructor
Definition at line 224 of file XalanDeque.hpp.
iterator
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef XalanDequeIterator<XalanDequeIteratorTraits<value_type>, ThisType> xalanc::XalanDeque< Type, ConstructionTraits >::iterator
Definition at line 215 of file XalanDeque.hpp.
reference
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef Type& xalanc::XalanDeque< Type, ConstructionTraits >::reference
Definition at line 207 of file XalanDeque.hpp.
reverse_iterator
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef reverse_iterator_ xalanc::XalanDeque< Type, ConstructionTraits >::reverse_iterator
Definition at line 221 of file XalanDeque.hpp.
reverse_iterator_
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef std::reverse_iterator<iterator> xalanc::XalanDeque< Type, ConstructionTraits >::reverse_iterator_
Definition at line 218 of file XalanDeque.hpp.
size_type
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef size_t xalanc::XalanDeque< Type, ConstructionTraits >::size_type
Definition at line 204 of file XalanDeque.hpp.
ThisType
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef XalanDeque<Type, ConstructionTraits> xalanc::XalanDeque< Type, ConstructionTraits >::ThisType
Definition at line 213 of file XalanDeque.hpp.
value_type
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef Type xalanc::XalanDeque< Type, ConstructionTraits >::value_type
Definition at line 206 of file XalanDeque.hpp.
Constructor & Destructor Documentation
XalanDeque() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> xalanc::XalanDeque< Type, ConstructionTraits >::XalanDeque (MemoryManager & memoryManager, size_type initialSize = 0, size_type blockSize = 10) inline
Definition at line 227 of file XalanDeque.hpp.
XalanDeque() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> xalanc::XalanDeque< Type, ConstructionTraits >::XalanDeque (const XalanDeque< Type, ConstructionTraits > & theRHS, MemoryManager & theMemoryManager) inline
Definition at line 248 of file XalanDeque.hpp.
~XalanDeque()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> xalanc::XalanDeque< Type, ConstructionTraits >::~XalanDeque () inline
Definition at line 282 of file XalanDeque.hpp.
Member Function Documentation
back()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> value_type& xalanc::XalanDeque< Type, ConstructionTraits >::back () inline
Definition at line 346 of file XalanDeque.hpp.
begin() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> iterator xalanc::XalanDeque< Type, ConstructionTraits >::begin () inline
Definition at line 290 of file XalanDeque.hpp.
Referenced by xalanc::XalanDeque< XercesBridgeNavigator >::operator=(), and xalanc::XalanDeque< XercesBridgeNavigator >::XalanDeque().
begin() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const_iterator xalanc::XalanDeque< Type, ConstructionTraits >::begin () const inline
Definition at line 296 of file XalanDeque.hpp.
clear()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanDeque< Type, ConstructionTraits >::clear () inline
Definition at line 368 of file XalanDeque.hpp.
create()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> static XalanDeque* xalanc::XalanDeque< Type, ConstructionTraits >::create (MemoryManager & theManager, size_type initialSize = 0, size_type blockSize = 10) inline static
Definition at line 267 of file XalanDeque.hpp.
empty()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> bool xalanc::XalanDeque< Type, ConstructionTraits >::empty () const inline
Definition at line 326 of file XalanDeque.hpp.
end() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> iterator xalanc::XalanDeque< Type, ConstructionTraits >::end () inline
Definition at line 302 of file XalanDeque.hpp.
Referenced by xalanc::XalanDeque< XercesBridgeNavigator >::operator=(), and xalanc::XalanDeque< XercesBridgeNavigator >::XalanDeque().
end() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const_iterator xalanc::XalanDeque< Type, ConstructionTraits >::end () const inline
Definition at line 308 of file XalanDeque.hpp.
getMemoryManager()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> MemoryManager& xalanc::XalanDeque< Type, ConstructionTraits >::getMemoryManager () inline
Definition at line 463 of file XalanDeque.hpp.
operator=()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> XalanDeque& xalanc::XalanDeque< Type, ConstructionTraits >::operator= (const XalanDeque< Type, ConstructionTraits > & theRHS) inline
Definition at line 444 of file XalanDeque.hpp.
operator[]() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> value_type& xalanc::XalanDeque< Type, ConstructionTraits >::operator[] (size_type index) inline
Definition at line 352 of file XalanDeque.hpp.
operator[]() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const value_type& xalanc::XalanDeque< Type, ConstructionTraits >::operator[] (size_type index) const inline
Definition at line 360 of file XalanDeque.hpp.
pop_back()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanDeque< Type, ConstructionTraits >::pop_back () inline
Definition at line 397 of file XalanDeque.hpp.
push_back()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanDeque< Type, ConstructionTraits >::push_back (const value_type & value) inline
Definition at line 385 of file XalanDeque.hpp.
rbegin()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const_reverse_iterator xalanc::XalanDeque< Type, ConstructionTraits >::rbegin () const inline
Definition at line 314 of file XalanDeque.hpp.
rend()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const_reverse_iterator xalanc::XalanDeque< Type, ConstructionTraits >::rend () const inline
Definition at line 320 of file XalanDeque.hpp.
resize()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanDeque< Type, ConstructionTraits >::resize (size_type newSize) inline
Definition at line 412 of file XalanDeque.hpp.
size()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> size_type xalanc::XalanDeque< Type, ConstructionTraits >::size () const inline
Definition at line 332 of file XalanDeque.hpp.
swap()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanDeque< Type, ConstructionTraits >::swap (XalanDeque< Type, ConstructionTraits > & theRHS) inline
Definition at line 433 of file XalanDeque.hpp.
Member Data Documentation
const_reference
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const typedef Type& xalanc::XalanDeque< Type, ConstructionTraits >::const_reference
Definition at line 208 of file XalanDeque.hpp.
The documentation for this class was generated from the following file:
xalanc/Include/XalanDeque.hpp