Xalan-C++ API Reference: xalanc::XalanFormatterWriter::NewLineWriterFunctor< WriterType > Class Template Reference
xalanc::XalanFormatterWriter::NewLineWriterFunctor< WriterType > Class Template Reference
#include <xalanc/XMLSupport/XalanFormatterWriter.hpp>
Public Types
typedef WriterType writer_type
Public Member Functions
NewLineWriterFunctor (WriterType &writer)
void operator() ()
Detailed Description
template<class WriterType>
class xalanc::XalanFormatterWriter::NewLineWriterFunctor< WriterType >
Definition at line 52 of file XalanFormatterWriter.hpp.
Member Typedef Documentation
writer_type
template<class WriterType > typedef WriterType xalanc::XalanFormatterWriter::NewLineWriterFunctor< WriterType >::writer_type
Definition at line 56 of file XalanFormatterWriter.hpp.
Constructor & Destructor Documentation
NewLineWriterFunctor()
template<class WriterType > xalanc::XalanFormatterWriter::NewLineWriterFunctor< WriterType >::NewLineWriterFunctor (WriterType & writer) inline
Definition at line 58 of file XalanFormatterWriter.hpp.
References xalanc::XalanOutputStream::getNewlineString(), and xalanc::length().
Member Function Documentation
operator()()
template<class WriterType > void xalanc::XalanFormatterWriter::NewLineWriterFunctor< WriterType >::operator() () inline
Definition at line 80 of file XalanFormatterWriter.hpp.
References xalanc::length().
The documentation for this class was generated from the following file:
xalanc/XMLSupport/XalanFormatterWriter.hpp