Xalan-C++ API Reference: xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion > Class Template Reference
xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion > Class Template Reference
FormatterToXMLUnicode formats SAX-style events into XML.
#include <xalanc/XMLSupport/FormatterToXMLUnicode.hpp>
Public Types
enum { eDefaultIndentAmount = 0 }
typedef UnicodeWriter::value_type value_type
Public Types inherited from xalanc::XalanXMLSerializerBase
enum { eBufferSize = 512 }
enum {
eNone = 0u, eAttr = 1u, eBoth = 2u, eForb = 4u,
eCRFb = 5u
}
typedef XalanVector< bool > BoolStackType
Public Types inherited from xalanc::FormatterListener
enum eFormat {
OUTPUT_METHOD_NONE = 0, OUTPUT_METHOD_XML = 1, OUTPUT_METHOD_HTML = 2, OUTPUT_METHOD_TEXT = 3,
OUTPUT_METHOD_DOM = 4, OUTPUT_METHOD_OTHER = 5
}
enum eXMLVersion { XML_VERSION_1_0 = 0, XML_VERSION_1_1 = 1 }
typedef xercesc::DocumentHandler ParentType
typedef XalanSize_t size_type
Public Member Functions
FormatterToXMLUnicode (MemoryManager &theManager, Writer &writer, const XalanDOMString &encoding, const XalanDOMString &doctypeSystem=s_emptyString, const XalanDOMString &doctypePublic=s_emptyString, bool xmlDecl=true, const XalanDOMString &standalone=s_emptyString, size_type indent=eDefaultIndentAmount)
Constructor.
virtual ~FormatterToXMLUnicode ()
Writer * getWriter () const
virtual void endDocument ()
virtual void startElement (const XMLCh *const name, AttributeList &attrs)
virtual void endElement (const XMLCh *const name)
virtual void charactersRaw (const XMLCh *const chars, const size_type length)
Receive notification of character data.
virtual void entityReference (const XMLCh *const name)
Receive notification of a entityReference.
virtual void comment (const XMLCh *const data)
Called when a Comment is to be constructed.
Public Member Functions inherited from xalanc::XalanXMLSerializerBase
XalanXMLSerializerBase (MemoryManager &theManager, eXMLVersion theXMLVersion, const XalanDOMString &theEncoding, const XalanDOMString &theDoctypeSystem, const XalanDOMString &theDoctypePublic, bool xmlDecl, const XalanDOMString &theStandalone)
Constructor.
virtual ~XalanXMLSerializerBase ()
MemoryManager & getMemoryManager ()
virtual void setDocumentLocator (const Locator *const locator)
virtual void startDocument ()
virtual void characters (const XMLCh *const chars, const size_type length)
virtual void charactersRaw (const XMLCh *const chars, const size_type length)=0
virtual void ignorableWhitespace (const XMLCh *const chars, const size_type length)
virtual void processingInstruction (const XMLCh *const target, const XMLCh *const data)
virtual void resetDocument ()
virtual void cdata (const XMLCh *const ch, const size_type length)
virtual const XalanDOMString & getDoctypeSystem () const
virtual const XalanDOMString & getDoctypePublic () const
virtual const XalanDOMString & getEncoding () const
const XalanDOMString & getVersion () const
const XalanDOMString & getStandalone () const
bool getShouldWriteXMLHeader () const
void setShouldWriteXMLHeader (bool b)
Public Member Functions inherited from xalanc::FormatterListener
FormatterListener (eFormat theFormat)
virtual ~FormatterListener ()
eFormat getOutputFormat () const
Get the output format for the instance.
eXMLVersion getXMLVersion () const
Get the version of XML the FormatterListener is generating.
bool isXML1_1Version () const
Determine if the version of XML output is 1.1.
const PrefixResolver * getPrefixResolver () const
Get the PrefixResolver for the FormatterListener.
void setPrefixResolver (const PrefixResolver *thePrefixResolver)
Set the PrefixResolver for the FormatterListener.
virtual void cdata (const XMLCh *const ch, const size_type length)=0
Receive notification of cdata.
virtual void characters (const XMLCh *const chars, const size_type length)=0
virtual void ignorableWhitespace (const XMLCh *const chars, const size_type length)=0
virtual const XalanDOMString & getMediaType () const
virtual int getIndent () const
Static Public Member Functions
static FormatterToXMLUnicode * create (MemoryManager &theManager, Writer &writer, const XalanDOMString &encoding, const XalanDOMString &doctypeSystem=s_emptyString, const XalanDOMString &doctypePublic=s_emptyString, bool xmlDecl=true, const XalanDOMString &standalone=s_emptyString, size_type indent=eDefaultIndentAmount)
Static Public Member Functions inherited from xalanc::XalanXMLSerializerBase
static void initialize (MemoryManager &theManager)
Perform static initialization.
static void terminate ()
Perform static shut down.
Protected Member Functions
virtual void flushBuffer ()
virtual void flushWriter ()
virtual void writeXMLHeader ()
void writeDoctypeDecl (const XalanDOMChar *name)
void writeProcessingInstruction (const XMLCh *target, const XMLCh *data)
void writeCharacters (const XMLCh *chars, size_type length)
void writeCDATA (const XMLCh *chars, size_type length)
void outputNewline ()
Output a line break.
void writeDefaultEscape (XalanDOMChar ch)
Escape and write a character.
void writeDefaultAttributeEscape (XalanDOMChar ch)
Escape and write a character in an attribute.
bool writeDefaultEntity (XalanDOMChar ch)
Handle one of the default entities, return false if it is not a default entity.
bool writeDefaultAttributeEntity (XalanDOMChar ch)
Handle one of the default entities, return false if it is not a default entity.
void writeParentTagEnd ()
Check to see if a parent's ">" has been written, and, if it has not, write it.
size_type writeNormalizedChar (XalanDOMChar ch, const XalanDOMChar chars[], size_type start, size_type length)
Write a normalized character to the stream.
void writeNumericCharacterReference (XMLUInt32 theNumber)
size_type writeNormalizedCharBig (const XalanDOMChar chars[], size_type start, size_type length)
void writeCDATAChars (const XalanDOMChar chars[], size_type length, bool &outsideCDATA)
Write characters for a CDATA section.
void writeAttrString (const XalanDOMChar *theString, size_type theStringLength)
Write an attribute string.
Protected Member Functions inherited from xalanc::XalanXMLSerializerBase
virtual void writeCharacters (const XMLCh *chars, size_type length)=0
virtual void writeCDATA (const XMLCh *chars, size_type length)=0
bool markParentForChildren ()
Mark the parent element as having a child.
bool getNeedToOutputDoctypeDecl () const
Determine if it a DOCTYPE declaration needs to be written.
void openElementForChildren ()
Open an element for possibile children.
bool outsideDocumentElement () const
bool childNodesWereAdded ()
Determine if an element ever had any children added.
void generateDoctypeDecl (const XalanDOMChar *name)
Protected Member Functions inherited from xalanc::FormatterListener
void setXMLVersion (eXMLVersion theVersion)
Set the output version during serializing.
Additional Inherited Members
Static Public Attributes inherited from xalanc::XalanXMLSerializerBase
static const XalanDOMString & s_1_0String
static const XalanDOMString & s_1_1String
Static Public Attributes inherited from xalanc::FormatterListener
static const XalanDOMChar s_piTarget []
static const XalanDOMChar s_piData []
static const XalanDOMString::size_type s_piTargetLength
static const XalanDOMString::size_type s_piDataLength
Static Protected Member Functions inherited from xalanc::XalanXMLSerializerBase
static bool isUTF16HighSurrogate (XalanDOMChar theChar)
static bool isUTF16LowSurrogate (XalanDOMChar theChar)
static XalanUnicodeChar decodeUTF16SurrogatePair (XalanDOMChar theHighSurrogate, XalanDOMChar theLowSurrogate, MemoryManager &theManager)
static void throwInvalidUTF16SurrogateException (XalanDOMChar ch, MemoryManager &theManager)
Throw an exception when an invalid surrogate is encountered.
static void throwInvalidUTF16SurrogateException (XalanDOMChar ch, XalanDOMChar next, MemoryManager &theManager)
Throw an exception when an invalid surrogate is encountered.
static void throwInvalidCharacterException (XalanUnicodeChar ch, MemoryManager &theManager)
Throw an exception when an invalid character is encountered.
static void throwInvalidXMLCharacterException (XalanUnicodeChar ch, const XalanDOMString &theXMLversion, MemoryManager &theManager)
Throw an exception when an invalid character for the specific XML version is encountered.
Protected Attributes inherited from xalanc::XalanXMLSerializerBase
bool m_nextIsRaw
Tell if the next text should be raw.
bool m_spaceBeforeClose
Add space before '/>' for XHTML.
const XalanDOMString m_doctypeSystem
The System ID for the doc type.
const XalanDOMString m_doctypePublic
The public ID for the doc type.
const XalanDOMString & m_version
Tells the XML version, for writing out to the XML decl.
const XalanDOMString m_standalone
Text for standalone part of header.
const XalanDOMString m_encoding
Protected Attributes inherited from xalanc::FormatterListener
const PrefixResolver * m_prefixResolver
Static Protected Attributes inherited from xalanc::FormatterListener
static const XalanDOMString s_emptyString
Detailed Description
template<class UnicodeWriter, class ConstantsType, class CharPredicate, class IndentHandler, FormatterListener::eXMLVersion XMLVersion>
class xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >
FormatterToXMLUnicode formats SAX-style events into XML.
Definition at line 57 of file FormatterToXMLUnicode.hpp.
Member Typedef Documentation
value_type
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> typedef UnicodeWriter::value_type xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::value_type
Definition at line 61 of file FormatterToXMLUnicode.hpp.
Member Enumeration Documentation
anonymous enum
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> anonymous enum
Enumerator
eDefaultIndentAmount
Definition at line 63 of file FormatterToXMLUnicode.hpp.
Constructor & Destructor Documentation
FormatterToXMLUnicode()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::FormatterToXMLUnicode (MemoryManager & theManager, Writer & writer, const XalanDOMString & encoding, const XalanDOMString & doctypeSystem = s_emptyString, const XalanDOMString & doctypePublic = s_emptyString, bool xmlDecl = true, const XalanDOMString & standalone = s_emptyString, size_type indent = eDefaultIndentAmount) inline
Constructor.
Parameters
theManager The MemoryManager instance to use for all memory allocations
writer the writer.
version the string to write for the XML version number.
doctypeSystem system identifier to be used in the document type declaration
doctypePublic public identifier to be used in the document type declaration
xmlDecl true if the XSLT processor should output an XML declaration
standalone The string the XSLT processor should output for the standalone document declaration
Definition at line 84 of file FormatterToXMLUnicode.hpp.
~FormatterToXMLUnicode()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> virtual xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::~FormatterToXMLUnicode () inline virtual
Definition at line 142 of file FormatterToXMLUnicode.hpp.
Member Function Documentation
charactersRaw()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> virtual void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::charactersRaw (const XMLCh *const chars, const size_type length) inline virtual
Receive notification of character data.
If available, when the disable-output-escaping attribute is used, output raw text without escaping.
Parameters
chars pointer to characters from the XML document
length number of characters to read from the array
Exceptions
SAXException
Implements xalanc::FormatterListener.
Definition at line 237 of file FormatterToXMLUnicode.hpp.
References xalanc::length().
comment()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> virtual void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::comment (const XMLCh *const data) inline virtual
Called when a Comment is to be constructed.
Parameters
data pointer to comment data
Exceptions
SAXException
Implements xalanc::XalanXMLSerializerBase.
Definition at line 264 of file FormatterToXMLUnicode.hpp.
create()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> static FormatterToXMLUnicode* xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::create (MemoryManager & theManager, Writer & writer, const XalanDOMString & encoding, const XalanDOMString & doctypeSystem = s_emptyString, const XalanDOMString & doctypePublic = s_emptyString, bool xmlDecl = true, const XalanDOMString & standalone = s_emptyString, size_type indent = eDefaultIndentAmount) inline static
Definition at line 110 of file FormatterToXMLUnicode.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
endDocument()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> virtual void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::endDocument () inline virtual
Implements xalanc::FormatterListener.
Definition at line 155 of file FormatterToXMLUnicode.hpp.
endElement()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> virtual void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::endElement (const XMLCh *const name) inline virtual
Implements xalanc::XalanXMLSerializerBase.
Definition at line 201 of file FormatterToXMLUnicode.hpp.
entityReference()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> virtual void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::entityReference (const XMLCh *const name) inline virtual
Receive notification of a entityReference.
Parameters
data pointer to characters from the XML document
Exceptions
SAXException
Implements xalanc::XalanXMLSerializerBase.
Definition at line 250 of file FormatterToXMLUnicode.hpp.
flushBuffer()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> virtual void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::flushBuffer () inline protected virtual
Implements xalanc::XalanXMLSerializerBase.
Definition at line 287 of file FormatterToXMLUnicode.hpp.
flushWriter()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> virtual void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::flushWriter () inline protected virtual
Definition at line 293 of file FormatterToXMLUnicode.hpp.
getWriter()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> Writer* xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::getWriter () const inline virtual
Reimplemented from xalanc::FormatterListener.
Definition at line 147 of file FormatterToXMLUnicode.hpp.
outputNewline()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::outputNewline () inline protected virtual
Output a line break.
Implements xalanc::XalanXMLSerializerBase.
Definition at line 495 of file FormatterToXMLUnicode.hpp.
startElement()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> virtual void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::startElement (const XMLCh *const name, AttributeList & attrs) inline virtual
Implements xalanc::XalanXMLSerializerBase.
Definition at line 167 of file FormatterToXMLUnicode.hpp.
writeAttrString()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeAttrString (const XalanDOMChar * theString, size_type theStringLength) inline protected
Write an attribute string.
Parameters
theString The string to write.
theStringLength The length of the string.
Definition at line 793 of file FormatterToXMLUnicode.hpp.
writeCDATA()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeCDATA (const XMLCh * chars, size_type length) inline protected
Definition at line 463 of file FormatterToXMLUnicode.hpp.
References xalanc::length().
writeCDATAChars()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeCDATAChars (const XalanDOMChar chars[], size_type length, bool & outsideCDATA) inline protected
Write characters for a CDATA section.
Parameters
ch the string to write.
length the length of the string.
Definition at line 710 of file FormatterToXMLUnicode.hpp.
References xalanc::length().
writeCharacters()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeCharacters (const XMLCh * chars, size_type length) inline protected
Definition at line 413 of file FormatterToXMLUnicode.hpp.
References xalanc::length().
writeDefaultAttributeEntity()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> bool xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeDefaultAttributeEntity (XalanDOMChar ch) inline protected
Handle one of the default entities, return false if it is not a default entity.
Definition at line 594 of file FormatterToXMLUnicode.hpp.
writeDefaultAttributeEscape()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeDefaultAttributeEscape (XalanDOMChar ch) inline protected
Escape and write a character in an attribute.
Definition at line 535 of file FormatterToXMLUnicode.hpp.
writeDefaultEntity()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> bool xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeDefaultEntity (XalanDOMChar ch) inline protected
Handle one of the default entities, return false if it is not a default entity.
Definition at line 561 of file FormatterToXMLUnicode.hpp.
writeDefaultEscape()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeDefaultEscape (XalanDOMChar ch) inline protected
Escape and write a character.
Definition at line 504 of file FormatterToXMLUnicode.hpp.
writeDoctypeDecl()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeDoctypeDecl (const XalanDOMChar * name) inline protected virtual
Implements xalanc::XalanXMLSerializerBase.
Definition at line 345 of file FormatterToXMLUnicode.hpp.
writeNormalizedChar()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> size_type xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeNormalizedChar (XalanDOMChar ch, const XalanDOMChar chars[], size_type start, size_type length) inline protected
Write a normalized character to the stream.
Parameters
ch the string to write.
start the start offset into the string.
length the length of the string.
Definition at line 638 of file FormatterToXMLUnicode.hpp.
writeNormalizedCharBig()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> size_type xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeNormalizedCharBig (const XalanDOMChar chars[], size_type start, size_type length) inline protected
Definition at line 679 of file FormatterToXMLUnicode.hpp.
References xalanc::length().
writeNumericCharacterReference()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeNumericCharacterReference (XMLUInt32 theNumber) inline protected
Definition at line 667 of file FormatterToXMLUnicode.hpp.
writeParentTagEnd()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeParentTagEnd () inline protected
Check to see if a parent's ">" has been written, and, if it has not, write it.
Definition at line 619 of file FormatterToXMLUnicode.hpp.
writeProcessingInstruction()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeProcessingInstruction (const XMLCh * target, const XMLCh * data) inline protected virtual
Implements xalanc::XalanXMLSerializerBase.
Definition at line 385 of file FormatterToXMLUnicode.hpp.
writeXMLHeader()
template<class UnicodeWriter , class ConstantsType , class CharPredicate , class IndentHandler , FormatterListener::eXMLVersion XMLVersion> virtual void xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeXMLHeader () inline protected virtual
Implements xalanc::XalanXMLSerializerBase.
Definition at line 299 of file FormatterToXMLUnicode.hpp.
The documentation for this class was generated from the following file:
xalanc/XMLSupport/FormatterToXMLUnicode.hpp