Xalan-C++ API Reference: xalanc::DOMServices Class Reference
xalanc::DOMServices Class Reference
#include <xalanc/DOMSupport/DOMServices.hpp>
Public Types
typedef void(FormatterListener::* MemberFunctionPtr) (const XMLCh *const, const FormatterListener::size_type)
Static Public Member Functions
static void initialize (MemoryManager &theManager)
Initialize static data.
static void terminate ()
Destroy static data.
static void getNodeData (const XalanNode &node, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanNode &node, ExecutionContext &context, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanAttr &attribute, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanComment &comment, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanDocument &document, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanDocument &document, ExecutionContext &context, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanDocumentFragment &documentFragment, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanDocumentFragment &documentFragment, ExecutionContext &context, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanElement &element, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanElement &element, ExecutionContext &context, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanProcessingInstruction &pi, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanText &text, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanText &text, ExecutionContext &context, XalanDOMString &data)
Retrieves data for node.
static void getNodeData (const XalanNode &node, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static void getNodeData (const XalanNode &node, ExecutionContext &context, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static void getNodeData (const XalanAttr &attribute, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static void getNodeData (const XalanComment &comment, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static void getNodeData (const XalanDocument &document, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static void getNodeData (const XalanDocument &document, ExecutionContext &context, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static void getNodeData (const XalanDocumentFragment &documentFragment, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static void getNodeData (const XalanDocumentFragment &documentFragment, ExecutionContext &context, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static void getNodeData (const XalanElement &element, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static void getNodeData (const XalanElement &element, ExecutionContext &context, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static void getNodeData (const XalanProcessingInstruction &pi, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static void getNodeData (const XalanText &text, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static void getNodeData (const XalanText &text, ExecutionContext &context, FormatterListener &formatterListener, MemberFunctionPtr function)
Sends the data for a node to a FormatterListener.
static const XalanDOMString & getNameOfNode (const XalanNode &n)
Retrieve the name of the node, taking into account the differences between the DOM and XSLT data models.
static const XalanDOMString & getNameOfNode (const XalanAttr &attr)
Retrieve the name of the node, taking into account the differences between the DOM and XSLT data models.
static const XalanDOMString & getNameOfNode (const XalanElement &element)
Retrieve the name of the node, taking into account the differences between the DOM and XSLT data models.
static const XalanDOMString & getLocalNameOfNode (const XalanNode &n)
Retrieve local name of node, taking into account the differences between the DOM and XSLT data models.
static const XalanDOMString & getNamespaceOfNode (const XalanNode &n)
Retrieve the namespace of the node, taking into account the differences between the DOM and XSLT data models.
static bool isNamespaceDeclaration (const XalanAttr &n)
Determine whether or not an attribute node is declaring a namespace.
static XalanNode * getParentOfNode (const XalanNode &node)
Retrieve the parent of a node.
static const XalanDOMString * getNamespaceForPrefix (const XalanDOMString &prefix, const XalanElement &namespaceContext)
Retrieve the URI corresponding to a namespace prefix.
static const XalanDOMString * getNamespaceForPrefix (const XalanDOMChar *theName, const PrefixResolver &thePrefixResolver, bool isAttribute, XalanDOMString &thePrefix)
Retrieve the URI corresponding to a namespace prefix, using the supplied name, and PrefixResolver.
static bool isNodeAfter (const XalanNode &node1, const XalanNode &node2)
Determine if a node is after another node, in document order.
static bool isNodeAfterSibling (const XalanNode &parent, const XalanNode &child1, const XalanNode &child2)
Determine if a node is after another node in the sibling list.
Static Public Attributes
static const XalanDOMString & s_XMLString
static const XalanDOMString & s_XMLStringWithSeparator
static const XalanDOMString & s_XMLNamespacePrefix
static const XalanDOMString & s_XMLNamespaceURI
static const XalanDOMString & s_XMLNamespace
static const XalanDOMString & s_XMLNamespaceWithSeparator
static const XalanDOMString & s_XMLNamespaceSeparatorString
static const XalanDOMString & s_XMLNamespacePrefixURI
static const XalanDOMString::size_type & s_XMLStringLength
static const XalanDOMString::size_type & s_XMLStringWithSeparatorLength
static const XalanDOMString::size_type & s_XMLNamespacePrefixLength
static const XalanDOMString::size_type & s_XMLNamespaceURILength
static const XalanDOMString::size_type & s_XMLNamespaceLength
static const XalanDOMString::size_type & s_XMLNamespaceWithSeparatorLength
static const XalanDOMString::size_type & s_XMLNamespaceSeparatorStringLength
static const XalanDOMString::size_type & s_XMLNamespacePrefixURILength
static const XalanDOMString s_emptyString
Friends
void getChildData (const XalanNode *child, XalanDOMString &data)
void getChildData (const XalanNode *child, ExecutionContext &executionContext, XalanDOMString &data)
void getChildData (const XalanNode *child, FormatterListener &formatterListener, DOMServices::MemberFunctionPtr function)
Detailed Description
Definition at line 53 of file DOMServices.hpp.
Member Typedef Documentation
MemberFunctionPtr
typedef void(FormatterListener::* xalanc::DOMServices::MemberFunctionPtr) (const XMLCh *const, const FormatterListener::size_type)
Definition at line 314 of file DOMServices.hpp.
Member Function Documentation
getLocalNameOfNode()
static const XalanDOMString& xalanc::DOMServices::getLocalNameOfNode (const XalanNode & n) inline static
Retrieve local name of node, taking into account the differences between the DOM and XSLT data models.
Parameters
node DOM node whose name is returned
Returns
name of node without namespace
Definition at line 619 of file DOMServices.hpp.
References xalanc::XalanDOMString::empty(), xalanc::XalanNode::getLocalName(), and xalanc::XalanNode::getNodeName().
getNameOfNode() [1/3]
static const XalanDOMString& xalanc::DOMServices::getNameOfNode (const XalanAttr & attr) inline static
Retrieve the name of the node, taking into account the differences between the DOM and XSLT data models.
Parameters
attr DOM attribute node whose name is returned
Returns
name of the node
Definition at line 577 of file DOMServices.hpp.
References xalanc::equals(), xalanc::XalanAttr::getLocalName(), xalanc::XalanAttr::getNodeName(), and xalanc::startsWith().
getNameOfNode() [2/3]
static const XalanDOMString& xalanc::DOMServices::getNameOfNode (const XalanElement & element) inline static
Retrieve the name of the node, taking into account the differences between the DOM and XSLT data models.
Parameters
attr DOM element node whose name is returned
Returns
name of the node
Definition at line 605 of file DOMServices.hpp.
References xalanc::XalanElement::getNodeName().
getNameOfNode() [3/3]
static const XalanDOMString& xalanc::DOMServices::getNameOfNode (const XalanNode & n) static
Retrieve the name of the node, taking into account the differences between the DOM and XSLT data models.
Parameters
node DOM node whose name is returned
Returns
name of the node
getNamespaceForPrefix() [1/2]
static const XalanDOMString* xalanc::DOMServices::getNamespaceForPrefix (const XalanDOMChar * theName, const PrefixResolver & thePrefixResolver, bool isAttribute, XalanDOMString & thePrefix) static
Retrieve the URI corresponding to a namespace prefix, using the supplied name, and PrefixResolver.
The routine also returns the prefix.
Parameters
theName The name that contains the prefix
thePrefixResolver The PrefixResolver to use
isAttribute If true, special rules for attributes are used
thePrefix The prefix
Returns
URI corresponding to namespace
getNamespaceForPrefix() [2/2]
static const XalanDOMString* xalanc::DOMServices::getNamespaceForPrefix (const XalanDOMString & prefix, const XalanElement & namespaceContext) static
Retrieve the URI corresponding to a namespace prefix.
Parameters
prefix prefix for a namespace
namespaceContext DOM element representing the context for namespace
Returns
URI corresponding to namespace
getNamespaceOfNode()
static const XalanDOMString& xalanc::DOMServices::getNamespaceOfNode (const XalanNode & n) static
Retrieve the namespace of the node, taking into account the differences between the DOM and XSLT data models.
Parameters
node DOM node whose namespace is returned
Returns
namespace of the node
getNodeData() [1/26]
static void xalanc::DOMServices::getNodeData (const XalanAttr & attribute, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Sends the data for a node to a FormatterListener.
Parameters
attribute DOM node whose data is to be returned
formatterListener the FormatterListener instance to receive the data
fRaw Whether or not the data should be sent raw.
Definition at line 362 of file DOMServices.hpp.
References xalanc::XalanAttr::getNodeValue().
getNodeData() [2/26]
static void xalanc::DOMServices::getNodeData (const XalanAttr & attribute, XalanDOMString & data) inline static
Retrieves data for node.
Parameters
attribute DOM node whose data is to be returned
data a string to which the node's data will be appended
Definition at line 138 of file DOMServices.hpp.
References xalanc::XalanDOMString::append(), and xalanc::XalanAttr::getNodeValue().
getNodeData() [3/26]
static void xalanc::DOMServices::getNodeData (const XalanComment & comment, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Sends the data for a node to a FormatterListener.
Parameters
comment DOM node whose data is to be returned
formatterListener the FormatterListener instance to receive the data
fRaw Whether or not the data should be sent raw.
Definition at line 378 of file DOMServices.hpp.
References xalanc::XalanComment::getData().
getNodeData() [4/26]
static void xalanc::DOMServices::getNodeData (const XalanComment & comment, XalanDOMString & data) inline static
Retrieves data for node.
Parameters
comment DOM node whose data is to be returned
data a string to which the node's data will be appended
Definition at line 154 of file DOMServices.hpp.
References xalanc::XalanDOMString::append(), and xalanc::XalanComment::getData().
getNodeData() [5/26]
static void xalanc::DOMServices::getNodeData (const XalanDocument & document, ExecutionContext & context, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Sends the data for a node to a FormatterListener.
Parameters
node DOM node whose data is to be returned
context The current execution context
formatterListener the FormatterListener instance to receive the data
function A pointer to the member function of FormatterListener to call
Definition at line 408 of file DOMServices.hpp.
References xalanc::ExecutionContext::hasPreserveOrStripSpaceConditions().
getNodeData() [6/26]
static void xalanc::DOMServices::getNodeData (const XalanDocument & document, ExecutionContext & context, XalanDOMString & data) inline static
Retrieves data for node.
Parameters
document The DOM node whose data is to be returned
context The current execution context
data a string to which the node's data will be appended
Definition at line 180 of file DOMServices.hpp.
References xalanc::ExecutionContext::hasPreserveOrStripSpaceConditions().
getNodeData() [7/26]
static void xalanc::DOMServices::getNodeData (const XalanDocument & document, FormatterListener & formatterListener, MemberFunctionPtr function) static
Sends the data for a node to a FormatterListener.
Parameters
document DOM node whose data is to be returned
formatterListener the FormatterListener instance to receive the data
fRaw Whether or not the data should be sent raw.
getNodeData() [8/26]
static void xalanc::DOMServices::getNodeData (const XalanDocument & document, XalanDOMString & data) static
Retrieves data for node.
Parameters
document DOM node whose data is to be returned
data a string to which the node's data will be appended
getNodeData() [9/26]
static void xalanc::DOMServices::getNodeData (const XalanDocumentFragment & documentFragment, ExecutionContext & context, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Sends the data for a node to a FormatterListener.
Parameters
documentFragment DOM node whose data is to be sent
context The current execution context
formatterListener the FormatterListener instance to receive the data
fRaw Whether or not the data should be sent raw.
Definition at line 446 of file DOMServices.hpp.
References xalanc::ExecutionContext::hasPreserveOrStripSpaceConditions().
getNodeData() [10/26]
static void xalanc::DOMServices::getNodeData (const XalanDocumentFragment & documentFragment, ExecutionContext & context, XalanDOMString & data) inline static
Retrieves data for node.
Parameters
documentFragment The DOM node whose data is to be returned
context The current execution context
data a string to which the node's data will be appended
Definition at line 214 of file DOMServices.hpp.
References xalanc::ExecutionContext::hasPreserveOrStripSpaceConditions().
getNodeData() [11/26]
static void xalanc::DOMServices::getNodeData (const XalanDocumentFragment & documentFragment, FormatterListener & formatterListener, MemberFunctionPtr function) static
Sends the data for a node to a FormatterListener.
Parameters
documentFragment DOM node whose data is to be sent
formatterListener the FormatterListener instance to receive the data
fRaw Whether or not the data should be sent raw.
getNodeData() [12/26]
static void xalanc::DOMServices::getNodeData (const XalanDocumentFragment & documentFragment, XalanDOMString & data) static
Retrieves data for node.
Parameters
documentFragment The DOM node whose data is to be returned
data a string to which the node's data will be appended
getNodeData() [13/26]
static void xalanc::DOMServices::getNodeData (const XalanElement & element, ExecutionContext & context, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Sends the data for a node to a FormatterListener.
Parameters
node DOM node whose data is to be returned
context The current execution context
formatterListener the FormatterListener instance to receive the data
function A pointer to the member function of FormatterListener to call
Definition at line 484 of file DOMServices.hpp.
References xalanc::ExecutionContext::hasPreserveOrStripSpaceConditions().
getNodeData() [14/26]
static void xalanc::DOMServices::getNodeData (const XalanElement & element, ExecutionContext & context, XalanDOMString & data) inline static
Retrieves data for node.
Parameters
node DOM node whose data is to be returned
context The current execution context
data a string to which the node's data will be appended
Definition at line 248 of file DOMServices.hpp.
References xalanc::ExecutionContext::hasPreserveOrStripSpaceConditions().
getNodeData() [15/26]
static void xalanc::DOMServices::getNodeData (const XalanElement & element, FormatterListener & formatterListener, MemberFunctionPtr function) static
Sends the data for a node to a FormatterListener.
Parameters
element DOM node whose data is to be returned
formatterListener the FormatterListener instance to receive the data
fRaw Whether or not the data should be sent raw.
getNodeData() [16/26]
static void xalanc::DOMServices::getNodeData (const XalanElement & element, XalanDOMString & data) static
Retrieves data for node.
Parameters
element DOM node whose data is to be returned
data a string to which the node's data will be appended
getNodeData() [17/26]
static void xalanc::DOMServices::getNodeData (const XalanNode & node, ExecutionContext & context, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Sends the data for a node to a FormatterListener.
Parameters
node DOM node whose data is to be returned
context The current execution context
formatterListener the FormatterListener instance to receive the data
function A pointer to the member function of FormatterListener to call
Definition at line 338 of file DOMServices.hpp.
References xalanc::ExecutionContext::hasPreserveOrStripSpaceConditions().
getNodeData() [18/26]
static void xalanc::DOMServices::getNodeData (const XalanNode & node, ExecutionContext & context, XalanDOMString & data) inline static
Retrieves data for node.
Parameters
node DOM node whose data is to be returned
context The current execution context
data a string to which the node's data will be appended
Definition at line 114 of file DOMServices.hpp.
References xalanc::ExecutionContext::hasPreserveOrStripSpaceConditions().
getNodeData() [19/26]
static void xalanc::DOMServices::getNodeData (const XalanNode & node, FormatterListener & formatterListener, MemberFunctionPtr function) static
Sends the data for a node to a FormatterListener.
Parameters
node DOM node whose data is to be returned
formatterListener the FormatterListener instance to receive the data
function A pointer to the member function of FormatterListener to call
getNodeData() [20/26]
static void xalanc::DOMServices::getNodeData (const XalanNode & node, XalanDOMString & data) static
Retrieves data for node.
Parameters
node DOM node whose data is to be returned
data a string to which the node's data will be appended
getNodeData() [21/26]
static void xalanc::DOMServices::getNodeData (const XalanProcessingInstruction & pi, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Sends the data for a node to a FormatterListener.
Parameters
pi DOM node whose data is to be returned
formatterListener the FormatterListener instance to receive the data
fRaw Whether or not the data should be sent raw.
Definition at line 508 of file DOMServices.hpp.
References xalanc::XalanProcessingInstruction::getData().
getNodeData() [22/26]
static void xalanc::DOMServices::getNodeData (const XalanProcessingInstruction & pi, XalanDOMString & data) inline static
Retrieves data for node.
Parameters
pi DOM node whose data is to be returned
data a string to which the node's data will be appended
Definition at line 270 of file DOMServices.hpp.
References xalanc::XalanDOMString::append(), and xalanc::XalanProcessingInstruction::getData().
getNodeData() [23/26]
static void xalanc::DOMServices::getNodeData (const XalanText & text, ExecutionContext & context, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Sends the data for a node to a FormatterListener.
Parameters
node DOM node whose data is to be returned
context The current execution context
formatterListener the FormatterListener instance to receive the data
fRaw Whether or not the data should be sent raw.
Definition at line 541 of file DOMServices.hpp.
References xalanc::ExecutionContext::hasPreserveOrStripSpaceConditions().
getNodeData() [24/26]
static void xalanc::DOMServices::getNodeData (const XalanText & text, ExecutionContext & context, XalanDOMString & data) inline static
Retrieves data for node.
Parameters
text DOM node whose data is to be returned
context The current execution context
data a string to which the node's data will be appended
Definition at line 299 of file DOMServices.hpp.
References xalanc::ExecutionContext::hasPreserveOrStripSpaceConditions().
getNodeData() [25/26]
static void xalanc::DOMServices::getNodeData (const XalanText & text, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Sends the data for a node to a FormatterListener.
Parameters
node DOM node whose data is to be returned
formatterListener the FormatterListener instance to receive the data
fRaw Whether or not the data should be sent raw.
Definition at line 524 of file DOMServices.hpp.
References xalanc::XalanText::getData().
getNodeData() [26/26]
static void xalanc::DOMServices::getNodeData (const XalanText & text, XalanDOMString & data) inline static
Retrieves data for node.
Parameters
node DOM node whose data is to be returned
data a string to which the node's data will be appended
Definition at line 284 of file DOMServices.hpp.
References xalanc::XalanDOMString::append(), and xalanc::XalanText::getData().
getParentOfNode()
static XalanNode* xalanc::DOMServices::getParentOfNode (const XalanNode & node) inline static
Retrieve the parent of a node.
This function has to be implemented, because the DOM WG decided that attributes don't have parents.
Parameters
node child node
Returns
parent node
Definition at line 668 of file DOMServices.hpp.
References xalanc::XalanNode::getNodeType(), and xalanc::XalanNode::getParentNode().
initialize()
static void xalanc::DOMServices::initialize (MemoryManager & theManager) static
Initialize static data.
Must be called before any other functions are called.
isNamespaceDeclaration()
static bool xalanc::DOMServices::isNamespaceDeclaration (const XalanAttr & n) inline static
Determine whether or not an attribute node is declaring a namespace.
Parameters
node DOM node to check
Returns
true if the attribute is declaring a namespace, false if not.
Definition at line 652 of file DOMServices.hpp.
References xalanc::equals(), xalanc::XalanAttr::getNodeName(), and xalanc::startsWith().
isNodeAfter()
static bool xalanc::DOMServices::isNodeAfter (const XalanNode & node1, const XalanNode & node2) static
Determine if a node is after another node, in document order.
Parameters
node1 The first node
node2 The second node
Returns
true if node1 one is after node2, or false if it is not.
isNodeAfterSibling()
static bool xalanc::DOMServices::isNodeAfterSibling (const XalanNode & parent, const XalanNode & child1, const XalanNode & child2) static
Determine if a node is after another node in the sibling list.
Parameters
parent The parent of the nodes.
node1 The first node
node2 The second node
Returns
true if node1 one is after node2, or false if it is not.
terminate()
static void xalanc::DOMServices::terminate () static
Destroy static data.
After thus function is called, no other functions can be called.
Friends And Related Function Documentation
getChildData [1/3]
void getChildData (const XalanNode * child, ExecutionContext & executionContext, XalanDOMString & data) friend
getChildData [2/3]
void getChildData (const XalanNode * child, FormatterListener & formatterListener, DOMServices::MemberFunctionPtr function) friend
getChildData [3/3]
void getChildData (const XalanNode * child, XalanDOMString & data) friend
Member Data Documentation
s_emptyString
const XalanDOMString xalanc::DOMServices::s_emptyString static
Definition at line 77 of file DOMServices.hpp.
s_XMLNamespace
const XalanDOMString& xalanc::DOMServices::s_XMLNamespace static
Definition at line 61 of file DOMServices.hpp.
s_XMLNamespaceLength
const XalanDOMString::size_type& xalanc::DOMServices::s_XMLNamespaceLength static
Definition at line 70 of file DOMServices.hpp.
s_XMLNamespacePrefix
const XalanDOMString& xalanc::DOMServices::s_XMLNamespacePrefix static
Definition at line 59 of file DOMServices.hpp.
s_XMLNamespacePrefixLength
const XalanDOMString::size_type& xalanc::DOMServices::s_XMLNamespacePrefixLength static
Definition at line 68 of file DOMServices.hpp.
s_XMLNamespacePrefixURI
const XalanDOMString& xalanc::DOMServices::s_XMLNamespacePrefixURI static
Definition at line 64 of file DOMServices.hpp.
s_XMLNamespacePrefixURILength
const XalanDOMString::size_type& xalanc::DOMServices::s_XMLNamespacePrefixURILength static
Definition at line 73 of file DOMServices.hpp.
s_XMLNamespaceSeparatorString
const XalanDOMString& xalanc::DOMServices::s_XMLNamespaceSeparatorString static
Definition at line 63 of file DOMServices.hpp.
s_XMLNamespaceSeparatorStringLength
const XalanDOMString::size_type& xalanc::DOMServices::s_XMLNamespaceSeparatorStringLength static
Definition at line 72 of file DOMServices.hpp.
s_XMLNamespaceURI
const XalanDOMString& xalanc::DOMServices::s_XMLNamespaceURI static
Definition at line 60 of file DOMServices.hpp.
s_XMLNamespaceURILength
const XalanDOMString::size_type& xalanc::DOMServices::s_XMLNamespaceURILength static
Definition at line 69 of file DOMServices.hpp.
s_XMLNamespaceWithSeparator
const XalanDOMString& xalanc::DOMServices::s_XMLNamespaceWithSeparator static
Definition at line 62 of file DOMServices.hpp.
s_XMLNamespaceWithSeparatorLength
const XalanDOMString::size_type& xalanc::DOMServices::s_XMLNamespaceWithSeparatorLength static
Definition at line 71 of file DOMServices.hpp.
s_XMLString
const XalanDOMString& xalanc::DOMServices::s_XMLString static
Definition at line 57 of file DOMServices.hpp.
s_XMLStringLength
const XalanDOMString::size_type& xalanc::DOMServices::s_XMLStringLength static
Definition at line 66 of file DOMServices.hpp.
s_XMLStringWithSeparator
const XalanDOMString& xalanc::DOMServices::s_XMLStringWithSeparator static
Definition at line 58 of file DOMServices.hpp.
s_XMLStringWithSeparatorLength
const XalanDOMString::size_type& xalanc::DOMServices::s_XMLStringWithSeparatorLength static
Definition at line 67 of file DOMServices.hpp.
The documentation for this class was generated from the following file:
xalanc/DOMSupport/DOMServices.hpp