Xalan-C++ API Reference: xalanc::XalanUTF8Writer Class Reference
xalanc::XalanUTF8Writer Class Reference
#include <xalanc/XMLSupport/XalanUTF8Writer.hpp>
Public Types
typedef char value_type
Public Types inherited from xalanc::XalanFormatterWriter
typedef FormatterListener::size_type size_type
Public Member Functions
XalanUTF8Writer (Writer &writer, MemoryManager &theMemoryManager)
virtual ~XalanUTF8Writer ()
void outputNewline ()
Output a line break.
size_type writeCDATAChar (const XalanDOMChar chars[], size_type start, size_type length, bool &)
void writeNameChar (const XalanDOMChar *data, size_type theLength)
Writes name characters.
void writePIChars (const XalanDOMChar *data, size_type theLength)
Writes PI characters.
void writeCommentChars (const XalanDOMChar *data, size_type theLength)
Writes comment characters.
void safeWriteContent (const XalanDOMChar *theChars, size_type theLength)
void write (const value_type *theChars, size_type theLength)
void write (const XalanDOMChar *theChars)
void write (const XalanDOMString &theChars)
void write (value_type theChar)
void write (const XalanDOMChar *theChars, size_type theLength)
size_type write (const XalanDOMChar chars[], size_type start, size_type length)
void writeSafe (const XalanDOMChar *theChars, size_type theLength)
void write (const value_type *theChars)
void flushWriter ()
void flushBuffer ()
Public Member Functions inherited from xalanc::XalanFormatterWriter
XalanFormatterWriter (Writer &theWriter, MemoryManager &theMemoryManager)
MemoryManager & getMemoryManager ()
virtual ~XalanFormatterWriter ()
Writer * getWriter () const
XalanOutputStream * getStream ()
const XalanOutputStream * getStream () const
void flushWriter ()
void throwUnrepresentableCharacterException (XalanUnicodeChar ch, MemoryManager &theManager)
Additional Inherited Members
Static Public Member Functions inherited from xalanc::XalanFormatterWriter
static bool isUTF16HighSurrogate (XalanDOMChar theChar)
static bool isUTF16LowSurrogate (XalanDOMChar theChar)
static XalanUnicodeChar decodeUTF16SurrogatePair (XalanDOMChar theHighSurrogate, XalanDOMChar theLowSurrogate, MemoryManager &theManager)
static void throwInvalidCharacterException (XalanUnicodeChar ch, MemoryManager &theManager)
static void throwInvalidUTF16SurrogateException (XalanDOMChar ch, XalanDOMChar next, MemoryManager &theManager)
Protected Member Functions inherited from xalanc::XalanFormatterWriter
const XalanDOMString & formatNumericCharacterReference (XalanUnicodeChar theChar)
Format a code point as a numeric character reference.
Protected Attributes inherited from xalanc::XalanFormatterWriter
Writer & m_writer
The writer.
MemoryManager & m_memoryManager
The MemoryManager instance to use for any dynamically- allocated memory.
XalanDOMString m_stringBuffer
const XalanDOMChar * m_newlineString
The string of characters that represents the newline.
size_type m_newlineStringLength
The length of the the string of characters that represents the newline.
Detailed Description
Definition at line 110 of file XalanUTF8Writer.hpp.
Member Typedef Documentation
value_type
typedef char xalanc::XalanUTF8Writer::value_type
Definition at line 114 of file XalanUTF8Writer.hpp.
Constructor & Destructor Documentation
XalanUTF8Writer()
xalanc::XalanUTF8Writer::XalanUTF8Writer (Writer & writer, MemoryManager & theMemoryManager)
~XalanUTF8Writer()
virtual xalanc::XalanUTF8Writer::~XalanUTF8Writer () inline virtual
Definition at line 122 of file XalanUTF8Writer.hpp.
Member Function Documentation
flushBuffer()
void xalanc::XalanUTF8Writer::flushBuffer () inline
Definition at line 375 of file XalanUTF8Writer.hpp.
flushWriter()
void xalanc::XalanUTF8Writer::flushWriter () inline
Definition at line 369 of file XalanUTF8Writer.hpp.
outputNewline()
void xalanc::XalanUTF8Writer::outputNewline () inline
Output a line break.
Definition at line 130 of file XalanUTF8Writer.hpp.
References xalanc::length().
safeWriteContent()
void xalanc::XalanUTF8Writer::safeWriteContent (const XalanDOMChar * theChars, size_type theLength) inline
Definition at line 189 of file XalanUTF8Writer.hpp.
write() [1/7]
void xalanc::XalanUTF8Writer::write (const value_type * theChars) inline
Definition at line 363 of file XalanUTF8Writer.hpp.
References xalanc::length().
write() [2/7]
void xalanc::XalanUTF8Writer::write (const value_type * theChars, size_type theLength) inline
Definition at line 200 of file XalanUTF8Writer.hpp.
write() [3/7]
void xalanc::XalanUTF8Writer::write (const XalanDOMChar * theChars) inline
Definition at line 236 of file XalanUTF8Writer.hpp.
References xalanc::length().
write() [4/7]
void xalanc::XalanUTF8Writer::write (const XalanDOMChar * theChars, size_type theLength) inline
Definition at line 264 of file XalanUTF8Writer.hpp.
write() [5/7]
size_type xalanc::XalanUTF8Writer::write (const XalanDOMChar chars[], size_type start, size_type length) inline
Definition at line 295 of file XalanUTF8Writer.hpp.
References xalanc::length().
write() [6/7]
void xalanc::XalanUTF8Writer::write (const XalanDOMString & theChars) inline
Definition at line 242 of file XalanUTF8Writer.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
write() [7/7]
void xalanc::XalanUTF8Writer::write (value_type theChar) inline
Definition at line 248 of file XalanUTF8Writer.hpp.
writeCDATAChar()
size_type xalanc::XalanUTF8Writer::writeCDATAChar (const XalanDOMChar chars[], size_type start, size_type length, bool &) inline
Definition at line 141 of file XalanUTF8Writer.hpp.
References xalanc::length().
writeCommentChars()
void xalanc::XalanUTF8Writer::writeCommentChars (const XalanDOMChar * data, size_type theLength) inline
Writes comment characters.
If characters that are not representable are encountered, an exception is thrown.
Definition at line 181 of file XalanUTF8Writer.hpp.
writeNameChar()
void xalanc::XalanUTF8Writer::writeNameChar (const XalanDOMChar * data, size_type theLength) inline
Writes name characters.
If characters that are not representable are encountered, an exception is thrown.
Definition at line 157 of file XalanUTF8Writer.hpp.
writePIChars()
void xalanc::XalanUTF8Writer::writePIChars (const XalanDOMChar * data, size_type theLength) inline
Writes PI characters.
If characters that are not representable are encountered, an exception is thrown.
Definition at line 169 of file XalanUTF8Writer.hpp.
writeSafe()
void xalanc::XalanUTF8Writer::writeSafe (const XalanDOMChar * theChars, size_type theLength) inline
Definition at line 326 of file XalanUTF8Writer.hpp.
The documentation for this class was generated from the following file:
xalanc/XMLSupport/XalanUTF8Writer.hpp