Xalan-C++ API Reference: xalanc::Stylesheet Class Reference
xalanc::Stylesheet Class Reference
This class represents the base stylesheet or an "import" stylesheet.
#include <xalanc/XSLT/Stylesheet.hpp>
Public Types
typedef StylesheetExecutionContext::ParamVectorType ParamVectorType
typedef XalanQName::NamespaceVectorType NamespaceVectorType
typedef XalanQName::NamespacesStackType NamespacesStackType
typedef XalanVector< ElemVariable * > ElemVariableVectorType
typedef XalanVector< KeyDeclaration > KeyDeclarationVectorType
typedef XalanVector< Stylesheet * > StylesheetVectorType
typedef XalanVector< XalanDOMString > URLStackType
typedef XalanVector< ElemDecimalFormat * > ElemDecimalFormatVectorType
typedef XalanVector< XalanSpaceNodeTester > WhitespaceElementsVectorType
typedef PatternTableVectorTypeDecl PatternTableVectorType
typedef XalanMap< XalanDOMString, ExtensionNSHandler * > ExtensionNamespacesMapType
typedef XalanMap< XalanQNameByReference, const ElemTemplate * > ElemTemplateMapType
typedef XalanMap< const XalanNode *, KeyTable * > KeyTablesTableType
typedef XalanMap< XalanDOMString, PatternTableVectorType > PatternTableMapType
typedef StylesheetConstructionContext::GetCachedString GetCachedString
Public Member Functions
Stylesheet (StylesheetRoot &root, const XalanDOMString &baseIdentifier, StylesheetConstructionContext &constructionContext)
Constructor for a Stylesheet needs a Document.
virtual ~Stylesheet ()
MemoryManager & getMemoryManager ()
double getXSLTVerDeclared () const
Retrieve XSLT version number.
void setXSLTVerDeclared (double ver)
Set XSLT version number.
const StylesheetRoot & getStylesheetRoot () const
Retrieve the root stylesheet object.
StylesheetRoot & getStylesheetRoot ()
Retrieve the root stylesheet object.
const NamespacesStackType & getNamespaces () const
Retrieve the stack of namespace lists.
NamespacesStackType & getNamespaces ()
Retrieve the stack of namespace lists.
const NamespacesHandler & getNamespacesHandler () const
NamespacesHandler & getNamespacesHandler ()
const NamespaceVectorType & getNamespaceDecls () const
Retrieve the list of namespace declarations currently in effect.
NamespaceVectorType & getNamespaceDecls ()
Retrieve the list of namespace declarations currently in effect.
void setNamespaceDecls (const NamespaceVectorType &ns)
Set the list of namespace declarations currently in effect.
void pushNamespaces (const AttributeListType &atts)
Push the namespace declarations from the current attribute list onto the namespace stack.
void popNamespaces ()
Pop a namespace declaration from the namespace stack.
void addWhitespaceElement (const XalanSpaceNodeTester &theTester)
virtual void postConstruction (StylesheetConstructionContext &constructionContext)
Called after construction is completed.
bool isAttrOK (const XalanDOMChar *attrName, const AttributeListType &atts, XalanSize_t which, StylesheetConstructionContext &constructionContext) const
See if this is a xmlns attribute, and, if so, process it.
const XalanDOMString * getNamespaceFromStack (const XalanDOMString &nodeName, XalanDOMString &theBuffer) const
Get the namespace from a qualified name.
const XalanDOMString * getNamespaceFromStack (const XalanDOMChar *nodeName, XalanDOMString &theBuffer) const
Get the namespace from a qualified name.
const XalanDOMString * getNamespaceForPrefixFromStack (const XalanDOMString &prefix) const
Get the namespace from a prefix by searching the stack of namespace lists.
const XalanDOMString * getNamespaceForPrefixFromStack (const XalanDOMChar *prefix) const
Get the namespace from a prefix by searching the stack of namespace lists.
const XalanDOMString * getNamespaceForPrefix (const XalanDOMString &prefix, StylesheetConstructionContext &constructionContext) const
Get the namespace for a prefix, and report an error if it wasn't found.
const XalanDOMString * getNamespaceForPrefix (const XalanDOMChar *prefix, StylesheetConstructionContext &constructionContext) const
Get the namespace for a prefix, and report an error if it wasn't found.
void processExcludeResultPrefixes (StylesheetConstructionContext &theConstructionContext, const XalanDOMChar *theValue)
See if a namespace should be excluded.
void addTemplate (ElemTemplate *theTemplate, StylesheetConstructionContext &constructionContext)
Add a template to the list of names templates.
bool getYesOrNo (const XalanDOMChar *aname, const XalanDOMChar *val, StylesheetConstructionContext &constructionContext) const
Process an attribute that has the value of 'yes' or 'no'.
const XalanDOMString & getBaseIdentifier () const
Retrieve the base identifier with which this stylesheet is associated.
const XalanDOMString & getCurrentIncludeBaseIdentifier () const
Retrieve the base identifier for the most recently included stylesheet.
void processNSAliasElement (const XalanDOMChar *name, const AttributeListType &atts, StylesheetConstructionContext &constructionContext)
Process an xsl:namespace-alias element.
void processDecimalFormatElement (StylesheetConstructionContext &constructionContext, const AttributeListType &atts, const Locator *locator=0)
Process an xsl:decimal-format element.
const XalanDecimalFormatSymbols * getDecimalFormatSymbols (const XalanQName &theQName) const
Retrieve the XalanDecimalFormatSymbols instance associated with the QName.
void addImport (Stylesheet *theStylesheet)
Add an imported stylesheet.
bool isWrapperless () const
whether there is a wrapper template
ElemTemplateElement * initWrapperless (StylesheetConstructionContext &constructionContext, const Locator *locator)
URLStackType & getIncludeStack ()
Retrieve the stack of who's including who.
void processKeyElement (const PrefixResolver &nsContext, const AttributeListType &atts, const Locator *locator, StylesheetConstructionContext &constructionContext)
Process the xsl:key element.
const ElemTemplate * findNamedTemplate (const XalanQName &qname) const
Locate a template via the "name" attribute.
const ElemTemplate * findTemplate (StylesheetExecutionContext &executionContext, XalanNode *targetNode) const
Given a target element, find the template that best matches in the given XSL document, according to the rules specified in the xsl draft.
const ElemTemplate * findTemplate (StylesheetExecutionContext &executionContext, XalanNode *targetNode, XalanNode::NodeType targetNodeType, const XalanQName &mode, bool onlyUseImports) const
Given a target element, find the template that best matches in the given XSL document, according to the rules specified in the xsl draft.
const PatternTableVectorType * locateElementMatchPatternDataList (const XalanDOMString &theName) const
Given a name, locate the start of a list of possible templates that match that name.
const PatternTableVectorType * locateAttributeMatchPatternDataList (const XalanDOMString &theName) const
Given a name, locate the start of a list of possible templates that match that name.
const PatternTableVectorType * locateMatchPatternDataList (const XalanNode &theNode, XalanNode::NodeType targetNodeType) const
Given a XalanNode, locate the start of a list of possible templates that match it.
void processExtensionNamespace (StylesheetConstructionContext &theConstructionContext, const XalanDOMString &uri)
Add an extension namespace handler.
ExtensionNSHandler * lookupExtensionNSHandler (const XalanDOMString &uri) const
Return the handler for a given extension namespace.
void setTopLevelVariable (ElemVariable *var)
Set a top level variable.
void pushTopLevelVariables (StylesheetExecutionContext &executionContext, const ParamVectorType &topLevelParams) const
Set a list of top level variables in the specified execution context stylesheet.
virtual const XalanDOMString * getNamespaceForPrefix (const XalanDOMString &prefix) const
Retrieve a namespace corresponding to a prefix.
virtual const XalanDOMString & getURI () const
Retrieve the base URI for the resolver.
const XalanDOMString & getXSLTNamespaceURI () const
void setXSLTNamespaceURI (const XalanDOMString &theURI)
const ElemTemplate * getFirstTemplate () const
Public Member Functions inherited from xalanc::PrefixResolver
PrefixResolver ()
PrefixResolver (const PrefixResolver &)
virtual ~PrefixResolver ()
Static Public Member Functions
static Stylesheet * create (MemoryManager &theManager, StylesheetRoot &root, const XalanDOMString &baseIdentifier, StylesheetConstructionContext &constructionContext)
static void addObjectIfNotFound (const XalanMatchPatternData *thePattern, PatternTableVectorType &theVector)
Add object to vector of match patterns if not already there.
static void addObjectIfNotFound (const XalanMatchPatternData *thePattern, const XalanMatchPatternData *theArray[], XalanSize_t &theArraySize)
Add object to array of match patterns if not already there.
Protected Attributes
StylesheetRoot & m_stylesheetRoot
The root of the stylesheet tree.
XalanDOMString m_baseIdent
The base URL of the XSL document.
KeyDeclarationVectorType m_keyDeclarations
Table of KeyDeclaration objects, which are set by the xsl:key element.
WhitespaceElementsVectorType m_whitespaceElements
Static Protected Attributes
static const XalanQNameByReference s_emptyQName
Detailed Description
This class represents the base stylesheet or an "import" stylesheet.
"include" stylesheets are combined with the including stylesheet.
Definition at line 86 of file Stylesheet.hpp.
Member Typedef Documentation
ElemDecimalFormatVectorType
typedef XalanVector<ElemDecimalFormat*> xalanc::Stylesheet::ElemDecimalFormatVectorType
Definition at line 99 of file Stylesheet.hpp.
ElemTemplateMapType
typedef XalanMap<XalanQNameByReference, const ElemTemplate* > xalanc::Stylesheet::ElemTemplateMapType
Definition at line 106 of file Stylesheet.hpp.
ElemVariableVectorType
typedef XalanVector<ElemVariable*> xalanc::Stylesheet::ElemVariableVectorType
Definition at line 95 of file Stylesheet.hpp.
ExtensionNamespacesMapType
typedef XalanMap<XalanDOMString, ExtensionNSHandler*> xalanc::Stylesheet::ExtensionNamespacesMapType
Definition at line 103 of file Stylesheet.hpp.
GetCachedString
typedef StylesheetConstructionContext::GetCachedString xalanc::Stylesheet::GetCachedString
Definition at line 112 of file Stylesheet.hpp.
KeyDeclarationVectorType
typedef XalanVector<KeyDeclaration> xalanc::Stylesheet::KeyDeclarationVectorType
Definition at line 96 of file Stylesheet.hpp.
KeyTablesTableType
typedef XalanMap<const XalanNode*, KeyTable* > xalanc::Stylesheet::KeyTablesTableType
Definition at line 108 of file Stylesheet.hpp.
NamespacesStackType
typedef XalanQName::NamespacesStackType xalanc::Stylesheet::NamespacesStackType
Definition at line 93 of file Stylesheet.hpp.
NamespaceVectorType
typedef XalanQName::NamespaceVectorType xalanc::Stylesheet::NamespaceVectorType
Definition at line 92 of file Stylesheet.hpp.
ParamVectorType
typedef StylesheetExecutionContext::ParamVectorType xalanc::Stylesheet::ParamVectorType
Definition at line 91 of file Stylesheet.hpp.
PatternTableMapType
typedef XalanMap<XalanDOMString, PatternTableVectorType> xalanc::Stylesheet::PatternTableMapType
Definition at line 110 of file Stylesheet.hpp.
PatternTableVectorType
typedef PatternTableVectorTypeDecl xalanc::Stylesheet::PatternTableVectorType
Definition at line 101 of file Stylesheet.hpp.
StylesheetVectorType
typedef XalanVector<Stylesheet*> xalanc::Stylesheet::StylesheetVectorType
Definition at line 97 of file Stylesheet.hpp.
URLStackType
typedef XalanVector<XalanDOMString> xalanc::Stylesheet::URLStackType
Definition at line 98 of file Stylesheet.hpp.
WhitespaceElementsVectorType
typedef XalanVector<XalanSpaceNodeTester> xalanc::Stylesheet::WhitespaceElementsVectorType
Definition at line 100 of file Stylesheet.hpp.
Constructor & Destructor Documentation
Stylesheet()
xalanc::Stylesheet::Stylesheet (StylesheetRoot & root, const XalanDOMString & baseIdentifier, StylesheetConstructionContext & constructionContext)
Constructor for a Stylesheet needs a Document.
Exceptions
XSLProcessorException thrown if the active ProblemListener and XMLParserLiaison decide the error condition is severe enough to halt processing.
~Stylesheet()
virtual xalanc::Stylesheet::~Stylesheet () virtual
Member Function Documentation
addImport()
void xalanc::Stylesheet::addImport (Stylesheet * theStylesheet) inline
Add an imported stylesheet.
Parameters
theStylesheet The stylesheet to add.
Definition at line 480 of file Stylesheet.hpp.
addObjectIfNotFound() [1/2]
static void xalanc::Stylesheet::addObjectIfNotFound (const XalanMatchPatternData * thePattern, const XalanMatchPatternData * theArray[], XalanSize_t & theArraySize) static
Add object to array of match patterns if not already there.
theArraySize size will be incremented if the pattern was added.
Parameters
thePattern pattern to add
theArray vector of patterns to add to
theArraySize The size of the array
addObjectIfNotFound() [2/2]
static void xalanc::Stylesheet::addObjectIfNotFound (const XalanMatchPatternData * thePattern, PatternTableVectorType & theVector) static
Add object to vector of match patterns if not already there.
Parameters
thePattern pattern to add
theVector vector of patterns to add to
addTemplate()
void xalanc::Stylesheet::addTemplate (ElemTemplate * theTemplate, StylesheetConstructionContext & constructionContext)
Add a template to the list of names templates.
Parameters
theTemplate template to add
constructionContext context for construction
addWhitespaceElement()
void xalanc::Stylesheet::addWhitespaceElement (const XalanSpaceNodeTester & theTester)
create()
static Stylesheet* xalanc::Stylesheet::create (MemoryManager & theManager, StylesheetRoot & root, const XalanDOMString & baseIdentifier, StylesheetConstructionContext & constructionContext) static
findNamedTemplate()
const ElemTemplate* xalanc::Stylesheet::findNamedTemplate (const XalanQName & qname) const
Locate a template via the "name" attribute.
Parameters
name qualified name of template
Returns
pointer to template found or 0 if none found
findTemplate() [1/2]
const ElemTemplate* xalanc::Stylesheet::findTemplate (StylesheetExecutionContext & executionContext, XalanNode * targetNode) const inline
Given a target element, find the template that best matches in the given XSL document, according to the rules specified in the xsl draft.
Parameters
executionContext current execution context
targetNode element that needs a rule
Returns
pointer to rule that best matches targetNode
Definition at line 545 of file Stylesheet.hpp.
References xalanc::XalanNode::getNodeType().
findTemplate() [2/2]
const ElemTemplate* xalanc::Stylesheet::findTemplate (StylesheetExecutionContext & executionContext, XalanNode * targetNode, XalanNode::NodeType targetNodeType, const XalanQName & mode, bool onlyUseImports) const
Given a target element, find the template that best matches in the given XSL document, according to the rules specified in the xsl draft.
Parameters
executionContext current execution context
targetNode node that needs a rule
targetNodeType the type of targetNode
mode string indicating the mode
onlyUseImports only use imports, do not use any templates from the stylesheet itself
Returns
pointer to rule that best matches targetElem
getBaseIdentifier()
const XalanDOMString& xalanc::Stylesheet::getBaseIdentifier () const inline
Retrieve the base identifier with which this stylesheet is associated.
Returns
string for base identifier
Definition at line 421 of file Stylesheet.hpp.
getCurrentIncludeBaseIdentifier()
const XalanDOMString& xalanc::Stylesheet::getCurrentIncludeBaseIdentifier () const inline
Retrieve the base identifier for the most recently included stylesheet.
This will return the same value as getBaseIdentifier(), if no include is being processed.
Returns
string for base identifier
Definition at line 435 of file Stylesheet.hpp.
References xalanc::XalanDOMString::empty().
getDecimalFormatSymbols()
const XalanDecimalFormatSymbols* xalanc::Stylesheet::getDecimalFormatSymbols (const XalanQName & theQName) const
Retrieve the XalanDecimalFormatSymbols instance associated with the QName.
Parameters
theQName the QName for the lookup
Returns
a pointer to the matching instance, or 0 if none was found
getFirstTemplate()
const ElemTemplate* xalanc::Stylesheet::getFirstTemplate () const inline
Definition at line 709 of file Stylesheet.hpp.
getIncludeStack()
URLStackType& xalanc::Stylesheet::getIncludeStack () inline
Retrieve the stack of who's including who.
Returns
stack of includes
Definition at line 507 of file Stylesheet.hpp.
getMemoryManager()
MemoryManager& xalanc::Stylesheet::getMemoryManager () inline
Definition at line 134 of file Stylesheet.hpp.
getNamespaceDecls() [1/2]
NamespaceVectorType& xalanc::Stylesheet::getNamespaceDecls () inline
Retrieve the list of namespace declarations currently in effect.
Returns
vector of namespace vectors
Definition at line 234 of file Stylesheet.hpp.
getNamespaceDecls() [2/2]
const NamespaceVectorType& xalanc::Stylesheet::getNamespaceDecls () const inline
Retrieve the list of namespace declarations currently in effect.
Returns
vector of namespace vectors
Definition at line 223 of file Stylesheet.hpp.
getNamespaceForPrefix() [1/3]
const XalanDOMString* xalanc::Stylesheet::getNamespaceForPrefix (const XalanDOMChar * prefix, StylesheetConstructionContext & constructionContext) const
Get the namespace for a prefix, and report an error if it wasn't found.
Parameters
prefix prefix to search
constructionContext The current construction context
Returns
namespace corresponding to prefix, or null if not found.
getNamespaceForPrefix() [2/3]
virtual const XalanDOMString* xalanc::Stylesheet::getNamespaceForPrefix (const XalanDOMString & prefix) const virtual
Retrieve a namespace corresponding to a prefix.
This assumes that the PrevixResolver holds its own namespace context, or is a namespace context itself.
Parameters
prefix Prefix to resolve
Returns
namespace that prefix resolves to, or null if prefix is not found
Implements xalanc::PrefixResolver.
getNamespaceForPrefix() [3/3]
const XalanDOMString* xalanc::Stylesheet::getNamespaceForPrefix (const XalanDOMString & prefix, StylesheetConstructionContext & constructionContext) const
Get the namespace for a prefix, and report an error if it wasn't found.
Parameters
prefix prefix to search
constructionContext The current construction context
Returns
namespace corresponding to prefix, or null if not found.
getNamespaceForPrefixFromStack() [1/2]
const XalanDOMString* xalanc::Stylesheet::getNamespaceForPrefixFromStack (const XalanDOMChar * prefix) const inline
Get the namespace from a prefix by searching the stack of namespace lists.
Parameters
prefix prefix to search
Returns
namespace corresponding to prefix, or null if not found.
Definition at line 341 of file Stylesheet.hpp.
getNamespaceForPrefixFromStack() [2/2]
const XalanDOMString* xalanc::Stylesheet::getNamespaceForPrefixFromStack (const XalanDOMString & prefix) const inline
Get the namespace from a prefix by searching the stack of namespace lists.
Parameters
prefix prefix to search
Returns
namespace corresponding to prefix, or null if not found.
Definition at line 328 of file Stylesheet.hpp.
getNamespaceFromStack() [1/2]
const XalanDOMString* xalanc::Stylesheet::getNamespaceFromStack (const XalanDOMChar * nodeName, XalanDOMString & theBuffer) const
Get the namespace from a qualified name.
Parameters
nodeName name of node
Returns
namespace string for node, or null if not found.
getNamespaceFromStack() [2/2]
const XalanDOMString* xalanc::Stylesheet::getNamespaceFromStack (const XalanDOMString & nodeName, XalanDOMString & theBuffer) const inline
Get the namespace from a qualified name.
Parameters
nodeName name of node
Returns
namespace string for node, or null if not found.
Definition at line 302 of file Stylesheet.hpp.
References xalanc::XalanDOMString::c_str().
getNamespaces() [1/2]
NamespacesStackType& xalanc::Stylesheet::getNamespaces () inline
Retrieve the stack of namespace lists.
Returns
vector of namespace vectors
Definition at line 200 of file Stylesheet.hpp.
getNamespaces() [2/2]
const NamespacesStackType& xalanc::Stylesheet::getNamespaces () const inline
Retrieve the stack of namespace lists.
Returns
vector of namespace vectors
Definition at line 189 of file Stylesheet.hpp.
getNamespacesHandler() [1/2]
NamespacesHandler& xalanc::Stylesheet::getNamespacesHandler () inline
Definition at line 212 of file Stylesheet.hpp.
getNamespacesHandler() [2/2]
const NamespacesHandler& xalanc::Stylesheet::getNamespacesHandler () const inline
Definition at line 206 of file Stylesheet.hpp.
getStylesheetRoot() [1/2]
StylesheetRoot& xalanc::Stylesheet::getStylesheetRoot () inline
Retrieve the root stylesheet object.
Returns
reference to the stylesheet object
Definition at line 178 of file Stylesheet.hpp.
getStylesheetRoot() [2/2]
const StylesheetRoot& xalanc::Stylesheet::getStylesheetRoot () const inline
Retrieve the root stylesheet object.
Returns
const reference to the stylesheet object
Definition at line 167 of file Stylesheet.hpp.
getURI()
virtual const XalanDOMString& xalanc::Stylesheet::getURI () const virtual
Retrieve the base URI for the resolver.
Returns
URI string
Implements xalanc::PrefixResolver.
getXSLTNamespaceURI()
const XalanDOMString& xalanc::Stylesheet::getXSLTNamespaceURI () const inline
Definition at line 697 of file Stylesheet.hpp.
getXSLTVerDeclared()
double xalanc::Stylesheet::getXSLTVerDeclared () const inline
Retrieve XSLT version number.
Returns
number representing XSLT version
Definition at line 145 of file Stylesheet.hpp.
getYesOrNo()
bool xalanc::Stylesheet::getYesOrNo (const XalanDOMChar * aname, const XalanDOMChar * val, StylesheetConstructionContext & constructionContext) const
Process an attribute that has the value of 'yes' or 'no'.
Parameters
aname name of attribute
val value
constructionContext context for construction
Returns
true if value equals string constant for "yes," false otherwise
initWrapperless()
ElemTemplateElement* xalanc::Stylesheet::initWrapperless (StylesheetConstructionContext & constructionContext, const Locator * locator)
isAttrOK()
bool xalanc::Stylesheet::isAttrOK (const XalanDOMChar * attrName, const AttributeListType & atts, XalanSize_t which, StylesheetConstructionContext & constructionContext) const
See if this is a xmlns attribute, and, if so, process it.
Parameters
attrName qualified name of attribute
atts attribute list where the element comes from (not used at this time)
which index into the attribute list (not used at this time)
Returns
true if this is a namespace name
isWrapperless()
bool xalanc::Stylesheet::isWrapperless () const inline
whether there is a wrapper template
Returns
true is there is a wrapper
Definition at line 491 of file Stylesheet.hpp.
locateAttributeMatchPatternDataList()
const PatternTableVectorType* xalanc::Stylesheet::locateAttributeMatchPatternDataList (const XalanDOMString & theName) const
Given a name, locate the start of a list of possible templates that match that name.
If none match, then use the default list.
Parameters
theName The name to match
locateElementMatchPatternDataList()
const PatternTableVectorType* xalanc::Stylesheet::locateElementMatchPatternDataList (const XalanDOMString & theName) const
Given a name, locate the start of a list of possible templates that match that name.
If none match, then use the default list.
Parameters
theName The name to match
locateMatchPatternDataList()
const PatternTableVectorType* xalanc::Stylesheet::locateMatchPatternDataList (const XalanNode & theNode, XalanNode::NodeType targetNodeType) const
Given a XalanNode, locate the start of a list of possible templates that match it.
Parameters
XalanNode The node to match
lookupExtensionNSHandler()
ExtensionNSHandler* xalanc::Stylesheet::lookupExtensionNSHandler (const XalanDOMString & uri) const inline
Return the handler for a given extension namespace.
Parameters
uri the URI of the extension namespace.
Returns
pointer to extension handler
Definition at line 655 of file Stylesheet.hpp.
popNamespaces()
void xalanc::Stylesheet::popNamespaces () inline
Pop a namespace declaration from the namespace stack.
Definition at line 263 of file Stylesheet.hpp.
postConstruction()
virtual void xalanc::Stylesheet::postConstruction (StylesheetConstructionContext & constructionContext) virtual
Called after construction is completed.
Reimplemented in xalanc::StylesheetRoot.
processDecimalFormatElement()
void xalanc::Stylesheet::processDecimalFormatElement (StylesheetConstructionContext & constructionContext, const AttributeListType & atts, const Locator * locator = 0)
Process an xsl:decimal-format element.
Parameters
elemDecimalFormat the element
processExcludeResultPrefixes()
void xalanc::Stylesheet::processExcludeResultPrefixes (StylesheetConstructionContext & theConstructionContext, const XalanDOMChar * theValue) inline
See if a namespace should be excluded.
Parameters
theConstructionContext the current construction context.
theValue the prefix of the namespace.
Returns
Definition at line 380 of file Stylesheet.hpp.
processExtensionNamespace()
void xalanc::Stylesheet::processExtensionNamespace (StylesheetConstructionContext & theConstructionContext, const XalanDOMString & uri)
Add an extension namespace handler.
This provides methods for calling an element extension as well as for function calls (which is passed on to XPath).
Parameters
constructionContext The current construction context.
uri The namespace URI of the extension.
processKeyElement()
void xalanc::Stylesheet::processKeyElement (const PrefixResolver & nsContext, const AttributeListType & atts, const Locator * locator, StylesheetConstructionContext & constructionContext)
Process the xsl:key element.
Parameters
nsContext The PrefixResolver instance for namespace prefixes.
atts The attribute list for element. #param locator The Locator instance for error reporting, if any. May be 0.
constructionContext The current construction context.
processNSAliasElement()
void xalanc::Stylesheet::processNSAliasElement (const XalanDOMChar * name, const AttributeListType & atts, StylesheetConstructionContext & constructionContext)
Process an xsl:namespace-alias element.
Parameters
name the element name.
attrs the current attribute list
constructionContext the active construction context
pushNamespaces()
void xalanc::Stylesheet::pushNamespaces (const AttributeListType & atts)
Push the namespace declarations from the current attribute list onto the namespace stack.
Parameters
atts attribute list constaining namespaces
pushTopLevelVariables()
void xalanc::Stylesheet::pushTopLevelVariables (StylesheetExecutionContext & executionContext, const ParamVectorType & topLevelParams) const
Set a list of top level variables in the specified execution context stylesheet.
Parameters
executionContext current execution context
topLevelParams list of top level parameters
setNamespaceDecls()
void xalanc::Stylesheet::setNamespaceDecls (const NamespaceVectorType & ns) inline
Set the list of namespace declarations currently in effect.
Parameters
ns vector of namespace vectors
Definition at line 245 of file Stylesheet.hpp.
setTopLevelVariable()
void xalanc::Stylesheet::setTopLevelVariable (ElemVariable * var) inline
Set a top level variable.
Parameters
var top-level variable declared with "xsl:variable" or xsl:param-variable.
Definition at line 670 of file Stylesheet.hpp.
setXSLTNamespaceURI()
void xalanc::Stylesheet::setXSLTNamespaceURI (const XalanDOMString & theURI) inline
Definition at line 703 of file Stylesheet.hpp.
setXSLTVerDeclared()
void xalanc::Stylesheet::setXSLTVerDeclared (double ver) inline
Set XSLT version number.
Parameters
ver number representing XSLT version
Definition at line 156 of file Stylesheet.hpp.
Member Data Documentation
m_baseIdent
XalanDOMString xalanc::Stylesheet::m_baseIdent protected
The base URL of the XSL document.
Definition at line 724 of file Stylesheet.hpp.
m_keyDeclarations
KeyDeclarationVectorType xalanc::Stylesheet::m_keyDeclarations protected
Table of KeyDeclaration objects, which are set by the xsl:key element.
Definition at line 730 of file Stylesheet.hpp.
m_stylesheetRoot
StylesheetRoot& xalanc::Stylesheet::m_stylesheetRoot protected
The root of the stylesheet tree.
Definition at line 719 of file Stylesheet.hpp.
m_whitespaceElements
WhitespaceElementsVectorType xalanc::Stylesheet::m_whitespaceElements protected
Definition at line 732 of file Stylesheet.hpp.
s_emptyQName
const XalanQNameByReference xalanc::Stylesheet::s_emptyQName static protected
Definition at line 734 of file Stylesheet.hpp.
The documentation for this class was generated from the following file:
xalanc/XSLT/Stylesheet.hpp