Xalan-C++ API Reference: xalanc::XalanAttr Class Reference
xalanc::XalanAttr Class Reference abstract
#include <xalanc/XalanDOM/XalanAttr.hpp>
Public Member Functions
XalanAttr ()
virtual ~XalanAttr ()
virtual const XalanDOMString & getNodeName () const =0
Gets the name of this node, depending on its type.
virtual const XalanDOMString & getNodeValue () const =0
Gets the value of this node, depending on its type.
virtual NodeType getNodeType () const =0
An enum value representing the type of the underlying object.
virtual XalanNode * getParentNode () const =0
Gets the parent of this node.
virtual const XalanNodeList * getChildNodes () const =0
Gets a XalanNodeList that contains all children of this node.
virtual XalanNode * getFirstChild () const =0
Gets the first child of this node.
virtual XalanNode * getLastChild () const =0
Gets the last child of this node.
virtual XalanNode * getPreviousSibling () const =0
Gets the node immediately preceding this node.
virtual XalanNode * getNextSibling () const =0
Gets the node immediately following this node.
virtual const XalanNamedNodeMap * getAttributes () const =0
Gets a XalanNamedNodeMap containing the attributes of this node (if it is an XalanElement) or a null pointer otherwise.
virtual XalanDocument * getOwnerDocument () const =0
Gets the XalanDocument object associated with this node.
virtual const XalanDOMString & getNamespaceURI () const =0
Get the namespace URI of this node.
virtual const XalanDOMString & getPrefix () const =0
Get the namespace prefix of this node.
virtual const XalanDOMString & getLocalName () const =0
Returns the local part of the qualified name of this node.
virtual bool isIndexed () const =0
Determine if the document is node-order indexed.
virtual IndexType getIndex () const =0
Get the node's index.
virtual const XalanDOMString & getName () const =0
Returns the name of this attribute.
virtual const XalanDOMString & getValue () const =0
Returns the value of the attribute.
virtual XalanElement * getOwnerElement () const =0
The XalanElement node this attribute is attached to.
Public Member Functions inherited from xalanc::XalanNode
XalanNode ()
virtual ~XalanNode ()
Protected Member Functions
XalanAttr (const XalanAttr &theSource)
XalanAttr & operator= (const XalanAttr &theSource)
bool operator== (const XalanAttr &theRHS) const
Protected Member Functions inherited from xalanc::XalanNode
XalanNode (const XalanNode &theSource)
XalanNode & operator= (const XalanNode &theSource)
bool operator== (const XalanNode &theRHS) const
Additional Inherited Members
Public Types inherited from xalanc::XalanNode
enum NodeType {
UNKNOWN_NODE = 0, ELEMENT_NODE = 1, ATTRIBUTE_NODE = 2, TEXT_NODE = 3,
CDATA_SECTION_NODE = 4, ENTITY_REFERENCE_NODE = 5, ENTITY_NODE = 6, PROCESSING_INSTRUCTION_NODE = 7,
COMMENT_NODE = 8, DOCUMENT_NODE = 9, DOCUMENT_TYPE_NODE = 10, DOCUMENT_FRAGMENT_NODE = 11,
NOTATION_NODE = 12
}
typedef unsigned long IndexType
Detailed Description
Definition at line 40 of file XalanAttr.hpp.
Constructor & Destructor Documentation
XalanAttr() [1/2]
xalanc::XalanAttr::XalanAttr ()
~XalanAttr()
virtual xalanc::XalanAttr::~XalanAttr () virtual
XalanAttr() [2/2]
xalanc::XalanAttr::XalanAttr (const XalanAttr & theSource) protected
Member Function Documentation
getAttributes()
virtual const XalanNamedNodeMap* xalanc::XalanAttr::getAttributes () const pure virtual
Gets a XalanNamedNodeMap containing the attributes of this node (if it is an XalanElement) or a null pointer otherwise.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
getChildNodes()
virtual const XalanNodeList* xalanc::XalanAttr::getChildNodes () const pure virtual
Gets a XalanNodeList that contains all children of this node.
If there are no children, this is a XalanNodeList containing no nodes.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
getFirstChild()
virtual XalanNode* xalanc::XalanAttr::getFirstChild () const pure virtual
Gets the first child of this node.
If there is no such node, this returns a null pointer.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
getIndex()
virtual IndexType xalanc::XalanAttr::getIndex () const pure virtual
Get the node's index.
Valid only if the owner document reports that the document is node-order indexed.
Returns
The index value, or 0 if the node is not indexed.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
getLastChild()
virtual XalanNode* xalanc::XalanAttr::getLastChild () const pure virtual
Gets the last child of this node.
If there is no such node, this returns a null pointer.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
getLocalName()
virtual const XalanDOMString& xalanc::XalanAttr::getLocalName () const pure virtual
Returns the local part of the qualified name of this node.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, xalanc::XercesAttrWrapper, and xalanc::XalanSourceTreeAttrNS.
Referenced by xalanc::DOMServices::getNameOfNode().
getName()
virtual const XalanDOMString& xalanc::XalanAttr::getName () const pure virtual
Returns the name of this attribute.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
getNamespaceURI()
virtual const XalanDOMString& xalanc::XalanAttr::getNamespaceURI () const pure virtual
Get the namespace URI of this node.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, xalanc::XercesAttrWrapper, and xalanc::XalanSourceTreeAttrNS.
getNextSibling()
virtual XalanNode* xalanc::XalanAttr::getNextSibling () const pure virtual
Gets the node immediately following this node.
If there is no such node, this returns a null pointer.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
getNodeName()
virtual const XalanDOMString& xalanc::XalanAttr::getNodeName () const pure virtual
Gets the name of this node, depending on its type.
Implements xalanc::XalanNode.
Implemented in xalanc::XalanSourceTreeAttr, xalanc::XercesAttrBridge, and xalanc::XercesAttrWrapper.
Referenced by xalanc::DOMServices::getNameOfNode(), and xalanc::DOMServices::isNamespaceDeclaration().
getNodeType()
virtual NodeType xalanc::XalanAttr::getNodeType () const pure virtual
An enum value representing the type of the underlying object.
Implements xalanc::XalanNode.
Implemented in xalanc::XalanSourceTreeAttr, xalanc::XercesAttrBridge, and xalanc::XercesAttrWrapper.
getNodeValue()
virtual const XalanDOMString& xalanc::XalanAttr::getNodeValue () const pure virtual
Gets the value of this node, depending on its type.
Implements xalanc::XalanNode.
Implemented in xalanc::XalanSourceTreeAttr, xalanc::XercesAttrBridge, and xalanc::XercesAttrWrapper.
Referenced by xalanc::DOMServices::getNodeData().
getOwnerDocument()
virtual XalanDocument* xalanc::XalanAttr::getOwnerDocument () const pure virtual
Gets the XalanDocument object associated with this node.
This may be a null pointer.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
getOwnerElement()
virtual XalanElement* xalanc::XalanAttr::getOwnerElement () const pure virtual
The XalanElement node this attribute is attached to.
If there is no such node, this returns a null pointer.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
getParentNode()
virtual XalanNode* xalanc::XalanAttr::getParentNode () const pure virtual
Gets the parent of this node.
If there is no such node, this returns a null pointer.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
getPrefix()
virtual const XalanDOMString& xalanc::XalanAttr::getPrefix () const pure virtual
Get the namespace prefix of this node.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, xalanc::XercesAttrWrapper, and xalanc::XalanSourceTreeAttrNS.
getPreviousSibling()
virtual XalanNode* xalanc::XalanAttr::getPreviousSibling () const pure virtual
Gets the node immediately preceding this node.
If there is no such node, this returns a null pointer.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
getValue()
virtual const XalanDOMString& xalanc::XalanAttr::getValue () const pure virtual
Returns the value of the attribute.
The value of the attribute is returned as a string.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
isIndexed()
virtual bool xalanc::XalanAttr::isIndexed () const pure virtual
Determine if the document is node-order indexed.
Returns
true if the document is indexed, otherwise false.
Implements xalanc::XalanNode.
Implemented in xalanc::XercesAttrBridge, xalanc::XalanSourceTreeAttr, and xalanc::XercesAttrWrapper.
operator=()
XalanAttr& xalanc::XalanAttr::operator= (const XalanAttr & theSource) protected
operator==()
bool xalanc::XalanAttr::operator== (const XalanAttr & theRHS) const protected
The documentation for this class was generated from the following file:
xalanc/XalanDOM/XalanAttr.hpp