Xalan-C++ API Reference: xalanc::XPathExecutionContext Class Reference
xalanc::XPathExecutionContext Class Reference abstract
#include <xalanc/XPath/XPathExecutionContext.hpp>
Classes
class ContextNodeListPushAndPop
class CurrentNodePushAndPop
class GetCachedNodeList
class GetCachedString
class PrefixResolverSetAndRestore
Public Types
typedef XalanVector< XObjectPtr > XObjectArgVectorType
typedef NodeRefListBase::size_type size_type
typedef GetCachedNodeList BorrowReturnMutableNodeRefList
typedef GetCachedString GetAndReleaseCachedString
Public Types inherited from xalanc::ProblemListenerBase
enum eSource {
eXMLPARSER = 0, eXMLParser = 0, eXSLPROCESSOR = 1, eXSLTProcessor = 1,
eXPATH = 2, eXPath = 2, eSourceCount
}
enum eClassification {
eMESSAGE = 0, eMessage = 0, eWARNING = 1, eWarning = 1,
eERROR = 2, eError = 2, eClassificationCount
}
typedef eSource eProblemSource
Public Member Functions
XPathExecutionContext (MemoryManager &theMemoryManager, XObjectFactory *theXObjectFactory=0)
virtual ~XPathExecutionContext ()
virtual void reset ()=0
Reset the instance.
virtual XalanNode * getCurrentNode () const =0
Retrieve the node currently being executed.
virtual void pushCurrentNode (XalanNode *theCurrentNode)=0
Change the node currently being executed.
virtual void popCurrentNode ()=0
Reset the node currently being executed.
XObjectFactory & getXObjectFactory () const
Retrieve the factory object for creating XObjects.
virtual bool isNodeAfter (const XalanNode &node1, const XalanNode &node2) const =0
Determine if a node is after another node, in document order.
virtual void pushContextNodeList (const NodeRefListBase &theList)=0
Push the node list for current context.
virtual void popContextNodeList ()=0
Pop the node list for current context.
virtual const NodeRefListBase & getContextNodeList () const =0
Get the node list for current context.
virtual size_type getContextNodeListLength () const =0
virtual size_type getContextNodeListPosition (const XalanNode &contextNode) const =0
virtual bool elementAvailable (const XalanQName &theQName) const =0
Determine if an external element is available.
virtual bool elementAvailable (const XalanDOMString &theName, const Locator *locator) const =0
Determine if an external element is available by resolving a string to a QName.
virtual bool functionAvailable (const XalanQName &theQName) const =0
Determine if a function is available.
virtual bool functionAvailable (const XalanDOMString &theName, const Locator *locator) const =0
Determine if a function is available.
virtual const XObjectPtr extFunction (const XalanDOMString &theNamespace, const XalanDOMString &functionName, XalanNode *context, const XObjectArgVectorType &argVec, const Locator *locator)=0
Handle an extension function.
virtual XalanDocument * parseXML (MemoryManager &theManager, const XalanDOMString &urlString, const XalanDOMString &base, ErrorHandler *theErrorHandler=0) const =0
Provides support for XML parsing service.
virtual MutableNodeRefList * borrowMutableNodeRefList ()=0
Borrow a cached MutableNodeRefList instance.
virtual bool returnMutableNodeRefList (MutableNodeRefList *theList)=0
Return a previously borrowed MutableNodeRefList instance.
virtual XalanDOMString & getCachedString ()=0
Get a cached string for temporary use.
virtual bool releaseCachedString (XalanDOMString &theString)=0
Return a cached string.
virtual MutableNodeRefList * createMutableNodeRefList (MemoryManager &theManager) const =0
Create a MutableNodeRefList with the appropriate context.
virtual void getNodeSetByKey (XalanNode *context, const XalanQName &qname, const XalanDOMString &ref, const Locator *locator, MutableNodeRefList &nodelist)=0
Given a valid element key, return the corresponding node list.
virtual void getNodeSetByKey (XalanNode *context, const XalanDOMString &name, const XalanDOMString &ref, const Locator *locator, MutableNodeRefList &nodelist)=0
Given a valid element key, return the corresponding node list.
virtual const XObjectPtr getVariable (const XalanQName &name, const Locator *locator=0)=0
Given a name, locate a variable in the current context, and return a pointer to the object.
virtual const PrefixResolver * getPrefixResolver () const =0
Retrieve the resolver for namespaces.
virtual void setPrefixResolver (const PrefixResolver *thePrefixResolver)=0
Change the resolver for namespaces.
virtual const XalanDOMString * getNamespaceForPrefix (const XalanDOMString &prefix) const =0
Retrieve the URI corresponding to a namespace prefix.
virtual const XalanDOMString & findURIFromDoc (const XalanDocument *owner) const =0
Given a DOM Document, tell what URI was used to parse it.
virtual const XalanDOMString & getUnparsedEntityURI (const XalanDOMString &theName, const XalanDocument &theDocument) const =0
The getUnparsedEntityURI function returns the URI of the unparsed entity with the specified name in the same document as the context node (see [3.3 Unparsed Entities]).
virtual XalanDocument * getSourceDocument (const XalanDOMString &theURI) const =0
Get the document associated with the given URI.
virtual void setSourceDocument (const XalanDOMString &theURI, XalanDocument *theDocument)=0
Associate a document with a given URI.
virtual void formatNumber (double number, const XalanDOMString &pattern, XalanDOMString &theResult, const XalanNode *context=0, const Locator *locator=0)=0
Formats a number according to the specified pattern.
virtual void formatNumber (double number, const XalanDOMString &pattern, const XalanDOMString &dfsName, XalanDOMString &theResult, const XalanNode *context=0, const Locator *locator=0)=0
Formats a number according to the specified pattern.
virtual void problem (eSource source, eClassification classification, const XalanDOMString &msg, const Locator *locator, const XalanNode *sourceNode)=0
Function that is called when a problem event occurs.
virtual void problem (eSource source, eClassification classification, const XalanDOMString &msg, const XalanNode *sourceNode)=0
Function that is called when a problem event occurs.
virtual bool shouldStripSourceNode (const XalanText &node)=0
Determine if a text node should be stripped from the source tree, as if it weren't there.
Public Member Functions inherited from xalanc::ExecutionContext
ExecutionContext (MemoryManager &theMemoryManager)
virtual ~ExecutionContext ()
bool hasPreserveOrStripSpaceConditions () const
MemoryManager & getMemoryManager () const
MemoryManager & getExceptionMemoryManager () const
Public Member Functions inherited from xalanc::ProblemListenerBase
ProblemListenerBase ()
virtual ~ProblemListenerBase ()
Protected Attributes
XObjectFactory * m_xobjectFactory
Protected Attributes inherited from xalanc::ExecutionContext
MemoryManager & m_memoryManager
bool m_hasPreserveOrStripConditions
Additional Inherited Members
Static Public Member Functions inherited from xalanc::ProblemListenerBase
static void defaultFormat (PrintWriter &pw, eSource source, eClassification classification, const XalanDOMString &msg, const Locator *locator, const XalanNode *sourceNode)
Function to format a problem call to a PrintWriter instance.
static void defaultFormat (PrintWriter &pw, eSource source, eClassification classification, const XalanDOMString &msg, const XalanNode *sourceNode)
Function to format a problem call to a PrintWriter instance.
Static Protected Attributes inherited from xalanc::ProblemListenerBase
static const XalanMessages::Codes s_messageCodes [eSourceCount][eClassificationCount]
Detailed Description
Definition at line 82 of file XPathExecutionContext.hpp.
Member Typedef Documentation
BorrowReturnMutableNodeRefList
typedef GetCachedNodeList xalanc::XPathExecutionContext::BorrowReturnMutableNodeRefList
Definition at line 428 of file XPathExecutionContext.hpp.
GetAndReleaseCachedString
typedef GetCachedString xalanc::XPathExecutionContext::GetAndReleaseCachedString
Definition at line 505 of file XPathExecutionContext.hpp.
size_type
typedef NodeRefListBase::size_type xalanc::XPathExecutionContext::size_type
Definition at line 88 of file XPathExecutionContext.hpp.
XObjectArgVectorType
typedef XalanVector<XObjectPtr> xalanc::XPathExecutionContext::XObjectArgVectorType
Definition at line 86 of file XPathExecutionContext.hpp.
Constructor & Destructor Documentation
XPathExecutionContext()
xalanc::XPathExecutionContext::XPathExecutionContext (MemoryManager & theMemoryManager, XObjectFactory * theXObjectFactory = 0) explicit
~XPathExecutionContext()
virtual xalanc::XPathExecutionContext::~XPathExecutionContext () virtual
Member Function Documentation
borrowMutableNodeRefList()
virtual MutableNodeRefList* xalanc::XPathExecutionContext::borrowMutableNodeRefList () pure virtual
Borrow a cached MutableNodeRefList instance.
Returns
A pointer to the instance.
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
createMutableNodeRefList()
virtual MutableNodeRefList* xalanc::XPathExecutionContext::createMutableNodeRefList (MemoryManager & theManager) const pure virtual
Create a MutableNodeRefList with the appropriate context.
Returns
pointer to node list created
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
elementAvailable() [1/2]
virtual bool xalanc::XPathExecutionContext::elementAvailable (const XalanDOMString & theName, const Locator * locator) const pure virtual
Determine if an external element is available by resolving a string to a QName.
Parameters
theName The name of the element
locator A Locator instance for error reporting
Returns
whether the given element is available or not
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
elementAvailable() [2/2]
virtual bool xalanc::XPathExecutionContext::elementAvailable (const XalanQName & theQName) const pure virtual
Determine if an external element is available.
Parameters
theQName The QName of the element
Returns
whether the given element is available or not
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
extFunction()
virtual const XObjectPtr xalanc::XPathExecutionContext::extFunction (const XalanDOMString & theNamespace, const XalanDOMString & functionName, XalanNode * context, const XObjectArgVectorType & argVec, const Locator * locator) pure virtual
Handle an extension function.
Parameters
theNamespace namespace of function
functionName extension function name
context The context node
argVec vector of arguments to function
locator A Locator instance for error reporting
Returns
pointer to XObject result
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
Referenced by xalanc::XPath::extfunction().
findURIFromDoc()
virtual const XalanDOMString& xalanc::XPathExecutionContext::findURIFromDoc (const XalanDocument * owner) const pure virtual
Given a DOM Document, tell what URI was used to parse it.
Needed for relative resolution.
Parameters
owner source document
Returns
document URI
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
formatNumber() [1/2]
virtual void xalanc::XPathExecutionContext::formatNumber (double number, const XalanDOMString & pattern, const XalanDOMString & dfsName, XalanDOMString & theResult, const XalanNode * context = 0, const Locator * locator = 0) pure virtual
Formats a number according to the specified pattern.
Parameters
number the number to be formatted
pattern the format pattern
dfsName the name of decimal format to use
theResult the formatted number
context the source node
locator the locator
Returns
a pointer to the functor, 0 if none was found
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
formatNumber() [2/2]
virtual void xalanc::XPathExecutionContext::formatNumber (double number, const XalanDOMString & pattern, XalanDOMString & theResult, const XalanNode * context = 0, const Locator * locator = 0) pure virtual
Formats a number according to the specified pattern.
Parameters
number the number to be formatted
pattern the format pattern
theResult the formatted number
context the source node
locator the locator
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
functionAvailable() [1/2]
virtual bool xalanc::XPathExecutionContext::functionAvailable (const XalanDOMString & theName, const Locator * locator) const pure virtual
Determine if a function is available.
Parameters
theName The name of the function
locator A Locator instance for error reporting
Returns
whether the function is available or not
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
functionAvailable() [2/2]
virtual bool xalanc::XPathExecutionContext::functionAvailable (const XalanQName & theQName) const pure virtual
Determine if a function is available.
Parameters
theQName The QName of the function
Returns
whether the function is available or not
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
getCachedString()
virtual XalanDOMString& xalanc::XPathExecutionContext::getCachedString () pure virtual
Get a cached string for temporary use.
Returns
A reference to the string
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
getContextNodeList()
virtual const NodeRefListBase& xalanc::XPathExecutionContext::getContextNodeList () const pure virtual
Get the node list for current context.
Returns
node list
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
getContextNodeListLength()
virtual size_type xalanc::XPathExecutionContext::getContextNodeListLength () const pure virtual
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
Referenced by xalanc::XPath::functionLast().
getContextNodeListPosition()
virtual size_type xalanc::XPathExecutionContext::getContextNodeListPosition (const XalanNode & contextNode) const pure virtual
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
Referenced by xalanc::XPath::functionPosition().
getCurrentNode()
virtual XalanNode* xalanc::XPathExecutionContext::getCurrentNode () const pure virtual
Retrieve the node currently being executed.
Returns
current node
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
Referenced by xalanc::XPath::execute().
getNamespaceForPrefix()
virtual const XalanDOMString* xalanc::XPathExecutionContext::getNamespaceForPrefix (const XalanDOMString & prefix) const pure virtual
Retrieve the URI corresponding to a namespace prefix.
Parameters
prefix prefix for a namespace
Returns
URI corresponding to namespace
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
getNodeSetByKey() [1/2]
virtual void xalanc::XPathExecutionContext::getNodeSetByKey (XalanNode * context, const XalanDOMString & name, const XalanDOMString & ref, const Locator * locator, MutableNodeRefList & nodelist) pure virtual
Given a valid element key, return the corresponding node list.
Parameters
context context node
name name of the key, which must match the 'name' attribute on xsl:key. Will be resolved to a qname using the provided resolver.
ref value that must match the value found by the 'match' attribute on xsl:key
locator The Locator to use for error reporting. Can be 0.
nodelist A node list to contain the nodes found
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
getNodeSetByKey() [2/2]
virtual void xalanc::XPathExecutionContext::getNodeSetByKey (XalanNode * context, const XalanQName & qname, const XalanDOMString & ref, const Locator * locator, MutableNodeRefList & nodelist) pure virtual
Given a valid element key, return the corresponding node list.
Parameters
context context node
name qname of the key, which must match the 'name' attribute on xsl:key
ref value that must match the value found by the 'match' attribute on xsl:key
locator The Locator to use for error reporting. Can be 0.
nodelist A node list to contain the nodes found
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
getPrefixResolver()
virtual const PrefixResolver* xalanc::XPathExecutionContext::getPrefixResolver () const pure virtual
Retrieve the resolver for namespaces.
Returns
object for namespace resolution
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
Referenced by xalanc::XPath::execute().
getSourceDocument()
virtual XalanDocument* xalanc::XPathExecutionContext::getSourceDocument (const XalanDOMString & theURI) const pure virtual
Get the document associated with the given URI.
Parameters
theURI document URI
Returns
a pointer to the document instance, if any.
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
getUnparsedEntityURI()
virtual const XalanDOMString& xalanc::XPathExecutionContext::getUnparsedEntityURI (const XalanDOMString & theName, const XalanDocument & theDocument) const pure virtual
The getUnparsedEntityURI function returns the URI of the unparsed entity with the specified name in the same document as the context node (see [3.3 Unparsed Entities]).
It returns the empty string if there is no such entity.
Parameters
theName name of entity
theDocument document containing entity
Returns
URI for the entity
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
getVariable()
virtual const XObjectPtr xalanc::XPathExecutionContext::getVariable (const XalanQName & name, const Locator * locator = 0) pure virtual
Given a name, locate a variable in the current context, and return a pointer to the object.
Parameters
theName name of variable
Returns
An XObjectPtr instance. If the variable is not found, an exception is thrown, or the routine returns an instance of XUnknown.
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
getXObjectFactory()
XObjectFactory& xalanc::XPathExecutionContext::getXObjectFactory () const inline
Retrieve the factory object for creating XObjects.
Returns
factory object instance
Definition at line 155 of file XPathExecutionContext.hpp.
isNodeAfter()
virtual bool xalanc::XPathExecutionContext::isNodeAfter (const XalanNode & node1, const XalanNode & node2) const pure virtual
Determine if a node is after another node, in document order.
Parameters
node1 The first node
node2 The second node
Returns
true if node1 one is after node2, or false if it is not.
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
parseXML()
virtual XalanDocument* xalanc::XPathExecutionContext::parseXML (MemoryManager & theManager, const XalanDOMString & urlString, const XalanDOMString & base, ErrorHandler * theErrorHandler = 0) const pure virtual
Provides support for XML parsing service.
Parameters
theManager The MemoryManager instance to use.
urlString location of the XML
base base location for URI
theErrorHandler An optional ErrorHandler instance for error reporting.
Returns
parsed document
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
popContextNodeList()
virtual void xalanc::XPathExecutionContext::popContextNodeList () pure virtual
Pop the node list for current context.
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
popCurrentNode()
virtual void xalanc::XPathExecutionContext::popCurrentNode () pure virtual
Reset the node currently being executed.
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
problem() [1/2]
virtual void xalanc::XPathExecutionContext::problem (eSource source, eClassification classification, const XalanDOMString & msg, const Locator * locator, const XalanNode * sourceNode) pure virtual
Function that is called when a problem event occurs.
Parameters
source Either eXMLParser, eXSLProcessor, or eXPATH.
classification Either eMessage, eWarning, or eError.
locator The current Locator instance for the stylesheet. Maybe be a null pointer.
sourceNode The current source node, if any.
msg The error message.
Implements xalanc::ExecutionContext.
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
problem() [2/2]
virtual void xalanc::XPathExecutionContext::problem (eSource source, eClassification classification, const XalanDOMString & msg, const XalanNode * sourceNode) pure virtual
Function that is called when a problem event occurs.
This version assumes location information is already formatted into the message.
Parameters
source either eXMLPARSER, eXSLPROCESSOR, or eXPATH
classification either eMESSAGE, eERROR or eWARNING
msg string message explaining the problem.
Implements xalanc::ExecutionContext.
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
pushContextNodeList()
virtual void xalanc::XPathExecutionContext::pushContextNodeList (const NodeRefListBase & theList) pure virtual
Push the node list for current context.
Parameters
theList new node list
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
pushCurrentNode()
virtual void xalanc::XPathExecutionContext::pushCurrentNode (XalanNode * theCurrentNode) pure virtual
Change the node currently being executed.
Parameters
theCurrentNode new current node
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
Referenced by xalanc::XPathExecutionContext::CurrentNodePushAndPop::CurrentNodePushAndPop().
releaseCachedString()
virtual bool xalanc::XPathExecutionContext::releaseCachedString (XalanDOMString & theString) pure virtual
Return a cached string.
Parameters
theString The string to release.
Returns
true if the string was released successfully.
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
reset()
virtual void xalanc::XPathExecutionContext::reset () pure virtual
Reset the instance.
This must be called before another execution is attempted.
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
returnMutableNodeRefList()
virtual bool xalanc::XPathExecutionContext::returnMutableNodeRefList (MutableNodeRefList * theList) pure virtual
Return a previously borrowed MutableNodeRefList instance.
Parameters
theList A pointer the to previously borrowed instance.
Returns
true if the list was borrowed (at therefore, destroyed), false if not.
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
setPrefixResolver()
virtual void xalanc::XPathExecutionContext::setPrefixResolver (const PrefixResolver * thePrefixResolver) pure virtual
Change the resolver for namespaces.
Parameters
thePrefixResolver new object for namespace resolution
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
setSourceDocument()
virtual void xalanc::XPathExecutionContext::setSourceDocument (const XalanDOMString & theURI, XalanDocument * theDocument) pure virtual
Associate a document with a given URI.
Parameters
theURI document URI
theDocument source document
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
shouldStripSourceNode()
virtual bool xalanc::XPathExecutionContext::shouldStripSourceNode (const XalanText & node) pure virtual
Determine if a text node should be stripped from the source tree, as if it weren't there.
Parameters
textNode text node from the source tree
Returns
true if the text node should be stripped
Implements xalanc::ExecutionContext.
Implemented in xalanc::StylesheetExecutionContext, xalanc::StylesheetExecutionContextDefault, and xalanc::XPathExecutionContextDefault.
Member Data Documentation
m_xobjectFactory
XObjectFactory* xalanc::XPathExecutionContext::m_xobjectFactory protected
Definition at line 728 of file XPathExecutionContext.hpp.
The documentation for this class was generated from the following file:
xalanc/XPath/XPathExecutionContext.hpp