Xalan-C++ API Reference: xalanc::XalanVector< Type, ConstructionTraits > Class Template Reference
xalanc::XalanVector< Type, ConstructionTraits > Class Template Reference
#include <xalanc/Include/XalanVector.hpp>
Public Types
typedef Type value_type
typedef value_type * pointer
typedef value_type & reference
typedef size_t size_type
typedef ptrdiff_t difference_type
typedef value_type * iterator
typedef std::reverse_iterator< iterator > reverse_iterator_
typedef std::reverse_iterator< const_iterator > const_reverse_iterator_
typedef reverse_iterator_ reverse_iterator
typedef const_reverse_iterator_ const_reverse_iterator
typedef XalanVector< value_type, ConstructionTraits > ThisType
typedef ConstructionTraits::Constructor Constructor
typedef Constructor::ConstructableType ConstructibleType
Public Member Functions
XalanVector (MemoryManager &theManager XALAN_DEFAULT_CONSTRUCTOR_MEMMGR, size_type initialAllocation=size_type(0))
XalanVector (const ThisType &theSource, MemoryManager &theManager XALAN_DEFAULT_CONSTRUCTOR_MEMMGR, size_type theInitialAllocation=size_type(0))
XalanVector (const_iterator theFirst, const_iterator theLast, MemoryManager &theManager)
XalanVector (size_type theInsertSize, const value_type &theData, MemoryManager &theManager)
~XalanVector ()
void push_back (const value_type &data)
void pop_back ()
iterator erase (iterator theFirst, iterator theLast)
iterator erase (iterator position)
void insert (iterator thePosition, const_iterator theFirst, const_iterator theLast)
void insert (iterator thePosition, size_type theCount, const value_type &theData)
iterator insert (iterator thePosition, const value_type &theData)
void assign (const_iterator theFirst, const_iterator theLast)
void assign (iterator theFirst, iterator theLast)
void assign (size_type theCount, const value_type &theData)
size_type size () const
size_type max_size () const
void resize (size_type theSize)
void resize (size_type theSize, const value_type &theValue)
size_type capacity () const
bool empty () const
void reserve (size_type theSize)
reference front ()
const_reference front () const
reference back ()
const_reference back () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
reference at (size_type theIndex)
const_reference at (size_type theIndex) const
reference operator[] (size_type theIndex)
const_reference operator[] (size_type theIndex) const
void clear ()
ThisType & operator= (const ThisType &theRHS)
void swap (ThisType &theOther)
const MemoryManager & getMemoryManager () const
MemoryManager & getMemoryManager ()
pointer detach ()
Static Public Member Functions
static XalanVector * create (MemoryManager &theManager, size_type initialAllocation=size_type(0))
static XalanVector * create (const_iterator theFirst, const_iterator theLast, MemoryManager &theManager)
Public Attributes
const typedef value_type * const_pointer
const typedef value_type & const_reference
const typedef value_type * const_iterator
Detailed Description
template<class Type, class ConstructionTraits = MemoryManagedConstructionTraits<Type>>
class xalanc::XalanVector< Type, ConstructionTraits >
Definition at line 58 of file XalanVector.hpp.
Member Typedef Documentation
const_reverse_iterator
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef const_reverse_iterator_ xalanc::XalanVector< Type, ConstructionTraits >::const_reverse_iterator
Definition at line 78 of file XalanVector.hpp.
const_reverse_iterator_
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef std::reverse_iterator<const_iterator> xalanc::XalanVector< Type, ConstructionTraits >::const_reverse_iterator_
Definition at line 75 of file XalanVector.hpp.
ConstructibleType
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef Constructor::ConstructableType xalanc::XalanVector< Type, ConstructionTraits >::ConstructibleType
Definition at line 83 of file XalanVector.hpp.
Constructor
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef ConstructionTraits::Constructor xalanc::XalanVector< Type, ConstructionTraits >::Constructor
Definition at line 82 of file XalanVector.hpp.
difference_type
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef ptrdiff_t xalanc::XalanVector< Type, ConstructionTraits >::difference_type
Definition at line 69 of file XalanVector.hpp.
iterator
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef value_type* xalanc::XalanVector< Type, ConstructionTraits >::iterator
Definition at line 71 of file XalanVector.hpp.
pointer
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef value_type* xalanc::XalanVector< Type, ConstructionTraits >::pointer
Definition at line 64 of file XalanVector.hpp.
reference
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef value_type& xalanc::XalanVector< Type, ConstructionTraits >::reference
Definition at line 66 of file XalanVector.hpp.
reverse_iterator
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef reverse_iterator_ xalanc::XalanVector< Type, ConstructionTraits >::reverse_iterator
Definition at line 77 of file XalanVector.hpp.
reverse_iterator_
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef std::reverse_iterator<iterator> xalanc::XalanVector< Type, ConstructionTraits >::reverse_iterator_
Definition at line 74 of file XalanVector.hpp.
size_type
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef size_t xalanc::XalanVector< Type, ConstructionTraits >::size_type
Definition at line 68 of file XalanVector.hpp.
ThisType
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef XalanVector<value_type, ConstructionTraits> xalanc::XalanVector< Type, ConstructionTraits >::ThisType
Definition at line 80 of file XalanVector.hpp.
value_type
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> typedef Type xalanc::XalanVector< Type, ConstructionTraits >::value_type
Definition at line 63 of file XalanVector.hpp.
Constructor & Destructor Documentation
XalanVector() [1/4]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> xalanc::XalanVector< Type, ConstructionTraits >::XalanVector (MemoryManager &theManager XALAN_DEFAULT_CONSTRUCTOR_MEMMGR, size_type initialAllocation = size_type(0)) inline
Definition at line 85 of file XalanVector.hpp.
XalanVector() [2/4]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> xalanc::XalanVector< Type, ConstructionTraits >::XalanVector (const ThisType & theSource, MemoryManager &theManager XALAN_DEFAULT_CONSTRUCTOR_MEMMGR, size_type theInitialAllocation = size_type(0)) inline
Definition at line 113 of file XalanVector.hpp.
XalanVector() [3/4]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> xalanc::XalanVector< Type, ConstructionTraits >::XalanVector (const_iterator theFirst, const_iterator theLast, MemoryManager & theManager) inline
Definition at line 141 of file XalanVector.hpp.
XalanVector() [4/4]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> xalanc::XalanVector< Type, ConstructionTraits >::XalanVector (size_type theInsertSize, const value_type & theData, MemoryManager & theManager) inline
Definition at line 178 of file XalanVector.hpp.
~XalanVector()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> xalanc::XalanVector< Type, ConstructionTraits >::~XalanVector () inline
Definition at line 196 of file XalanVector.hpp.
Member Function Documentation
assign() [1/3]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanVector< Type, ConstructionTraits >::assign (const_iterator theFirst, const_iterator theLast) inline
Definition at line 501 of file XalanVector.hpp.
assign() [2/3]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanVector< Type, ConstructionTraits >::assign (iterator theFirst, iterator theLast) inline
Definition at line 514 of file XalanVector.hpp.
assign() [3/3]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanVector< Type, ConstructionTraits >::assign (size_type theCount, const value_type & theData) inline
Definition at line 524 of file XalanVector.hpp.
at() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> reference xalanc::XalanVector< Type, ConstructionTraits >::at (size_type theIndex) inline
Definition at line 714 of file XalanVector.hpp.
at() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const_reference xalanc::XalanVector< Type, ConstructionTraits >::at (size_type theIndex) const inline
Definition at line 725 of file XalanVector.hpp.
back() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> reference xalanc::XalanVector< Type, ConstructionTraits >::back () inline
Definition at line 637 of file XalanVector.hpp.
Referenced by xalanc::EnumerateDirectory(), xalanc::Counter::getLast(), and xalanc::XalanDeque< XercesBridgeNavigator >::pop_back().
back() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const_reference xalanc::XalanVector< Type, ConstructionTraits >::back () const inline
Definition at line 643 of file XalanVector.hpp.
begin() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> iterator xalanc::XalanVector< Type, ConstructionTraits >::begin () inline
Definition at line 649 of file XalanVector.hpp.
Referenced by xalanc::XalanMap< const XalanDOMChar *, XalanSourceTreeElement * >::compactBuckets(), xalanc::XalanMap< const XalanDOMChar *, XalanSourceTreeElement * >::find(), xalanc::operator<(), xalanc::XalanVector< XalanDOMChar >::operator=(), xalanc::operator==(), and xalanc::XalanVector< XalanDOMChar >::XalanVector().
begin() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const_iterator xalanc::XalanVector< Type, ConstructionTraits >::begin () const inline
Definition at line 657 of file XalanVector.hpp.
capacity()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> size_type xalanc::XalanVector< Type, ConstructionTraits >::capacity () const inline
Definition at line 592 of file XalanVector.hpp.
Referenced by xalanc::XalanMap< const XalanDOMChar *, XalanSourceTreeElement * >::compactBuckets().
clear()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanVector< Type, ConstructionTraits >::clear () inline
Definition at line 752 of file XalanVector.hpp.
Referenced by xalanc::XSLTEngineImpl::clearTopLevelParams().
create() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> static XalanVector* xalanc::XalanVector< Type, ConstructionTraits >::create (const_iterator theFirst, const_iterator theLast, MemoryManager & theManager) inline static
Definition at line 161 of file XalanVector.hpp.
create() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> static XalanVector* xalanc::XalanVector< Type, ConstructionTraits >::create (MemoryManager & theManager, size_type initialAllocation = size_type(0)) inline static
Definition at line 97 of file XalanVector.hpp.
detach()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> pointer xalanc::XalanVector< Type, ConstructionTraits >::detach () inline
Definition at line 857 of file XalanVector.hpp.
empty()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> bool xalanc::XalanVector< Type, ConstructionTraits >::empty () const inline
Definition at line 600 of file XalanVector.hpp.
Referenced by xalanc::c_str(), xalanc::Counter::getLast(), xalanc::XalanDeque< XercesBridgeNavigator >::pop_back(), and xalanc::toCharArray().
end() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> iterator xalanc::XalanVector< Type, ConstructionTraits >::end () inline
Definition at line 665 of file XalanVector.hpp.
Referenced by xalanc::XalanMap< const XalanDOMChar *, XalanSourceTreeElement * >::compactBuckets(), xalanc::XalanMap< const XalanDOMChar *, XalanSourceTreeElement * >::find(), xalanc::XalanVector< XalanDOMChar >::insert(), xalanc::operator<(), xalanc::XalanVector< XalanDOMChar >::operator=(), xalanc::operator==(), and xalanc::XalanVector< XalanDOMChar >::XalanVector().
end() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const_iterator xalanc::XalanVector< Type, ConstructionTraits >::end () const inline
Definition at line 673 of file XalanVector.hpp.
erase() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> iterator xalanc::XalanVector< Type, ConstructionTraits >::erase (iterator position) inline
Definition at line 253 of file XalanVector.hpp.
erase() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> iterator xalanc::XalanVector< Type, ConstructionTraits >::erase (iterator theFirst, iterator theLast) inline
Definition at line 231 of file XalanVector.hpp.
Referenced by xalanc::XalanMap< const XalanDOMChar *, XalanSourceTreeElement * >::compactBuckets().
front() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> reference xalanc::XalanVector< Type, ConstructionTraits >::front () inline
Definition at line 621 of file XalanVector.hpp.
front() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const_reference xalanc::XalanVector< Type, ConstructionTraits >::front () const inline
Definition at line 629 of file XalanVector.hpp.
getMemoryManager() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> MemoryManager& xalanc::XalanVector< Type, ConstructionTraits >::getMemoryManager () inline
Definition at line 845 of file XalanVector.hpp.
getMemoryManager() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const MemoryManager& xalanc::XalanVector< Type, ConstructionTraits >::getMemoryManager () const inline
Definition at line 837 of file XalanVector.hpp.
insert() [1/3]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> iterator xalanc::XalanVector< Type, ConstructionTraits >::insert (iterator thePosition, const value_type & theData) inline
Definition at line 479 of file XalanVector.hpp.
insert() [2/3]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanVector< Type, ConstructionTraits >::insert (iterator thePosition, const_iterator theFirst, const_iterator theLast) inline
Definition at line 259 of file XalanVector.hpp.
Referenced by xalanc::XalanVector< XalanDOMChar >::insert(), and xalanc::XalanVector< XalanDOMChar >::XalanVector().
insert() [3/3]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanVector< Type, ConstructionTraits >::insert (iterator thePosition, size_type theCount, const value_type & theData) inline
Definition at line 378 of file XalanVector.hpp.
max_size()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> size_type xalanc::XalanVector< Type, ConstructionTraits >::max_size () const inline
Definition at line 542 of file XalanVector.hpp.
operator=()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> ThisType& xalanc::XalanVector< Type, ConstructionTraits >::operator= (const ThisType & theRHS) inline
Definition at line 766 of file XalanVector.hpp.
operator[]() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> reference xalanc::XalanVector< Type, ConstructionTraits >::operator[] (size_type theIndex) inline
Definition at line 736 of file XalanVector.hpp.
operator[]() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const_reference xalanc::XalanVector< Type, ConstructionTraits >::operator[] (size_type theIndex) const inline
Definition at line 744 of file XalanVector.hpp.
pop_back()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanVector< Type, ConstructionTraits >::pop_back () inline
Definition at line 219 of file XalanVector.hpp.
Referenced by xalanc::EnumerateDirectory(), and xalanc::XalanDeque< XercesBridgeNavigator >::pop_back().
push_back()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanVector< Type, ConstructionTraits >::push_back (const value_type & data) inline
Definition at line 209 of file XalanVector.hpp.
Referenced by xalanc::EnumerateDirectory(), and xalanc::XalanMap< const XalanDOMChar *, XalanSourceTreeElement * >::rehash().
rbegin() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> reverse_iterator xalanc::XalanVector< Type, ConstructionTraits >::rbegin () inline
Definition at line 681 of file XalanVector.hpp.
rbegin() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const_reverse_iterator xalanc::XalanVector< Type, ConstructionTraits >::rbegin () const inline
Definition at line 689 of file XalanVector.hpp.
rend() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> reverse_iterator xalanc::XalanVector< Type, ConstructionTraits >::rend () inline
Definition at line 697 of file XalanVector.hpp.
rend() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const_reverse_iterator xalanc::XalanVector< Type, ConstructionTraits >::rend () const inline
Definition at line 705 of file XalanVector.hpp.
reserve()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanVector< Type, ConstructionTraits >::reserve (size_type theSize) inline
Definition at line 608 of file XalanVector.hpp.
resize() [1/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanVector< Type, ConstructionTraits >::resize (size_type theSize) inline
Definition at line 550 of file XalanVector.hpp.
resize() [2/2]
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanVector< Type, ConstructionTraits >::resize (size_type theSize, const value_type & theValue) inline
Definition at line 558 of file XalanVector.hpp.
size()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> size_type xalanc::XalanVector< Type, ConstructionTraits >::size () const inline
Definition at line 534 of file XalanVector.hpp.
Referenced by xalanc::c_str(), xalanc::XalanMap< const XalanDOMChar *, XalanSourceTreeElement * >::compactBuckets(), xalanc::EnumerateDirectory(), and xalanc::operator==().
swap()
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> void xalanc::XalanVector< Type, ConstructionTraits >::swap (ThisType & theOther) inline
Definition at line 814 of file XalanVector.hpp.
Referenced by xalanc::XalanMap< const XalanDOMChar *, XalanSourceTreeElement * >::compactBuckets(), xalanc::XalanDeque< XercesBridgeNavigator >::swap(), and xalanc::swap().
Member Data Documentation
const_iterator
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const typedef value_type* xalanc::XalanVector< Type, ConstructionTraits >::const_iterator
Definition at line 72 of file XalanVector.hpp.
const_pointer
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const typedef value_type* xalanc::XalanVector< Type, ConstructionTraits >::const_pointer
Definition at line 65 of file XalanVector.hpp.
const_reference
template<class Type , class ConstructionTraits = MemoryManagedConstructionTraits<Type>> const typedef value_type& xalanc::XalanVector< Type, ConstructionTraits >::const_reference
Definition at line 67 of file XalanVector.hpp.
The documentation for this class was generated from the following file:
xalanc/Include/XalanVector.hpp