Xalan-C++ API Reference: xalanc::XObject Class Reference
xalanc::XObject Class Reference abstract
Class to hold XPath return types.
#include <xalanc/XPath/XObject.hpp>
Classes
class XObjectException
class XObjectInvalidConversionException
Public Types
enum eObjectType {
eTypeNull = 0, eTypeUnknown = 1, eTypeBoolean = 2, eTypeNumber = 3,
eTypeString = 4, eTypeNodeSet = 5, eTypeResultTreeFrag = 6, eTypeUserDefined = 7,
eTypeStringReference = 8, eTypeStringAdapter = 9, eTypeStringCached = 10, eTypeXTokenNumberAdapter = 11,
eTypeXTokenStringAdapter = 12, eTypeNodeSetNodeProxy = 13, eUnknown
}
Enumeration of possible object types.
typedef XPathExecutionContext::GetCachedString GetCachedString
typedef void(FormatterListener::* MemberFunctionPtr) (const XMLCh *const, const FormatterListener::size_type)
Public Member Functions
XObject (eObjectType theObjectType, MemoryManager &theMemoryManager)
Create an XObject.
virtual const XalanDOMString & getTypeString () const =0
Given a request type, return the equivalent string.
virtual double num (XPathExecutionContext &executionContext) const
Cast result object to a number.
virtual double num () const
Cast result object to a number.
virtual bool boolean (XPathExecutionContext &executionContext) const =0
Cast result object to a boolean.
virtual const XalanDOMString & str (XPathExecutionContext &executionContext) const =0
Cast result object to a string.
virtual const XalanDOMString & str () const =0
Cast result object to a string.
virtual void str (XPathExecutionContext &executionContext, FormatterListener &formatterListener, MemberFunctionPtr function) const =0
Send the string value to a FormatterListener instance.
virtual void str (FormatterListener &formatterListener, MemberFunctionPtr function) const =0
Send the string value to a FormatterListener instance.
virtual void str (XPathExecutionContext &executionContext, XalanDOMString &theBuffer) const =0
Append the string value directly a string.
virtual void str (XalanDOMString &theBuffer) const =0
Append the string value directly a string.
virtual double stringLength (XPathExecutionContext &executionContext) const =0
Get the length of the string value of the instance.
virtual const XalanDocumentFragment & rtree () const
Cast result object to a result tree fragment.
virtual const NodeRefListBase & nodeset () const
Cast result object to a nodelist.
virtual void ProcessXObjectTypeCallback (XObjectTypeCallback &theCallbackObject)=0
Process a callback request for preferred type information.
virtual void ProcessXObjectTypeCallback (XObjectTypeCallback &theCallbackObject) const =0
Process a callback request for preferred type information.
bool equals (const XObject &theRHS, XPathExecutionContext &executionContext) const
Tell if two objects are functionally equal.
bool notEquals (const XObject &theRHS, XPathExecutionContext &executionContext) const
Tell if two objects are functionally not equal.
bool lessThan (const XObject &theRHS, XPathExecutionContext &executionContext) const
Tell if one object is less than the other.
bool lessThanOrEquals (const XObject &theRHS, XPathExecutionContext &executionContext) const
Tell if one object is less than or equal the other.
bool greaterThan (const XObject &theRHS, XPathExecutionContext &executionContext) const
Tell if one object is greater than the other.
bool greaterThanOrEquals (const XObject &theRHS, XPathExecutionContext &executionContext) const
Tell if one object is greater than or equal the other.
eObjectType getType () const
Tell what kind of class this is.
void setFactory (XObjectFactory *theFactory)
Static Public Member Functions
static void initialize (MemoryManager &theMemoryManager)
Perform static initialization.
static void terminate ()
Perform static shut down.
static bool boolean (double theNumber)
Static conversion function.
static bool boolean (const XalanDOMString &theString)
Static conversion function.
static bool boolean (const NodeRefListBase &theNodeList)
Static conversion function.
static const XalanDOMString & string (bool theBool)
Static conversion function.
static void string (bool theBool, XalanDOMString &theString)
Static conversion function.
static void string (bool theBool, FormatterListener &formatterListener, MemberFunctionPtr function)
Static conversion function.
static void string (double theNumber, XalanDOMString &theString)
Static conversion function.
static void string (double theNumber, FormatterListener &formatterListener, MemberFunctionPtr function)
Static conversion function.
static void string (const XalanNode &theNode, XalanDOMString &theString)
Static conversion function.
static void string (const XalanNode &theNode, FormatterListener &formatterListener, MemberFunctionPtr function)
Static conversion function.
static void string (const NodeRefListBase &theNodeList, XalanDOMString &theString)
Static conversion function.
static void string (const NodeRefListBase &theNodeList, FormatterListener &formatterListener, MemberFunctionPtr function)
Static conversion function.
static void string (const XalanNode &theNode, XPathExecutionContext &theExecutionContext, XalanDOMString &theString)
Static conversion function.
static void string (const XalanNode &theNode, XPathExecutionContext &theExecutionContext, FormatterListener &formatterListener, MemberFunctionPtr function)
Static conversion function.
static void string (const NodeRefListBase &theNodeList, XPathExecutionContext &theExecutionContext, XalanDOMString &theString)
Static conversion function.
static void string (const NodeRefListBase &theNodeList, XPathExecutionContext &theExecutionContext, FormatterListener &formatterListener, MemberFunctionPtr function)
Static conversion function.
static void string (const XalanDOMString &theString, FormatterListener &formatterListener, MemberFunctionPtr function)
Calls the supplied FormatterListener member function with the string.
static double number (bool theBoolean)
Static conversion function.
static double number (const XalanDOMString &theString, MemoryManager &theManager)
static double number (XPathExecutionContext &executionContext, const NodeRefListBase &theNodeList)
Static conversion function.
static double number (XPathExecutionContext &executionContext, const XalanNode &theNode)
Static conversion function.
Protected Member Functions
XObject (const XObject &)
Create an XObject from another XObject.
XObject (const XObject &source, MemoryManager &theManager)
Create an XObject from another XObject.
MemoryManager & getMemoryManager () const
Get the MemoryManager for this instance.
void throwInvalidConversionException (const XalanDOMString &theTargetType) const
virtual eObjectType getRealType () const
Tell what kind of class this is.
virtual void referenced ()
virtual void dereferenced ()
virtual ~XObject ()
Protected Member Functions inherited from xalanc::XalanReferenceCountedObject
XalanReferenceCountedObject ()
Create a XalanReferenceCountedObject.
virtual ~XalanReferenceCountedObject ()
virtual XalanSize_t getReferenceCount () const
Static Protected Attributes
static const XalanDOMString s_emptyString
static const XalanDOMString & s_booleanString
static const XalanDOMString & s_falseString
static const XalanDOMString & s_nodesetString
static const XalanDOMString & s_numberString
static const XalanDOMString & s_resultTreeFragmentString
static const XalanDOMString & s_stringString
static const XalanDOMString & s_trueString
Friends
class XObjectPtr
class XObjectFactory
Additional Inherited Members
Static Protected Member Functions inherited from xalanc::XalanReferenceCountedObject
static void addReference (XalanReferenceCountedObject *theInstance)
Increment reference count.
static void removeReference (XalanReferenceCountedObject *theInstance)
Decrement reference count.
Detailed Description
Class to hold XPath return types.
Definition at line 63 of file XObject.hpp.
Member Typedef Documentation
GetCachedString
typedef XPathExecutionContext::GetCachedString xalanc::XObject::GetCachedString
Definition at line 69 of file XObject.hpp.
MemberFunctionPtr
typedef void(FormatterListener::* xalanc::XObject::MemberFunctionPtr) (const XMLCh *const, const FormatterListener::size_type)
Definition at line 180 of file XObject.hpp.
Member Enumeration Documentation
eObjectType
enum xalanc::XObject::eObjectType
Enumeration of possible object types.
Enumerator
eTypeNull
eTypeUnknown
eTypeBoolean
eTypeNumber
eTypeString
eTypeNodeSet
eTypeResultTreeFrag
eTypeUserDefined
eTypeStringReference
eTypeStringAdapter
eTypeStringCached
eTypeXTokenNumberAdapter
eTypeXTokenStringAdapter
eTypeNodeSetNodeProxy
eUnknown
Definition at line 74 of file XObject.hpp.
Constructor & Destructor Documentation
XObject() [1/3]
xalanc::XObject::XObject (eObjectType theObjectType, MemoryManager & theMemoryManager)
Create an XObject.
Parameters
theObjectType The enum for the type of the object.
theMemoryManager The MemoryManager instance.
XObject() [2/3]
xalanc::XObject::XObject (const XObject &) protected
Create an XObject from another XObject.
The recommended copy constructor is the next overload, that accepts an explicit MemoryManager instance.
Parameters
source The source for the copy
XObject() [3/3]
xalanc::XObject::XObject (const XObject & source, MemoryManager & theManager) protected
Create an XObject from another XObject.
Parameters
source The source for the copy
theMemoryManager The MemoryManager instance.
~XObject()
virtual xalanc::XObject::~XObject () protected virtual
Referenced by xalanc::XObjectFactory::deleteObject().
Member Function Documentation
boolean() [1/4]
static bool xalanc::XObject::boolean (const NodeRefListBase & theNodeList) inline static
Static conversion function.
Returns the boolean value of the supplied NodeRefListBase.
Parameters
theNodeList The NodeRefListBase to convert.
Returns
bool value
Definition at line 398 of file XObject.hpp.
References xalanc::NodeRefListBase::getLength().
boolean() [2/4]
static bool xalanc::XObject::boolean (const XalanDOMString & theString) inline static
Static conversion function.
Returns the boolean value of the supplied XalanDOMString.
Parameters
theString The XalanDOMString to convert.
Returns
bool value
Definition at line 385 of file XObject.hpp.
References xalanc::XalanDOMString::length().
boolean() [3/4]
static bool xalanc::XObject::boolean (double theNumber) inline static
Static conversion function.
Returns the boolean value of the supplied double.
Parameters
theString The double to convert.
Returns
bool value
Definition at line 372 of file XObject.hpp.
boolean() [4/4]
virtual bool xalanc::XObject::boolean (XPathExecutionContext & executionContext) const pure virtual
Cast result object to a boolean.
Parameters
executionContext The current XPathExecutionContext
Returns
boolean value
Implemented in xalanc::XToken, xalanc::XUnknown, xalanc::XResultTreeFrag, xalanc::XStringBase, xalanc::XBoolean, xalanc::XNumberBase, and xalanc::XNodeSetBase.
dereferenced()
virtual void xalanc::XObject::dereferenced () protected virtual
Implements xalanc::XalanReferenceCountedObject.
Reimplemented in xalanc::XToken, and xalanc::XResultTreeFrag.
equals()
bool xalanc::XObject::equals (const XObject & theRHS, XPathExecutionContext & executionContext) const
Tell if two objects are functionally equal.
Parameters
theRHS object to compare
executionContext the current execution context
Returns
true if they are equal
getMemoryManager()
MemoryManager& xalanc::XObject::getMemoryManager () const inline protected
Get the MemoryManager for this instance.
Returns
The MemoryManager.
Definition at line 821 of file XObject.hpp.
getRealType()
virtual eObjectType xalanc::XObject::getRealType () const protected virtual
Tell what kind of class this is.
Returns
numeric type value
Reimplemented in xalanc::XTokenNumberAdapter, xalanc::XTokenStringAdapter, xalanc::XNodeSetNodeProxy, xalanc::XStringAdapter, xalanc::XStringCached, and xalanc::XStringReference.
Referenced by xalanc::XObjectFactory::getRealType().
getType()
eObjectType xalanc::XObject::getType () const inline
Tell what kind of class this is.
Returns
numeric type value
Definition at line 358 of file XObject.hpp.
getTypeString()
virtual const XalanDOMString& xalanc::XObject::getTypeString () const pure virtual
Given a request type, return the equivalent string.
For diagnostic purposes.
Returns
string for type
Implemented in xalanc::XToken, xalanc::XUnknown, xalanc::XResultTreeFrag, xalanc::XStringBase, xalanc::XBoolean, xalanc::XNumberBase, and xalanc::XNodeSetBase.
greaterThan()
bool xalanc::XObject::greaterThan (const XObject & theRHS, XPathExecutionContext & executionContext) const
Tell if one object is greater than the other.
Parameters
theRHS object to compare
Returns
true if they are equal
greaterThanOrEquals()
bool xalanc::XObject::greaterThanOrEquals (const XObject & theRHS, XPathExecutionContext & executionContext) const
Tell if one object is greater than or equal the other.
Parameters
theRHS object to compare
Returns
true if they are equal
initialize()
static void xalanc::XObject::initialize (MemoryManager & theMemoryManager) static
Perform static initialization.
See class XPathInit.
Parameters
theMemoryManager The MemoryManager instance.
lessThan()
bool xalanc::XObject::lessThan (const XObject & theRHS, XPathExecutionContext & executionContext) const
Tell if one object is less than the other.
Parameters
theRHS object to compare
Returns
true if they are equal
lessThanOrEquals()
bool xalanc::XObject::lessThanOrEquals (const XObject & theRHS, XPathExecutionContext & executionContext) const
Tell if one object is less than or equal the other.
Parameters
theRHS object to compare
Returns
true if they are equal
nodeset()
virtual const NodeRefListBase& xalanc::XObject::nodeset () const virtual
Cast result object to a nodelist.
This function does not have access to the current XPathExecutionContext, so the result may contain data from whitespace text nodes that might have been stripped otherwise.
Parameters
executionContext The current XPathExecutionContext
Returns
node list
Reimplemented in xalanc::XNodeSetBase, xalanc::XNodeSet, and xalanc::XNodeSetNodeProxy.
Referenced by xalanc::XPath::group().
notEquals()
bool xalanc::XObject::notEquals (const XObject & theRHS, XPathExecutionContext & executionContext) const
Tell if two objects are functionally not equal.
Parameters
theRHS object to compare
executionContext the current execution context
Returns
true if they are equal
num() [1/2]
virtual double xalanc::XObject::num () const virtual
Cast result object to a number.
This function does not have access to the current XPathExecutionContext, so the result may contain data from whitespace text nodes that might have been stripped otherwise.
Returns
numeric value
Reimplemented in xalanc::XToken, xalanc::XUnknown, xalanc::XResultTreeFrag, xalanc::XTokenNumberAdapter, xalanc::XTokenStringAdapter, and xalanc::XNumber.
num() [2/2]
virtual double xalanc::XObject::num (XPathExecutionContext & executionContext) const virtual
Cast result object to a number.
Parameters
executionContext The current XPathExecutionContext
Returns
numeric value
Reimplemented in xalanc::XNumberBase, xalanc::XToken, xalanc::XUnknown, xalanc::XResultTreeFrag, xalanc::XStringBase, xalanc::XTokenNumberAdapter, xalanc::XBoolean, xalanc::XTokenStringAdapter, xalanc::XNumber, and xalanc::XNodeSetBase.
number() [1/4]
static double xalanc::XObject::number (bool theBoolean) inline static
Static conversion function.
Returns
bool value
Definition at line 693 of file XObject.hpp.
number() [2/4]
static double xalanc::XObject::number (const XalanDOMString & theString, MemoryManager & theManager) inline static
Definition at line 699 of file XObject.hpp.
number() [3/4]
static double xalanc::XObject::number (XPathExecutionContext & executionContext, const NodeRefListBase & theNodeList) static
Static conversion function.
Returns
The number value of the node list
number() [4/4]
static double xalanc::XObject::number (XPathExecutionContext & executionContext, const XalanNode & theNode) static
Static conversion function.
Returns
The number value of the node
ProcessXObjectTypeCallback() [1/2]
virtual void xalanc::XObject::ProcessXObjectTypeCallback (XObjectTypeCallback & theCallbackObject) const pure virtual
Process a callback request for preferred type information.
Parameters
theCallbackObject object to call back
Implemented in xalanc::XToken, xalanc::XResultTreeFrag, xalanc::XUnknown, xalanc::XStringBase, xalanc::XBoolean, xalanc::XNodeSetBase, and xalanc::XNumberBase.
ProcessXObjectTypeCallback() [2/2]
virtual void xalanc::XObject::ProcessXObjectTypeCallback (XObjectTypeCallback & theCallbackObject) pure virtual
Process a callback request for preferred type information.
Parameters
theCallbackObject object to call back
Implemented in xalanc::XToken, xalanc::XResultTreeFrag, xalanc::XUnknown, xalanc::XStringBase, xalanc::XBoolean, xalanc::XNodeSetBase, and xalanc::XNumberBase.
referenced()
virtual void xalanc::XObject::referenced () protected virtual
Implements xalanc::XalanReferenceCountedObject.
Reimplemented in xalanc::XToken.
rtree()
virtual const XalanDocumentFragment& xalanc::XObject::rtree () const virtual
Cast result object to a result tree fragment.
Parameters
executionContext The current XPathExecutionContext
Returns
result tree fragment
Reimplemented in xalanc::XResultTreeFrag, xalanc::XStringBase, and xalanc::XNodeSetBase.
Referenced by xalanc::XSLTEngineImpl::outputResultTreeFragment().
setFactory()
void xalanc::XObject::setFactory (XObjectFactory * theFactory) inline
Definition at line 731 of file XObject.hpp.
str() [1/6]
virtual const XalanDOMString& xalanc::XObject::str () const pure virtual
Cast result object to a string.
This function does not have access to the current XPathExecutionContext, so the result may contain data from whitespace text nodes that might have been stripped otherwise.
Parameters
executionContext The current XPathExecutionContext
Returns
string value
Implemented in xalanc::XStringBase, xalanc::XNumberBase, xalanc::XToken, xalanc::XUnknown, xalanc::XResultTreeFrag, xalanc::XString, xalanc::XTokenNumberAdapter, xalanc::XBoolean, xalanc::XTokenStringAdapter, xalanc::XNodeSetBase, xalanc::XNumber, xalanc::XStringAdapter, xalanc::XStringCached, and xalanc::XStringReference.
str() [2/6]
virtual void xalanc::XObject::str (FormatterListener & formatterListener, MemberFunctionPtr function) const pure virtual
Send the string value to a FormatterListener instance.
This function does not have access to the current XPathExecutionContext, so the result may contain data from whitespace text nodes that might have been stripped otherwise.
Parameters
formatterListener The FormatterListener instance
function A pointer to the member function of FormatterListener to call
Implemented in xalanc::XStringBase, xalanc::XNumberBase, xalanc::XToken, xalanc::XUnknown, xalanc::XResultTreeFrag, xalanc::XString, xalanc::XTokenNumberAdapter, xalanc::XBoolean, xalanc::XTokenStringAdapter, xalanc::XNodeSetBase, xalanc::XNumber, xalanc::XStringAdapter, xalanc::XStringCached, and xalanc::XStringReference.
str() [3/6]
virtual void xalanc::XObject::str (XalanDOMString & theBuffer) const pure virtual
Append the string value directly a string.
This function does not have access to the current XPathExecutionContext, so the result may contain data from whitespace text nodes that might have been stripped otherwise.
Parameters
theBuffer The buffer for the data
Implemented in xalanc::XStringBase, xalanc::XNumberBase, xalanc::XToken, xalanc::XUnknown, xalanc::XResultTreeFrag, xalanc::XString, xalanc::XTokenNumberAdapter, xalanc::XBoolean, xalanc::XTokenStringAdapter, xalanc::XNodeSetBase, xalanc::XNumber, xalanc::XStringAdapter, xalanc::XStringCached, and xalanc::XStringReference.
str() [4/6]
virtual const XalanDOMString& xalanc::XObject::str (XPathExecutionContext & executionContext) const pure virtual
Cast result object to a string.
Parameters
executionContext The current XPathExecutionContext
Returns
string value
Implemented in xalanc::XStringBase, xalanc::XNumberBase, xalanc::XToken, xalanc::XUnknown, xalanc::XResultTreeFrag, xalanc::XString, xalanc::XTokenNumberAdapter, xalanc::XBoolean, xalanc::XTokenStringAdapter, xalanc::XNodeSetBase, xalanc::XNumber, xalanc::XStringAdapter, xalanc::XStringCached, and xalanc::XStringReference.
str() [5/6]
virtual void xalanc::XObject::str (XPathExecutionContext & executionContext, FormatterListener & formatterListener, MemberFunctionPtr function) const pure virtual
Send the string value to a FormatterListener instance.
Parameters
executionContext The current XPathExecutionContext
formatterListener The FormatterListener instance
function A pointer to the member function of FormatterListener to call
Implemented in xalanc::XStringBase, xalanc::XNumberBase, xalanc::XToken, xalanc::XUnknown, xalanc::XResultTreeFrag, xalanc::XString, xalanc::XTokenNumberAdapter, xalanc::XBoolean, xalanc::XTokenStringAdapter, xalanc::XNodeSetBase, xalanc::XNumber, xalanc::XStringAdapter, xalanc::XStringCached, and xalanc::XStringReference.
str() [6/6]
virtual void xalanc::XObject::str (XPathExecutionContext & executionContext, XalanDOMString & theBuffer) const pure virtual
Append the string value directly a string.
Parameters
executionContext The current XPathExecutionContext
theBuffer The buffer for the data
Implemented in xalanc::XStringBase, xalanc::XNumberBase, xalanc::XToken, xalanc::XUnknown, xalanc::XResultTreeFrag, xalanc::XString, xalanc::XTokenNumberAdapter, xalanc::XBoolean, xalanc::XTokenStringAdapter, xalanc::XNodeSetBase, xalanc::XNumber, xalanc::XStringAdapter, xalanc::XStringCached, and xalanc::XStringReference.
string() [1/14]
static const XalanDOMString& xalanc::XObject::string (bool theBool) inline static
Static conversion function.
Returns a reference to a XalanDOMString instance with the string value of the boolean.
Parameters
theBool The boolean value to convert.
Returns
The string value of the boolean
Definition at line 412 of file XObject.hpp.
string() [2/14]
static void xalanc::XObject::string (bool theBool, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Static conversion function.
Calls the supplied FormatterListener member function with the string value of the boolean.
Parameters
theBool The boolean value to convert.
formatterListener The FormatterListener instance.
function The FormatterListener member function to call.
Definition at line 441 of file XObject.hpp.
string() [3/14]
static void xalanc::XObject::string (bool theBool, XalanDOMString & theString) inline static
Static conversion function.
Appends the supplied boolean value to a string.
Parameters
theBool The boolean value to convert.
theString The string value of the provided boolean value.
Definition at line 425 of file XObject.hpp.
References xalanc::XalanDOMString::append().
string() [4/14]
static void xalanc::XObject::string (const NodeRefListBase & theNodeList, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Static conversion function.
Calls the supplied FormatterListener member function with the string value of the NodeRefListBase.
Deprecated:
This function is deprecated and should not be used.
Parameters
theNodeList The NodeRefListBase to convert.
formatterListener The FormatterListener instance.
function The FormatterListener member function to call.
Definition at line 557 of file XObject.hpp.
References xalanc::NodeRefListBase::getLength(), and xalanc::NodeRefListBase::item().
string() [5/14]
static void xalanc::XObject::string (const NodeRefListBase & theNodeList, XalanDOMString & theString) inline static
Static conversion function.
Append the string value of the NodeRefListBase to the supplied XalanDOMString parameter.
Deprecated:
This function is deprecated and should not be used.
Parameters
theNodeList The NodeRefListBase to convert.
theString The output XalanDOMString.
Definition at line 534 of file XObject.hpp.
References xalanc::NodeRefListBase::getLength(), and xalanc::NodeRefListBase::item().
string() [6/14]
static void xalanc::XObject::string (const NodeRefListBase & theNodeList, XPathExecutionContext & theExecutionContext, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Static conversion function.
Calls the supplied FormatterListener member function with the string value of the NodeRefListBase.
Parameters
theNodeList The NodeRefListBase to convert.
theExecutionContext The current XPathExecutionContext.
formatterListener The FormatterListener instance.
function The FormatterListener member function to call.
Definition at line 642 of file XObject.hpp.
References xalanc::NodeRefListBase::getLength(), and xalanc::NodeRefListBase::item().
string() [7/14]
static void xalanc::XObject::string (const NodeRefListBase & theNodeList, XPathExecutionContext & theExecutionContext, XalanDOMString & theString) inline static
Static conversion function.
Append the string value of the NodeRefListBase to the supplied XalanDOMString parameter.
Parameters
theNodeList The NodeRefListBase to convert.
theExecutionContext The current XPathExecutionContext.
theString The output XalanDOMString.
Definition at line 619 of file XObject.hpp.
References xalanc::NodeRefListBase::getLength(), and xalanc::NodeRefListBase::item().
string() [8/14]
static void xalanc::XObject::string (const XalanDOMString & theString, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Calls the supplied FormatterListener member function with the string.
Parameters
theString The XalanDOMString to convert.
formatterListener The FormatterListener instance.
function The FormatterListener member function to call.
Definition at line 669 of file XObject.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
string() [9/14]
static void xalanc::XObject::string (const XalanNode & theNode, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Static conversion function.
Calls the supplied FormatterListener member function with the string value of the XalanNode.
Deprecated:
This function is deprecated and should not be used.
Parameters
theNode The XalanNode to convert.
formatterListener The FormatterListener instance.
function The FormatterListener member function to call.
Definition at line 516 of file XObject.hpp.
string() [10/14]
static void xalanc::XObject::string (const XalanNode & theNode, XalanDOMString & theString) inline static
Static conversion function.
Append the string value of the XalanNode to the supplied XalanDOMString parameter.
Deprecated:
This function is deprecated and should not be used.
Parameters
theNode The XalanNode to convert.
theString The output XalanDOMString.
Definition at line 498 of file XObject.hpp.
string() [11/14]
static void xalanc::XObject::string (const XalanNode & theNode, XPathExecutionContext & theExecutionContext, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Static conversion function.
Calls the supplied FormatterListener member function with the string value of the XalanNode.
Parameters
theNode The XalanNode to convert.
theExecutionContext The current XPathExecutionContext.
formatterListener The FormatterListener instance.
function The FormatterListener member function to call.
Definition at line 597 of file XObject.hpp.
string() [12/14]
static void xalanc::XObject::string (const XalanNode & theNode, XPathExecutionContext & theExecutionContext, XalanDOMString & theString) inline static
Static conversion function.
Append the string value of the XalanNode to the supplied XalanDOMString parameter.
Parameters
theNode The XalanNode to convert.
theExecutionContext The current XPathExecutionContext.
theString The output XalanDOMString.
Definition at line 579 of file XObject.hpp.
string() [13/14]
static void xalanc::XObject::string (double theNumber, FormatterListener & formatterListener, MemberFunctionPtr function) inline static
Static conversion function.
Calls the supplied FormatterListener member function with the string value of the double.
Parameters
theNumber The double to convert.
formatterListener The FormatterListener instance.
function The FormatterListener member function to call.
Definition at line 480 of file XObject.hpp.
string() [14/14]
static void xalanc::XObject::string (double theNumber, XalanDOMString & theString) inline static
Static conversion function.
Append the string value of the double to the supplied XalanDOMString parameter.
Parameters
theNumber The double to convert.
theString The output XalanDOMString.
Definition at line 464 of file XObject.hpp.
References xalanc::NumberToDOMString().
stringLength()
virtual double xalanc::XObject::stringLength (XPathExecutionContext & executionContext) const pure virtual
Get the length of the string value of the instance.
Returns
The length of the string value
Implemented in xalanc::XStringBase, xalanc::XNumberBase, xalanc::XToken, xalanc::XUnknown, xalanc::XResultTreeFrag, xalanc::XString, xalanc::XBoolean, xalanc::XTokenNumberAdapter, xalanc::XTokenStringAdapter, xalanc::XNodeSetBase, xalanc::XNumber, xalanc::XStringAdapter, xalanc::XStringCached, and xalanc::XStringReference.
terminate()
static void xalanc::XObject::terminate () static
Perform static shut down.
See class XPathInit.
throwInvalidConversionException()
void xalanc::XObject::throwInvalidConversionException (const XalanDOMString & theTargetType) const protected
Friends And Related Function Documentation
XObjectFactory
friend class XObjectFactory friend
Definition at line 728 of file XObject.hpp.
XObjectPtr
friend class XObjectPtr friend
Definition at line 67 of file XObject.hpp.
Member Data Documentation
s_booleanString
const XalanDOMString& xalanc::XObject::s_booleanString static protected
Definition at line 850 of file XObject.hpp.
s_emptyString
const XalanDOMString xalanc::XObject::s_emptyString static protected
Definition at line 848 of file XObject.hpp.
s_falseString
const XalanDOMString& xalanc::XObject::s_falseString static protected
Definition at line 852 of file XObject.hpp.
s_nodesetString
const XalanDOMString& xalanc::XObject::s_nodesetString static protected
Definition at line 854 of file XObject.hpp.
s_numberString
const XalanDOMString& xalanc::XObject::s_numberString static protected
Definition at line 856 of file XObject.hpp.
s_resultTreeFragmentString
const XalanDOMString& xalanc::XObject::s_resultTreeFragmentString static protected
Definition at line 858 of file XObject.hpp.
s_stringString
const XalanDOMString& xalanc::XObject::s_stringString static protected
Definition at line 860 of file XObject.hpp.
s_trueString
const XalanDOMString& xalanc::XObject::s_trueString static protected
Definition at line 862 of file XObject.hpp.
The documentation for this class was generated from the following file:
xalanc/XPath/XObject.hpp