Xalan-C++ API Reference: xalanc::XalanAllocationGuard Class Reference
xalanc::XalanAllocationGuard Class Reference
#include <xalanc/Include/XalanMemoryManagement.hpp>
Public Types
typedef std::size_t size_type
Public Member Functions
XalanAllocationGuard (MemoryManager &theMemoryManager, void *thePointer)
XalanAllocationGuard (MemoryManager &theMemoryManager, size_type theSize)
~XalanAllocationGuard ()
void * get () const
void release ()
Detailed Description
Definition at line 96 of file XalanMemoryManagement.hpp.
Member Typedef Documentation
size_type
typedef std::size_t xalanc::XalanAllocationGuard::size_type
Definition at line 100 of file XalanMemoryManagement.hpp.
Constructor & Destructor Documentation
XalanAllocationGuard() [1/2]
xalanc::XalanAllocationGuard::XalanAllocationGuard (MemoryManager & theMemoryManager, void * thePointer) inline
Definition at line 102 of file XalanMemoryManagement.hpp.
XalanAllocationGuard() [2/2]
xalanc::XalanAllocationGuard::XalanAllocationGuard (MemoryManager & theMemoryManager, size_type theSize) inline
Definition at line 110 of file XalanMemoryManagement.hpp.
~XalanAllocationGuard()
xalanc::XalanAllocationGuard::~XalanAllocationGuard () inline
Definition at line 118 of file XalanMemoryManagement.hpp.
Member Function Documentation
get()
void* xalanc::XalanAllocationGuard::get () const inline
Definition at line 127 of file XalanMemoryManagement.hpp.
Referenced by xalanc::XalanEXSLTFunctionObjectType::clone(), xalanc::NameSpace::create(), xalanc::XalanVector< XalanDOMChar >::create(), xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::create(), xalanc::XalanDeque< XercesBridgeNavigator >::create(), xalanc::DefaultCacheCreateFunctor< ObjectType >::operator()(), xalanc::XalanMessageLoader::XalanMessageLoaderCreateFunct< Type >::operator()(), xalanc::DefaultCacheCreateFunctorMemMgr< FormatterToTextDOMString >::operator()(), xalanc::XalanConstruct(), and xalanc::XalanCopyConstruct().
release()
void xalanc::XalanAllocationGuard::release () inline
Definition at line 133 of file XalanMemoryManagement.hpp.
Referenced by xalanc::XalanEXSLTFunctionObjectType::clone(), xalanc::NameSpace::create(), xalanc::XalanVector< XalanDOMChar >::create(), xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::create(), xalanc::XalanDeque< XercesBridgeNavigator >::create(), xalanc::DefaultCacheCreateFunctor< ObjectType >::operator()(), xalanc::XalanMessageLoader::XalanMessageLoaderCreateFunct< Type >::operator()(), xalanc::DefaultCacheCreateFunctorMemMgr< FormatterToTextDOMString >::operator()(), xalanc::XalanConstruct(), and xalanc::XalanCopyConstruct().
The documentation for this class was generated from the following file:
xalanc/Include/XalanMemoryManagement.hpp