Xalan-C++ API Reference: xalanc::URISupport Class Reference
xalanc::URISupport Class Reference
#include <xalanc/PlatformSupport/URISupport.hpp>
Classes
class InvalidURIException
Normalizes the string passed in, replacing \ with /.
Public Types
typedef XalanAutoPtr< XMLURLType > URLAutoPtrType
Static Public Member Functions
static URLAutoPtrType getURLFromString (const XalanDOMString &urlString, MemoryManager &theManager)
Determine the fully qualified URI for a string.
static void getURLFromString (const XalanDOMString &urlString, XMLURLType &url, MemoryManager &theManager)
Determine the fully qualified URI for a string.
static URLAutoPtrType getURLFromString (const XalanDOMChar *urlString, MemoryManager &theManager)
Determine the fully qualified URI for a string.
static void getURLFromString (const XalanDOMChar *urlString, XMLURLType &url, MemoryManager &theManager)
Determine the fully qualified URI for a string.
static URLAutoPtrType getURLFromString (const XalanDOMString &urlString, const XalanDOMString &base, MemoryManager &theManager)
Determine the fully qualified URI for a string.
static URLAutoPtrType getURLFromString (const XalanDOMChar *urlString, const XalanDOMChar *base)
Determine the fully qualified URI for a string.
static void getURLStringFromString (const XalanDOMString &urlString, XalanDOMString &theNormalizedURI)
Determine the fully qualified URI for a string.
static void getURLStringFromString (const XalanDOMChar *urlString, XalanDOMString &theNormalizedURI)
Determine the fully qualified URI for a string.
static void getURLStringFromString (const XalanDOMChar *urlString, XalanDOMString::size_type len, XalanDOMString &theNormalizedURI)
Determine the fully qualified URI for a string.
static void getURLStringFromString (const XalanDOMString &urlString, const XalanDOMString &base, XalanDOMString &theNormalizedURI)
Determine the fully qualified URI for a string.
static void getURLStringFromString (const XalanDOMChar *urlString, const XalanDOMChar *base, XalanDOMString &theNormalizedURI)
Determine the fully qualified URI for a string.
static void getURLStringFromString (const XalanDOMChar *urlString, XalanDOMString::size_type urlStringLen, const XalanDOMChar *base, XalanDOMString::size_type baseLen, XalanDOMString &theNormalizedURI)
Determine the fully qualified URI for a string.
static XalanDOMString & NormalizeURIText (XalanDOMString &uriString)
Normalizes the string passed in, replacing \ with /.
Static Public Attributes
static const XalanDOMChar s_fileProtocolString1 []
static const XalanDOMChar s_fileProtocolString2 []
Detailed Description
Definition at line 52 of file URISupport.hpp.
Member Typedef Documentation
URLAutoPtrType
typedef XalanAutoPtr<XMLURLType> xalanc::URISupport::URLAutoPtrType
Definition at line 56 of file URISupport.hpp.
Member Function Documentation
getURLFromString() [1/6]
static URLAutoPtrType xalanc::URISupport::getURLFromString (const XalanDOMChar * urlString, const XalanDOMChar * base) static
Determine the fully qualified URI for a string.
Parameters
urlString string to qualify
base base location for URI
Returns
auto pointer to fully qualified URI
getURLFromString() [2/6]
static URLAutoPtrType xalanc::URISupport::getURLFromString (const XalanDOMChar * urlString, MemoryManager & theManager) static
Determine the fully qualified URI for a string.
Parameters
urlString string to qualify
Returns
auto pointer to fully qualified URI
getURLFromString() [3/6]
static void xalanc::URISupport::getURLFromString (const XalanDOMChar * urlString, XMLURLType & url, MemoryManager & theManager) inline static
Determine the fully qualified URI for a string.
Parameters
urlString string to qualify
url to update with the qualified string.
Definition at line 103 of file URISupport.hpp.
References xalanc::XalanDOMString::c_str().
getURLFromString() [4/6]
static URLAutoPtrType xalanc::URISupport::getURLFromString (const XalanDOMString & urlString, const XalanDOMString & base, MemoryManager & theManager) inline static
Determine the fully qualified URI for a string.
Parameters
urlString string to qualify
base base location for URI
Returns
auto pointer to fully qualified URI
Definition at line 123 of file URISupport.hpp.
getURLFromString() [5/6]
static URLAutoPtrType xalanc::URISupport::getURLFromString (const XalanDOMString & urlString, MemoryManager & theManager) inline static
Determine the fully qualified URI for a string.
Parameters
urlString string to qualify
Returns
auto pointer to fully qualified URI
Definition at line 65 of file URISupport.hpp.
References xalanc::XalanDOMString::c_str().
getURLFromString() [6/6]
static void xalanc::URISupport::getURLFromString (const XalanDOMString & urlString, XMLURLType & url, MemoryManager & theManager) inline static
Determine the fully qualified URI for a string.
Parameters
urlString string to qualify
url to update with the qualified string.
Definition at line 78 of file URISupport.hpp.
References xalanc::XalanDOMString::c_str().
getURLStringFromString() [1/6]
static void xalanc::URISupport::getURLStringFromString (const XalanDOMChar * urlString, const XalanDOMChar * base, XalanDOMString & theNormalizedURI) inline static
Determine the fully qualified URI for a string.
Parameters
urlString string to qualify
base base location for URI
theNormalizedURI fully qualified URI
Definition at line 220 of file URISupport.hpp.
References xalanc::length().
getURLStringFromString() [2/6]
static void xalanc::URISupport::getURLStringFromString (const XalanDOMChar * urlString, XalanDOMString & theNormalizedURI) inline static
Determine the fully qualified URI for a string.
Parameters
urlString string to qualify
theNormalizedURI fully qualified URI
Definition at line 170 of file URISupport.hpp.
References xalanc::length().
getURLStringFromString() [3/6]
static void xalanc::URISupport::getURLStringFromString (const XalanDOMChar * urlString, XalanDOMString::size_type len, XalanDOMString & theNormalizedURI) static
Determine the fully qualified URI for a string.
Parameters
urlString string to qualify
len the length of urlString
theNormalizedURI fully qualified URI
getURLStringFromString() [4/6]
static void xalanc::URISupport::getURLStringFromString (const XalanDOMChar * urlString, XalanDOMString::size_type urlStringLen, const XalanDOMChar * base, XalanDOMString::size_type baseLen, XalanDOMString & theNormalizedURI) static
Determine the fully qualified URI for a string.
Parameters
urlString string to qualify
base base location for URI
theNormalizedURI fully qualified URI
getURLStringFromString() [5/6]
static void xalanc::URISupport::getURLStringFromString (const XalanDOMString & urlString, const XalanDOMString & base, XalanDOMString & theNormalizedURI) inline static
Determine the fully qualified URI for a string.
Parameters
urlString string to qualify
base base location for URI
theNormalizedURI fully qualified URI
Definition at line 203 of file URISupport.hpp.
References xalanc::XalanDOMString::c_str().
getURLStringFromString() [6/6]
static void xalanc::URISupport::getURLStringFromString (const XalanDOMString & urlString, XalanDOMString & theNormalizedURI) inline static
Determine the fully qualified URI for a string.
Parameters
urlString string to qualify
Returns
string to fully qualified URI
Definition at line 155 of file URISupport.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
NormalizeURIText()
static XalanDOMString& xalanc::URISupport::NormalizeURIText (XalanDOMString & uriString) static
Normalizes the string passed in, replacing \ with /.
Parameters
urlString string to normalize
Returns
a reference to the passed parameter
Member Data Documentation
s_fileProtocolString1
const XalanDOMChar xalanc::URISupport::s_fileProtocolString1[] static
Definition at line 302 of file URISupport.hpp.
s_fileProtocolString2
const XalanDOMChar xalanc::URISupport::s_fileProtocolString2[] static
Definition at line 304 of file URISupport.hpp.
The documentation for this class was generated from the following file:
xalanc/PlatformSupport/URISupport.hpp