Xalan-C++ API Reference: xalanc::NodeRefListBase Class Reference
xalanc::NodeRefListBase Class Reference abstract
Local implementation of NodeRefList.
#include <xalanc/XPath/NodeRefListBase.hpp>
Public Types
typedef XalanSize_t size_type
Public Member Functions
NodeRefListBase ()
virtual ~NodeRefListBase ()
virtual XalanNode * item (size_type index) const =0
Returns the indexth item in the collection.
virtual size_type getLength () const =0
Determine the number of nodes in the list.
virtual size_type indexOf (const XalanNode *theNode) const =0
Retrieve the zero based index of the node in the list.
Static Public Attributes
static const size_type npos
Protected Member Functions
NodeRefListBase (const NodeRefListBase &)
NodeRefListBase & operator= (const NodeRefListBase &)
Detailed Description
Local implementation of NodeRefList.
This class is for internal use only.
Definition at line 44 of file NodeRefListBase.hpp.
Member Typedef Documentation
size_type
typedef XalanSize_t xalanc::NodeRefListBase::size_type
Definition at line 53 of file NodeRefListBase.hpp.
Constructor & Destructor Documentation
NodeRefListBase() [1/2]
xalanc::NodeRefListBase::NodeRefListBase ()
~NodeRefListBase()
virtual xalanc::NodeRefListBase::~NodeRefListBase () virtual
NodeRefListBase() [2/2]
xalanc::NodeRefListBase::NodeRefListBase (const NodeRefListBase &) inline protected
Definition at line 90 of file NodeRefListBase.hpp.
Member Function Documentation
getLength()
virtual size_type xalanc::NodeRefListBase::getLength () const pure virtual
Determine the number of nodes in the list.
The range of valid child node indices is 0 to length-1 inclusive.
Returns
number of nodes
Implemented in xalanc::NodeRefList, xalanc::XNodeSetNodeProxy::Proxy, and xalanc::XalanDocumentFragmentNodeRefListBaseProxy.
Referenced by xalanc::XObject::boolean(), and xalanc::XObject::string().
indexOf()
virtual size_type xalanc::NodeRefListBase::indexOf (const XalanNode * theNode) const pure virtual
Retrieve the zero based index of the node in the list.
Parameters
theNode node whose index to find
Returns
index of node
Implemented in xalanc::NodeRefList, xalanc::XNodeSetNodeProxy::Proxy, and xalanc::XalanDocumentFragmentNodeRefListBaseProxy.
item()
virtual XalanNode* xalanc::NodeRefListBase::item (size_type index) const pure virtual
Returns the indexth item in the collection.
If index is greater than or equal to the number of nodes in the list, this returns null.
Parameters
index index into the collection
Returns
node at the indexth position in the NodeList, or null if that is not a valid index
Implemented in xalanc::NodeRefList, xalanc::XNodeSetNodeProxy::Proxy, and xalanc::XalanDocumentFragmentNodeRefListBaseProxy.
Referenced by xalanc::XObject::string().
operator=()
NodeRefListBase& xalanc::NodeRefListBase::operator= (const NodeRefListBase &) inline protected
Definition at line 95 of file NodeRefListBase.hpp.
Member Data Documentation
npos
const size_type xalanc::NodeRefListBase::npos static
Definition at line 86 of file NodeRefListBase.hpp.
The documentation for this class was generated from the following file:
xalanc/XPath/NodeRefListBase.hpp