Xalan-C++ API Reference: xalanc::ResultNamespacesStack Class Reference
xalanc::ResultNamespacesStack Class Reference
#include <xalanc/XSLT/ResultNamespacesStack.hpp>
Public Types
typedef XalanVector< bool > BoolVectorType
typedef XalanQName::NamespaceVectorType NamespaceVectorType
typedef XalanQName::NamespacesStackType NamespacesStackType
typedef NamespacesStackType::size_type size_type
Public Member Functions
ResultNamespacesStack (MemoryManager &theManager)
~ResultNamespacesStack ()
void addDeclaration (const XalanDOMString &thePrefix, const XalanDOMString &theNamespaceURI)
void addDeclaration (const XalanDOMString &thePrefix, const XalanDOMChar *theNamespaceURI)
void addDeclaration (const XalanDOMString &thePrefix, const XalanDOMChar *theNamespaceURI, XalanDOMString::size_type theLength)
void pushContext ()
void popContext ()
const XalanDOMString * getNamespaceForPrefix (const XalanDOMString &thePrefix) const
const XalanDOMString * getPrefixForNamespace (const XalanDOMString &theNamespaceURI) const
bool prefixIsPresentLocal (const XalanDOMString &thePrefix)
See if the prefix has been mapped to a namespace in the current context, without looking down the stack of namespaces.
void clear ()
size_type size () const
bool empty () const
Detailed Description
Definition at line 44 of file ResultNamespacesStack.hpp.
Member Typedef Documentation
BoolVectorType
typedef XalanVector<bool> xalanc::ResultNamespacesStack::BoolVectorType
Definition at line 52 of file ResultNamespacesStack.hpp.
NamespacesStackType
typedef XalanQName::NamespacesStackType xalanc::ResultNamespacesStack::NamespacesStackType
Definition at line 56 of file ResultNamespacesStack.hpp.
NamespaceVectorType
typedef XalanQName::NamespaceVectorType xalanc::ResultNamespacesStack::NamespaceVectorType
Definition at line 55 of file ResultNamespacesStack.hpp.
size_type
typedef NamespacesStackType::size_type xalanc::ResultNamespacesStack::size_type
Definition at line 58 of file ResultNamespacesStack.hpp.
Constructor & Destructor Documentation
ResultNamespacesStack()
xalanc::ResultNamespacesStack::ResultNamespacesStack (MemoryManager & theManager) explicit
~ResultNamespacesStack()
xalanc::ResultNamespacesStack::~ResultNamespacesStack ()
Member Function Documentation
addDeclaration() [1/3]
void xalanc::ResultNamespacesStack::addDeclaration (const XalanDOMString & thePrefix, const XalanDOMChar * theNamespaceURI) inline
Definition at line 78 of file ResultNamespacesStack.hpp.
References xalanc::length().
addDeclaration() [2/3]
void xalanc::ResultNamespacesStack::addDeclaration (const XalanDOMString & thePrefix, const XalanDOMChar * theNamespaceURI, XalanDOMString::size_type theLength)
addDeclaration() [3/3]
void xalanc::ResultNamespacesStack::addDeclaration (const XalanDOMString & thePrefix, const XalanDOMString & theNamespaceURI) inline
Definition at line 67 of file ResultNamespacesStack.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
clear()
void xalanc::ResultNamespacesStack::clear ()
empty()
bool xalanc::ResultNamespacesStack::empty () const inline
Definition at line 123 of file ResultNamespacesStack.hpp.
getNamespaceForPrefix()
const XalanDOMString* xalanc::ResultNamespacesStack::getNamespaceForPrefix (const XalanDOMString & thePrefix) const
getPrefixForNamespace()
const XalanDOMString* xalanc::ResultNamespacesStack::getPrefixForNamespace (const XalanDOMString & theNamespaceURI) const
popContext()
void xalanc::ResultNamespacesStack::popContext ()
prefixIsPresentLocal()
bool xalanc::ResultNamespacesStack::prefixIsPresentLocal (const XalanDOMString & thePrefix)
See if the prefix has been mapped to a namespace in the current context, without looking down the stack of namespaces.
pushContext()
void xalanc::ResultNamespacesStack::pushContext ()
size()
size_type xalanc::ResultNamespacesStack::size () const inline
Definition at line 117 of file ResultNamespacesStack.hpp.
The documentation for this class was generated from the following file:
xalanc/XSLT/ResultNamespacesStack.hpp