Xalan-C++ API Reference: xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType > Class Template Reference
xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType > Class Template Reference
#include <xalanc/XMLSupport/XalanOtherEncodingWriter.hpp>
Classes
class ThrowTranscodingException
class WriteCharRef
Public Types
typedef XalanOtherEncodingWriter< Predicate, ConstantsType > ThisType
typedef XalanDOMChar value_type
Public Types inherited from xalanc::XalanFormatterWriter
typedef FormatterListener::size_type size_type
Public Member Functions
XalanOtherEncodingWriter (Writer &writer, MemoryManager &theMemoryManager)
virtual ~XalanOtherEncodingWriter ()
void outputNewline ()
Output a line break.
size_type writeCDATAChar (const XalanDOMChar chars[], size_type start, size_type length, bool &outsideCDATA)
Writes CDATA chars , if not presentable, fixes it with addition CDATA sections.
void writeNameChar (const XalanDOMChar *data, size_type theLength)
Writes name characters.
void writePIChars (const XalanDOMChar *data, size_type theLength)
Writes PI characters.
void writeCommentChars (const XalanDOMChar *data, size_type theLength)
Writes comment characters.
void write (const XalanDOMChar *theChars, size_type theLength)
void write (const XalanDOMString &theChars)
void write (XalanDOMChar theChar)
Writes writes a UTF-16 code unit that isn't part of the surrogate pair.
size_type write (const XalanDOMChar chars[], size_type start, size_type length)
void writeSafe (const XalanDOMChar *theChars, size_type theLength)
void write (const XalanDOMChar *theChars)
void flushWriter ()
void flushBuffer ()
Public Member Functions inherited from xalanc::XalanFormatterWriter
XalanFormatterWriter (Writer &theWriter, MemoryManager &theMemoryManager)
MemoryManager & getMemoryManager ()
virtual ~XalanFormatterWriter ()
Writer * getWriter () const
XalanOutputStream * getStream ()
const XalanOutputStream * getStream () const
void flushWriter ()
void throwUnrepresentableCharacterException (XalanUnicodeChar ch, MemoryManager &theManager)
Friends
class WriteCharRef
class ThrowTranscodingException
Additional Inherited Members
Static Public Member Functions inherited from xalanc::XalanFormatterWriter
static bool isUTF16HighSurrogate (XalanDOMChar theChar)
static bool isUTF16LowSurrogate (XalanDOMChar theChar)
static XalanUnicodeChar decodeUTF16SurrogatePair (XalanDOMChar theHighSurrogate, XalanDOMChar theLowSurrogate, MemoryManager &theManager)
static void throwInvalidCharacterException (XalanUnicodeChar ch, MemoryManager &theManager)
static void throwInvalidUTF16SurrogateException (XalanDOMChar ch, XalanDOMChar next, MemoryManager &theManager)
Protected Member Functions inherited from xalanc::XalanFormatterWriter
const XalanDOMString & formatNumericCharacterReference (XalanUnicodeChar theChar)
Format a code point as a numeric character reference.
Protected Attributes inherited from xalanc::XalanFormatterWriter
Writer & m_writer
The writer.
MemoryManager & m_memoryManager
The MemoryManager instance to use for any dynamically- allocated memory.
XalanDOMString m_stringBuffer
const XalanDOMChar * m_newlineString
The string of characters that represents the newline.
size_type m_newlineStringLength
The length of the the string of characters that represents the newline.
Detailed Description
template<class Predicate, class ConstantsType>
class xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >
Definition at line 33 of file XalanOtherEncodingWriter.hpp.
Member Typedef Documentation
ThisType
template<class Predicate , class ConstantsType > typedef XalanOtherEncodingWriter<Predicate, ConstantsType> xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::ThisType
Definition at line 37 of file XalanOtherEncodingWriter.hpp.
value_type
template<class Predicate , class ConstantsType > typedef XalanDOMChar xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::value_type
Definition at line 84 of file XalanOtherEncodingWriter.hpp.
Constructor & Destructor Documentation
XalanOtherEncodingWriter()
template<class Predicate , class ConstantsType > xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::XalanOtherEncodingWriter (Writer & writer, MemoryManager & theMemoryManager) inline
Definition at line 86 of file XalanOtherEncodingWriter.hpp.
~XalanOtherEncodingWriter()
template<class Predicate , class ConstantsType > virtual xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::~XalanOtherEncodingWriter () inline virtual
Definition at line 103 of file XalanOtherEncodingWriter.hpp.
Member Function Documentation
flushBuffer()
template<class Predicate , class ConstantsType > void xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::flushBuffer () inline
Definition at line 355 of file XalanOtherEncodingWriter.hpp.
flushWriter()
template<class Predicate , class ConstantsType > void xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::flushWriter () inline
Definition at line 349 of file XalanOtherEncodingWriter.hpp.
outputNewline()
template<class Predicate , class ConstantsType > void xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::outputNewline () inline
Output a line break.
Definition at line 111 of file XalanOtherEncodingWriter.hpp.
References xalanc::length().
write() [1/5]
template<class Predicate , class ConstantsType > void xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::write (const XalanDOMChar * theChars) inline
Definition at line 343 of file XalanOtherEncodingWriter.hpp.
References xalanc::length().
write() [2/5]
template<class Predicate , class ConstantsType > void xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::write (const XalanDOMChar * theChars, size_type theLength) inline
Definition at line 249 of file XalanOtherEncodingWriter.hpp.
write() [3/5]
template<class Predicate , class ConstantsType > size_type xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::write (const XalanDOMChar chars[], size_type start, size_type length) inline
Definition at line 295 of file XalanOtherEncodingWriter.hpp.
References xalanc::length().
write() [4/5]
template<class Predicate , class ConstantsType > void xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::write (const XalanDOMString & theChars) inline
Definition at line 260 of file XalanOtherEncodingWriter.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
write() [5/5]
template<class Predicate , class ConstantsType > void xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::write (XalanDOMChar theChar) inline
Writes writes a UTF-16 code unit that isn't part of the surrogate pair.
Definition at line 270 of file XalanOtherEncodingWriter.hpp.
writeCDATAChar()
template<class Predicate , class ConstantsType > size_type xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::writeCDATAChar (const XalanDOMChar chars[], size_type start, size_type length, bool & outsideCDATA) inline
Writes CDATA chars , if not presentable, fixes it with addition CDATA sections.
Definition at line 126 of file XalanOtherEncodingWriter.hpp.
References xalanc::length().
writeCommentChars()
template<class Predicate , class ConstantsType > void xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::writeCommentChars (const XalanDOMChar * data, size_type theLength) inline
Writes comment characters.
If a character is not representable, or must be written as a character reference for compatibility with XML 1.1, an exception is thrown.
Definition at line 238 of file XalanOtherEncodingWriter.hpp.
writeNameChar()
template<class Predicate , class ConstantsType > void xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::writeNameChar (const XalanDOMChar * data, size_type theLength) inline
Writes name characters.
If a character is not representable, an exception is thrown.
Definition at line 207 of file XalanOtherEncodingWriter.hpp.
writePIChars()
template<class Predicate , class ConstantsType > void xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::writePIChars (const XalanDOMChar * data, size_type theLength) inline
Writes PI characters.
If a character is not representable, an exception is thrown.
Definition at line 222 of file XalanOtherEncodingWriter.hpp.
writeSafe()
template<class Predicate , class ConstantsType > void xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::writeSafe (const XalanDOMChar * theChars, size_type theLength) inline
Definition at line 305 of file XalanOtherEncodingWriter.hpp.
Friends And Related Function Documentation
ThrowTranscodingException
template<class Predicate , class ConstantsType > friend class ThrowTranscodingException friend
Definition at line 82 of file XalanOtherEncodingWriter.hpp.
WriteCharRef
template<class Predicate , class ConstantsType > friend class WriteCharRef friend
Definition at line 81 of file XalanOtherEncodingWriter.hpp.
The documentation for this class was generated from the following file:
xalanc/XMLSupport/XalanOtherEncodingWriter.hpp