Xalan-C++ API Reference: xalanc::XalanDOMString Class Reference
xalanc::XalanDOMString Class Reference
#include <xalanc/XalanDOM/XalanDOMString.hpp>
Classes
class TranscodingError
Public Types
typedef XalanVector< XalanDOMChar > XalanDOMCharVectorType
typedef XalanVector< char > CharVectorType
typedef XalanVector< wchar_t > WideCharVectorType
typedef XalanDOMChar value_type
typedef XalanDOMChar & reference
typedef XalanSize_t size_type
typedef XalanDOMCharVectorType::iterator iterator
typedef XalanDOMCharVectorType::const_iterator const_iterator
typedef XalanDOMCharVectorType::reverse_iterator reverse_iterator
typedef XalanDOMCharVectorType::const_reverse_iterator const_reverse_iterator
Public Member Functions
XalanDOMString (MemoryManager &theManager XALAN_DEFAULT_CONSTRUCTOR_MEMMGR)
XalanDOMString (const char *theString, MemoryManager &theManager XALAN_DEFAULT_MEMMGR, size_type theCount=size_type(npos))
XalanDOMString (const XalanDOMString &theSource, MemoryManager &theManager XALAN_DEFAULT_CONSTRUCTOR_MEMMGR, size_type theStartPosition=0, size_type theCount=size_type(npos))
XalanDOMString (const XalanDOMChar *theString, MemoryManager &theManager XALAN_DEFAULT_MEMMGR, size_type theCount=size_type(npos))
XalanDOMString (size_type theCount, XalanDOMChar theChar, MemoryManager &theManager XALAN_DEFAULT_MEMMGR)
XalanDOMString * clone (MemoryManager &theManager)
~XalanDOMString ()
XalanDOMString & operator= (const XalanDOMString &theRHS)
XalanDOMString & operator= (const XalanDOMChar *theRHS)
XalanDOMString & operator= (const char *theRHS)
XalanDOMString & operator= (XalanDOMChar theRHS)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size () const
size_type length () const
size_type max_size () const
void resize (size_type theCount, XalanDOMChar theChar)
void resize (size_type theCount)
size_type capacity () const
void reserve (size_type theCount=0)
void clear ()
iterator erase (iterator thePosition)
iterator erase (iterator theFirst, iterator theLast)
XalanDOMString & erase (size_type theStartPosition=0, size_type theCount=size_type(npos))
bool empty () const
const_reference operator[] (size_type theIndex) const
reference operator[] (size_type theIndex)
const_reference at (size_type theIndex) const
reference at (size_type theIndex)
const XalanDOMChar * c_str () const
const XalanDOMChar * data () const
void swap (XalanDOMString &theOther)
XalanDOMString & operator+= (const XalanDOMString &theSource)
XalanDOMString & operator+= (const XalanDOMChar *theString)
XalanDOMString & operator+= (XalanDOMChar theChar)
XalanDOMString & assign (const XalanDOMChar *theSource)
XalanDOMString & assign (const XalanDOMChar *theSource, size_type theCount)
XalanDOMString & assign (const char *theSource)
XalanDOMString & assign (const char *theSource, size_type theCount)
XalanDOMString & assign (const XalanDOMString &theSource, size_type thePosition, size_type theCount)
XalanDOMString & assign (const XalanDOMString &theSource)
XalanDOMString & assign (size_type theCount, XalanDOMChar theChar)
XalanDOMString & assign (iterator theFirstPosition, iterator theLastPosition)
XalanDOMString & append (const XalanDOMString &theSource)
XalanDOMString & append (const XalanDOMString &theSource, size_type thePosition, size_type theCount)
XalanDOMString & append (const XalanDOMChar *theString, size_type theCount)
XalanDOMString & append (const XalanDOMChar *theString)
XalanDOMString & append (const char *theString, size_type theCount)
XalanDOMString & append (const char *theString)
XalanDOMString & append (size_type theCount, XalanDOMChar theChar)
void push_back (XalanDOMChar theChar)
XalanDOMString & insert (size_type thePosition, const XalanDOMString &theString)
XalanDOMString & insert (size_type thePosition1, const XalanDOMString &theString, size_type thePosition2, size_type theCount)
XalanDOMString & insert (size_type thePosition, const XalanDOMChar *theString, size_type theCount)
XalanDOMString & insert (size_type thePosition, const XalanDOMChar *theString)
XalanDOMString & insert (size_type thePosition, size_type theCount, XalanDOMChar theChar)
iterator insert (iterator thePosition, XalanDOMChar theChar)
void insert (iterator thePosition, size_type theCount, XalanDOMChar theChar)
void insert (iterator theInsertPosition, iterator theFirstPosition, iterator theLastPosition)
XalanDOMString & substr (XalanDOMString &theSubstring, size_type thePosition=0, size_type theCount=size_type(npos)) const
int compare (const XalanDOMString &theString) const
int compare (size_type thePosition1, size_type theCount1, const XalanDOMString &theString) const
int compare (size_type thePosition1, size_type theCount1, const XalanDOMString &theString, size_type thePosition2, size_type theCount2) const
int compare (const XalanDOMChar *theString) const
int compare (size_type thePosition1, size_type theCount1, const XalanDOMChar *theString, size_type theCount2=size_type(npos)) const
void reset (MemoryManager &theManager, const char *theString)
void reset (MemoryManager &theManager, const XalanDOMChar *theString)
void transcode (CharVectorType &theResult) const
Transcode the string to the local code page.
MemoryManager & getMemoryManager ()
size_t hash () const
Static Public Member Functions
static size_t hash (const XalanDOMChar *theString, size_type theLength)
static bool equals (const XalanDOMChar *theLHS, size_type theLHSLength, const XalanDOMChar *theRHS, size_type theRHSLength)
static bool equals (const XalanDOMChar *theLHS, const XalanDOMChar *theRHS)
static bool equals (const XalanDOMString &theLHS, const XalanDOMString &theRHS)
static bool equals (const XalanDOMString &theLHS, const XalanDOMChar *theRHS)
static bool equals (const XalanDOMChar *theLHS, const XalanDOMString &theRHS)
static size_type length (const XalanDOMChar *theString)
static size_type length (const char *theString)
Public Attributes
const typedef XalanDOMChar & const_reference
Static Public Attributes
static const size_type npos
Protected Member Functions
void invariants () const
iterator getBackInsertIterator ()
const_iterator getBackInsertIterator () const
iterator getIteratorForPosition (size_type thePosition)
const_iterator getIteratorForPosition (size_type thePosition) const
Detailed Description
Definition at line 45 of file XalanDOMString.hpp.
Member Typedef Documentation
CharVectorType
typedef XalanVector<char> xalanc::XalanDOMString::CharVectorType
Definition at line 50 of file XalanDOMString.hpp.
const_iterator
typedef XalanDOMCharVectorType::const_iterator xalanc::XalanDOMString::const_iterator
Definition at line 60 of file XalanDOMString.hpp.
const_reverse_iterator
typedef XalanDOMCharVectorType::const_reverse_iterator xalanc::XalanDOMString::const_reverse_iterator
Definition at line 62 of file XalanDOMString.hpp.
iterator
typedef XalanDOMCharVectorType::iterator xalanc::XalanDOMString::iterator
Definition at line 59 of file XalanDOMString.hpp.
reference
typedef XalanDOMChar& xalanc::XalanDOMString::reference
Definition at line 54 of file XalanDOMString.hpp.
reverse_iterator
typedef XalanDOMCharVectorType::reverse_iterator xalanc::XalanDOMString::reverse_iterator
Definition at line 61 of file XalanDOMString.hpp.
size_type
typedef XalanSize_t xalanc::XalanDOMString::size_type
Definition at line 57 of file XalanDOMString.hpp.
value_type
typedef XalanDOMChar xalanc::XalanDOMString::value_type
Definition at line 53 of file XalanDOMString.hpp.
WideCharVectorType
typedef XalanVector<wchar_t> xalanc::XalanDOMString::WideCharVectorType
Definition at line 51 of file XalanDOMString.hpp.
XalanDOMCharVectorType
typedef XalanVector<XalanDOMChar> xalanc::XalanDOMString::XalanDOMCharVectorType
Definition at line 49 of file XalanDOMString.hpp.
Constructor & Destructor Documentation
XalanDOMString() [1/5]
xalanc::XalanDOMString::XalanDOMString (MemoryManager &theManager XALAN_DEFAULT_CONSTRUCTOR_MEMMGR)
XalanDOMString() [2/5]
xalanc::XalanDOMString::XalanDOMString (const char * theString, MemoryManager &theManager XALAN_DEFAULT_MEMMGR, size_type theCount = size_type(npos)) explicit
XalanDOMString() [3/5]
xalanc::XalanDOMString::XalanDOMString (const XalanDOMString & theSource, MemoryManager &theManager XALAN_DEFAULT_CONSTRUCTOR_MEMMGR, size_type theStartPosition = 0, size_type theCount = size_type(npos))
XalanDOMString() [4/5]
xalanc::XalanDOMString::XalanDOMString (const XalanDOMChar * theString, MemoryManager &theManager XALAN_DEFAULT_MEMMGR, size_type theCount = size_type(npos)) explicit
XalanDOMString() [5/5]
xalanc::XalanDOMString::XalanDOMString (size_type theCount, XalanDOMChar theChar, MemoryManager &theManager XALAN_DEFAULT_MEMMGR)
~XalanDOMString()
xalanc::XalanDOMString::~XalanDOMString () inline
Definition at line 94 of file XalanDOMString.hpp.
Member Function Documentation
append() [1/7]
XalanDOMString& xalanc::XalanDOMString::append (const char * theString) inline
Definition at line 518 of file XalanDOMString.hpp.
References xalanc::append(), and xalanc::length().
append() [2/7]
XalanDOMString& xalanc::XalanDOMString::append (const char * theString, size_type theCount)
append() [3/7]
XalanDOMString& xalanc::XalanDOMString::append (const XalanDOMChar * theString) inline
Definition at line 507 of file XalanDOMString.hpp.
References xalanc::append(), and xalanc::length().
append() [4/7]
XalanDOMString& xalanc::XalanDOMString::append (const XalanDOMChar * theString, size_type theCount)
append() [5/7]
XalanDOMString& xalanc::XalanDOMString::append (const XalanDOMString & theSource) inline
Definition at line 484 of file XalanDOMString.hpp.
References xalanc::append(), c_str(), and length().
Referenced by xalanc::append(), xalanc::DOMServices::getNodeData(), and xalanc::XObject::string().
append() [6/7]
XalanDOMString& xalanc::XalanDOMString::append (const XalanDOMString & theSource, size_type thePosition, size_type theCount) inline
Definition at line 490 of file XalanDOMString.hpp.
References xalanc::append(), c_str(), and length().
append() [7/7]
XalanDOMString& xalanc::XalanDOMString::append (size_type theCount, XalanDOMChar theChar)
assign() [1/8]
XalanDOMString& xalanc::XalanDOMString::assign (const char * theSource) inline
Definition at line 416 of file XalanDOMString.hpp.
References xalanc::append(), and xalanc::erase().
assign() [2/8]
XalanDOMString& xalanc::XalanDOMString::assign (const char * theSource, size_type theCount) inline
Definition at line 428 of file XalanDOMString.hpp.
References xalanc::append(), and xalanc::erase().
assign() [3/8]
XalanDOMString& xalanc::XalanDOMString::assign (const XalanDOMChar * theSource) inline
Definition at line 390 of file XalanDOMString.hpp.
References xalanc::append(), and xalanc::erase().
Referenced by xalanc::assign(), xalanc::AVT::evaluate(), xalanc::XPathFunctionTable::getInstalledFunctionNames(), xalanc::StylesheetRoot::getOutputDoctypePublic(), xalanc::StylesheetRoot::getOutputDoctypeSystem(), xalanc::StylesheetRoot::getOutputEncoding(), xalanc::StylesheetRoot::getOutputMediaType(), xalanc::StylesheetRoot::getOutputStandalone(), xalanc::StylesheetRoot::getOutputVersion(), xalanc::XPathFunctionTable::idToName(), substr(), and xalanc::TranscodeFromLocalCodePage().
assign() [4/8]
XalanDOMString& xalanc::XalanDOMString::assign (const XalanDOMChar * theSource, size_type theCount) inline
Definition at line 402 of file XalanDOMString.hpp.
References xalanc::append(), and xalanc::erase().
assign() [5/8]
XalanDOMString& xalanc::XalanDOMString::assign (const XalanDOMString & theSource) inline
Definition at line 448 of file XalanDOMString.hpp.
assign() [6/8]
XalanDOMString& xalanc::XalanDOMString::assign (const XalanDOMString & theSource, size_type thePosition, size_type theCount)
assign() [7/8]
XalanDOMString& xalanc::XalanDOMString::assign (iterator theFirstPosition, iterator theLastPosition)
assign() [8/8]
XalanDOMString& xalanc::XalanDOMString::assign (size_type theCount, XalanDOMChar theChar) inline
Definition at line 465 of file XalanDOMString.hpp.
References xalanc::append(), and xalanc::erase().
at() [1/2]
reference xalanc::XalanDOMString::at (size_type theIndex) inline
Definition at line 336 of file XalanDOMString.hpp.
at() [2/2]
const_reference xalanc::XalanDOMString::at (size_type theIndex) const inline
Definition at line 328 of file XalanDOMString.hpp.
begin() [1/2]
iterator xalanc::XalanDOMString::begin () inline
Definition at line 123 of file XalanDOMString.hpp.
begin() [2/2]
const_iterator xalanc::XalanDOMString::begin () const inline
Definition at line 131 of file XalanDOMString.hpp.
c_str()
const XalanDOMChar* xalanc::XalanDOMString::c_str () const inline
Definition at line 344 of file XalanDOMString.hpp.
Referenced by xalanc::ResultNamespacesStack::addDeclaration(), xalanc::XalanNamespacesStack::addDeclaration(), xalanc::XSLTEngineImpl::addResultAttribute(), xalanc::XSLTEngineImpl::addResultNamespaceDecl(), append(), xalanc::c_wstr(), xalanc::collationCompare(), compare(), xalanc::compare(), xalanc::compareIgnoreCaseASCII(), xalanc::XSLException::defaultFormat(), xalanc::DOMStringToDouble(), xalanc::DOMStringToInt(), xalanc::DOMStringToLong(), xalanc::DOMStringToUnsignedLong(), xalanc::endsWith(), equals(), xalanc::equals(), xalanc::equalsIgnoreCaseASCII(), xalanc::Stylesheet::getNamespaceFromStack(), xalanc::URISupport::getURLFromString(), xalanc::URISupport::getURLStringFromString(), xalanc::indexOf(), insert(), xalanc::XPathFunctionTable::InstallFunction(), xalanc::lastIndexOf(), xalanc::MakeXalanDOMCharVector(), xalanc::c_wstr_functor::operator()(), xalanc::OutputString(), xalanc::XalanParsedURI::parse(), xalanc::XalanParsedURI::resolve(), xalanc::startsWith(), xalanc::XObject::string(), xalanc::XalanFormatterWriter::throwInvalidCharacterException(), xalanc::XalanFormatterWriter::throwInvalidUTF16SurrogateException(), xalanc::toCharArray(), xalanc::TranscodeToLocalCodePage(), xalanc::XPathFunctionTable::UninstallFunction(), xalanc::XalanUTF16Writer::write(), xalanc::XalanUTF8Writer::write(), xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::write(), xalanc::XercesWrapperHelper::XalanDOMStringToXercesDOMString(), and xalanc::XalanParsedURI::XalanParsedURI().
capacity()
size_type xalanc::XalanDOMString::capacity () const inline
Definition at line 238 of file XalanDOMString.hpp.
clear()
void xalanc::XalanDOMString::clear () inline
Definition at line 257 of file XalanDOMString.hpp.
Referenced by xalanc::clear(), and xalanc::XalanFormatterWriter::formatNumericCharacterReference().
clone()
XalanDOMString* xalanc::XalanDOMString::clone (MemoryManager & theManager)
compare() [1/5]
int xalanc::XalanDOMString::compare (const XalanDOMChar * theString) const
compare() [2/5]
int xalanc::XalanDOMString::compare (const XalanDOMString & theString) const inline
Definition at line 612 of file XalanDOMString.hpp.
References c_str(), and xalanc::compare().
Referenced by xalanc::EnumerateDirectory(), xalanc::XSLTEngineImpl::LessXalanDOMStringPointers::operator()(), xalanc::DOMStringLessThanFunction::operator()(), and xalanc::DOMStringPointerLessThanFunction::operator()().
compare() [3/5]
int xalanc::XalanDOMString::compare (size_type thePosition1, size_type theCount1, const XalanDOMChar * theString, size_type theCount2 = size_type(npos)) const
compare() [4/5]
int xalanc::XalanDOMString::compare (size_type thePosition1, size_type theCount1, const XalanDOMString & theString) const inline
Definition at line 620 of file XalanDOMString.hpp.
References c_str(), xalanc::compare(), and length().
compare() [5/5]
int xalanc::XalanDOMString::compare (size_type thePosition1, size_type theCount1, const XalanDOMString & theString, size_type thePosition2, size_type theCount2) const inline
Definition at line 631 of file XalanDOMString.hpp.
References c_str(), and xalanc::compare().
data()
const XalanDOMChar* xalanc::XalanDOMString::data () const inline
Definition at line 352 of file XalanDOMString.hpp.
References xalanc::c_str().
empty()
bool xalanc::XalanDOMString::empty () const inline
Definition at line 304 of file XalanDOMString.hpp.
Referenced by xalanc::Stylesheet::getCurrentIncludeBaseIdentifier(), xalanc::DOMServices::getLocalNameOfNode(), xalanc::isEmpty(), and xalanc::OutputString().
end() [1/2]
iterator xalanc::XalanDOMString::end () inline
Definition at line 139 of file XalanDOMString.hpp.
end() [2/2]
const_iterator xalanc::XalanDOMString::end () const inline
Definition at line 147 of file XalanDOMString.hpp.
equals() [1/5]
static bool xalanc::XalanDOMString::equals (const XalanDOMChar * theLHS, const XalanDOMChar * theRHS) inline static
Definition at line 717 of file XalanDOMString.hpp.
References xalanc::equals(), and xalanc::length().
equals() [2/5]
static bool xalanc::XalanDOMString::equals (const XalanDOMChar * theLHS, const XalanDOMString & theRHS) inline static
Definition at line 738 of file XalanDOMString.hpp.
References c_str(), and xalanc::equals().
equals() [3/5]
static bool xalanc::XalanDOMString::equals (const XalanDOMChar * theLHS, size_type theLHSLength, const XalanDOMChar * theRHS, size_type theRHSLength) static
equals() [4/5]
static bool xalanc::XalanDOMString::equals (const XalanDOMString & theLHS, const XalanDOMChar * theRHS) inline static
Definition at line 730 of file XalanDOMString.hpp.
References c_str(), and xalanc::equals().
equals() [5/5]
static bool xalanc::XalanDOMString::equals (const XalanDOMString & theLHS, const XalanDOMString & theRHS) static
erase() [1/3]
iterator xalanc::XalanDOMString::erase (iterator theFirst, iterator theLast) inline
Definition at line 283 of file XalanDOMString.hpp.
erase() [2/3]
iterator xalanc::XalanDOMString::erase (iterator thePosition) inline
Definition at line 269 of file XalanDOMString.hpp.
Referenced by xalanc::erase().
erase() [3/3]
XalanDOMString& xalanc::XalanDOMString::erase (size_type theStartPosition = 0, size_type theCount = size_type(npos))
getBackInsertIterator() [1/2]
iterator xalanc::XalanDOMString::getBackInsertIterator () inline protected
Definition at line 787 of file XalanDOMString.hpp.
getBackInsertIterator() [2/2]
const_iterator xalanc::XalanDOMString::getBackInsertIterator () const inline protected
Definition at line 795 of file XalanDOMString.hpp.
getIteratorForPosition() [1/2]
iterator xalanc::XalanDOMString::getIteratorForPosition (size_type thePosition) inline protected
Definition at line 803 of file XalanDOMString.hpp.
getIteratorForPosition() [2/2]
const_iterator xalanc::XalanDOMString::getIteratorForPosition (size_type thePosition) const inline protected
Definition at line 811 of file XalanDOMString.hpp.
getMemoryManager()
MemoryManager& xalanc::XalanDOMString::getMemoryManager () inline
Definition at line 688 of file XalanDOMString.hpp.
Referenced by xalanc::append(), and xalanc::operator<<().
hash() [1/2]
size_t xalanc::XalanDOMString::hash () const inline
Definition at line 694 of file XalanDOMString.hpp.
References xalanc::c_str(), and xalanc::length().
Referenced by xalanc::DOMStringHashFunction::operator()(), and xalanc::DOMStringPointerHashFunction::operator()().
hash() [2/2]
static size_t xalanc::XalanDOMString::hash (const XalanDOMChar * theString, size_type theLength) inline static
Definition at line 700 of file XalanDOMString.hpp.
insert() [1/8]
void xalanc::XalanDOMString::insert (iterator theInsertPosition, iterator theFirstPosition, iterator theLastPosition)
insert() [2/8]
void xalanc::XalanDOMString::insert (iterator thePosition, size_type theCount, XalanDOMChar theChar)
insert() [3/8]
iterator xalanc::XalanDOMString::insert (iterator thePosition, XalanDOMChar theChar)
insert() [4/8]
XalanDOMString& xalanc::XalanDOMString::insert (size_type thePosition, const XalanDOMChar * theString) inline
Definition at line 563 of file XalanDOMString.hpp.
References xalanc::insert(), and xalanc::length().
insert() [5/8]
XalanDOMString& xalanc::XalanDOMString::insert (size_type thePosition, const XalanDOMChar * theString, size_type theCount)
insert() [6/8]
XalanDOMString& xalanc::XalanDOMString::insert (size_type thePosition, const XalanDOMString & theString) inline
Definition at line 539 of file XalanDOMString.hpp.
References c_str(), xalanc::insert(), and length().
Referenced by xalanc::insert().
insert() [7/8]
XalanDOMString& xalanc::XalanDOMString::insert (size_type thePosition, size_type theCount, XalanDOMChar theChar)
insert() [8/8]
XalanDOMString& xalanc::XalanDOMString::insert (size_type thePosition1, const XalanDOMString & theString, size_type thePosition2, size_type theCount) inline
Definition at line 547 of file XalanDOMString.hpp.
References c_str(), and xalanc::insert().
invariants()
void xalanc::XalanDOMString::invariants () const inline protected
Definition at line 773 of file XalanDOMString.hpp.
length() [1/3]
size_type xalanc::XalanDOMString::length () const inline
Definition at line 209 of file XalanDOMString.hpp.
Referenced by xalanc::ResultNamespacesStack::addDeclaration(), xalanc::XalanNamespacesStack::addDeclaration(), xalanc::XSLTEngineImpl::addResultNamespaceDecl(), append(), xalanc::XObject::boolean(), xalanc::collationCompare(), compare(), xalanc::compare(), xalanc::compareIgnoreCaseASCII(), xalanc::endsWith(), xalanc::equals(), xalanc::equalsIgnoreCaseASCII(), xalanc::URISupport::getURLStringFromString(), xalanc::indexOf(), insert(), xalanc::length(), xalanc::XalanParsedURI::parse(), xalanc::XalanParsedURI::resolve(), xalanc::startsWith(), xalanc::XObject::string(), xalanc::XalanUTF16Writer::write(), xalanc::XalanUTF8Writer::write(), xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::write(), xalanc::XercesWrapperHelper::XalanDOMStringToXercesDOMString(), xalanc::XercesBridgeHelper::XalanDOMStringToXercesDOMString(), and xalanc::XalanParsedURI::XalanParsedURI().
length() [2/3]
static size_type xalanc::XalanDOMString::length (const char * theString) static
length() [3/3]
static size_type xalanc::XalanDOMString::length (const XalanDOMChar * theString) static
max_size()
size_type xalanc::XalanDOMString::max_size () const inline
Definition at line 217 of file XalanDOMString.hpp.
operator+=() [1/3]
XalanDOMString& xalanc::XalanDOMString::operator+= (const XalanDOMChar * theString) inline
Definition at line 376 of file XalanDOMString.hpp.
References xalanc::append().
operator+=() [2/3]
XalanDOMString& xalanc::XalanDOMString::operator+= (const XalanDOMString & theSource) inline
Definition at line 370 of file XalanDOMString.hpp.
References xalanc::append().
operator+=() [3/3]
XalanDOMString& xalanc::XalanDOMString::operator+= (XalanDOMChar theChar) inline
Definition at line 382 of file XalanDOMString.hpp.
References xalanc::append().
operator=() [1/4]
XalanDOMString& xalanc::XalanDOMString::operator= (const char * theRHS) inline
Definition at line 111 of file XalanDOMString.hpp.
References xalanc::assign().
operator=() [2/4]
XalanDOMString& xalanc::XalanDOMString::operator= (const XalanDOMChar * theRHS) inline
Definition at line 105 of file XalanDOMString.hpp.
References xalanc::assign().
operator=() [3/4]
XalanDOMString& xalanc::XalanDOMString::operator= (const XalanDOMString & theRHS) inline
Definition at line 99 of file XalanDOMString.hpp.
References xalanc::assign().
operator=() [4/4]
XalanDOMString& xalanc::XalanDOMString::operator= (XalanDOMChar theRHS) inline
Definition at line 117 of file XalanDOMString.hpp.
References xalanc::assign().
operator[]() [1/2]
reference xalanc::XalanDOMString::operator[] (size_type theIndex) inline
Definition at line 320 of file XalanDOMString.hpp.
operator[]() [2/2]
const_reference xalanc::XalanDOMString::operator[] (size_type theIndex) const inline
Definition at line 312 of file XalanDOMString.hpp.
push_back()
void xalanc::XalanDOMString::push_back (XalanDOMChar theChar) inline
Definition at line 529 of file XalanDOMString.hpp.
References xalanc::append().
Referenced by xalanc::XalanFormatterWriter::formatNumericCharacterReference().
rbegin() [1/2]
reverse_iterator xalanc::XalanDOMString::rbegin () inline
Definition at line 155 of file XalanDOMString.hpp.
rbegin() [2/2]
const_reverse_iterator xalanc::XalanDOMString::rbegin () const inline
Definition at line 170 of file XalanDOMString.hpp.
rend() [1/2]
reverse_iterator xalanc::XalanDOMString::rend () inline
Definition at line 185 of file XalanDOMString.hpp.
rend() [2/2]
const_reverse_iterator xalanc::XalanDOMString::rend () const inline
Definition at line 193 of file XalanDOMString.hpp.
reserve()
void xalanc::XalanDOMString::reserve (size_type theCount = 0) inline
Definition at line 249 of file XalanDOMString.hpp.
Referenced by xalanc::reserve().
reset() [1/2]
void xalanc::XalanDOMString::reset (MemoryManager & theManager, const char * theString)
reset() [2/2]
void xalanc::XalanDOMString::reset (MemoryManager & theManager, const XalanDOMChar * theString)
resize() [1/2]
void xalanc::XalanDOMString::resize (size_type theCount) inline
Definition at line 230 of file XalanDOMString.hpp.
resize() [2/2]
void xalanc::XalanDOMString::resize (size_type theCount, XalanDOMChar theChar)
size()
size_type xalanc::XalanDOMString::size () const inline
Definition at line 201 of file XalanDOMString.hpp.
Referenced by xalanc::XSLException::defaultFormat(), and xalanc::EnumerateDirectory().
substr()
XalanDOMString& xalanc::XalanDOMString::substr (XalanDOMString & theSubstring, size_type thePosition = 0, size_type theCount = size_type(npos)) const inline
Definition at line 595 of file XalanDOMString.hpp.
References assign(), and xalanc::length().
Referenced by xalanc::EnumerateDirectory().
swap()
void xalanc::XalanDOMString::swap (XalanDOMString & theOther) inline
Definition at line 360 of file XalanDOMString.hpp.
References xalanc::swap().
Referenced by xalanc::releaseMemory().
transcode()
void xalanc::XalanDOMString::transcode (CharVectorType & theResult) const
Transcode the string to the local code page.
If the string cannot be properly transcoded, and the transcoder can detect the error a TranscodingError exception is thrown.
Parameters
theResult A CharVectorType instance for the transcoded string. The string is null-terminated.
Member Data Documentation
const_reference
const typedef XalanDOMChar& xalanc::XalanDOMString::const_reference
Definition at line 55 of file XalanDOMString.hpp.
npos
const size_type xalanc::XalanDOMString::npos static
Definition at line 64 of file XalanDOMString.hpp.
The documentation for this class was generated from the following file:
xalanc/XalanDOM/XalanDOMString.hpp