Xalan-C++ API Reference: xalanc::XalanNamespacesStack Class Reference
xalanc::XalanNamespacesStack Class Reference
#include <xalanc/DOMSupport/XalanNamespacesStack.hpp>
Classes
class PrefixResolverProxy
class XalanNamespacesStackEntry
Public Types
typedef XalanNamespacesStackEntry value_type
typedef XalanDeque< value_type, ConstructWithMemoryManagerTraits< value_type > > NamespacesStackType
typedef XalanVector< bool > BoolVectorType
typedef NamespacesStackType::iterator iterator
typedef NamespacesStackType::reverse_iterator reverse_iterator
typedef NamespacesStackType::const_iterator const_iterator
typedef NamespacesStackType::const_reverse_iterator const_reverse_iterator
typedef NamespacesStackType::size_type size_type
Public Member Functions
XalanNamespacesStack (MemoryManager &theManager)
~XalanNamespacesStack ()
void addDeclaration (const XalanDOMString &thePrefix, const XalanDOMString &theURI)
void addDeclaration (const XalanDOMString &thePrefix, const XalanDOMChar *theURI)
void addDeclaration (const XalanDOMString &thePrefix, const XalanDOMChar *theURI, XalanDOMString::size_type theLength)
void pushContext ()
void popContext ()
const XalanDOMString * getNamespaceForPrefix (const XalanDOMString &thePrefix) const
const XalanDOMString * getPrefixForNamespace (const XalanDOMString &theURI) const
bool prefixIsPresentLocal (const XalanDOMString &thePrefix)
See if the prefix has been mapped to a namespace in the current context, without looking down the stack of namespaces.
void clear ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type size () const
bool empty () const
Public Attributes
const typedef XalanDOMString *(value_type::* MemberFunctionType)(const XalanDOMString &) const
Detailed Description
Definition at line 45 of file XalanNamespacesStack.hpp.
Member Typedef Documentation
BoolVectorType
typedef XalanVector<bool> xalanc::XalanNamespacesStack::BoolVectorType
Definition at line 223 of file XalanNamespacesStack.hpp.
const_iterator
typedef NamespacesStackType::const_iterator xalanc::XalanNamespacesStack::const_iterator
Definition at line 227 of file XalanNamespacesStack.hpp.
const_reverse_iterator
typedef NamespacesStackType::const_reverse_iterator xalanc::XalanNamespacesStack::const_reverse_iterator
Definition at line 228 of file XalanNamespacesStack.hpp.
iterator
typedef NamespacesStackType::iterator xalanc::XalanNamespacesStack::iterator
Definition at line 225 of file XalanNamespacesStack.hpp.
NamespacesStackType
typedef XalanDeque<value_type, ConstructWithMemoryManagerTraits<value_type> > xalanc::XalanNamespacesStack::NamespacesStackType
Definition at line 222 of file XalanNamespacesStack.hpp.
reverse_iterator
typedef NamespacesStackType::reverse_iterator xalanc::XalanNamespacesStack::reverse_iterator
Definition at line 226 of file XalanNamespacesStack.hpp.
size_type
typedef NamespacesStackType::size_type xalanc::XalanNamespacesStack::size_type
Definition at line 230 of file XalanNamespacesStack.hpp.
value_type
typedef XalanNamespacesStackEntry xalanc::XalanNamespacesStack::value_type
Definition at line 220 of file XalanNamespacesStack.hpp.
Constructor & Destructor Documentation
XalanNamespacesStack()
xalanc::XalanNamespacesStack::XalanNamespacesStack (MemoryManager & theManager) explicit
~XalanNamespacesStack()
xalanc::XalanNamespacesStack::~XalanNamespacesStack ()
Member Function Documentation
addDeclaration() [1/3]
void xalanc::XalanNamespacesStack::addDeclaration (const XalanDOMString & thePrefix, const XalanDOMChar * theURI) inline
Definition at line 252 of file XalanNamespacesStack.hpp.
References xalanc::length().
addDeclaration() [2/3]
void xalanc::XalanNamespacesStack::addDeclaration (const XalanDOMString & thePrefix, const XalanDOMChar * theURI, XalanDOMString::size_type theLength)
addDeclaration() [3/3]
void xalanc::XalanNamespacesStack::addDeclaration (const XalanDOMString & thePrefix, const XalanDOMString & theURI) inline
Definition at line 241 of file XalanNamespacesStack.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
begin() [1/2]
iterator xalanc::XalanNamespacesStack::begin () inline
Definition at line 294 of file XalanNamespacesStack.hpp.
begin() [2/2]
const_iterator xalanc::XalanNamespacesStack::begin () const inline
Definition at line 300 of file XalanNamespacesStack.hpp.
clear()
void xalanc::XalanNamespacesStack::clear ()
empty()
bool xalanc::XalanNamespacesStack::empty () const inline
Definition at line 348 of file XalanNamespacesStack.hpp.
end() [1/2]
iterator xalanc::XalanNamespacesStack::end () inline
Definition at line 306 of file XalanNamespacesStack.hpp.
end() [2/2]
const_iterator xalanc::XalanNamespacesStack::end () const inline
Definition at line 312 of file XalanNamespacesStack.hpp.
getNamespaceForPrefix()
const XalanDOMString* xalanc::XalanNamespacesStack::getNamespaceForPrefix (const XalanDOMString & thePrefix) const
getPrefixForNamespace()
const XalanDOMString* xalanc::XalanNamespacesStack::getPrefixForNamespace (const XalanDOMString & theURI) const inline
Definition at line 278 of file XalanNamespacesStack.hpp.
popContext()
void xalanc::XalanNamespacesStack::popContext ()
prefixIsPresentLocal()
bool xalanc::XalanNamespacesStack::prefixIsPresentLocal (const XalanDOMString & thePrefix)
See if the prefix has been mapped to a namespace in the current context, without looking down the stack of namespaces.
pushContext()
void xalanc::XalanNamespacesStack::pushContext ()
rbegin() [1/2]
reverse_iterator xalanc::XalanNamespacesStack::rbegin () inline
Definition at line 318 of file XalanNamespacesStack.hpp.
rbegin() [2/2]
const_reverse_iterator xalanc::XalanNamespacesStack::rbegin () const inline
Definition at line 324 of file XalanNamespacesStack.hpp.
rend() [1/2]
reverse_iterator xalanc::XalanNamespacesStack::rend () inline
Definition at line 330 of file XalanNamespacesStack.hpp.
rend() [2/2]
const_reverse_iterator xalanc::XalanNamespacesStack::rend () const inline
Definition at line 336 of file XalanNamespacesStack.hpp.
size()
size_type xalanc::XalanNamespacesStack::size () const inline
Definition at line 342 of file XalanNamespacesStack.hpp.
Member Data Documentation
MemberFunctionType
const typedef XalanDOMString*(value_type::* xalanc::XalanNamespacesStack::MemberFunctionType) (const XalanDOMString &) const
Definition at line 232 of file XalanNamespacesStack.hpp.
The documentation for this class was generated from the following file:
xalanc/DOMSupport/XalanNamespacesStack.hpp