Xalan-C++ API Reference: xalanc::XalanParsedURI Class Reference
xalanc::XalanParsedURI Class Reference
URI handling (hopefully) according to RFC2396.
#include <xalanc/PlatformSupport/XalanParsedURI.hpp>
Public Types
enum eComponent { d_scheme = 1, d_authority = 2, d_query = 4, d_fragment = 8 }
Public Member Functions
XalanParsedURI (MemoryManager &theManager)
Default constructor.
XalanParsedURI (const XalanDOMChar *uriString, XalanDOMString::size_type uriStringLen, MemoryManager &theManager)
Constructor which parses the passed in uri.
XalanParsedURI (const XalanDOMString &uriString, MemoryManager &theManager)
Constructor which parses the passed in uri.
MemoryManager & getMemoryManager ()
void parse (const XalanDOMChar *uriString, XalanDOMString::size_type uriStringLen)
Parse the passed in uri.
void parse (const XalanDOMString &uriString)
Parse the passed in uri.
XalanDOMString & make (XalanDOMString &theResult) const
Reassemble the uri components to make a complete URI.
void resolve (const XalanParsedURI &base)
Resolve this URI relative to another, according to RFC2396.
void resolve (const XalanDOMChar *base, const XalanDOMString::size_type baseLen)
Resolve this URI relative to another.
void resolve (const XalanDOMString &base)
Resolve this URI relative to another.
const XalanDOMString & getScheme () const
Get the scheme component.
bool isSchemeDefined () const
See if the scheme component is defined.
void setScheme (const XalanDOMChar *scheme)
Set the scheme component.
void setScheme (const XalanDOMString &scheme)
Set the scheme component.
const XalanDOMString & getAuthority () const
Get the authority component.
bool isAuthorityDefined () const
See if the authority component is defined.
void setAuthority (const XalanDOMChar *authority)
Set the authority component.
void setAuthority (const XalanDOMString &authority)
Set the authority component.
const XalanDOMString & getPath () const
Get the path component.
void setPath (const XalanDOMChar *path)
Set the path component.
void setPath (const XalanDOMString &path)
Set the path component.
const XalanDOMString & getQuery () const
Get function to get the query component.
bool isQueryDefined () const
See if the query component is defined.
void setQuery (const XalanDOMChar *query)
Set the query component.
void setQuery (const XalanDOMString &query)
Set the query component.
const XalanDOMString & getFragment () const
Get the fragment component.
bool isFragmentDefined () const
See if the fragment component is defined.
void setFragment (const XalanDOMChar *fragment)
Set the fragment component.
void setFragment (const XalanDOMString &fragment)
Set the fragment component.
unsigned int getDefined () const
Get the defined components mask.
void setDefined (unsigned int defined)
Set the defined components mask.
Static Public Member Functions
static XalanDOMString & resolve (const XalanDOMChar *relative, XalanDOMString::size_type relativeLen, const XalanDOMChar *base, XalanDOMString::size_type baseLen, XalanDOMString &theResult)
Resolve the one URI relative to another.
static XalanDOMString & resolve (const XalanDOMString &relative, const XalanDOMString &base, XalanDOMString &theResult)
Resolve the one URI relative to another.
Detailed Description
URI handling (hopefully) according to RFC2396.
Definition at line 41 of file XalanParsedURI.hpp.
Member Enumeration Documentation
eComponent
enum xalanc::XalanParsedURI::eComponent
Enumerator
d_scheme
d_authority
d_query
d_fragment
Definition at line 47 of file XalanParsedURI.hpp.
Constructor & Destructor Documentation
XalanParsedURI() [1/3]
xalanc::XalanParsedURI::XalanParsedURI (MemoryManager & theManager) inline
Default constructor.
Definition at line 58 of file XalanParsedURI.hpp.
XalanParsedURI() [2/3]
xalanc::XalanParsedURI::XalanParsedURI (const XalanDOMChar * uriString, XalanDOMString::size_type uriStringLen, MemoryManager & theManager) inline
Constructor which parses the passed in uri.
Parameters
uriString URI to parse
uriStringLen Length of the URI string
Definition at line 74 of file XalanParsedURI.hpp.
XalanParsedURI() [3/3]
xalanc::XalanParsedURI::XalanParsedURI (const XalanDOMString & uriString, MemoryManager & theManager) inline
Constructor which parses the passed in uri.
Parameters
uriString URI to parse
Definition at line 93 of file XalanParsedURI.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
Member Function Documentation
getAuthority()
const XalanDOMString& xalanc::XalanParsedURI::getAuthority () const inline
Get the authority component.
Definition at line 245 of file XalanParsedURI.hpp.
getDefined()
unsigned int xalanc::XalanParsedURI::getDefined () const inline
Get the defined components mask.
Definition at line 371 of file XalanParsedURI.hpp.
getFragment()
const XalanDOMString& xalanc::XalanParsedURI::getFragment () const inline
Get the fragment component.
Definition at line 337 of file XalanParsedURI.hpp.
getMemoryManager()
MemoryManager& xalanc::XalanParsedURI::getMemoryManager () inline
Definition at line 107 of file XalanParsedURI.hpp.
getPath()
const XalanDOMString& xalanc::XalanParsedURI::getPath () const inline
Get the path component.
Definition at line 279 of file XalanParsedURI.hpp.
getQuery()
const XalanDOMString& xalanc::XalanParsedURI::getQuery () const inline
Get function to get the query component.
Definition at line 303 of file XalanParsedURI.hpp.
getScheme()
const XalanDOMString& xalanc::XalanParsedURI::getScheme () const inline
Get the scheme component.
Definition at line 211 of file XalanParsedURI.hpp.
isAuthorityDefined()
bool xalanc::XalanParsedURI::isAuthorityDefined () const inline
See if the authority component is defined.
Definition at line 253 of file XalanParsedURI.hpp.
isFragmentDefined()
bool xalanc::XalanParsedURI::isFragmentDefined () const inline
See if the fragment component is defined.
Definition at line 345 of file XalanParsedURI.hpp.
isQueryDefined()
bool xalanc::XalanParsedURI::isQueryDefined () const inline
See if the query component is defined.
Definition at line 311 of file XalanParsedURI.hpp.
isSchemeDefined()
bool xalanc::XalanParsedURI::isSchemeDefined () const inline
See if the scheme component is defined.
Definition at line 219 of file XalanParsedURI.hpp.
make()
XalanDOMString& xalanc::XalanParsedURI::make (XalanDOMString & theResult) const
Reassemble the uri components to make a complete URI.
Returns
The reassembled URI
parse() [1/2]
void xalanc::XalanParsedURI::parse (const XalanDOMChar * uriString, XalanDOMString::size_type uriStringLen)
Parse the passed in uri.
Parameters
uriString URI to parse
uriStringLen Length of the URI string
parse() [2/2]
void xalanc::XalanParsedURI::parse (const XalanDOMString & uriString) inline
Parse the passed in uri.
Parameters
uriString URI to parse
uriStringLen Length of the URI string
Definition at line 128 of file XalanParsedURI.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
resolve() [1/5]
void xalanc::XalanParsedURI::resolve (const XalanDOMChar * base, const XalanDOMString::size_type baseLen) inline
Resolve this URI relative to another.
Parameters
base The base URI string
baseLen The length of the base URI
Definition at line 154 of file XalanParsedURI.hpp.
resolve() [2/5]
static XalanDOMString& xalanc::XalanParsedURI::resolve (const XalanDOMChar * relative, XalanDOMString::size_type relativeLen, const XalanDOMChar * base, XalanDOMString::size_type baseLen, XalanDOMString & theResult) static
Resolve the one URI relative to another.
@relative The URI string to resolve @relativeLen The lengh of the relative URI string @base The base URI string @baseLen The length of the base URI string
resolve() [3/5]
void xalanc::XalanParsedURI::resolve (const XalanDOMString & base) inline
Resolve this URI relative to another.
Parameters
base The base URI string
Definition at line 168 of file XalanParsedURI.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
resolve() [4/5]
static XalanDOMString& xalanc::XalanParsedURI::resolve (const XalanDOMString & relative, const XalanDOMString & base, XalanDOMString & theResult) inline static
Resolve the one URI relative to another.
@relative The URI string to resolve @base The base URI string
Definition at line 199 of file XalanParsedURI.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
resolve() [5/5]
void xalanc::XalanParsedURI::resolve (const XalanParsedURI & base)
Resolve this URI relative to another, according to RFC2396.
Parameters
base The base URI to use during resolution.
setAuthority() [1/2]
void xalanc::XalanParsedURI::setAuthority (const XalanDOMChar * authority) inline
Set the authority component.
Also sets the authority defined flag.
Definition at line 261 of file XalanParsedURI.hpp.
setAuthority() [2/2]
void xalanc::XalanParsedURI::setAuthority (const XalanDOMString & authority) inline
Set the authority component.
Also sets the authority defined flag.
Definition at line 270 of file XalanParsedURI.hpp.
setDefined()
void xalanc::XalanParsedURI::setDefined (unsigned int defined) inline
Set the defined components mask.
Definition at line 379 of file XalanParsedURI.hpp.
setFragment() [1/2]
void xalanc::XalanParsedURI::setFragment (const XalanDOMChar * fragment) inline
Set the fragment component.
Also sets the fragment defined flag.
Definition at line 353 of file XalanParsedURI.hpp.
setFragment() [2/2]
void xalanc::XalanParsedURI::setFragment (const XalanDOMString & fragment) inline
Set the fragment component.
Also sets the fragment defined flag.
Definition at line 362 of file XalanParsedURI.hpp.
setPath() [1/2]
void xalanc::XalanParsedURI::setPath (const XalanDOMChar * path) inline
Set the path component.
Definition at line 287 of file XalanParsedURI.hpp.
setPath() [2/2]
void xalanc::XalanParsedURI::setPath (const XalanDOMString & path) inline
Set the path component.
Definition at line 295 of file XalanParsedURI.hpp.
setQuery() [1/2]
void xalanc::XalanParsedURI::setQuery (const XalanDOMChar * query) inline
Set the query component.
Also sets the query defined flag.
Definition at line 319 of file XalanParsedURI.hpp.
setQuery() [2/2]
void xalanc::XalanParsedURI::setQuery (const XalanDOMString & query) inline
Set the query component.
Also sets the query defined flag.
Definition at line 328 of file XalanParsedURI.hpp.
setScheme() [1/2]
void xalanc::XalanParsedURI::setScheme (const XalanDOMChar * scheme) inline
Set the scheme component.
Also sets the scheme defined flag.
Definition at line 227 of file XalanParsedURI.hpp.
setScheme() [2/2]
void xalanc::XalanParsedURI::setScheme (const XalanDOMString & scheme) inline
Set the scheme component.
Also sets the scheme defined flag.
Definition at line 236 of file XalanParsedURI.hpp.
The documentation for this class was generated from the following file:
xalanc/PlatformSupport/XalanParsedURI.hpp