Xalan-C++ API Reference: xalanc::XalanNode Class Reference
xalanc::XalanNode Class Reference abstract
#include <xalanc/XalanDOM/XalanNode.hpp>
Public Types
enum NodeType {
UNKNOWN_NODE = 0, ELEMENT_NODE = 1, ATTRIBUTE_NODE = 2, TEXT_NODE = 3,
CDATA_SECTION_NODE = 4, ENTITY_REFERENCE_NODE = 5, ENTITY_NODE = 6, PROCESSING_INSTRUCTION_NODE = 7,
COMMENT_NODE = 8, DOCUMENT_NODE = 9, DOCUMENT_TYPE_NODE = 10, DOCUMENT_FRAGMENT_NODE = 11,
NOTATION_NODE = 12
}
typedef unsigned long IndexType
Public Member Functions
XalanNode ()
virtual ~XalanNode ()
virtual const XalanDOMString & getNodeName () const =0
Gets the name of this node, depending on its type.
virtual const XalanDOMString & getNodeValue () const =0
Gets the value of this node, depending on its type.
virtual NodeType getNodeType () const =0
An enum value representing the type of the underlying object.
virtual XalanNode * getParentNode () const =0
Gets the parent of this node.
virtual const XalanNodeList * getChildNodes () const =0
Gets a XalanNodeList that contains all children of this node.
virtual XalanNode * getFirstChild () const =0
Gets the first child of this node.
virtual XalanNode * getLastChild () const =0
Gets the last child of this node.
virtual XalanNode * getPreviousSibling () const =0
Gets the node immediately preceding this node.
virtual XalanNode * getNextSibling () const =0
Gets the node immediately following this node.
virtual const XalanNamedNodeMap * getAttributes () const =0
Gets a XalanNamedNodeMap containing the attributes of this node (if it is an XalanElement) or a null pointer otherwise.
virtual XalanDocument * getOwnerDocument () const =0
Gets the XalanDocument object associated with this node.
virtual const XalanDOMString & getNamespaceURI () const =0
Get the namespace URI of this node.
virtual const XalanDOMString & getPrefix () const =0
Get the namespace prefix of this node.
virtual const XalanDOMString & getLocalName () const =0
Returns the local part of the qualified name of this node.
virtual bool isIndexed () const =0
Determine if the document is node-order indexed.
virtual IndexType getIndex () const =0
Get the node's index.
Protected Member Functions
XalanNode (const XalanNode &theSource)
XalanNode & operator= (const XalanNode &theSource)
bool operator== (const XalanNode &theRHS) const
Detailed Description
Definition at line 38 of file XalanNode.hpp.
Member Typedef Documentation
IndexType
typedef unsigned long xalanc::XalanNode::IndexType
Definition at line 64 of file XalanNode.hpp.
Member Enumeration Documentation
NodeType
enum xalanc::XalanNode::NodeType
Enumerator
UNKNOWN_NODE
ELEMENT_NODE
ATTRIBUTE_NODE
TEXT_NODE
CDATA_SECTION_NODE
ENTITY_REFERENCE_NODE
ENTITY_NODE
PROCESSING_INSTRUCTION_NODE
COMMENT_NODE
DOCUMENT_NODE
DOCUMENT_TYPE_NODE
DOCUMENT_FRAGMENT_NODE
NOTATION_NODE
Definition at line 47 of file XalanNode.hpp.
Constructor & Destructor Documentation
XalanNode() [1/2]
xalanc::XalanNode::XalanNode ()
~XalanNode()
virtual xalanc::XalanNode::~XalanNode () virtual
XalanNode() [2/2]
xalanc::XalanNode::XalanNode (const XalanNode & theSource) protected
Member Function Documentation
getAttributes()
virtual const XalanNamedNodeMap* xalanc::XalanNode::getAttributes () const pure virtual
Gets a XalanNamedNodeMap containing the attributes of this node (if it is an XalanElement) or a null pointer otherwise.
Implemented in xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanProcessingInstruction, xalanc::XalanDocument, xalanc::XalanSourceTreeElement, xalanc::XalanAttr, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XalanSourceTreeDocument, xalanc::XercesElementBridge, xalanc::XercesDocumentWrapper, xalanc::XercesDocumentBridge, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesCommentBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, xalanc::XObjectResultTreeFragProxyBase, xalanc::XalanSourceTreeElementA, and xalanc::XalanSourceTreeElementNA.
getChildNodes()
virtual const XalanNodeList* xalanc::XalanNode::getChildNodes () const pure virtual
Gets a XalanNodeList that contains all children of this node.
If there are no children, this is a XalanNodeList containing no nodes.
Implemented in xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanProcessingInstruction, xalanc::XalanDocument, xalanc::XalanAttr, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentWrapper, xalanc::XercesDocumentBridge, xalanc::XercesElementBridge, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesCommentBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeElement, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, and xalanc::XObjectResultTreeFragProxyBase.
getFirstChild()
virtual XalanNode* xalanc::XalanNode::getFirstChild () const pure virtual
Gets the first child of this node.
If there is no such node, this returns a null pointer.
Implemented in xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanProcessingInstruction, xalanc::XalanDocument, xalanc::XalanAttr, xalanc::XObjectResultTreeFragProxyBase, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentWrapper, xalanc::XercesDocumentBridge, xalanc::XercesElementBridge, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesCommentBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeElement, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XObjectResultTreeFragProxy, xalanc::XercesTextWrapper, and xalanc::XNodeSetResultTreeFragProxy.
getIndex()
virtual IndexType xalanc::XalanNode::getIndex () const pure virtual
Get the node's index.
Valid only if the owner document reports that the document is node-order indexed.
Returns
The index value, or 0 if the node is not indexed.
Implemented in xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanProcessingInstruction, xalanc::XalanDocument, xalanc::XalanAttr, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XercesElementBridge, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesCommentBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentBridge, xalanc::XercesDocumentWrapper, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeElement, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, and xalanc::XObjectResultTreeFragProxyBase.
getLastChild()
virtual XalanNode* xalanc::XalanNode::getLastChild () const pure virtual
Gets the last child of this node.
If there is no such node, this returns a null pointer.
Implemented in xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanProcessingInstruction, xalanc::XalanDocument, xalanc::XalanAttr, xalanc::XObjectResultTreeFragProxyBase, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentWrapper, xalanc::XercesDocumentBridge, xalanc::XercesElementBridge, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesCommentBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeElement, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XObjectResultTreeFragProxy, xalanc::XercesTextWrapper, and xalanc::XNodeSetResultTreeFragProxy.
getLocalName()
virtual const XalanDOMString& xalanc::XalanNode::getLocalName () const pure virtual
Returns the local part of the qualified name of this node.
Implemented in xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanProcessingInstruction, xalanc::XalanDocument, xalanc::XalanSourceTreeElement, xalanc::XalanAttr, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XercesElementBridge, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesCommentBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentBridge, xalanc::XercesDocumentWrapper, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, xalanc::XObjectResultTreeFragProxyBase, xalanc::XalanSourceTreeElementA, xalanc::XalanSourceTreeElementANS, xalanc::XalanSourceTreeAttrNS, xalanc::XalanSourceTreeElementNA, and xalanc::XalanSourceTreeElementNANS.
Referenced by xalanc::DOMServices::getLocalNameOfNode().
getNamespaceURI()
virtual const XalanDOMString& xalanc::XalanNode::getNamespaceURI () const pure virtual
Get the namespace URI of this node.
Implemented in xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanProcessingInstruction, xalanc::XalanDocument, xalanc::XalanSourceTreeElement, xalanc::XalanAttr, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XercesElementBridge, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesCommentBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentBridge, xalanc::XercesDocumentWrapper, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, xalanc::XObjectResultTreeFragProxyBase, xalanc::XalanSourceTreeElementA, xalanc::XalanSourceTreeElementANS, xalanc::XalanSourceTreeAttrNS, xalanc::XalanSourceTreeElementNA, and xalanc::XalanSourceTreeElementNANS.
getNextSibling()
virtual XalanNode* xalanc::XalanNode::getNextSibling () const pure virtual
Gets the node immediately following this node.
If there is no such node, this returns a null pointer.
Implemented in xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanProcessingInstruction, xalanc::XalanDocument, xalanc::XalanAttr, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XalanSourceTreeDocument, xalanc::XercesElementBridge, xalanc::XercesDocumentWrapper, xalanc::XercesDocumentBridge, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesCommentBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeElement, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, and xalanc::XObjectResultTreeFragProxyBase.
getNodeName()
virtual const XalanDOMString& xalanc::XalanNode::getNodeName () const pure virtual
Gets the name of this node, depending on its type.
Implemented in xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanEntity, xalanc::XalanAttr, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocument, xalanc::XalanDocumentFragment, xalanc::XalanProcessingInstruction, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentWrapper, xalanc::XercesDocumentBridge, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeElement, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XercesElementBridge, xalanc::XalanSourceTreeAttr, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesCommentBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, and xalanc::XObjectResultTreeFragProxyBase.
Referenced by xalanc::DOMServices::getLocalNameOfNode().
getNodeType()
virtual NodeType xalanc::XalanNode::getNodeType () const pure virtual
An enum value representing the type of the underlying object.
Implemented in xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocument, xalanc::XalanAttr, xalanc::XalanProcessingInstruction, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentWrapper, xalanc::XercesDocumentBridge, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XercesElementBridge, xalanc::XalanSourceTreeElement, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XalanSourceTreeAttr, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesCommentBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, and xalanc::XObjectResultTreeFragProxyBase.
Referenced by xalanc::Stylesheet::findTemplate(), xalanc::DOMServices::getParentOfNode(), and xalanc::XPath::NodeTester::operator()().
getNodeValue()
virtual const XalanDOMString& xalanc::XalanNode::getNodeValue () const pure virtual
Gets the value of this node, depending on its type.
Implemented in xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanAttr, xalanc::XalanDocument, xalanc::XalanProcessingInstruction, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentWrapper, xalanc::XercesDocumentBridge, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeElement, xalanc::XercesElementBridge, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesCommentBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, and xalanc::XObjectResultTreeFragProxyBase.
getOwnerDocument()
virtual XalanDocument* xalanc::XalanNode::getOwnerDocument () const pure virtual
Gets the XalanDocument object associated with this node.
This may be a null pointer.
Implemented in xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanProcessingInstruction, xalanc::XalanDocument, xalanc::XalanAttr, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XalanSourceTreeDocument, xalanc::XercesElementBridge, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesCommentBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XercesDocumentWrapper, xalanc::XercesDocumentBridge, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeElement, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, and xalanc::XObjectResultTreeFragProxyBase.
getParentNode()
virtual XalanNode* xalanc::XalanNode::getParentNode () const pure virtual
Gets the parent of this node.
If there is no such node, this returns a null pointer.
Implemented in xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocument, xalanc::XalanProcessingInstruction, xalanc::XalanAttr, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentWrapper, xalanc::XercesDocumentBridge, xalanc::XercesElementBridge, xalanc::XalanSourceTreeComment, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesCommentBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeElement, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, and xalanc::XObjectResultTreeFragProxyBase.
Referenced by xalanc::DOMServices::getParentOfNode().
getPrefix()
virtual const XalanDOMString& xalanc::XalanNode::getPrefix () const pure virtual
Get the namespace prefix of this node.
Implemented in xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanProcessingInstruction, xalanc::XalanDocument, xalanc::XalanSourceTreeElement, xalanc::XalanAttr, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XercesElementBridge, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesCommentBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentBridge, xalanc::XercesDocumentWrapper, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, xalanc::XObjectResultTreeFragProxyBase, xalanc::XalanSourceTreeElementA, xalanc::XalanSourceTreeElementANS, xalanc::XalanSourceTreeAttrNS, xalanc::XalanSourceTreeElementNA, and xalanc::XalanSourceTreeElementNANS.
getPreviousSibling()
virtual XalanNode* xalanc::XalanNode::getPreviousSibling () const pure virtual
Gets the node immediately preceding this node.
If there is no such node, this returns a null pointer.
Implemented in xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanProcessingInstruction, xalanc::XalanDocument, xalanc::XalanAttr, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentWrapper, xalanc::XercesDocumentBridge, xalanc::XercesElementBridge, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesCommentBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeElement, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, and xalanc::XObjectResultTreeFragProxyBase.
isIndexed()
virtual bool xalanc::XalanNode::isIndexed () const pure virtual
Determine if the document is node-order indexed.
Returns
true if the document is indexed, otherwise false.
Implemented in xalanc::XalanEntity, xalanc::XalanEntityReference, xalanc::XalanNotation, xalanc::XalanText, xalanc::XalanDocumentType, xalanc::XalanElement, xalanc::XalanProcessingInstruction, xalanc::XalanDocument, xalanc::XalanAttr, xalanc::XalanDocumentFragment, xalanc::XalanCDATASection, xalanc::XalanCharacterData, xalanc::XalanComment, xalanc::XercesElementBridge, xalanc::XercesDocumentFragmentBridge, xalanc::XercesDocumentTypeBridge, xalanc::XercesEntityBridge, xalanc::XercesTextBridge, xalanc::XercesAttrBridge, xalanc::XercesCDATASectionBridge, xalanc::XercesEntityReferenceBridge, xalanc::XercesCommentBridge, xalanc::XercesNotationBridge, xalanc::XercesProcessingInstructionBridge, xalanc::XalanSourceTreeDocument, xalanc::XercesDocumentBridge, xalanc::XercesDocumentWrapper, xalanc::XalanSourceTreeComment, xalanc::XObjectResultTreeFragProxyText, xalanc::XalanSourceTreeText, xalanc::XalanSourceTreeElement, xalanc::XalanSourceTreeProcessingInstruction, xalanc::XalanSourceTreeAttr, xalanc::XalanSourceTreeDocumentFragment, xalanc::XercesEntityReferenceWrapper, xalanc::XercesEntityWrapper, xalanc::XercesProcessingInstructionWrapper, xalanc::XercesCDATASectionWrapper, xalanc::XercesDocumentTypeWrapper, xalanc::XercesNotationWrapper, xalanc::XercesAttrWrapper, xalanc::XercesElementWrapper, xalanc::XercesCommentWrapper, xalanc::XercesTextWrapper, and xalanc::XObjectResultTreeFragProxyBase.
operator=()
XalanNode& xalanc::XalanNode::operator= (const XalanNode & theSource) protected
operator==()
bool xalanc::XalanNode::operator== (const XalanNode & theRHS) const protected
The documentation for this class was generated from the following file:
xalanc/XalanDOM/XalanNode.hpp