Xalan-C++ API Reference: xalanc::XalanFormatterWriter Class Reference
xalanc::XalanFormatterWriter Class Reference
#include <xalanc/XMLSupport/XalanFormatterWriter.hpp>
Classes
class CommonRepresentableCharFunctor
class NewLineWriterFunctor
class WhiteSpaceWriterFunctor
Public Types
typedef FormatterListener::size_type size_type
Public Member Functions
XalanFormatterWriter (Writer &theWriter, MemoryManager &theMemoryManager)
MemoryManager & getMemoryManager ()
virtual ~XalanFormatterWriter ()
Writer * getWriter () const
XalanOutputStream * getStream ()
const XalanOutputStream * getStream () const
void flushWriter ()
void throwUnrepresentableCharacterException (XalanUnicodeChar ch, MemoryManager &theManager)
Static Public Member Functions
static bool isUTF16HighSurrogate (XalanDOMChar theChar)
static bool isUTF16LowSurrogate (XalanDOMChar theChar)
static XalanUnicodeChar decodeUTF16SurrogatePair (XalanDOMChar theHighSurrogate, XalanDOMChar theLowSurrogate, MemoryManager &theManager)
static void throwInvalidCharacterException (XalanUnicodeChar ch, MemoryManager &theManager)
static void throwInvalidUTF16SurrogateException (XalanDOMChar ch, XalanDOMChar next, MemoryManager &theManager)
Protected Member Functions
const XalanDOMString & formatNumericCharacterReference (XalanUnicodeChar theChar)
Format a code point as a numeric character reference.
Protected Attributes
Writer & m_writer
The writer.
MemoryManager & m_memoryManager
The MemoryManager instance to use for any dynamically- allocated memory.
XalanDOMString m_stringBuffer
const XalanDOMChar * m_newlineString
The string of characters that represents the newline.
size_type m_newlineStringLength
The length of the the string of characters that represents the newline.
Detailed Description
Definition at line 44 of file XalanFormatterWriter.hpp.
Member Typedef Documentation
size_type
typedef FormatterListener::size_type xalanc::XalanFormatterWriter::size_type
Definition at line 48 of file XalanFormatterWriter.hpp.
Constructor & Destructor Documentation
XalanFormatterWriter()
xalanc::XalanFormatterWriter::XalanFormatterWriter (Writer & theWriter, MemoryManager & theMemoryManager) inline
Definition at line 159 of file XalanFormatterWriter.hpp.
References xalanc::XalanOutputStream::getNewlineString(), xalanc::Writer::getStream(), and xalanc::length().
~XalanFormatterWriter()
virtual xalanc::XalanFormatterWriter::~XalanFormatterWriter () inline virtual
Definition at line 192 of file XalanFormatterWriter.hpp.
Member Function Documentation
decodeUTF16SurrogatePair()
static XalanUnicodeChar xalanc::XalanFormatterWriter::decodeUTF16SurrogatePair (XalanDOMChar theHighSurrogate, XalanDOMChar theLowSurrogate, MemoryManager & theManager) inline static
Definition at line 234 of file XalanFormatterWriter.hpp.
flushWriter()
void xalanc::XalanFormatterWriter::flushWriter () inline
Definition at line 215 of file XalanFormatterWriter.hpp.
formatNumericCharacterReference()
const XalanDOMString& xalanc::XalanFormatterWriter::formatNumericCharacterReference (XalanUnicodeChar theChar) inline protected
Format a code point as a numeric character reference.
Parameters
theChar A Unicode code point.
Definition at line 343 of file XalanFormatterWriter.hpp.
References xalanc::XalanDOMString::clear(), and xalanc::XalanDOMString::push_back().
getMemoryManager()
MemoryManager& xalanc::XalanFormatterWriter::getMemoryManager () inline
Definition at line 186 of file XalanFormatterWriter.hpp.
getStream() [1/2]
XalanOutputStream* xalanc::XalanFormatterWriter::getStream () inline
Definition at line 203 of file XalanFormatterWriter.hpp.
getStream() [2/2]
const XalanOutputStream* xalanc::XalanFormatterWriter::getStream () const inline
Definition at line 209 of file XalanFormatterWriter.hpp.
getWriter()
Writer* xalanc::XalanFormatterWriter::getWriter () const inline
Definition at line 197 of file XalanFormatterWriter.hpp.
isUTF16HighSurrogate()
static bool xalanc::XalanFormatterWriter::isUTF16HighSurrogate (XalanDOMChar theChar) inline static
Definition at line 222 of file XalanFormatterWriter.hpp.
isUTF16LowSurrogate()
static bool xalanc::XalanFormatterWriter::isUTF16LowSurrogate (XalanDOMChar theChar) inline static
Definition at line 228 of file XalanFormatterWriter.hpp.
throwInvalidCharacterException()
static void xalanc::XalanFormatterWriter::throwInvalidCharacterException (XalanUnicodeChar ch, MemoryManager & theManager) inline static
Definition at line 250 of file XalanFormatterWriter.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::NumberToHexDOMString().
throwInvalidUTF16SurrogateException()
static void xalanc::XalanFormatterWriter::throwInvalidUTF16SurrogateException (XalanDOMChar ch, XalanDOMChar next, MemoryManager & theManager) inline static
Definition at line 284 of file XalanFormatterWriter.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::NumberToHexDOMString().
throwUnrepresentableCharacterException()
void xalanc::XalanFormatterWriter::throwUnrepresentableCharacterException (XalanUnicodeChar ch, MemoryManager & theManager) inline
Definition at line 268 of file XalanFormatterWriter.hpp.
References xalanc::XalanOutputStream::getOutputEncoding().
Member Data Documentation
m_memoryManager
MemoryManager& xalanc::XalanFormatterWriter::m_memoryManager protected
The MemoryManager instance to use for any dynamically- allocated memory.
Definition at line 323 of file XalanFormatterWriter.hpp.
m_newlineString
const XalanDOMChar* xalanc::XalanFormatterWriter::m_newlineString protected
The string of characters that represents the newline.
Definition at line 330 of file XalanFormatterWriter.hpp.
m_newlineStringLength
size_type xalanc::XalanFormatterWriter::m_newlineStringLength protected
The length of the the string of characters that represents the newline.
Definition at line 335 of file XalanFormatterWriter.hpp.
m_stringBuffer
XalanDOMString xalanc::XalanFormatterWriter::m_stringBuffer protected
Definition at line 325 of file XalanFormatterWriter.hpp.
m_writer
Writer& xalanc::XalanFormatterWriter::m_writer protected
The writer.
Definition at line 317 of file XalanFormatterWriter.hpp.
The documentation for this class was generated from the following file:
xalanc/XMLSupport/XalanFormatterWriter.hpp