Xalan-C++ API Reference: xalanc::StylesheetRoot Class Reference
xalanc::StylesheetRoot Class Reference
This acts as the stylesheet root of the stylesheet tree, and holds values that are shared by all stylesheets in the tree.
#include <xalanc/XSLT/StylesheetRoot.hpp>
Public Types
typedef XalanVector< const XalanQName * > XalanQNameVectorType
typedef AttributeSetVectorTypeDecl AttributeSetVectorType
typedef XalanMap< const XalanQName *, AttributeSetVectorType > AttributeSetMapType
Public Types inherited from xalanc::Stylesheet
typedef StylesheetExecutionContext::ParamVectorType ParamVectorType
typedef XalanQName::NamespaceVectorType NamespaceVectorType
typedef XalanQName::NamespacesStackType NamespacesStackType
typedef XalanVector< ElemVariable * > ElemVariableVectorType
typedef XalanVector< KeyDeclaration > KeyDeclarationVectorType
typedef XalanVector< Stylesheet * > StylesheetVectorType
typedef XalanVector< XalanDOMString > URLStackType
typedef XalanVector< ElemDecimalFormat * > ElemDecimalFormatVectorType
typedef XalanVector< XalanSpaceNodeTester > WhitespaceElementsVectorType
typedef PatternTableVectorTypeDecl PatternTableVectorType
typedef XalanMap< XalanDOMString, ExtensionNSHandler * > ExtensionNamespacesMapType
typedef XalanMap< XalanQNameByReference, const ElemTemplate * > ElemTemplateMapType
typedef XalanMap< const XalanNode *, KeyTable * > KeyTablesTableType
typedef XalanMap< XalanDOMString, PatternTableVectorType > PatternTableMapType
typedef StylesheetConstructionContext::GetCachedString GetCachedString
Public Member Functions
StylesheetRoot (const XalanDOMString &baseIdentifier, StylesheetConstructionContext &constructionContext)
Construct a Stylesheet from a Document.
virtual ~StylesheetRoot ()
MemoryManager & getMemoryManager ()
virtual void postConstruction (StylesheetConstructionContext &constructionContext)
Called after construction is completed.
void process (XalanNode *sourceTree, XSLTResultTarget &outputTarget, StylesheetExecutionContext &executionContext) const
Transform the source tree to the output in the given result tree target.
FormatterListener * setupFormatterListener (XSLTResultTarget &outputTarget, StylesheetExecutionContext &executionContext) const
Have the stylesheet create the appropriate FormatterListener, based on the XSLTResultTarget provided.
FormatterListener::eFormat getOutputMethod () const
Return the output method that was specified in the stylesheet.
bool isOutputMethodSet () const
XalanDOMString & getOutputVersion (XalanDOMString &theResult) const
Get the output version string that was specified in the xsl:output element.
bool getOutputIndent () const
Determine if output indenting was specified in the xsl:output element.
bool getHTMLOutputIndent () const
Determine if output indenting should be enabled for HTML output.
XalanDOMString & getOutputEncoding (XalanDOMString &theResult) const
Get the output encoding string that was specified in the xsl:output element.
XalanDOMString & getOutputMediaType (XalanDOMString &theResult) const
Get the media-type string that was specified in the xsl:output element.
XalanDOMString & getOutputDoctypeSystem (XalanDOMString &theResult) const
Get the doctype-system-id string that was specified in the xsl:output element.
XalanDOMString & getOutputDoctypePublic (XalanDOMString &theResult) const
Get the doctype-public-id string that was specified in the xsl:output element.
bool getOmitOutputXMLDecl () const
Determine whether to output XML declarations.
XalanDOMString & getOutputStandalone (XalanDOMString &theResult) const
Get the standalone string that was specified in the xsl:output element.
ElemTemplateElement * getDefaultTextRule () const
Get the template representing the default rule for text.
ElemTemplateElement * getDefaultRule () const
Get the template representing the default rule.
ElemTemplateElement * getDefaultRootRule () const
Get the template representing the default root rule.
void processOutputSpec (const XalanDOMChar *name, const AttributeListType &atts, StylesheetConstructionContext &constructionContext)
Process the "xsl:output" element.
URLStackType & getImportStack ()
Retrieve the stack of imported stylesheets.
const URLStackType & getImportStack () const
Retrieve the stack of imported stylesheets.
void setIndentResult (bool bIndent)
Change the value of the flag for indenting results.
void setOutputMethod (FormatterListener::eFormat meth)
Change the value of the output method, one of the FormatterListener::eFormat values.
bool hasCDATASectionElements () const
bool isCDATASectionElementName (const XalanQName &theQName) const
Determine if a QName is in the list of CDATA section element QNames.
void getNodeSetByKey (XalanNode *context, const XalanQName &qname, const XalanDOMString &ref, const PrefixResolver &resolver, MutableNodeRefList &nodelist, StylesheetExecutionContext &executionContext, const Locator *locator, KeyTablesTableType &theKeysTable) const
Given a valid element key, return the corresponding node list.
unsigned long getNextElemNumberID ()
unsigned long getElemNumberCount () const
bool hasPreserveOrStripSpaceElements () const
bool shouldStripSourceNode (const XalanText &theNode) const
Check to see if a whitespace text node should be stripped from the source tree.
void addAttributeSet (ElemAttributeSet &theAttributeSet)
const ElemAttributeSet * getAttributeSet (StylesheetExecutionContext &theExecutionContext, const XalanQName &theQName, size_type matchingIndex, const Locator *theLocator) const
Get the nth attribute set with the specified name.
Public Member Functions inherited from xalanc::Stylesheet
Stylesheet (StylesheetRoot &root, const XalanDOMString &baseIdentifier, StylesheetConstructionContext &constructionContext)
Constructor for a Stylesheet needs a Document.
virtual ~Stylesheet ()
MemoryManager & getMemoryManager ()
double getXSLTVerDeclared () const
Retrieve XSLT version number.
void setXSLTVerDeclared (double ver)
Set XSLT version number.
const StylesheetRoot & getStylesheetRoot () const
Retrieve the root stylesheet object.
StylesheetRoot & getStylesheetRoot ()
Retrieve the root stylesheet object.
const NamespacesStackType & getNamespaces () const
Retrieve the stack of namespace lists.
NamespacesStackType & getNamespaces ()
Retrieve the stack of namespace lists.
const NamespacesHandler & getNamespacesHandler () const
NamespacesHandler & getNamespacesHandler ()
const NamespaceVectorType & getNamespaceDecls () const
Retrieve the list of namespace declarations currently in effect.
NamespaceVectorType & getNamespaceDecls ()
Retrieve the list of namespace declarations currently in effect.
void setNamespaceDecls (const NamespaceVectorType &ns)
Set the list of namespace declarations currently in effect.
void pushNamespaces (const AttributeListType &atts)
Push the namespace declarations from the current attribute list onto the namespace stack.
void popNamespaces ()
Pop a namespace declaration from the namespace stack.
void addWhitespaceElement (const XalanSpaceNodeTester &theTester)
bool isAttrOK (const XalanDOMChar *attrName, const AttributeListType &atts, XalanSize_t which, StylesheetConstructionContext &constructionContext) const
See if this is a xmlns attribute, and, if so, process it.
const XalanDOMString * getNamespaceFromStack (const XalanDOMString &nodeName, XalanDOMString &theBuffer) const
Get the namespace from a qualified name.
const XalanDOMString * getNamespaceFromStack (const XalanDOMChar *nodeName, XalanDOMString &theBuffer) const
Get the namespace from a qualified name.
const XalanDOMString * getNamespaceForPrefixFromStack (const XalanDOMString &prefix) const
Get the namespace from a prefix by searching the stack of namespace lists.
const XalanDOMString * getNamespaceForPrefixFromStack (const XalanDOMChar *prefix) const
Get the namespace from a prefix by searching the stack of namespace lists.
const XalanDOMString * getNamespaceForPrefix (const XalanDOMString &prefix, StylesheetConstructionContext &constructionContext) const
Get the namespace for a prefix, and report an error if it wasn't found.
const XalanDOMString * getNamespaceForPrefix (const XalanDOMChar *prefix, StylesheetConstructionContext &constructionContext) const
Get the namespace for a prefix, and report an error if it wasn't found.
void processExcludeResultPrefixes (StylesheetConstructionContext &theConstructionContext, const XalanDOMChar *theValue)
See if a namespace should be excluded.
void addTemplate (ElemTemplate *theTemplate, StylesheetConstructionContext &constructionContext)
Add a template to the list of names templates.
bool getYesOrNo (const XalanDOMChar *aname, const XalanDOMChar *val, StylesheetConstructionContext &constructionContext) const
Process an attribute that has the value of 'yes' or 'no'.
const XalanDOMString & getBaseIdentifier () const
Retrieve the base identifier with which this stylesheet is associated.
const XalanDOMString & getCurrentIncludeBaseIdentifier () const
Retrieve the base identifier for the most recently included stylesheet.
void processNSAliasElement (const XalanDOMChar *name, const AttributeListType &atts, StylesheetConstructionContext &constructionContext)
Process an xsl:namespace-alias element.
void processDecimalFormatElement (StylesheetConstructionContext &constructionContext, const AttributeListType &atts, const Locator *locator=0)
Process an xsl:decimal-format element.
const XalanDecimalFormatSymbols * getDecimalFormatSymbols (const XalanQName &theQName) const
Retrieve the XalanDecimalFormatSymbols instance associated with the QName.
void addImport (Stylesheet *theStylesheet)
Add an imported stylesheet.
bool isWrapperless () const
whether there is a wrapper template
ElemTemplateElement * initWrapperless (StylesheetConstructionContext &constructionContext, const Locator *locator)
URLStackType & getIncludeStack ()
Retrieve the stack of who's including who.
void processKeyElement (const PrefixResolver &nsContext, const AttributeListType &atts, const Locator *locator, StylesheetConstructionContext &constructionContext)
Process the xsl:key element.
const ElemTemplate * findNamedTemplate (const XalanQName &qname) const
Locate a template via the "name" attribute.
const ElemTemplate * findTemplate (StylesheetExecutionContext &executionContext, XalanNode *targetNode) const
Given a target element, find the template that best matches in the given XSL document, according to the rules specified in the xsl draft.
const ElemTemplate * findTemplate (StylesheetExecutionContext &executionContext, XalanNode *targetNode, XalanNode::NodeType targetNodeType, const XalanQName &mode, bool onlyUseImports) const
Given a target element, find the template that best matches in the given XSL document, according to the rules specified in the xsl draft.
const PatternTableVectorType * locateElementMatchPatternDataList (const XalanDOMString &theName) const
Given a name, locate the start of a list of possible templates that match that name.
const PatternTableVectorType * locateAttributeMatchPatternDataList (const XalanDOMString &theName) const
Given a name, locate the start of a list of possible templates that match that name.
const PatternTableVectorType * locateMatchPatternDataList (const XalanNode &theNode, XalanNode::NodeType targetNodeType) const
Given a XalanNode, locate the start of a list of possible templates that match it.
void processExtensionNamespace (StylesheetConstructionContext &theConstructionContext, const XalanDOMString &uri)
Add an extension namespace handler.
ExtensionNSHandler * lookupExtensionNSHandler (const XalanDOMString &uri) const
Return the handler for a given extension namespace.
void setTopLevelVariable (ElemVariable *var)
Set a top level variable.
void pushTopLevelVariables (StylesheetExecutionContext &executionContext, const ParamVectorType &topLevelParams) const
Set a list of top level variables in the specified execution context stylesheet.
virtual const XalanDOMString * getNamespaceForPrefix (const XalanDOMString &prefix) const
Retrieve a namespace corresponding to a prefix.
virtual const XalanDOMString & getURI () const
Retrieve the base URI for the resolver.
const XalanDOMString & getXSLTNamespaceURI () const
void setXSLTNamespaceURI (const XalanDOMString &theURI)
const ElemTemplate * getFirstTemplate () const
Public Member Functions inherited from xalanc::PrefixResolver
PrefixResolver ()
PrefixResolver (const PrefixResolver &)
virtual ~PrefixResolver ()
Static Public Member Functions
static StylesheetRoot * create (MemoryManager &theManager, const XalanDOMString &baseIdentifier, StylesheetConstructionContext &constructionContext)
Static Public Member Functions inherited from xalanc::Stylesheet
static Stylesheet * create (MemoryManager &theManager, StylesheetRoot &root, const XalanDOMString &baseIdentifier, StylesheetConstructionContext &constructionContext)
static void addObjectIfNotFound (const XalanMatchPatternData *thePattern, PatternTableVectorType &theVector)
Add object to vector of match patterns if not already there.
static void addObjectIfNotFound (const XalanMatchPatternData *thePattern, const XalanMatchPatternData *theArray[], XalanSize_t &theArraySize)
Add object to array of match patterns if not already there.
Additional Inherited Members
Protected Attributes inherited from xalanc::Stylesheet
StylesheetRoot & m_stylesheetRoot
The root of the stylesheet tree.
XalanDOMString m_baseIdent
The base URL of the XSL document.
KeyDeclarationVectorType m_keyDeclarations
Table of KeyDeclaration objects, which are set by the xsl:key element.
WhitespaceElementsVectorType m_whitespaceElements
Static Protected Attributes inherited from xalanc::Stylesheet
static const XalanQNameByReference s_emptyQName
Detailed Description
This acts as the stylesheet root of the stylesheet tree, and holds values that are shared by all stylesheets in the tree.
Definition at line 63 of file StylesheetRoot.hpp.
Member Typedef Documentation
AttributeSetMapType
typedef XalanMap<const XalanQName*, AttributeSetVectorType> xalanc::StylesheetRoot::AttributeSetMapType
Definition at line 72 of file StylesheetRoot.hpp.
AttributeSetVectorType
typedef AttributeSetVectorTypeDecl xalanc::StylesheetRoot::AttributeSetVectorType
Definition at line 69 of file StylesheetRoot.hpp.
XalanQNameVectorType
typedef XalanVector<const XalanQName*> xalanc::StylesheetRoot::XalanQNameVectorType
Definition at line 67 of file StylesheetRoot.hpp.
Constructor & Destructor Documentation
StylesheetRoot()
xalanc::StylesheetRoot::StylesheetRoot (const XalanDOMString & baseIdentifier, StylesheetConstructionContext & constructionContext)
Construct a Stylesheet from a Document.
Parameters
baseIdentifier document identifier
constructionContext context for construction of object
~StylesheetRoot()
virtual xalanc::StylesheetRoot::~StylesheetRoot () virtual
Member Function Documentation
addAttributeSet()
void xalanc::StylesheetRoot::addAttributeSet (ElemAttributeSet & theAttributeSet)
create()
static StylesheetRoot* xalanc::StylesheetRoot::create (MemoryManager & theManager, const XalanDOMString & baseIdentifier, StylesheetConstructionContext & constructionContext) static
getAttributeSet()
const ElemAttributeSet* xalanc::StylesheetRoot::getAttributeSet (StylesheetExecutionContext & theExecutionContext, const XalanQName & theQName, size_type matchingIndex, const Locator * theLocator) const
Get the nth attribute set with the specified name.
Parameters
execution context for executing this stylesheet
theQName the name of the attribute set
matchingIndex index of the attribute set with the specified name
theLocator the locator
Returns
a pointer to the attribute, 0 if no matching attribute set
getDefaultRootRule()
ElemTemplateElement* xalanc::StylesheetRoot::getDefaultRootRule () const inline
Get the template representing the default root rule.
Returns
pointer to default root template rule
Definition at line 302 of file StylesheetRoot.hpp.
getDefaultRule()
ElemTemplateElement* xalanc::StylesheetRoot::getDefaultRule () const inline
Get the template representing the default rule.
Returns
pointer to default template rule
Definition at line 291 of file StylesheetRoot.hpp.
getDefaultTextRule()
ElemTemplateElement* xalanc::StylesheetRoot::getDefaultTextRule () const inline
Get the template representing the default rule for text.
Returns
pointer to template rule for text
Definition at line 280 of file StylesheetRoot.hpp.
getElemNumberCount()
unsigned long xalanc::StylesheetRoot::getElemNumberCount () const inline
Definition at line 415 of file StylesheetRoot.hpp.
getHTMLOutputIndent()
bool xalanc::StylesheetRoot::getHTMLOutputIndent () const inline
Determine if output indenting should be enabled for HTML output.
Semantically, this implies the output method is implicit, not explicit, but we don't really check that.
Returns
true to indent
Definition at line 188 of file StylesheetRoot.hpp.
getImportStack() [1/2]
URLStackType& xalanc::StylesheetRoot::getImportStack () inline
Retrieve the stack of imported stylesheets.
Returns
stack of URIs for stylesheets
Definition at line 326 of file StylesheetRoot.hpp.
getImportStack() [2/2]
const URLStackType& xalanc::StylesheetRoot::getImportStack () const inline
Retrieve the stack of imported stylesheets.
Returns
const stack of URIs for stylesheets
Definition at line 337 of file StylesheetRoot.hpp.
getMemoryManager()
MemoryManager& xalanc::StylesheetRoot::getMemoryManager () inline
Definition at line 94 of file StylesheetRoot.hpp.
getNextElemNumberID()
unsigned long xalanc::StylesheetRoot::getNextElemNumberID () inline
Definition at line 409 of file StylesheetRoot.hpp.
getNodeSetByKey()
void xalanc::StylesheetRoot::getNodeSetByKey (XalanNode * context, const XalanQName & qname, const XalanDOMString & ref, const PrefixResolver & resolver, MutableNodeRefList & nodelist, StylesheetExecutionContext & executionContext, const Locator * locator, KeyTablesTableType & theKeysTable) const
Given a valid element key, return the corresponding node list.
Parameters
context context node
qname qname of the key, which must match the 'name' attribute on xsl:key
ref value that must match the value found by the 'match' attribute on xsl:key
resolver resolver for namespace resolution
nodelist A node list to contain the nodes found
executionContext The current execution context
theKeysTable The table of keys to search.
getOmitOutputXMLDecl()
bool xalanc::StylesheetRoot::getOmitOutputXMLDecl () const inline
Determine whether to output XML declarations.
Returns
true to output declarations
Definition at line 255 of file StylesheetRoot.hpp.
getOutputDoctypePublic()
XalanDOMString& xalanc::StylesheetRoot::getOutputDoctypePublic (XalanDOMString & theResult) const inline
Get the doctype-public-id string that was specified in the xsl:output element.
Returns
document type public id string
Definition at line 242 of file StylesheetRoot.hpp.
References xalanc::XalanDOMString::assign().
getOutputDoctypeSystem()
XalanDOMString& xalanc::StylesheetRoot::getOutputDoctypeSystem (XalanDOMString & theResult) const inline
Get the doctype-system-id string that was specified in the xsl:output element.
Returns
document type string
Definition at line 228 of file StylesheetRoot.hpp.
References xalanc::XalanDOMString::assign().
getOutputEncoding()
XalanDOMString& xalanc::StylesheetRoot::getOutputEncoding (XalanDOMString & theResult) const inline
Get the output encoding string that was specified in the xsl:output element.
Returns
encoding string
Definition at line 200 of file StylesheetRoot.hpp.
References xalanc::XalanDOMString::assign().
getOutputIndent()
bool xalanc::StylesheetRoot::getOutputIndent () const inline
Determine if output indenting was specified in the xsl:output element.
Returns
true to indent
Definition at line 173 of file StylesheetRoot.hpp.
getOutputMediaType()
XalanDOMString& xalanc::StylesheetRoot::getOutputMediaType (XalanDOMString & theResult) const inline
Get the media-type string that was specified in the xsl:output element.
Returns
media type string
Definition at line 214 of file StylesheetRoot.hpp.
References xalanc::XalanDOMString::assign().
getOutputMethod()
FormatterListener::eFormat xalanc::StylesheetRoot::getOutputMethod () const inline
Return the output method that was specified in the stylesheet.
The returned value is one of FormatterLister::eFormat values.
Returns
value of output method
Definition at line 141 of file StylesheetRoot.hpp.
getOutputStandalone()
XalanDOMString& xalanc::StylesheetRoot::getOutputStandalone (XalanDOMString & theResult) const inline
Get the standalone string that was specified in the xsl:output element.
(either "yes" or "no")
Returns
standalone string
Definition at line 267 of file StylesheetRoot.hpp.
References xalanc::XalanDOMString::assign().
getOutputVersion()
XalanDOMString& xalanc::StylesheetRoot::getOutputVersion (XalanDOMString & theResult) const inline
Get the output version string that was specified in the xsl:output element.
Returns
output version string
Definition at line 159 of file StylesheetRoot.hpp.
References xalanc::XalanDOMString::assign().
hasCDATASectionElements()
bool xalanc::StylesheetRoot::hasCDATASectionElements () const inline
Definition at line 366 of file StylesheetRoot.hpp.
hasPreserveOrStripSpaceElements()
bool xalanc::StylesheetRoot::hasPreserveOrStripSpaceElements () const inline
Definition at line 421 of file StylesheetRoot.hpp.
isCDATASectionElementName()
bool xalanc::StylesheetRoot::isCDATASectionElementName (const XalanQName & theQName) const
Determine if a QName is in the list of CDATA section element QNames.
Parameters
theQName The QName of the element to check.
Returns
true or false
isOutputMethodSet()
bool xalanc::StylesheetRoot::isOutputMethodSet () const inline
Definition at line 147 of file StylesheetRoot.hpp.
postConstruction()
virtual void xalanc::StylesheetRoot::postConstruction (StylesheetConstructionContext & constructionContext) virtual
Called after construction is completed.
Reimplemented from xalanc::Stylesheet.
process()
void xalanc::StylesheetRoot::process (XalanNode * sourceTree, XSLTResultTarget & outputTarget, StylesheetExecutionContext & executionContext) const
Transform the source tree to the output in the given result tree target.
Parameters
inputSource The input source
outputTarget The output result target
constructionContext context for construction of object
processOutputSpec()
void xalanc::StylesheetRoot::processOutputSpec (const XalanDOMChar * name, const AttributeListType & atts, StylesheetConstructionContext & constructionContext)
Process the "xsl:output" element.
Parameters
name name of element
atts attribute list for element
constructionContext context for construction of object
setIndentResult()
void xalanc::StylesheetRoot::setIndentResult (bool bIndent) inline
Change the value of the flag for indenting results.
Parameters
bIndent true to indent results
Definition at line 348 of file StylesheetRoot.hpp.
setOutputMethod()
void xalanc::StylesheetRoot::setOutputMethod (FormatterListener::eFormat meth) inline
Change the value of the output method, one of the FormatterListener::eFormat values.
Parameters
meth new method number
Definition at line 360 of file StylesheetRoot.hpp.
setupFormatterListener()
FormatterListener* xalanc::StylesheetRoot::setupFormatterListener (XSLTResultTarget & outputTarget, StylesheetExecutionContext & executionContext) const
Have the stylesheet create the appropriate FormatterListener, based on the XSLTResultTarget provided.
setupFormatterListener also calls setFormatterListener() on the execution context instance. setupFormatterListener() is done automatically by process(), but this is provided as an escape, to allow for changing the FormatterListener on-the-fly.
Parameters
outputTarget The output source tree
constructionContext context for construction of object
Returns
a pointer to the new FormatterListener instance.
shouldStripSourceNode()
bool xalanc::StylesheetRoot::shouldStripSourceNode (const XalanText & theNode) const inline
Check to see if a whitespace text node should be stripped from the source tree.
Parameters
theNode The text node to check.
Definition at line 433 of file StylesheetRoot.hpp.
References xalanc::XalanText::isWhitespace().
The documentation for this class was generated from the following file:
xalanc/XSLT/StylesheetRoot.hpp