Xalan-C++ API Reference: xalanc::XSLException Class Reference
xalanc::XSLException Class Reference abstract
#include <xalanc/PlatformSupport/XSLException.hpp>
Public Member Functions
XSLException (const XalanDOMString &theMessage, MemoryManager &theManager, const Locator *theLocator)
Constructor.
XSLException (const XalanDOMString &theMessage, MemoryManager &theManager)
Constructor.
XSLException (const XSLException &other)
virtual ~XSLException ()
virtual const XalanDOMChar * getType () const =0
Retrieve type of exception.
const XalanDOMString & getMessage () const
Retrieve message for exception.
const XalanDOMString & getURI () const
Get the URI for the associated document, if any.
XalanFileLoc getLineNumber () const
Retrieve the line number.
XalanFileLoc getColumnNumber () const
Retrieve the column number.
const MemoryManager & getMemoryManager () const
MemoryManager & getMemoryManager ()
XalanDOMString & defaultFormat (XalanDOMString &theBuffer) const
Static Public Member Functions
static XalanDOMString & defaultFormat (const XalanDOMString &theMessage, const XalanDOMString &theURI, XalanFileLoc theLineNumber, XalanFileLoc theColumnNumber, const XalanDOMChar *theType, XalanDOMString &theBuffer)
static XalanDOMString & defaultFormat (const XalanDOMChar *theMessage, const XalanDOMChar *theURI, XalanFileLoc theLineNumber, XalanFileLoc theColumnNumber, const XalanDOMChar *theType, XalanDOMString &theBuffer)
static XalanDOMString & defaultFormat (const XalanDOMChar *theMessage, const XalanDOMString::size_type theMessageLength, const XalanDOMChar *theURI, const XalanDOMString::size_type theURILength, XalanFileLoc theLineNumber, XalanFileLoc theColumnNumber, const XalanDOMChar *theType, const XalanDOMString::size_type theTypeLength, XalanDOMString &theBuffer)
Protected Attributes
MemoryManager & m_memoryManager
Detailed Description
Definition at line 42 of file XSLException.hpp.
Constructor & Destructor Documentation
XSLException() [1/3]
xalanc::XSLException::XSLException (const XalanDOMString & theMessage, MemoryManager & theManager, const Locator * theLocator)
Constructor.
Parameters
theMessage The message to display when exception thrown
theManager The MemoryManager instance to use.
theLocator The locator instance for error reporting, if any.
XSLException() [2/3]
xalanc::XSLException::XSLException (const XalanDOMString & theMessage, MemoryManager & theManager)
Constructor.
Use this constructor when the message has already been formatted.
Parameters
theMessage The message to display when exception thrown
theManager The MemoryManager instance to use.
XSLException() [3/3]
xalanc::XSLException::XSLException (const XSLException & other)
~XSLException()
virtual xalanc::XSLException::~XSLException () virtual
Member Function Documentation
defaultFormat() [1/4]
static XalanDOMString& xalanc::XSLException::defaultFormat (const XalanDOMChar * theMessage, const XalanDOMChar * theURI, XalanFileLoc theLineNumber, XalanFileLoc theColumnNumber, const XalanDOMChar * theType, XalanDOMString & theBuffer) inline static
Definition at line 163 of file XSLException.hpp.
References xalanc::length().
defaultFormat() [2/4]
static XalanDOMString& xalanc::XSLException::defaultFormat (const XalanDOMChar * theMessage, const XalanDOMString::size_type theMessageLength, const XalanDOMChar * theURI, const XalanDOMString::size_type theURILength, XalanFileLoc theLineNumber, XalanFileLoc theColumnNumber, const XalanDOMChar * theType, const XalanDOMString::size_type theTypeLength, XalanDOMString & theBuffer) static
defaultFormat() [3/4]
static XalanDOMString& xalanc::XSLException::defaultFormat (const XalanDOMString & theMessage, const XalanDOMString & theURI, XalanFileLoc theLineNumber, XalanFileLoc theColumnNumber, const XalanDOMChar * theType, XalanDOMString & theBuffer) inline static
Definition at line 142 of file XSLException.hpp.
References xalanc::XalanDOMString::c_str(), xalanc::length(), and xalanc::XalanDOMString::size().
defaultFormat() [4/4]
XalanDOMString& xalanc::XSLException::defaultFormat (XalanDOMString & theBuffer) const
getColumnNumber()
XalanFileLoc xalanc::XSLException::getColumnNumber () const inline
Retrieve the column number.
Returns
the column number
Definition at line 121 of file XSLException.hpp.
getLineNumber()
XalanFileLoc xalanc::XSLException::getLineNumber () const inline
Retrieve the line number.
Returns
the line number
Definition at line 110 of file XSLException.hpp.
getMemoryManager() [1/2]
MemoryManager& xalanc::XSLException::getMemoryManager () inline
Definition at line 133 of file XSLException.hpp.
getMemoryManager() [2/2]
const MemoryManager& xalanc::XSLException::getMemoryManager () const inline
Definition at line 127 of file XSLException.hpp.
getMessage()
const XalanDOMString& xalanc::XSLException::getMessage () const inline
Retrieve message for exception.
Returns
exception message
Definition at line 88 of file XSLException.hpp.
getType()
virtual const XalanDOMChar* xalanc::XSLException::getType () const pure virtual
Retrieve type of exception.
Returns
type of exception
Implemented in xalanc::XObject::XObjectInvalidConversionException, xalanc::XObject::XObjectException, xalanc::XalanOutputStream::TranscodingException, xalanc::XalanQName::InvalidQNameException, xalanc::XalanOutputStream::TranscoderInternalFailureException, xalanc::XalanOutputStream::UnsupportedEncodingException, xalanc::XalanTranscodingServices::UnrepresentableCharacterException, xalanc::VariablesStack::InvalidStackContextException, xalanc::XalanOutputStream::XalanOutputStreamException, xalanc::URISupport::InvalidURIException, xalanc::XalanTranscodingServices::MakeTranscoderException, xalanc::XalanFileOutputStream::XalanFileOutputStreamWriteException, xalanc::XalanFileOutputStream::XalanFileOutputStreamOpenException, xalanc::ElemMessage::ElemMessageTerminateException, xalanc::XalanStdOutputStream::XalanStdOutputStreamWriteException, xalanc::XalanFStreamOutputStream::XalanFStreamOutputStreamWriteException, xalanc::XalanXPathException, xalanc::DOMSupportException, xalanc::XPathParserException, and xalanc::XSLTProcessorException.
getURI()
const XalanDOMString& xalanc::XSLException::getURI () const inline
Get the URI for the associated document, if any.
Returns
The URI.
Definition at line 99 of file XSLException.hpp.
Member Data Documentation
m_memoryManager
MemoryManager& xalanc::XSLException::m_memoryManager protected
Definition at line 199 of file XSLException.hpp.
The documentation for this class was generated from the following file:
xalanc/PlatformSupport/XSLException.hpp