Xalan-C++ API Reference: xalanc::TraceListener Class Reference
xalanc::TraceListener Class Reference abstract
#include <xalanc/XSLT/TraceListener.hpp>
Classes
struct TraceListenerGenerateFunctor
struct TraceListenerSelectFunctor
struct TraceListenerTraceFunctor
Public Member Functions
TraceListener ()
virtual ~TraceListener ()
virtual void trace (const TracerEvent &ev)=0
Method that is called when a trace event occurs.
virtual void selected (const SelectionEvent &ev)=0
Method that is called just after the formatter listener is called.
virtual void generated (const GenerateEvent &ev)=0
Method that is called just after the formatter listener is called.
Detailed Description
Definition at line 36 of file TraceListener.hpp.
Constructor & Destructor Documentation
TraceListener()
xalanc::TraceListener::TraceListener ()
~TraceListener()
virtual xalanc::TraceListener::~TraceListener () virtual
Member Function Documentation
generated()
virtual void xalanc::TraceListener::generated (const GenerateEvent & ev) pure virtual
Method that is called just after the formatter listener is called.
Parameters
ev generate event
Implemented in xalanc::TraceListenerDefault.
Referenced by xalanc::TraceListener::TraceListenerGenerateFunctor::operator()().
selected()
virtual void xalanc::TraceListener::selected (const SelectionEvent & ev) pure virtual
Method that is called just after the formatter listener is called.
Parameters
ev generate event
Implemented in xalanc::TraceListenerDefault.
Referenced by xalanc::TraceListener::TraceListenerSelectFunctor::operator()().
trace()
virtual void xalanc::TraceListener::trace (const TracerEvent & ev) pure virtual
Method that is called when a trace event occurs.
The method is blocking. It must return before processing continues.
Parameters
ev trace event
Implemented in xalanc::TraceListenerDefault.
Referenced by xalanc::TraceListener::TraceListenerTraceFunctor::operator()().
The documentation for this class was generated from the following file:
xalanc/XSLT/TraceListener.hpp