Xalan-C++ API Reference: xalanc::XalanMemMgrAutoPtrArray< Type > Class Template Reference
xalanc::XalanMemMgrAutoPtrArray< Type > Class Template Reference
#include <xalanc/Include/XalanMemMgrAutoPtr.hpp>
Classes
class MemMgrAutoPtrArrayData
Public Types
typedef std::size_t size_type
Public Member Functions
XalanMemMgrAutoPtrArray (MemoryManager &theManager, Type *ptr, size_type size)
XalanMemMgrAutoPtrArray ()
XalanMemMgrAutoPtrArray (const XalanMemMgrAutoPtrArray< Type > &theSource)
XalanMemMgrAutoPtrArray< Type > & operator= (XalanMemMgrAutoPtrArray< Type > &theRHS)
~XalanMemMgrAutoPtrArray ()
Type & operator* () const
Type * operator-> () const
Type * get () const
size_type getSize () const
MemoryManager * getMemoryManager ()
const MemoryManager * getMemoryManager () const
XalanMemMgrAutoPtrArray< Type > & operator++ ()
MemMgrAutoPtrArrayData release ()
Type * releasePtr ()
void reset (MemoryManager *theManager=0, Type *thePointer=0, size_type size=0)
Type & operator[] (size_type index) const
Detailed Description
template<class Type>
class xalanc::XalanMemMgrAutoPtrArray< Type >
Definition at line 217 of file XalanMemMgrAutoPtr.hpp.
Member Typedef Documentation
size_type
template<class Type > typedef std::size_t xalanc::XalanMemMgrAutoPtrArray< Type >::size_type
Definition at line 221 of file XalanMemMgrAutoPtr.hpp.
Constructor & Destructor Documentation
XalanMemMgrAutoPtrArray() [1/3]
template<class Type > xalanc::XalanMemMgrAutoPtrArray< Type >::XalanMemMgrAutoPtrArray (MemoryManager & theManager, Type * ptr, size_type size) inline
Definition at line 303 of file XalanMemMgrAutoPtr.hpp.
XalanMemMgrAutoPtrArray() [2/3]
template<class Type > xalanc::XalanMemMgrAutoPtrArray< Type >::XalanMemMgrAutoPtrArray () inline
Definition at line 314 of file XalanMemMgrAutoPtr.hpp.
XalanMemMgrAutoPtrArray() [3/3]
template<class Type > xalanc::XalanMemMgrAutoPtrArray< Type >::XalanMemMgrAutoPtrArray (const XalanMemMgrAutoPtrArray< Type > & theSource) inline
Definition at line 319 of file XalanMemMgrAutoPtr.hpp.
~XalanMemMgrAutoPtrArray()
template<class Type > xalanc::XalanMemMgrAutoPtrArray< Type >::~XalanMemMgrAutoPtrArray () inline
Definition at line 337 of file XalanMemMgrAutoPtr.hpp.
Member Function Documentation
get()
template<class Type > Type* xalanc::XalanMemMgrAutoPtrArray< Type >::get () const inline
Definition at line 355 of file XalanMemMgrAutoPtr.hpp.
getMemoryManager() [1/2]
template<class Type > MemoryManager* xalanc::XalanMemMgrAutoPtrArray< Type >::getMemoryManager () inline
Definition at line 367 of file XalanMemMgrAutoPtr.hpp.
getMemoryManager() [2/2]
template<class Type > const MemoryManager* xalanc::XalanMemMgrAutoPtrArray< Type >::getMemoryManager () const inline
Definition at line 373 of file XalanMemMgrAutoPtr.hpp.
getSize()
template<class Type > size_type xalanc::XalanMemMgrAutoPtrArray< Type >::getSize () const inline
Definition at line 361 of file XalanMemMgrAutoPtr.hpp.
operator*()
template<class Type > Type& xalanc::XalanMemMgrAutoPtrArray< Type >::operator* () const inline
Definition at line 343 of file XalanMemMgrAutoPtr.hpp.
operator++()
template<class Type > XalanMemMgrAutoPtrArray<Type>& xalanc::XalanMemMgrAutoPtrArray< Type >::operator++ () inline
Definition at line 379 of file XalanMemMgrAutoPtr.hpp.
operator->()
template<class Type > Type* xalanc::XalanMemMgrAutoPtrArray< Type >::operator-> () const inline
Definition at line 349 of file XalanMemMgrAutoPtr.hpp.
operator=()
template<class Type > XalanMemMgrAutoPtrArray<Type>& xalanc::XalanMemMgrAutoPtrArray< Type >::operator= (XalanMemMgrAutoPtrArray< Type > & theRHS) inline
Definition at line 325 of file XalanMemMgrAutoPtr.hpp.
References xalanc::XalanMemMgrAutoPtrArray< Type >::release().
operator[]()
template<class Type > Type& xalanc::XalanMemMgrAutoPtrArray< Type >::operator[] (size_type index) const inline
Definition at line 429 of file XalanMemMgrAutoPtr.hpp.
release()
template<class Type > MemMgrAutoPtrArrayData xalanc::XalanMemMgrAutoPtrArray< Type >::release () inline
Definition at line 400 of file XalanMemMgrAutoPtr.hpp.
References xalanc::XalanMemMgrAutoPtrArray< Type >::MemMgrAutoPtrArrayData::reset().
Referenced by xalanc::XalanMemMgrAutoPtrArray< Type >::operator=().
releasePtr()
template<class Type > Type* xalanc::XalanMemMgrAutoPtrArray< Type >::releasePtr () inline
Definition at line 410 of file XalanMemMgrAutoPtr.hpp.
References xalanc::XalanMemMgrAutoPtrArray< Type >::MemMgrAutoPtrArrayData::m_dataArray.
reset()
template<class Type > void xalanc::XalanMemMgrAutoPtrArray< Type >::reset (MemoryManager * theManager = 0, Type * thePointer = 0, size_type size = 0) inline
Definition at line 418 of file XalanMemMgrAutoPtr.hpp.
The documentation for this class was generated from the following file:
xalanc/Include/XalanMemMgrAutoPtr.hpp