Xalan-C++ API Reference: xalanc::XalanUTF16Writer Class Reference
xalanc::XalanUTF16Writer Class Reference
#include <xalanc/XMLSupport/XalanUTF16Writer.hpp>
Public Types
typedef XalanDOMChar value_type
Public Types inherited from xalanc::XalanFormatterWriter
typedef FormatterListener::size_type size_type
Public Member Functions
XalanUTF16Writer (Writer &writer, MemoryManager &theMemoryManager)
virtual ~XalanUTF16Writer ()
void outputNewline ()
Output a line break.
size_type writeCDATAChar (const XalanDOMChar chars[], size_type start, size_type, bool &)
void writeNameChar (const XalanDOMChar *data, size_type theLength)
Writes name chars, if not representable, throws.
void writePIChars (const XalanDOMChar *data, size_type theLength)
Writes name chars, if not representable, throws.
void writeCommentChars (const XalanDOMChar *data, size_type theLength)
Writes name chars, if not representable, throws.
void safeWriteContent (const XalanDOMChar *theChars, size_type theLength)
void write (const value_type *theChars, size_type theLength)
void write (const XalanDOMString &theChars)
void write (value_type theChar)
size_type write (const value_type chars[], size_type start, size_type)
void writeSafe (const XalanDOMChar *theChars, size_type theLength)
void write (const value_type *theChars)
void flushBuffer ()
Public Member Functions inherited from xalanc::XalanFormatterWriter
XalanFormatterWriter (Writer &theWriter, MemoryManager &theMemoryManager)
MemoryManager & getMemoryManager ()
virtual ~XalanFormatterWriter ()
Writer * getWriter () const
XalanOutputStream * getStream ()
const XalanOutputStream * getStream () const
void flushWriter ()
void throwUnrepresentableCharacterException (XalanUnicodeChar ch, MemoryManager &theManager)
Additional Inherited Members
Static Public Member Functions inherited from xalanc::XalanFormatterWriter
static bool isUTF16HighSurrogate (XalanDOMChar theChar)
static bool isUTF16LowSurrogate (XalanDOMChar theChar)
static XalanUnicodeChar decodeUTF16SurrogatePair (XalanDOMChar theHighSurrogate, XalanDOMChar theLowSurrogate, MemoryManager &theManager)
static void throwInvalidCharacterException (XalanUnicodeChar ch, MemoryManager &theManager)
static void throwInvalidUTF16SurrogateException (XalanDOMChar ch, XalanDOMChar next, MemoryManager &theManager)
Protected Member Functions inherited from xalanc::XalanFormatterWriter
const XalanDOMString & formatNumericCharacterReference (XalanUnicodeChar theChar)
Format a code point as a numeric character reference.
Protected Attributes inherited from xalanc::XalanFormatterWriter
Writer & m_writer
The writer.
MemoryManager & m_memoryManager
The MemoryManager instance to use for any dynamically- allocated memory.
XalanDOMString m_stringBuffer
const XalanDOMChar * m_newlineString
The string of characters that represents the newline.
size_type m_newlineStringLength
The length of the the string of characters that represents the newline.
Detailed Description
Definition at line 28 of file XalanUTF16Writer.hpp.
Member Typedef Documentation
value_type
typedef XalanDOMChar xalanc::XalanUTF16Writer::value_type
Definition at line 32 of file XalanUTF16Writer.hpp.
Constructor & Destructor Documentation
XalanUTF16Writer()
xalanc::XalanUTF16Writer::XalanUTF16Writer (Writer & writer, MemoryManager & theMemoryManager)
~XalanUTF16Writer()
virtual xalanc::XalanUTF16Writer::~XalanUTF16Writer () inline virtual
Definition at line 40 of file XalanUTF16Writer.hpp.
Member Function Documentation
flushBuffer()
void xalanc::XalanUTF16Writer::flushBuffer () inline
Definition at line 192 of file XalanUTF16Writer.hpp.
outputNewline()
void xalanc::XalanUTF16Writer::outputNewline () inline
Output a line break.
Definition at line 48 of file XalanUTF16Writer.hpp.
References xalanc::length().
safeWriteContent()
void xalanc::XalanUTF16Writer::safeWriteContent (const XalanDOMChar * theChars, size_type theLength) inline
Definition at line 107 of file XalanUTF16Writer.hpp.
write() [1/5]
void xalanc::XalanUTF16Writer::write (const value_type * theChars) inline
Definition at line 186 of file XalanUTF16Writer.hpp.
References xalanc::length().
write() [2/5]
void xalanc::XalanUTF16Writer::write (const value_type * theChars, size_type theLength) inline
Definition at line 115 of file XalanUTF16Writer.hpp.
write() [3/5]
size_type xalanc::XalanUTF16Writer::write (const value_type chars[], size_type start, size_type) inline
Definition at line 167 of file XalanUTF16Writer.hpp.
write() [4/5]
void xalanc::XalanUTF16Writer::write (const XalanDOMString & theChars) inline
Definition at line 145 of file XalanUTF16Writer.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
write() [5/5]
void xalanc::XalanUTF16Writer::write (value_type theChar) inline
Definition at line 151 of file XalanUTF16Writer.hpp.
writeCDATAChar()
size_type xalanc::XalanUTF16Writer::writeCDATAChar (const XalanDOMChar chars[], size_type start, size_type , bool &) inline
Definition at line 60 of file XalanUTF16Writer.hpp.
writeCommentChars()
void xalanc::XalanUTF16Writer::writeCommentChars (const XalanDOMChar * data, size_type theLength) inline
Writes name chars, if not representable, throws.
Definition at line 99 of file XalanUTF16Writer.hpp.
writeNameChar()
void xalanc::XalanUTF16Writer::writeNameChar (const XalanDOMChar * data, size_type theLength) inline
Writes name chars, if not representable, throws.
Definition at line 77 of file XalanUTF16Writer.hpp.
writePIChars()
void xalanc::XalanUTF16Writer::writePIChars (const XalanDOMChar * data, size_type theLength) inline
Writes name chars, if not representable, throws.
Definition at line 88 of file XalanUTF16Writer.hpp.
writeSafe()
void xalanc::XalanUTF16Writer::writeSafe (const XalanDOMChar * theChars, size_type theLength) inline
Definition at line 178 of file XalanUTF16Writer.hpp.
The documentation for this class was generated from the following file:
xalanc/XMLSupport/XalanUTF16Writer.hpp