Xalan-C++ API Reference: xalanc::NameSpace Class Reference
xalanc::NameSpace Class Reference
A representation of a namespace.
#include <xalanc/XPath/NameSpace.hpp>
Public Member Functions
NameSpace (MemoryManager &theManager)
NameSpace (const XalanDOMString &prefix, const XalanDOMString &uri, MemoryManager &theManager)
Construct a namespace for placement on the result tree namespace stack.
NameSpace (const NameSpace &other, MemoryManager &theManager)
~NameSpace ()
const XalanDOMString & getPrefix () const
Retrieve the prefix for namespace.
void setPrefix (const XalanDOMString &prefix)
Set the prefix for namespace.
const XalanDOMString & getURI () const
Retrieve the URI for namespace.
void setURI (const XalanDOMString &uri)
Set the URI for namespace.
void setURI (const XalanDOMChar *uri)
Set the URI for namespace.
void setURI (const XalanDOMChar *uri, XalanDOMString::size_type len)
Set the URI for namespace.
bool empty () const
void clear ()
bool operator== (const NameSpace &theRHS) const
Equality operator.
Static Public Member Functions
static NameSpace * create (const XalanDOMString &prefix, const XalanDOMString &uri, MemoryManager &theManager)
Detailed Description
A representation of a namespace.
One of these will be pushed on the namespace stack for each element.
Definition at line 40 of file NameSpace.hpp.
Constructor & Destructor Documentation
NameSpace() [1/3]
xalanc::NameSpace::NameSpace (MemoryManager & theManager) inline explicit
Definition at line 45 of file NameSpace.hpp.
NameSpace() [2/3]
xalanc::NameSpace::NameSpace (const XalanDOMString & prefix, const XalanDOMString & uri, MemoryManager & theManager) inline
Construct a namespace for placement on the result tree namespace stack.
Parameters
prefix namespace prefix
uri URI of namespace
Definition at line 58 of file NameSpace.hpp.
NameSpace() [3/3]
xalanc::NameSpace::NameSpace (const NameSpace & other, MemoryManager & theManager) inline
Definition at line 88 of file NameSpace.hpp.
~NameSpace()
xalanc::NameSpace::~NameSpace () inline
Definition at line 96 of file NameSpace.hpp.
Member Function Documentation
clear()
void xalanc::NameSpace::clear () inline
Definition at line 180 of file NameSpace.hpp.
create()
static NameSpace* xalanc::NameSpace::create (const XalanDOMString & prefix, const XalanDOMString & uri, MemoryManager & theManager) inline static
Definition at line 68 of file NameSpace.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
empty()
bool xalanc::NameSpace::empty () const inline
Definition at line 174 of file NameSpace.hpp.
getPrefix()
const XalanDOMString& xalanc::NameSpace::getPrefix () const inline
Retrieve the prefix for namespace.
Returns
prefix string
Definition at line 106 of file NameSpace.hpp.
getURI()
const XalanDOMString& xalanc::NameSpace::getURI () const inline
Retrieve the URI for namespace.
Returns
URI string
Definition at line 128 of file NameSpace.hpp.
operator==()
bool xalanc::NameSpace::operator== (const NameSpace & theRHS) const inline
Equality operator.
Parameters
theRHS namespace to compare
Definition at line 193 of file NameSpace.hpp.
References xalanc::equals().
setPrefix()
void xalanc::NameSpace::setPrefix (const XalanDOMString & prefix) inline
Set the prefix for namespace.
Parameters
prefix The new prefix value
Definition at line 117 of file NameSpace.hpp.
setURI() [1/3]
void xalanc::NameSpace::setURI (const XalanDOMChar * uri) inline
Set the URI for namespace.
Parameters
uri The new uri value
Definition at line 150 of file NameSpace.hpp.
setURI() [2/3]
void xalanc::NameSpace::setURI (const XalanDOMChar * uri, XalanDOMString::size_type len) inline
Set the URI for namespace.
Parameters
uri The new uri value
len The length of the uri
Definition at line 164 of file NameSpace.hpp.
setURI() [3/3]
void xalanc::NameSpace::setURI (const XalanDOMString & uri) inline
Set the URI for namespace.
Parameters
uri The new uri value
Definition at line 139 of file NameSpace.hpp.
The documentation for this class was generated from the following file:
xalanc/XPath/NameSpace.hpp