Xalan-C++ API Reference: xalanc::MutableNodeRefList Class Reference
xalanc::MutableNodeRefList Class Reference
Local implementation of MutableNodeRefList.
#include <xalanc/XPath/MutableNodeRefList.hpp>
Classes
class addNodeInDocOrderFunctor
Public Types
typedef NodeListVectorType::iterator NodeListIteratorType
Public Types inherited from xalanc::NodeRefList
typedef XalanVector< XalanNode * > NodeListVectorType
Public Types inherited from xalanc::NodeRefListBase
typedef XalanSize_t size_type
Public Member Functions
MutableNodeRefList (MemoryManager &theManager)
Construct an empty mutable node list.
MutableNodeRefList (const MutableNodeRefList &theSource, MemoryManager &theManager)
Construct a mutable node list from another list.
MutableNodeRefList (const NodeRefListBase &theSource, MemoryManager &theManager)
Construct a mutable node list from another list.
virtual ~MutableNodeRefList ()
MutableNodeRefList & operator= (const MutableNodeRefList &theRHS)
MutableNodeRefList & operator= (const NodeRefList &theRHS)
MutableNodeRefList & operator= (const NodeRefListBase &theRHS)
MutableNodeRefList & operator= (const XalanNodeList *theRHS)
void addNode (XalanNode *n)
Add a node at to the list.
void insertNode (XalanNode *n, size_type pos)
Insert a node at a given position.
void removeNode (const XalanNode *n)
Remove a node from the list.
void removeNode (size_type pos)
Remove a node from the list.
void clear ()
Remove all nodes.
void setNode (size_type pos, XalanNode *n=0)
Set a item.
void addNodes (const XalanNodeList &nodelist)
Copy NodeList members into this nodelist, adding in document order.
void addNodes (const NodeRefListBase &nodelist)
Copy NodeList members into this nodelist, adding in document order.
void addNodesInDocOrder (const XalanNodeList &nodelist, XPathExecutionContext &executionContext)
Copy NodeList members into this nodelist, adding in document order.
void addNodesInDocOrder (const NodeRefListBase &nodelist, XPathExecutionContext &executionContext)
Copy NodeList members into this nodelist, adding in document order.
void addNodesInDocOrder (const MutableNodeRefList &nodelist, XPathExecutionContext &executionContext)
Copy NodeList members into this nodelist, adding in document order.
void addNodeInDocOrder (XalanNode *node, XPathExecutionContext &executionContext)
Add a node into list where it should occur in document order.
void clearNulls ()
Clear any null entries in the node list.
void reverse ()
Reverse the nodes in the list.
void reserve (size_type theCount)
Reserve space for the supplied number of nodes.
bool getUnknownOrder () const
See if the order of the nodes is an unknown order.
void setUnknownOrder ()
bool getDocumentOrder () const
See if the order of the nodes is document order.
void setDocumentOrder ()
Set the known order of the nodes.
bool getReverseDocumentOrder () const
See if the order of the nodes is reverse document order.
void setReverseDocumentOrder ()
Set the known order of the nodes.
void swap (MutableNodeRefList &theOther)
Public Member Functions inherited from xalanc::NodeRefList
NodeRefList (MemoryManager &theManager XALAN_DEFAULT_CONSTRUCTOR_MEMMGR)
NodeRefList (const NodeRefList &theSource, MemoryManager &theManager XALAN_DEFAULT_CONSTRUCTOR_MEMMGR)
Construct a node list from another.
MemoryManager & getMemoryManager ()
NodeRefList (const NodeRefListBase &theSource, MemoryManager &theManager XALAN_DEFAULT_CONSTRUCTOR_MEMMGR)
Construct a node list from another.
virtual ~NodeRefList ()
NodeRefList & operator= (const NodeRefListBase &theRHS)
NodeRefList & operator= (const NodeRefList &theRHS)
bool empty () const
virtual XalanNode * item (size_type index) const
Returns the indexth item in the collection.
virtual size_type getLength () const
Determine the number of nodes in the list.
virtual size_type indexOf (const XalanNode *theNode) const
Retrieve the zero based index of the node in the list.
bool checkForDuplicates (MemoryManager &theManager) const
void swap (NodeRefList &theOther)
Public Member Functions inherited from xalanc::NodeRefListBase
NodeRefListBase ()
virtual ~NodeRefListBase ()
Static Public Member Functions
static MutableNodeRefList * create (MemoryManager &theManager)
Additional Inherited Members
Static Public Attributes inherited from xalanc::NodeRefListBase
static const size_type npos
Protected Types inherited from xalanc::NodeRefList
enum { eDefaultVectorSize = 100 }
Protected Member Functions inherited from xalanc::NodeRefList
void ensureAllocation (NodeListVectorType::size_type theSize=0)
Ensure that an allocation is either the default allocation amount, or the amount specified in the parameter, whichever is larger.
Protected Member Functions inherited from xalanc::NodeRefListBase
NodeRefListBase (const NodeRefListBase &)
NodeRefListBase & operator= (const NodeRefListBase &)
Protected Attributes inherited from xalanc::NodeRefList
NodeListVectorType m_nodeList
Detailed Description
Local implementation of MutableNodeRefList.
This class is for internal use only.
Definition at line 46 of file MutableNodeRefList.hpp.
Member Typedef Documentation
NodeListIteratorType
typedef NodeListVectorType::iterator xalanc::MutableNodeRefList::NodeListIteratorType
Definition at line 291 of file MutableNodeRefList.hpp.
Constructor & Destructor Documentation
MutableNodeRefList() [1/3]
xalanc::MutableNodeRefList::MutableNodeRefList (MemoryManager & theManager) explicit
Construct an empty mutable node list.
MutableNodeRefList() [2/3]
xalanc::MutableNodeRefList::MutableNodeRefList (const MutableNodeRefList & theSource, MemoryManager & theManager)
Construct a mutable node list from another list.
Parameters
theSource source list
MutableNodeRefList() [3/3]
xalanc::MutableNodeRefList::MutableNodeRefList (const NodeRefListBase & theSource, MemoryManager & theManager) explicit
Construct a mutable node list from another list.
Parameters
theSource source list
~MutableNodeRefList()
virtual xalanc::MutableNodeRefList::~MutableNodeRefList () virtual
Member Function Documentation
addNode()
void xalanc::MutableNodeRefList::addNode (XalanNode * n)
Add a node at to the list.
Parameters
n node to add
addNodeInDocOrder()
void xalanc::MutableNodeRefList::addNodeInDocOrder (XalanNode * node, XPathExecutionContext & executionContext)
Add a node into list where it should occur in document order.
Parameters
node node object to add
executionContext the current execution context
addNodes() [1/2]
void xalanc::MutableNodeRefList::addNodes (const NodeRefListBase & nodelist)
Copy NodeList members into this nodelist, adding in document order.
If a node is null, don't add it.
Parameters
nodelist node list to add
addNodes() [2/2]
void xalanc::MutableNodeRefList::addNodes (const XalanNodeList & nodelist)
Copy NodeList members into this nodelist, adding in document order.
If a node is null, don't add it.
Parameters
nodelist node list to add
addNodesInDocOrder() [1/3]
void xalanc::MutableNodeRefList::addNodesInDocOrder (const MutableNodeRefList & nodelist, XPathExecutionContext & executionContext)
Copy NodeList members into this nodelist, adding in document order.
Parameters
nodelist node list to add
executionContext the current execution context
addNodesInDocOrder() [2/3]
void xalanc::MutableNodeRefList::addNodesInDocOrder (const NodeRefListBase & nodelist, XPathExecutionContext & executionContext)
Copy NodeList members into this nodelist, adding in document order.
Parameters
nodelist node list to add
executionContext the current execution context
addNodesInDocOrder() [3/3]
void xalanc::MutableNodeRefList::addNodesInDocOrder (const XalanNodeList & nodelist, XPathExecutionContext & executionContext)
Copy NodeList members into this nodelist, adding in document order.
Parameters
nodelist node list to add
executionContext the current execution context
Referenced by xalanc::XPath::group().
clear()
void xalanc::MutableNodeRefList::clear ()
Remove all nodes.
clearNulls()
void xalanc::MutableNodeRefList::clearNulls ()
Clear any null entries in the node list.
create()
static MutableNodeRefList* xalanc::MutableNodeRefList::create (MemoryManager & theManager) static
getDocumentOrder()
bool xalanc::MutableNodeRefList::getDocumentOrder () const inline
See if the order of the nodes is document order.
Definition at line 255 of file MutableNodeRefList.hpp.
getReverseDocumentOrder()
bool xalanc::MutableNodeRefList::getReverseDocumentOrder () const inline
See if the order of the nodes is reverse document order.
Definition at line 275 of file MutableNodeRefList.hpp.
getUnknownOrder()
bool xalanc::MutableNodeRefList::getUnknownOrder () const inline
See if the order of the nodes is an unknown order.
Definition at line 240 of file MutableNodeRefList.hpp.
insertNode()
void xalanc::MutableNodeRefList::insertNode (XalanNode * n, size_type pos)
Insert a node at a given position.
Parameters
n node to insert
pos position of insertion
operator=() [1/4]
MutableNodeRefList& xalanc::MutableNodeRefList::operator= (const MutableNodeRefList & theRHS)
operator=() [2/4]
MutableNodeRefList& xalanc::MutableNodeRefList::operator= (const NodeRefList & theRHS)
operator=() [3/4]
MutableNodeRefList& xalanc::MutableNodeRefList::operator= (const NodeRefListBase & theRHS)
operator=() [4/4]
MutableNodeRefList& xalanc::MutableNodeRefList::operator= (const XalanNodeList * theRHS)
removeNode() [1/2]
void xalanc::MutableNodeRefList::removeNode (const XalanNode * n)
Remove a node from the list.
Parameters
n node to insert
removeNode() [2/2]
void xalanc::MutableNodeRefList::removeNode (size_type pos)
Remove a node from the list.
Parameters
pos position of node in list
reserve()
void xalanc::MutableNodeRefList::reserve (size_type theCount) inline
Reserve space for the supplied number of nodes.
This is taken as an optimization, and may be ignored. You might want to call this when you know the number of nodes you're about to add to this list.
Remember to take into account the current size of the list when calling this. That means you will probably want to add the result of getLength() to the number of nodes you're planning to add.
Parameters
theCount the number of nodes to reserve space for
Definition at line 231 of file MutableNodeRefList.hpp.
reverse()
void xalanc::MutableNodeRefList::reverse ()
Reverse the nodes in the list.
setDocumentOrder()
void xalanc::MutableNodeRefList::setDocumentOrder () inline
Set the known order of the nodes.
This should only be done when the order is known. Otherwise, disaster will ensue.
Definition at line 266 of file MutableNodeRefList.hpp.
Referenced by xalanc::XPath::group().
setNode()
void xalanc::MutableNodeRefList::setNode (size_type pos, XalanNode * n = 0)
Set a item.
Parameters
pos position of node to modify
n node to insert, default is empty node
setReverseDocumentOrder()
void xalanc::MutableNodeRefList::setReverseDocumentOrder () inline
Set the known order of the nodes.
This should only be done when the order is known. Otherwise, disaster will ensue.
Definition at line 286 of file MutableNodeRefList.hpp.
setUnknownOrder()
void xalanc::MutableNodeRefList::setUnknownOrder () inline
Definition at line 246 of file MutableNodeRefList.hpp.
swap()
void xalanc::MutableNodeRefList::swap (MutableNodeRefList & theOther) inline
Definition at line 319 of file MutableNodeRefList.hpp.
References xalanc::swap().
The documentation for this class was generated from the following file:
xalanc/XPath/MutableNodeRefList.hpp