Xalan-C++ API Reference: xalanc Namespace Reference
xalanc Namespace Reference
Simple empty elem to push on the stack when nothing else got pushed, so that pop() works correctly.
Namespaces
XalanUnicode
Classes
class ArenaAllocator
class ArenaBlock
class ArenaBlockBase
class AttributeListImpl
class AttributesImpl
class AttributeVectorEntry
class AttributeVectorEntryExtended
class AVT
Class to hold an Attribute Value Template.
class AVTPart
Class to hold a part, either a string or XPath, of an Attribute Value Template.
class AVTPartSimple
Simple string part of a complex AVT.
class AVTPartXPath
Simple string part of a complex AVT.
struct c_wstr_functor
class ClearCacheResetFunctor
struct ClearFunctor
Functor to call a clear() member function on its argument.
struct CollationCacheStruct
class CollectionClearGuard
class CollectionDeleteGuard
class Constants
Primary constants used in the XSLTProcessor classes.
struct ConstructValueWithMemoryManager
struct ConstructValueWithNoMemoryManager
struct ConstructWithMemoryManager
struct ConstructWithMemoryManagerTraits
struct ConstructWithNoMemoryManager
struct ConstructWithNoMemoryManagerTraits
struct Counter
<meta name="usage" content="internal"> A class that does incremental counting for support of xsl:number.
class CountersTable
<meta name="usage" content="internal"> This is a table of counters, keyed by ElemNumber objects, each of which has a list of Counter objects.
struct DecimalFormatCacheStruct
struct DecimalToRoman
Structure to help in converting integrals to roman numerals.
class DefaultCacheCreateFunctor
class DefaultCacheCreateFunctorMemMgr
class DefaultCacheResetFunctor
struct DeleteFunctor
Functor to delete objects, used in STL iteration algorithms.
struct DirectoryEnumeratorFunctor
struct DirectoryFilterPredicate
class DOMServices
struct DOMStringEqualsFunction
Equals functor for DOMStrings.
struct DOMStringGreaterThanFunction
Greater than functor for DOMStrings.
struct DOMStringGreaterThanOrEqualFunction
Greater than or equal functor for DOMStrings.
struct DOMStringHashFunction
Hash functor for DOMStrings.
class DOMStringHelper
struct DOMStringLessThanFunction
Less than functor for DOMStrings.
struct DOMStringLessThanIgnoreCaseASCIIFunction
Less than functor for DOMStrings which ignores case for the characters a-z and A-Z.
struct DOMStringLessThanOrEqualFunction
Less than or equal functor for DOMStrings.
struct DOMStringNotEqualsFunction
Not equals functor for DOMStrings.
struct DOMStringPointerEqualToFunction
Equal to functor for DOMStrings.
struct DOMStringPointerHashFunction
Hash functor for DOMStrings.
struct DOMStringPointerLessThanFunction
Less than functor for DOMStrings.
class DOMStringPrintWriter
class DOMSupport
class DOMSupportDefault
class DOMSupportException
class DOMSupportInit
class DoubleSupport
class ElemApplyImport
class ElemApplyTemplates
class ElemAttribute
class ElemAttributeSet
class ElemCallTemplate
class ElemChoose
class ElemComment
class ElemCopy
class ElemCopyOf
class ElemDecimalFormat
class ElemElement
class ElemEmpty
class ElementPrefixResolverProxy
class ElemExtensionCall
class ElemFallback
class ElemForEach
class ElemForwardCompatible
class ElemIf
class ElemLiteralResult
class ElemMessage
class ElemNumber
class ElemOtherwise
class ElemParam
class ElemPI
class ElemSort
class ElemTemplate
class ElemTemplateElement
class ElemText
This primarily acts as a marker on the element stack to signal that whitespace should be preserved.
class ElemTextLiteral
class ElemUse
class ElemValueOf
class ElemVariable
class ElemWhen
class ElemWithParam
struct equal_null_terminated_arrays
class ExecutionContext
struct ExplicitMemoryManagedConstructionTraits
class ExtensionFunctionHandler
Class handling an extension namespace for XPath.
class ExtensionNSHandler
struct FilesOnlyFilterPredicate
struct FindFileStruct
class FormatterListener
A SAX-based formatter interface for the XSL processor.
class FormatterStringLengthCounter
This class takes SAX events (in addition to some extra events that SAX doesn't handle yet) and produces counts the characters sent to the characters event.
class FormatterToDeprecatedXercesDOM
This class takes SAX events (in addition to some extra events that SAX doesn't handle yet) and adds the result to a document or document fragment.
class FormatterToHTML
FormatterToHTML formats SAX-style events into HTML.
class FormatterToNull
This class takes SAX events (in addition to some extra events that SAX doesn't handle yet) and produces absolutely nothing.
class FormatterToSourceTree
This class takes SAX events (in addition to some extra events that SAX doesn't handle yet) and adds the result to a document or document fragment.
class FormatterToText
This class takes SAX events (in addition to some extra events that SAX doesn't handle yet) and produces simple text only.
class FormatterToXercesDOM
This class takes SAX events (in addition to some extra events that SAX doesn't handle yet) and adds the result to a document or document fragment.
class FormatterToXML
FormatterToXML formats SAX-style events into XML.
class FormatterToXMLUnicode
FormatterToXMLUnicode formats SAX-style events into XML.
class FormatterTreeWalker
class Function
class FunctionConcat
XPath implementation of "concat" function.
class FunctionContains
XPath implementation of "contains" function.
class FunctionCurrent
class FunctionDifference
XPath implementation of "difference" function.
class FunctionDistinct
XPath implementation of "difference" function.
class FunctionDocument
class FunctionElementAvailable
class FunctionEvaluate
XPath implementation of "node-set" function.
class FunctionFormatNumber
class FunctionFunctionAvailable
class FunctionGenerateID
class FunctionHasSameNodes
XPath implementation of "has-same-nodes" function for NodeSets.
class FunctionID
XPath implementation of "id" function.
class FunctionIntersection
XPath implementation of "intersection" function for NodeSets.
class FunctionKey
class FunctionLang
XPath implementation of "lang" function.
class FunctionNamespaceURI
XPath implementation of "namespace-uri" function.
class FunctionNodeSet
XPath implementation of "node-set" function.
class FunctionNormalizeSpace
XPath implementation of "normalize-space" function.
class FunctionStartsWith
XPath implementation of "starts-with" function.
class FunctionString
XPath implementation of "string" function.
class FunctionSubstring
XPath implementation of "substring" function.
class FunctionSubstringAfter
XPath implementation of "substring-after" function.
class FunctionSubstringBefore
XPath implementation of "substring-before" function.
class FunctionSystemProperty
class FunctionTranslate
XPath implementation of "translate" function.
class FunctionUnparsedEntityURI
class GenerateEvent
This is the class for events generated by the XSL processor after it generates a new node in the result tree.
class GuardCachedObject
struct hash_non_terminated_array
struct hash_null_terminated_array
class ICUBridge
class ICUBridgeCleanup
class ICUBridgeCollationCompareFunctor
class ICUBridgeCollationCompareFunctorImpl
class ICUFormatNumberFunctor
class ICUResHandler
class ICUXalanNumberFormatFactory
class ICUXalanNumberFormatProxy
class InMemHandler
class KeyDeclaration
Holds the attribute declarations for the "xsl:key" element.
class KeyTable
struct less_no_case_ascii_wide_string
This functor is designed to compare 0-terminated wide strings in a case-insensitive manner.
struct less_null_terminated_arrays
This functor is designed to compare 0-terminated arrays.
struct MapValueDeleteFunctor
Functor to delete value objects in maps, used in STL iteration algorithms.
struct MemoryManagedConstructionTraits
class MsgFileOutputStream
class MutableNodeRefList
Local implementation of MutableNodeRefList.
class NamedNodeMapAttributeList
class NameSpace
A representation of a namespace.
class NamespacesHandler
class NLSHandler
class NodeNameTreeWalker
class NodeRefList
Local implementation of NodeRefList.
class NodeRefListBase
Local implementation of NodeRefList.
class NodeSorter
This class can sort vectors of nodes according to a select pattern.
class NodeSortKey
Simple data structure class for use by the NodeSorter class.
class NullPrintWriter
class OutputContextStack
class PlatformSupportInit
struct pointer_equal
struct pointer_equals
struct pointer_equals_predicate
struct pointer_less
class PrefixResolver
This class defines an interface for classes that resolve namespace prefixes to their URIs.
class PrintWriter
class ProblemListener
This is the abstract class that the XSL processor uses when it has a problem of some kind, that requires a message, an error or a warning.
class ProblemListenerBase
This is the abstract class that is used when reporting a problem some kind, that requires a message, an error or a warning.
class ProblemListenerDefault
The implementation of the default error handling for Xalan.
class ResultNamespacesStack
class ReusableArenaAllocator
class ReusableArenaBlock
class SAX2Handler
class SelectionEvent
class StdBinInputStream
class StringTokenizer
class Stylesheet
This class represents the base stylesheet or an "import" stylesheet.
class StylesheetConstructionContext
class StylesheetConstructionContextDefault
An default implementation of an abtract class which provides support for constructing the internal representation of a stylesheet.
class StylesheetExecutionContext
class StylesheetExecutionContextDefault
class StylesheetHandler
This class processes a stylesheet via SAX events, and inits the given stylesheet.
class StylesheetRoot
This acts as the stylesheet root of the stylesheet tree, and holds values that are shared by all stylesheets in the tree.
class TopLevelArg
This class holds an instance of an argument on the stack.
class TraceListener
class TraceListenerDefault
class TracerEvent
This is the parent class of events generated for tracing the progress of the XSL processor.
class TreeWalker
class URISupport
class VariablesStack
Defines a class to keep track of a stack for macro arguments.
class Writer
class XalanAllocationGuard
class XalanAllocator
class XalanArrayAllocator
class XalanArrayAutoPtr
class XalanAttr
class XalanAutoPtr
class XalanAVTAllocator
class XalanAVTPartSimpleAllocator
class XalanAVTPartXPathAllocator
class XalanBitmap
class XalanCDATASection
class XalanCharacterData
class XalanCollationServices
class XalanComment
class XalanCompiledStylesheet
This is an abstraction of the StylesheetRoot class.
class XalanCompiledStylesheetDefault
class XalanDecimalFormatSymbols
class XalanDefaultDocumentBuilder
This is class is designed to allow a XalanTranfomer object to use a document that is build dynamically by a user.
class XalanDefaultParsedSource
This is designed to allow a XalanTranfomer object to reuse a parsed document.
class XalanDefaultParsedSourceDOMSupport
class XalanDefaultParsedSourceHelper
class XalanDeque
Xalan implementation of deque.
struct XalanDequeConstIteratorTraits
class XalanDequeIterator
struct XalanDequeIteratorTraits
struct XalanDestroyFunctor
class XalanDiagnosticMemoryManager
class XalanDocument
class XalanDocumentBuilder
This is abstract base class designed to allow a XalanTranfomer object to use a document that is build dynamically by a user.
class XalanDocumentFragment
class XalanDocumentFragmentNodeRefListBaseProxy
class XalanDocumentPrefixResolver
class XalanDocumentType
class XalanDOMException
class XalanDOMImplementation
class XalanDOMInit
class XalanDOMString
class XalanDOMStringAllocator
class XalanDOMStringCache
class XalanDOMStringHashTable
class XalanDOMStringPool
class XalanDOMStringReusableAllocator
class XalanDummyIndentWriter
class XalanElemApplyTemplatesAllocator
class XalanElemAttributeAllocator
class XalanElemAttributeSetAllocator
class XalanElemCallTemplateAllocator
class XalanElemElementAllocator
class XalanElemEmptyAllocator
class XalanElement
class XalanElemLiteralResultAllocator
class XalanElemTemplateAllocator
class XalanElemTextAllocator
class XalanElemTextLiteralAllocator
class XalanElemValueOfAllocator
class XalanElemVariableAllocator
class XalanEmptyNamedNodeMap
class XalanEncodingPropertyCache
class XalanEntity
class XalanEntityReference
class XalanEXSLTCommonFunctionsInstaller
class XalanEXSLTDateTimeFunctionsInstaller
class XalanEXSLTDynamicFunctionsInstaller
class XalanEXSLTFunctionAbs
class XalanEXSLTFunctionAcos
class XalanEXSLTFunctionAlign
class XalanEXSLTFunctionAsin
class XalanEXSLTFunctionAtan
class XalanEXSLTFunctionAtan2
class XalanEXSLTFunctionConcat
class XalanEXSLTFunctionConstant
class XalanEXSLTFunctionCos
class XalanEXSLTFunctionDateTime
class XalanEXSLTFunctionDecodeURI
class XalanEXSLTFunctionDifference
class XalanEXSLTFunctionDistinct
class XalanEXSLTFunctionEncodeURI
class XalanEXSLTFunctionEvaluate
class XalanEXSLTFunctionExp
class XalanEXSLTFunctionHasSameNode
class XalanEXSLTFunctionHighest
class XalanEXSLTFunctionIntersection
class XalanEXSLTFunctionLeading
class XalanEXSLTFunctionLog
class XalanEXSLTFunctionLowest
class XalanEXSLTFunctionMax
class XalanEXSLTFunctionMin
class XalanEXSLTFunctionNodeSet
class XalanEXSLTFunctionObjectType
class XalanEXSLTFunctionPadding
class XalanEXSLTFunctionPower
class XalanEXSLTFunctionRandom
class XalanEXSLTFunctionSin
class XalanEXSLTFunctionSqrt
class XalanEXSLTFunctionTan
class XalanEXSLTFunctionTrailing
class XalanEXSLTMathFunctionsInstaller
class XalanEXSLTSetFunctionsInstaller
class XalanEXSLTStringFunctionsInstaller
class XalanExtensionsInstaller
class XalanFileOutputStream
class XalanFileUtility
class XalanFormatterWriter
class XalanFStreamOutputStream
class XalanHasher
struct XalanHashMemberPointer
struct XalanHashMemberReference
class XalanHTMLElementsProperties
class XalanIndentWriter
class XalanInMemoryMessageLoader
class XalanList
Xalan implementation of a doubly linked list.
struct XalanListConstIteratorTraits
struct XalanListIteratorBase
struct XalanListIteratorTraits
class XalanLocator
This class defines a base class for Locator derivations in Xalan.
class XalanMap
Xalan implementation of a hashtable.
struct XalanMapConstIteratorTraits
struct XalanMapIterator
struct XalanMapIteratorTraits
struct XalanMapKeyTraits
struct XalanMapKeyTraits< const XalanDOMChar * >
struct XalanMapKeyTraits< const XalanDOMString * >
struct XalanMapKeyTraits< const XalanQName * >
struct XalanMapKeyTraits< XalanDOMString * >
struct XalanMapKeyTraits< XalanDOMString >
struct XalanMapKeyTraits< XalanQName >
struct XalanMapKeyTraits< XalanQNameByReference >
struct XalanMapKeyTraits< XalanQNameByValue >
class XalanMatchPatternData
This class contains information concerning a match pattern in a stylesheet.
class XalanMatchPatternDataAllocator
class XalanMemMgrAutoPtr
class XalanMemMgrAutoPtrArray
class XalanMemMgrs
class XalanMemoryManager
class XalanMemoryManagerDefault
class XalanMemoryManagerObjectCacheDefault
class XalanMessageLoader
class XalanMsgContainer
class XalanNamedNodeMap
class XalanNamespace
class XalanNamespacesStack
class XalanNode
class XalanNodeList
class XalanNodeListDummy
class XalanNodeListSurrogate
class XalanNotation
class XalanNullOutputStream
class XalanNumberFormat
class XalanNumberingResourceBundle
class XalanObjectCache
class XalanObjectCacheDefault
class XalanObjectStackCache
class XalanObjectStackCacheDefault
class XalanOtherEncodingWriter
class XalanOutputStream
class XalanOutputStreamPrintWriter
class XalanOutputTranscoder
class XalanParamHolder
class XalanParsedSource
This is abstract base class designed to allow a XalanTranfomer object to reuse a parsed document.
class XalanParsedSourceHelper
class XalanParsedURI
URI handling (hopefully) according to RFC2396.
class XalanProcessingInstruction
class XalanQName
Class to represent a qualified name.
class XalanQNameByReference
class XalanQNameByValue
class XalanQNameByValueAllocator
class XalanReferenceCountedObject
Class to hold reference count information.
class XalanSet
Xalan set implementation.
struct XalanSetIterator
class XalanSimplePrefixResolver
class XalanSourceTreeAttr
class XalanSourceTreeAttributeAllocator
class XalanSourceTreeAttributeNSAllocator
class XalanSourceTreeAttrNS
class XalanSourceTreeComment
class XalanSourceTreeCommentAllocator
class XalanSourceTreeContentHandler
class XalanSourceTreeDocument
class XalanSourceTreeDocumentAllocator
class XalanSourceTreeDocumentFragment
class XalanSourceTreeDocumentFragmentAllocator
class XalanSourceTreeDOMSupport
class XalanSourceTreeElement
class XalanSourceTreeElementA
class XalanSourceTreeElementAAllocator
class XalanSourceTreeElementANS
class XalanSourceTreeElementANSAllocator
class XalanSourceTreeElementNA
class XalanSourceTreeElementNAAllocator
class XalanSourceTreeElementNANS
class XalanSourceTreeElementNANSAllocator
class XalanSourceTreeHelper
class XalanSourceTreeInit
class XalanSourceTreeParserLiaison
class XalanSourceTreeProcessingInstruction
class XalanSourceTreeProcessingInstructionAllocator
class XalanSourceTreeText
class XalanSourceTreeTextAllocator
class XalanSourceTreeTextIWS
class XalanSourceTreeTextIWSAllocator
class XalanSourceTreeWrapperParsedSource
This is designed to allow a XalanTranfomer object to wrap a parsed Xerces document.
class XalanSpaceNodeTester
class XalanStdOutputStream
class XalanText
class XalanToXercesTranscoderWrapper
class XalanTranscodingServices
class XalanTransformer
This is a simple C++ interface for some common usage patterns.
class XalanTransformerOutputStream
class XalanTransformerProblemListener
class XalanUTF16Transcoder
class XalanUTF16Writer
class XalanUTF8Writer
class XalanVector
struct XalanXMLChar
class XalanXMLFileReporter
class XalanXMLSerializerBase
XalanXMLSerializerBase serves as a base class for XML serializers based on FormatterListener events.
class XalanXMLSerializerFactory
A factory class for creating XML serializers.
class XalanXPathException
class XBoolean
class XercesAttrBridge
This class is deprecated.
class XercesAttributeBridgeAllocator
This class is deprecated.
class XercesAttrWrapper
class XercesAttrWrapperAllocator
class XercesBridgeHelper
This class is deprecated.
class XercesBridgeNavigator
This class is deprecated.
class XercesCDATASectionBridge
This class is deprecated.
class XercesCDATASectionWrapper
class XercesCommentBridge
This class is deprecated.
class XercesCommentWrapper
class XercesDocumentBridge
This class is deprecated.
class XercesDocumentFragmentBridge
This class is deprecated.
class XercesDocumentTypeBridge
This class is deprecated.
class XercesDocumentTypeWrapper
class XercesDocumentWrapper
class XercesDOM_AttrHack
class XercesDOM_ElementHack
class XercesDOM_NodeHack
This class is deprecated.
class XercesDOM_TextHack
class XercesDOMException
class XercesDOMFormatterWalker
class XercesDOMImplementationBridge
This class is deprecated.
class XercesDOMImplementationWrapper
class XercesDOMParsedSource
This is designed to allow a XalanTranfomer object to reuse a parsed document.
class XercesDOMParsedSourceHelper
class XercesDOMSupport
class XercesDOMWalker
class XercesDOMWrapperException
class XercesDOMWrapperParsedSource
This is designed to allow a XalanTranfomer object to wrap a parsed Xerces document.
class XercesElementBridge
This class is deprecated.
class XercesElementBridgeAllocator
This class is deprecated.
class XercesElementWrapper
class XercesElementWrapperAllocator
class XercesEntityBridge
This class is deprecated.
class XercesEntityReferenceBridge
This class is deprecated.
class XercesEntityReferenceWrapper
class XercesEntityWrapper
class XercesLiaisonXalanDOMStringPool
class XercesNamedNodeMapAttributeList
class XercesNamedNodeMapBridge
This class is deprecated.
class XercesNamedNodeMapWrapper
class XercesNodeListBridge
This class is deprecated.
class XercesNodeListWrapper
class XercesNotationBridge
This class is deprecated.
class XercesNotationWrapper
class XercesParserLiaison
class XercesProcessingInstructionBridge
This class is deprecated.
class XercesProcessingInstructionWrapper
class XercesTextBridge
This class is deprecated.
class XercesTextBridgeAllocator
This class is deprecated.
class XercesTextWrapper
class XercesTextWrapperAllocator
class XercesToXalanNodeMap
This class is deprecated.
class XercesTreeWalker
This class is deprecated.
class XercesWrapperHelper
class XercesWrapperNavigator
class XercesWrapperNavigatorAllocator
class XercesWrapperToXalanNodeMap
class XMLParserLiaison
class XMLSupportException
class XMLSupportInit
class XNodeSet
Class to hold XPath return types.
class XNodeSetAllocator
class XNodeSetBase
Class to hold XPath return types.
class XNodeSetNodeProxy
Class to hold XPath return types.
class XNodeSetNodeProxyAllocator
class XNodeSetResultTreeFragProxy
class XNumber
class XNumberAllocator
class XNumberBase
class XObject
Class to hold XPath return types.
class XObjectFactory
This class handles the creation of XObjects and manages their lifetime.
class XObjectFactoryDefault
This class handles the creation of XObjects and manages their lifetime.
class XObjectPtr
Class to hold XObjectPtr return types.
class XObjectResultTreeFragProxy
class XObjectResultTreeFragProxyBase
class XObjectResultTreeFragProxyText
class XObjectTypeCallback
The purpose of this class is to provide a way to get the "preferred" or closest matching type for XObject-derived classes.
class XPath
class XPathAllocator
class XPathConstructionContext
class XPathConstructionContextDefault
An default implementation of an abtract class which provides support for constructing the internal representation of an XPath.
class XPathEnvSupport
class XPathEnvSupportDefault
class XPathEvaluator
class XPathExceptionFunctionNotAvailable
Exception class thrown when an unknown function is encountered.
class XPathExceptionFunctionNotSupported
Exception class thrown when an installFunction() is called with a function name that is not supported.
class XPathExecutionContext
class XPathExecutionContextDefault
A basic implementation of the class XPathExecutionContext.
class XPathExpression
class XPathFactory
class XPathFactoryBlock
class XPathFactoryDefault
class XPathFunctionTable
Class defines a table of functions that can be called in XPath expresions.
class XPathGuard
Manages the lifetime of an XPath instance.
class XPathInit
class XPathParserException
Exception class thrown when a problem parsing an XPath is encountered.
class XPathProcessor
class XPathProcessorImpl
The XPathProcessorImpl class responsibilities include tokenizing and parsing the XPath expression, and acting as a general interface to XPaths.
class XResultTreeFrag
class XResultTreeFragAllocator
class XSLException
class XSLTEngineImpl
It's the responsibility of the XSLTEngineImpl class, collaborating with the XML parser liaison, the DOM, and the XPath engine, to transform a source tree of nodes into a result tree according to instructions and templates specified by a stylesheet tree.
class XSLTInit
class XSLTInputSource
class XSLTProcessor
This is an interface for an XSLT Processor engine.
class XSLTProcessorEnvSupport
class XSLTProcessorEnvSupportDefault
class XSLTProcessorException
class XSLTResultTarget
class XString
class XStringAdapter
class XStringAdapterAllocator
class XStringAllocator
class XStringBase
class XStringCached
class XStringCachedAllocator
class XStringReference
class XStringReferenceAllocator
class XToken
class XTokenNumberAdapter
class XTokenNumberAdapterAllocator
class XTokenStringAdapter
class XTokenStringAdapterAllocator
class XUnknown
Typedefs
typedef XalanVector< const XalanNode * > AttributeVectorTypeDecl
typedef U_ICU_NAMESPACE::Collator CollatorType
typedef StylesheetExecutionContextDefault::FormatNumberFunctor FormatNumberFunctor
typedef U_ICU_NAMESPACE::DecimalFormat DecimalFormatType
typedef size_t size_type
typedef MemoryManager MemoryManagerType
typedef xercesc::AttributeList AttributeListType
typedef xercesc::Attributes AttributesType
typedef xercesc::Locator LocatorType
typedef xercesc::XMLURL XMLURLType
typedef XalanVector< XalanDOMChar > XalanDOMCharVectorType
typedef XalanVector< char > CharVectorType
typedef xercesc::ContentHandler ContentHandlerType
typedef xercesc::DTDHandler DTDHandlerType
typedef xercesc::LexicalHandler LexicalHandlerType
typedef xercesc::EntityResolver EntityResolverType
typedef xercesc::ErrorHandler ErrorHandlerType
typedef xercesc::DOM_Document DOM_Document_Type
typedef xercesc::DOMDocument DOMDocument_Type
typedef xercesc::DOM_Attr DOM_AttrType
typedef xercesc::DOM_CharacterData DOM_CharacterDataType
typedef xercesc::DOM_Comment DOM_CommentType
typedef xercesc::DOM_CDATASection DOM_CDATASectionType
typedef xercesc::DOM_DocumentType DOM_DocumentType_Type
typedef xercesc::DOM_DocumentFragment DOM_DocumentFragmentType
typedef xercesc::DOM_DOMImplementation DOM_DOMImplementationType
typedef xercesc::DOM_Element DOM_ElementType
typedef xercesc::DOM_Entity DOM_EntityType
typedef xercesc::DOM_EntityReference DOM_EntityReferenceType
typedef xercesc::DOM_Node DOM_NodeType
typedef xercesc::DOM_Text DOM_TextType
typedef xercesc::DOM_NamedNodeMap DOM_NamedNodeMapType
typedef xercesc::DOM_NodeList DOM_NodeListType
typedef xercesc::DOM_Notation DOM_NotationType
typedef xercesc::DOM_ProcessingInstruction DOM_ProcessingInstructionType
typedef xercesc::DOM_DOMException DOM_DOMExceptionType
typedef xercesc::AttrImpl AttrImplType
typedef xercesc::ElementImpl ElementImplType
typedef xercesc::NodeImpl NodeImplType
typedef xercesc::TextImpl TextImplType
typedef xercesc::DOMString DOMStringType
typedef xercesc::SAXParseException SAXParseExceptionType
typedef xercesc::DOMAttr DOMAttrType
typedef xercesc::DOMCharacterData DOMCharacterDataType
typedef xercesc::DOMComment DOMCommentType
typedef xercesc::DOMCDATASection DOMCDATASectionType
typedef xercesc::DOMDocumentType DOMDocumentType_Type
typedef xercesc::DOMDocumentFragment DOMDocumentFragmentType
typedef xercesc::DOMImplementation DOMImplementationType
typedef xercesc::DOMElement DOMElementType
typedef xercesc::DOMEntity DOMEntityType
typedef xercesc::DOMEntityReference DOMEntityReferenceType
typedef xercesc::DOMNode DOMNodeType
typedef xercesc::DOMText DOMTextType
typedef xercesc::DOMNamedNodeMap DOMNamedNodeMapType
typedef xercesc::DOMNodeList DOMNodeListType
typedef xercesc::DOMNotation DOMNotationType
typedef xercesc::DOMProcessingInstruction DOMProcessingInstructionType
typedef xercesc::DOMException DOMExceptionType
typedef XMLSize_t XMLSizeType
typedef xercesc::DocumentHandler DocumentHandlerType
typedef xercesc::InputSource InputSourceType
typedef XalanMap< XalanDOMString, const Function * > FunctionTableTypeDefinition
typedef XalanVector< Counter > CounterVectorTypeDecl
typedef XalanVector< CounterVectorTypeDecl > ElemCounterVectorVectorTypeDecl
typedef XalanMap< XalanDOMString, MutableNodeRefList > NodeListMapTypeDefinitions
Table of element keys, keyed by document node.
typedef XalanVector< double > NumberVectorTypeDecl
typedef XalanVector< XalanDOMString > StringVectorTypeDecl
typedef XalanVector< const XalanMatchPatternData * > PatternTableVectorTypeDecl
typedef VariablesStack::ParamsVectorType ParamsVectorTypeDecl
typedef XalanVector< ElemAttributeSet * > AttributeSetVectorTypeDecl
typedef xercesc::BinInputStream BinInputStreamType
Functions
template<class Type >
XalanDestroyFunctor< Type > makeXalanDestroyFunctor (const Type *)
template<class MapType >
MapValueDeleteFunctor< MapType > makeMapValueDeleteFunctor (MapType &theMap)
template<class ScalarType >
size_t XalanScalarHash (ScalarType theValue, size_t theResult)
template<class Type >
void XalanDestroy (Type &theArg)
template<class Type >
void XalanDestroy (Type *theArg)
template<class Type >
void XalanDestroy (MemoryManager &theMemoryManager, Type *theArg)
template<class Type >
void XalanDestroy (MemoryManager &theMemoryManager, Type &theArg)
template<class Type >
Type * XalanConstruct (MemoryManager &theMemoryManager, Type *&theInstance)
template<class Type , class Param1Type >
Type * XalanConstruct (MemoryManager &theMemoryManager, Type *&theInstance, const Param1Type &theParam1)
template<class Type , class Param1Type >
Type * XalanConstruct (MemoryManager &theMemoryManager, Type *&theInstance, Param1Type &theParam1)
template<class Type , class Param1Type , class Param2Type >
Type * XalanConstruct (MemoryManager &theMemoryManager, Type *&theInstance, Param1Type &theParam1, const Param2Type &theParam2)
template<class Type , class Param1Type , class Param2Type , class Param3Type , class Param4Type >
Type * XalanConstruct (MemoryManager &theMemoryManager, Type *&theInstance, const Param1Type *theParam1, const Param2Type *theParam2, const Param3Type *theParam3, Param4Type &theParam4)
template<class Type , class Param1Type , class Param2Type , class Param3Type , class Param4Type , class Param5Type , class Param6Type >
Type * XalanConstruct (MemoryManager &theMemoryManager, Type *&theInstance, const Param1Type *theParam1, const Param2Type *theParam2, const Param3Type *theParam3, const Param4Type *theParam4, const Param5Type *theParam5, Param6Type &theParam6)
template<class Type , class Param1Type , class Param2Type , class Param3Type >
Type * XalanConstruct (MemoryManager &theMemoryManager, Type *&theInstance, Param1Type &theParam1, const Param2Type &theParam2, Param3Type &theParam3)
template<class Type , class Param1Type , class Param2Type , class Param3Type , class Param4Type , class Param5Type >
Type * XalanConstruct (MemoryManager &theMemoryManager, Type *&theInstance, Param1Type &theParam1, Param2Type &theParam2, const Param3Type &theParam3, const Param4Type &theParam4, const Param5Type &theParam5)
template<class Type , class Param1Type , class Param2Type , class Param3Type , class Param4Type , class Param5Type , class Param6Type >
Type * XalanConstruct (MemoryManager &theMemoryManager, Type *&theInstance, Param1Type &theParam1, Param2Type &theParam2, const Param3Type &theParam3, const Param4Type &theParam4, const Param5Type &theParam5, const Param6Type &theParam6)
template<class Type >
Type * XalanCopyConstruct (MemoryManager &theMemoryManager, const Type &theSource)
template<class Type , class Param1Type >
Type * XalanCopyConstruct (MemoryManager &theMemoryManager, const Type &theSource, Param1Type &theParam1)
template<class Type >
void swap (XalanVector< Type > &theLHS, XalanVector< Type > &theRHS)
template<class Type >
bool operator== (const XalanVector< Type > &theLHS, const XalanVector< Type > &theRHS)
template<class Type >
bool operator!= (const XalanVector< Type > &theLHS, const XalanVector< Type > &theRHS)
template<class Type >
bool operator< (const XalanVector< Type > &theLHS, const XalanVector< Type > &theRHS)
template<class Type >
bool operator<= (const XalanVector< Type > &theLHS, const XalanVector< Type > &theRHS)
template<class Type >
bool operator> (const XalanVector< Type > &theLHS, const XalanVector< Type > &theRHS)
template<class Type >
bool operator>= (const XalanVector< Type > &theLHS, const XalanVector< Type > &theRHS)
template<class OutputIteratorType , class FilterPredicateType , class StringType , class StringConversionFunction >
void EnumerateDirectory (MemoryManager &theMemoryManager, const StringType &theFullSearchSpec, OutputIteratorType theOutputIterator, FilterPredicateType theFilterPredicate, StringConversionFunction theConversionFunction, bool fIncludeSelfAndParent=false)
template<class OutputIteratorType , class FilterPredicateType , class StringType , class StringConversionFunction >
void EnumerateDirectory (MemoryManager &theMemoryManager, const StringType &theDirectory, const StringType &theSearchSpec, OutputIteratorType theOutputIterator, FilterPredicateType theFilterPredicate, StringConversionFunction theConversionFunction, bool fIncludeSelfAndParent=false)
template<class InputIteratorType , class OutputIteratorType >
OutputIteratorType XalanCopy (InputIteratorType begin, InputIteratorType end, OutputIteratorType iterator)
template<class InputIteratorType , class OutputIteratorType , class UnaryFunction >
OutputIteratorType XalanTransform (InputIteratorType begin, InputIteratorType end, OutputIteratorType iterator, UnaryFunction function)
const XalanDOMChar * c_wstr (const XalanDOMString &theString)
Get the underlying representation of the target XalanDOMString as a null-terminated string.
const char * c_str (const CharVectorType &theString)
Get the underlying representation of the target CharVectorType as a null-terminated string.
const XalanDOMChar * c_wstr (const XalanDOMChar *theString)
Get the underlying representation of the wide string as a UNICODE null-terminated string.
const XalanDOMChar * toCharArray (const XalanDOMString &theString)
Get the underlying representation of the target XalanDOMString as an array of XalanDOMChar, not guaranteed to be null-terminated.
const XalanDOMChar * toCharArray (const XalanDOMChar *theString)
Get the underlying representation of a XalanDOMChar.
const char * toCharArray (const CharVectorType &theString)
Get the underlying representation of the target CharVectorType as a pointer to an array of characters.
void reserve (XalanDOMString &theString, XalanDOMString::size_type theCount)
Reserve some space in the string for more efficient concatenation...
XalanDOMString::size_type length (const XalanDOMString &theString)
Get the length of a XalanDOMString.
XalanDOMString::size_type length (const XalanDOMChar *theString)
Get the length of a null-terminated string of XalanDOMChar characters.
XalanDOMString::size_type length (const char *theString)
Get the length of a null-terminated string.
bool isEmpty (const XalanDOMString &str)
Determines if the target string contains any elements.
XalanDOMString::size_type indexOf (const XalanDOMChar *theString, XalanDOMChar theChar)
Simulates the java String method indexOf().
XalanDOMString::size_type indexOf (const XalanDOMChar *theString, XalanDOMString::size_type theStringLength, XalanDOMChar theChar)
Simulates the java String method indexOf().
XalanDOMString::size_type indexOf (const XalanDOMString &theString, XalanDOMChar theChar)
Simulates the java String method indexOf().
indexOf (const XalanDOMChar *theString, XalanDOMString::size_type theStringLength, const XalanDOMChar *theSubstring, XalanDOMString::size_type theSubstringLength)
Simulates the java String method indexOf().
XalanDOMString::size_type indexOf (const XalanDOMChar *theString, const XalanDOMChar *theSubstring)
Simulates the java String method indexOf().
indexOf (const XalanDOMString &theString, const XalanDOMString &theSubstring)
Simulates the java String method indexOf().
lastIndexOf (const XalanDOMChar *theString, XalanDOMChar theChar)
Simulates the java String method lastIndexOf().
XalanDOMString::size_type lastIndexOf (const XalanDOMString &theString, XalanDOMChar theChar)
Simulates the java String method lastIndexOf().
startsWith (const XalanDOMChar *theString, XalanDOMString::size_type theStringLength, const XalanDOMChar *theSubstring, XalanDOMString::size_type theSubstringLength)
Simulates the java String method startsWith().
bool startsWith (const XalanDOMChar *theString, const XalanDOMChar *theSubstring)
Simulates the java String method startsWith().
bool startsWith (const XalanDOMChar *theString, const XalanDOMString &theSubstring)
Simulates the java String method startsWith().
bool startsWith (const XalanDOMString &theString, const XalanDOMChar *theSubstring)
Simulates the java String method startsWith().
bool startsWith (const XalanDOMString &theString, const XalanDOMChar *theSubstring, XalanDOMString::size_type theSubstringLength)
Simulates the java String method startsWith().
bool startsWith (const XalanDOMString &theString, const XalanDOMString &theSubstring)
Simulates the java String method startsWith().
endsWith (const XalanDOMChar *theString, XalanDOMString::size_type theStringLength, const XalanDOMChar *theSubstring, XalanDOMString::size_type theSubstringLength)
Simulates the java String method endsWith().
bool endsWith (const XalanDOMChar *theString, const XalanDOMChar *theSubstring)
Simulates the java String method endsWith().
bool endsWith (const XalanDOMString &theString, const XalanDOMString &theSubstring)
Simulates the java String method endsWith().
PointerToDOMString (const void *theValue, XalanDOMString &theResult)
Converts a pointer into a XalanDOMString.
NumberToDOMString (double theValue, XalanDOMString &theResult)
Converts a double value into a XalanDOMString.
NumberToDOMString (XMLUInt64 theValue, XalanDOMString &theResult)
Converts an 64-bit unsigned int value into a XalanDOMString.
NumberToDOMString (XMLInt64 theValue, XalanDOMString &theResult)
Converts an 64-bit signed int value into a XalanDOMString.
XalanDOMString & NumberToDOMString (XMLUInt32 theValue, XalanDOMString &theResult)
Converts a 32-bit unsigned int value into a XalanDOMString.
XalanDOMString & NumberToDOMString (XMLInt32 theValue, XalanDOMString &theResult)
Converts a 32-bit int value into a XalanDOMString.
XalanDOMString & NumberToDOMString (XMLUInt16 theValue, XalanDOMString &theResult)
Converts a 16-bit unsigned int value into a XalanDOMString.
XalanDOMString & NumberToDOMString (XMLInt16 theValue, XalanDOMString &theResult)
Converts a 16-bit int value into a XalanDOMString.
NumberToHexDOMString (XMLUInt64 theValue, XalanDOMString &theResult)
Converts an 64-bit unsigned int value into a XalanDOMString.
NumberToHexDOMString (XMLInt64 theValue, XalanDOMString &theResult)
Converts an 64-bit signed int value into a XalanDOMString.
XalanDOMString & NumberToHexDOMString (XMLUInt32 theValue, XalanDOMString &theResult)
Converts a 32-bit unsigned int value into a XalanDOMString.
XalanDOMString & NumberToHexDOMString (XMLInt32 theValue, XalanDOMString &theResult)
Converts a 32-bit signed int value into a XalanDOMString.
XalanDOMString & NumberToHexDOMString (XMLUInt16 theValue, XalanDOMString &theResult)
Converts a 16-bit unsigned int value into a XalanDOMString.
XalanDOMString & NumberToHexDOMString (XMLInt16 theValue, XalanDOMString &theResult)
Converts a 16-bit signed int value into a XalanDOMString.
WideStringToInt (const XalanDOMChar *theString)
Converts a wide string into an integer value.
WideStringToLong (const XalanDOMChar *theString)
Converts a wide string into a long value.
WideStringToUnsignedLong (const XalanDOMChar *theString)
Converts a wide string into an unsigned long value.
WideStringToDouble (const XalanDOMChar *theString, MemoryManager &theMemoryManager)
Converts a wide string into a double value.
int DOMStringToInt (const XalanDOMString &theString)
Converts a XalanDOMString into an integer value.
long DOMStringToLong (const XalanDOMString &theString)
Converts a XalanDOMString into a long value.
unsigned long DOMStringToUnsignedLong (const XalanDOMString &theString)
Converts a XalanDOMString into a long value.
double DOMStringToDouble (const XalanDOMString &theString, MemoryManager &theMemoryManager)
Converts a XalanDOMString into a double value.
OutputString (XalanOutputStream &theStream, const CharVectorType &theString)
Outputs the target string to the specified stream.
OutputString (std::ostream &theStream, const CharVectorType &theString)
Outputs the target string to the specified stream.
OutputString (XalanOutputStream &theStream, const XalanDOMChar *theString)
Outputs the target string to the specified stream.
OutputString (std::ostream &theStream, const XalanDOMChar *theString, MemoryManager &theMemoryManager)
Outputs the target string to the specified stream.
void OutputString (XalanOutputStream &theStream, const XalanDOMString &theString)
Outputs the target string to the specified stream.
void OutputString (std::ostream &theStream, const XalanDOMString &theString, MemoryManager &theMemoryManager)
Outputs the target string to the specified stream.
XalanOutputStream & operator<< (XalanOutputStream &theStream, const CharVectorType &theString)
Outputs the string to the specified stream.
std::ostream & operator<< (std::ostream &theStream, const CharVectorType &theString)
Outputs the string to the specified stream.
XalanOutputStream & operator<< (XalanOutputStream &theStream, const XalanDOMChar *theString)
Outputs the target string to the specified stream.
std::ostream & operator<< (std::ostream &theStream, const XalanDOMChar *theString)
Outputs the target string to the specified stream.
XalanOutputStream & operator<< (XalanOutputStream &theStream, const XalanDOMString &theString)
Outputs the target string to the specified stream.
std::ostream & operator<< (std::ostream &theStream, const XalanDOMString &theString)
Outputs the target string to the specified stream.
std::ostream & operator<< (std::ostream &theStream, XalanDOMString &theString)
Outputs the target string to the specified stream.
XalanDOMChar charAt (const XalanDOMString &theString, XalanDOMString::size_type theIndex)
Retrieves a character at a specified index in the target string.
bool isXMLWhitespace (XalanDOMChar theChar)
Determines whether character represents white space.
bool isXMLDigit (XalanDOMChar theChar)
Determines whether character represents a digit.
bool isXMLLetterOrDigit (XalanDOMChar theChar)
Determines whether character represents a letter or digit.
substring (const XalanDOMChar *theString, XalanDOMString &theSubstring, XalanDOMString::size_type theStartIndex, XalanDOMString::size_type theEndIndex=XalanDOMString::npos)
Simulates the java String method substring().
substring (const XalanDOMString &theString, XalanDOMString &theSubstring, XalanDOMString::size_type theStartIndex, XalanDOMString::size_type theEndIndex=XalanDOMString::npos)
Simulates the java String method substring().
substring (const XalanDOMString &theString, XalanDOMString::size_type theStartIndex, XalanDOMString &theResult, XalanDOMString::size_type theEndIndex=XalanDOMString::npos)
Simulates the java String method substring().
XalanDOMChar toLowerASCII (XalanDOMChar theChar)
Converts ASCII alphabetic characters from upper case to lower case.
XalanDOMChar toUpperASCII (XalanDOMChar theChar)
Converts ASCII alphabetic characters from lower case to upper case.
XalanDOMChar flipCaseASCII (XalanDOMChar theChar)
Flips the case to of the supplied character.
toLowerCaseASCII (const XalanDOMChar *theString, XalanDOMString &theResult)
Converts ASCII alphabetic characters from upper case to lower case.
toLowerCaseASCII (const XalanDOMString &theString, XalanDOMString &theResult)
Converts ASCII alphabetic characters from upper case to lower case.
toLowerCaseASCII (XalanDOMString &theString)
Converts ASCII alphabetic characters from upper case to lower case.
toUpperCaseASCII (const XalanDOMChar *theString, XalanDOMString &theResult)
Converts ASCII alphabetic characters from lower case to upper case.
toUpperCaseASCII (const XalanDOMString &theString, XalanDOMString &theResult)
Converts ASCII alphabetic characters from lower case to upper case.
toUpperCaseASCII (XalanDOMString &theString)
Converts ASCII alphabetic characters from lower case to upper case.
compare (const CharVectorType &theLHS, const CharVectorType &theRHS)
Compare the contents of two strings.
compare (const XalanDOMChar *theLHS, XalanDOMString::size_type theLHSLength, const XalanDOMChar *theRHS, XalanDOMString::size_type theRHSLength)
Compare the contents of two character arrays.
int compare (const XalanDOMChar *theLHS, const XalanDOMChar *theRHS)
Compare the contents of two null-terminated strings.
int compare (const XalanDOMString &theLHS, const XalanDOMString &theRHS)
Compare the contents of two strings.
int compare (const XalanDOMChar *theLHS, const XalanDOMString &theRHS)
Compare the contents of two strings.
int compare (const XalanDOMString &theLHS, const XalanDOMChar *theRHS)
Compare the contents of two strings.
compareIgnoreCaseASCII (const XalanDOMChar *theLHS, XalanDOMString::size_type theLHSLength, const XalanDOMChar *theRHS, XalanDOMString::size_type theRHSLength)
Compare the contents of two arrays in a case insensitive manner.
int compareIgnoreCaseASCII (const XalanDOMChar *theLHS, const XalanDOMChar *theRHS)
Compare the contents of two strings, in a case insensitive manner.
int compareIgnoreCaseASCII (const XalanDOMString &theLHS, const XalanDOMString &theRHS)
Compare the contents of two strings, in a case insensitive manner.
int compareIgnoreCaseASCII (const XalanDOMString &theLHS, const XalanDOMChar *theRHS)
Compare the contents of two strings, in a case insensitive manner.
int compareIgnoreCaseASCII (const XalanDOMChar *theLHS, const XalanDOMString &theRHS)
Compare the contents of two strings, in a case insensitive manner.
collationCompare (const XalanDOMChar *theLHS, XalanDOMString::size_type theLHSLength, const XalanDOMChar *theRHS, XalanDOMString::size_type theRHSLength)
Compare the contents of two character arrays.
collationCompare (const XalanDOMChar *theLHS, const XalanDOMChar *theRHS)
Compare the contents of two strings.
int collationCompare (const XalanDOMString &theLHS, const XalanDOMString &theRHS)
Compare the contents of two strings.
int collationCompare (const XalanDOMChar *theLHS, const XalanDOMString &theRHS)
Compare the contents of two strings.
int collationCompare (const XalanDOMString &theLHS, const XalanDOMChar *theRHS)
Compare the contents of two strings.
equals (const XalanDOMChar *theLHS, const XalanDOMChar *theRHS, XalanDOMString::size_type theLength)
Compare the contents of two arrays for equality.
bool equals (const XalanDOMChar *theLHS, XalanDOMString::size_type theLHSLength, const XalanDOMChar *theRHS, XalanDOMString::size_type theRHSLength)
Compare the contents of two arrays for equality.
bool equals (const XalanDOMChar *theLHS, const XalanDOMChar *theRHS)
Compare the contents of two strings for equality.
bool equals (const XalanDOMString &theLHS, const XalanDOMString &theRHS)
Compare the contents of two strings for equality.
bool equals (const XalanDOMChar *theLHS, const XalanDOMString &theRHS)
Compare the contents of two strings for equality.
bool equals (const XalanDOMString &theLHS, const XalanDOMChar *theRHS)
Compare the contents of two strings for equality.
bool equals (const XalanDOMString &theLHS, const XalanDOMChar *theRHS, XalanDOMString::size_type theRHSLength)
Compare the contents of two strings for equality.
equalsIgnoreCaseASCII (const XalanDOMChar *theLHS, const XalanDOMChar *theRHS, XalanDOMString::size_type theLength)
Compare the contents of two arrays for equality, without regard for case.
bool equalsIgnoreCaseASCII (const XalanDOMChar *theLHS, XalanDOMString::size_type theLHSLength, const XalanDOMChar *theRHS, XalanDOMString::size_type theRHSLength)
Compare the contents of two strings for equality, without regard for case.
bool equalsIgnoreCaseASCII (const XalanDOMChar *theLHS, const XalanDOMChar *theRHS)
Compare the contents of two strings for equality, without regard for case.
bool equalsIgnoreCaseASCII (const XalanDOMString &theLHS, const XalanDOMString &theRHS)
Compare the contents of two strings for equality, without regard for case Only the characters A-Z and a-z are considered.
bool equalsIgnoreCaseASCII (const XalanDOMChar *theLHS, const XalanDOMString &theRHS)
Compare the contents of two strings for equality, without regard for case.
bool equalsIgnoreCaseASCII (const XalanDOMString &theLHS, const XalanDOMChar *theRHS)
Compare the contents of two strings for equality, without regard for case.
bool operator< (const CharVectorType &theLHS, const CharVectorType &theRHS)
Implements operator< for CharVectorType.
bool operator< (const XalanDOMString &theLHS, const XalanDOMString &theRHS)
Implements operator< for DOMStrings.
XalanDOMString & assign (XalanDOMString &theString, const XalanDOMString &theStringToAssign)
Assign one string to another.
XalanDOMString & assign (XalanDOMString &theString, const XalanDOMChar *theStringToAssign, XalanDOMString::size_type theStringToAssignLength=XalanDOMString::npos)
Assign one string to another.
XalanDOMString & append (XalanDOMString &theString, const XalanDOMString &theStringToAppend)
Concatenate two strings.
XalanDOMString & append (XalanDOMString &theString, const XalanDOMChar *theStringToAppend, XalanDOMString::size_type theStringToAppendLength=XalanDOMString::npos)
Concatenate two strings.
XalanDOMString & append (XalanDOMString &theString, const char *theStringToAppend, XalanDOMString::size_type theStringToAppendLength=XalanDOMString::npos)
Concatenate two strings.
XalanDOMString & append (XalanDOMString &theString, const XalanDOMChar theCharToAppend)
Concatenate a string and a character.
XalanDOMString & append (XalanDOMString &theString, char theCharToAppend)
Concatenate a string and a character.
XalanDOMString & insert (XalanDOMString &theString, XalanDOMString::size_type thePosition, const XalanDOMString &theStringToInsert)
Insert a string into another string.
XalanDOMString & insert (XalanDOMString &theString, XalanDOMString::size_type thePosition, const XalanDOMChar *theStringToInsert)
Insert a string into another string.
trim (const XalanDOMString &theString, XalanDOMString &theResult)
Remove leading and trailing whitespace.
void clear (XalanDOMString &theString)
Remove all elements from target string.
void erase (XalanDOMString &theString)
Remove all elements from target string.
void releaseMemory (XalanDOMString &theString, MemoryManager &theManager)
Remove all elements from target string and frees all allocated memory.
CopyWideStringToVector (const XalanDOMChar *theString, CharVectorType &theVector)
CopyStringToVector (const char *theString, CharVectorType &theVector)
MakeXalanDOMCharVector (const char *data, XalanDOMCharVectorType &result, bool fTranscode=true)
Utility function to make a null-terminated vector of XMLChs, from a null-terminated array of chars, via transcoding, if requested.
MakeXalanDOMCharVector (const XalanDOMChar *data, XalanDOMCharVectorType &result)
Utility function to make a null-terminated vector of XMLChs, from a null-terminated array of XalanDOMChar.
XalanDOMCharVectorType & MakeXalanDOMCharVector (const XalanDOMString &data, XalanDOMCharVectorType &result)
Utility function to make a null-terminated vector of XMLChs, from a XalanDOMString.
isXMLWhitespace (const XalanDOMString &string)
Determines if the string contains only whitespace.
isXMLWhitespace (const XalanDOMChar ch[], XalanDOMString::size_type start, XalanDOMString::size_type length)
Determines if a range in an array contains only whitespace.
bool isXMLWhitespace (const XalanDOMChar *theString)
Determines if a null-terminated string contains only whitespace.
bool operator== (const XalanDOMString &theLHS, const XalanDOMString &theRHS)
bool operator== (const XalanDOMString &theLHS, const XalanDOMChar *theRHS)
bool operator== (const XalanDOMChar *theLHS, const XalanDOMString &theRHS)
bool operator!= (const XalanDOMString &theLHS, const XalanDOMString &theRHS)
bool operator!= (const XalanDOMChar *theLHS, const XalanDOMString &theRHS)
bool operator!= (const XalanDOMString &theLHS, const XalanDOMChar *theRHS)
TranscodeToLocalCodePage (const XalanDOMChar *theSourceString, XalanDOMString::size_type theSourceStringLength, CharVectorType &targetVector, bool terminate=false)
Convert a XalanDOMChar string to C++ standard library vector, transcoding to the default local code page.
TranscodeToLocalCodePage (const XalanDOMChar *theSourceString, XalanDOMString::size_type theSourceStringLength, CharVectorType &targetVector, bool terminate, char theSubstitutionChar)
Convert a XalanDOMChar string to C++ standard library vector, transcoding to the default local code page.
const XalanDOMString TranscodeFromLocalCodePage (const char *theSourceString, XalanDOMString::size_type theSourceStringLength=XalanDOMString::npos)
Convert a string to a XalanDOMString, transcoding from the default local code page.
TranscodeToLocalCodePage (const XalanDOMChar *theSourceString, CharVectorType &targetVector, bool terminate=false)
Convert a XalanDOMChar string to C++ standard library vector, transcoding to the default local code page.
TranscodeToLocalCodePage (const XalanDOMChar *theSourceString, CharVectorType &targetVector, bool terminate, char theSubstitutionChar)
Convert a XalanDOMChar string to C++ standard library vector, transcoding to the default local code page.
const CharVectorType TranscodeToLocalCodePage (const XalanDOMChar *theSourceString)
Convert XalanDOMString to C++ standard library vector, transcoding to the default local code page.
bool TranscodeToLocalCodePage (const XalanDOMString &theSourceString, CharVectorType &theTargetVector, bool terminate=false)
Convert XalanDOMString to C++ standard library vector, transcoding to the default local code page.
TranscodeToLocalCodePage (const XalanDOMString &theSourceString, CharVectorType &theTargetVector, bool terminate, char theSubstitutionChar)
Convert XalanDOMString to C++ standard library vector, transcoding to the default local code page.
const CharVectorType TranscodeToLocalCodePage (const XalanDOMString &theSourceString)
Convert XalanDOMString to C++ standard library vector, transcoding to the default local code page.
const XalanDOMString & TranscodeFromLocalCodePage (const char *theSourceString, XalanDOMString &theResult, XalanDOMString::size_type theSourceStringLength=XalanDOMString::npos)
Convert a string to a XalanDOMString, transcoding from the default local code page.
TranscodeFromLocalCodePage (const char *theSourceString, XalanDOMString::size_type theSourceStringLength, XalanDOMCharVectorType &theTargetVector, bool terminate=false)
Convert a string to a C++ standard library vector, transcoding from the default local code page.
TranscodeFromLocalCodePage (const char *theSourceString, XalanDOMCharVectorType &theTargetVector, bool terminate=false)
Convert a string to a C++ standard library vector, transcoding from the default local code page.
TranscodeFromLocalCodePage (const char *theSourceString, XalanDOMString::size_type theSourceStringLength, bool theSourceStringIsNullTerminated, XalanDOMCharVectorType &theTargetVector, bool terminate=false)
Convert a string to a C++ standard library vector, transcoding from the default local code page.
TranscodeFromLocalCodePage (const CharVectorType &theSourceString, XalanDOMString &theResult)
Convert a vector of characters to a XalanDOMString, transcoding from the default local code.
char bits19to21 (XalanUnicodeChar theChar)
char bits13to18 (XalanUnicodeChar theChar)
char bits13to16 (XalanUnicodeChar theChar)
char bits7to12 (XalanUnicodeChar theChar)
char bits7to11 (XalanUnicodeChar theChar)
char bits1to6 (XalanUnicodeChar theChar)
char leadingByteOf2 (char theBits)
char leadingByteOf3 (char theBits)
char leadingByteOf4 (char theBits)
char trailingByte (char theBits)
bool operator== (const XalanQName &theLHS, const XalanQName &theRHS)
bool operator!= (const XalanQName &theLHS, const XalanQName &theRHS)
bool operator< (const XalanQName &theLHS, const XalanQName &theRHS)
bool operator== (const XObjectPtr &theLHS, const XObjectPtr &theRHS)
bool operator!= (const XObjectPtr &theLHS, const XObjectPtr &theRHS)
bool operator< (const XObjectPtr &theLHS, const XObjectPtr &theRHS)
bool operator== (const ElemAttributeSet &theLHS, const ElemAttributeSet &theRHS)
bool operator< (const ElemAttributeSet &theLHS, const ElemAttributeSet &theRHS)
Detailed Description
Simple empty elem to push on the stack when nothing else got pushed, so that pop() works correctly.
Typedef Documentation
AttributeListType
typedef xercesc::AttributeList xalanc::AttributeListType
Definition at line 41 of file AttributeListImpl.hpp.
AttributeSetVectorTypeDecl
typedef XalanVector<ElemAttributeSet*> xalanc::AttributeSetVectorTypeDecl
Definition at line 52 of file StylesheetRoot.hpp.
AttributesType
typedef xercesc::Attributes xalanc::AttributesType
Definition at line 40 of file AttributesImpl.hpp.
AttributeVectorTypeDecl
typedef XalanVector<const XalanNode*> xalanc::AttributeVectorTypeDecl
Definition at line 54 of file XalanDocumentPrefixResolver.hpp.
AttrImplType
typedef xercesc::AttrImpl xalanc::AttrImplType
Definition at line 82 of file XercesBridgeTypes.hpp.
BinInputStreamType
typedef xercesc::BinInputStream xalanc::BinInputStreamType
Definition at line 52 of file XSLTInputSource.hpp.
CharVectorType
typedef XalanVector<char> xalanc::CharVectorType
Definition at line 1126 of file XalanDOMString.hpp.
CollatorType
typedef U_ICU_NAMESPACE::Collator xalanc::CollatorType
Definition at line 44 of file ICUBridgeCollationCompareFunctorImpl.hpp.
ContentHandlerType
typedef xercesc::ContentHandler xalanc::ContentHandlerType
Definition at line 65 of file XalanSourceTreeContentHandler.hpp.
CounterVectorTypeDecl
typedef XalanVector<Counter> xalanc::CounterVectorTypeDecl
Definition at line 145 of file CountersTable.hpp.
DecimalFormatType
typedef U_ICU_NAMESPACE::DecimalFormat xalanc::DecimalFormatType
Definition at line 53 of file ICUFormatNumberFunctor.hpp.
DocumentHandlerType
typedef xercesc::DocumentHandler xalanc::DocumentHandlerType
Definition at line 47 of file XMLParserLiaison.hpp.
DOM_AttrType
typedef xercesc::DOM_Attr xalanc::DOM_AttrType
Definition at line 62 of file XercesBridgeTypes.hpp.
DOM_CDATASectionType
typedef xercesc::DOM_CDATASection xalanc::DOM_CDATASectionType
Definition at line 65 of file XercesBridgeTypes.hpp.
DOM_CharacterDataType
typedef xercesc::DOM_CharacterData xalanc::DOM_CharacterDataType
Definition at line 63 of file XercesBridgeTypes.hpp.
DOM_CommentType
typedef xercesc::DOM_Comment xalanc::DOM_CommentType
Definition at line 64 of file XercesBridgeTypes.hpp.
DOM_Document_Type
typedef xercesc::DOM_Document xalanc::DOM_Document_Type
Definition at line 48 of file XercesDOMWrapperParsedSource.hpp.
DOM_DocumentFragmentType
typedef xercesc::DOM_DocumentFragment xalanc::DOM_DocumentFragmentType
Definition at line 69 of file XercesBridgeTypes.hpp.
DOM_DocumentType_Type
typedef xercesc::DOM_DocumentType xalanc::DOM_DocumentType_Type
Definition at line 67 of file XercesBridgeTypes.hpp.
DOM_DOMExceptionType
typedef xercesc::DOM_DOMException xalanc::DOM_DOMExceptionType
Definition at line 81 of file XercesBridgeTypes.hpp.
DOM_DOMImplementationType
typedef xercesc::DOM_DOMImplementation xalanc::DOM_DOMImplementationType
Definition at line 70 of file XercesBridgeTypes.hpp.
DOM_ElementType
typedef xercesc::DOM_Element xalanc::DOM_ElementType
Definition at line 71 of file XercesBridgeTypes.hpp.
DOM_EntityReferenceType
typedef xercesc::DOM_EntityReference xalanc::DOM_EntityReferenceType
Definition at line 73 of file XercesBridgeTypes.hpp.
DOM_EntityType
typedef xercesc::DOM_Entity xalanc::DOM_EntityType
Definition at line 72 of file XercesBridgeTypes.hpp.
DOM_NamedNodeMapType
typedef xercesc::DOM_NamedNodeMap xalanc::DOM_NamedNodeMapType
Definition at line 76 of file XercesBridgeTypes.hpp.
DOM_NodeListType
typedef xercesc::DOM_NodeList xalanc::DOM_NodeListType
Definition at line 77 of file XercesBridgeTypes.hpp.
DOM_NodeType
typedef xercesc::DOM_Node xalanc::DOM_NodeType
Definition at line 74 of file XercesBridgeTypes.hpp.
DOM_NotationType
typedef xercesc::DOM_Notation xalanc::DOM_NotationType
Definition at line 78 of file XercesBridgeTypes.hpp.
DOM_ProcessingInstructionType
typedef xercesc::DOM_ProcessingInstruction xalanc::DOM_ProcessingInstructionType
Definition at line 79 of file XercesBridgeTypes.hpp.
DOM_TextType
typedef xercesc::DOM_Text xalanc::DOM_TextType
Definition at line 75 of file XercesBridgeTypes.hpp.
DOMAttrType
typedef xercesc::DOMAttr xalanc::DOMAttrType
Definition at line 56 of file XercesWrapperTypes.hpp.
DOMCDATASectionType
typedef xercesc::DOMCDATASection xalanc::DOMCDATASectionType
Definition at line 59 of file XercesWrapperTypes.hpp.
DOMCharacterDataType
typedef xercesc::DOMCharacterData xalanc::DOMCharacterDataType
Definition at line 57 of file XercesWrapperTypes.hpp.
DOMCommentType
typedef xercesc::DOMComment xalanc::DOMCommentType
Definition at line 58 of file XercesWrapperTypes.hpp.
DOMDocument_Type
typedef xercesc::DOMDocument xalanc::DOMDocument_Type
Definition at line 49 of file XercesDOMWrapperParsedSource.hpp.
DOMDocumentFragmentType
typedef xercesc::DOMDocumentFragment xalanc::DOMDocumentFragmentType
Definition at line 63 of file XercesWrapperTypes.hpp.
DOMDocumentType_Type
typedef xercesc::DOMDocumentType xalanc::DOMDocumentType_Type
Definition at line 61 of file XercesWrapperTypes.hpp.
DOMElementType
typedef xercesc::DOMElement xalanc::DOMElementType
Definition at line 65 of file XercesWrapperTypes.hpp.
DOMEntityReferenceType
typedef xercesc::DOMEntityReference xalanc::DOMEntityReferenceType
Definition at line 67 of file XercesWrapperTypes.hpp.
DOMEntityType
typedef xercesc::DOMEntity xalanc::DOMEntityType
Definition at line 66 of file XercesWrapperTypes.hpp.
DOMExceptionType
typedef xercesc::DOMException xalanc::DOMExceptionType
Definition at line 75 of file XercesWrapperTypes.hpp.
DOMImplementationType
typedef xercesc::DOMImplementation xalanc::DOMImplementationType
Definition at line 64 of file XercesWrapperTypes.hpp.
DOMNamedNodeMapType
typedef xercesc::DOMNamedNodeMap xalanc::DOMNamedNodeMapType
Definition at line 70 of file XercesWrapperTypes.hpp.
DOMNodeListType
typedef xercesc::DOMNodeList xalanc::DOMNodeListType
Definition at line 71 of file XercesWrapperTypes.hpp.
DOMNodeType
typedef xercesc::DOMNode xalanc::DOMNodeType
Definition at line 68 of file XercesWrapperTypes.hpp.
DOMNotationType
typedef xercesc::DOMNotation xalanc::DOMNotationType
Definition at line 72 of file XercesWrapperTypes.hpp.
DOMProcessingInstructionType
typedef xercesc::DOMProcessingInstruction xalanc::DOMProcessingInstructionType
Definition at line 73 of file XercesWrapperTypes.hpp.
DOMStringType
typedef xercesc::DOMString xalanc::DOMStringType
Definition at line 86 of file XercesBridgeTypes.hpp.
DOMTextType
typedef xercesc::DOMText xalanc::DOMTextType
Definition at line 69 of file XercesWrapperTypes.hpp.
DTDHandlerType
typedef xercesc::DTDHandler xalanc::DTDHandlerType
Definition at line 66 of file XalanSourceTreeContentHandler.hpp.
ElemCounterVectorVectorTypeDecl
typedef XalanVector<CounterVectorTypeDecl> xalanc::ElemCounterVectorVectorTypeDecl
Definition at line 148 of file CountersTable.hpp.
ElementImplType
typedef xercesc::ElementImpl xalanc::ElementImplType
Definition at line 83 of file XercesBridgeTypes.hpp.
EntityResolverType
typedef xercesc::EntityResolver xalanc::EntityResolverType
Definition at line 57 of file XalanCompiledStylesheetDefault.hpp.
ErrorHandlerType
typedef xercesc::ErrorHandler xalanc::ErrorHandlerType
Definition at line 58 of file XalanCompiledStylesheetDefault.hpp.
FormatNumberFunctor
typedef StylesheetExecutionContextDefault::FormatNumberFunctor xalanc::FormatNumberFunctor
Definition at line 51 of file ICUFormatNumberFunctor.hpp.
FunctionTableTypeDefinition
typedef XalanMap<XalanDOMString, const Function*> xalanc::FunctionTableTypeDefinition
Definition at line 41 of file XPathEnvSupportDefault.hpp.
InputSourceType
typedef xercesc::InputSource xalanc::InputSourceType
Definition at line 50 of file XMLParserLiaison.hpp.
LexicalHandlerType
typedef xercesc::LexicalHandler xalanc::LexicalHandlerType
Definition at line 67 of file XalanSourceTreeContentHandler.hpp.
LocatorType
typedef xercesc::Locator xalanc::LocatorType
Definition at line 47 of file ExecutionContext.hpp.
MemoryManagerType
typedef MemoryManager xalanc::MemoryManagerType
Definition at line 43 of file XalanMemoryManagement.hpp.
NodeImplType
typedef xercesc::NodeImpl xalanc::NodeImplType
Definition at line 84 of file XercesBridgeTypes.hpp.
NodeListMapTypeDefinitions
typedef XalanMap<XalanDOMString, MutableNodeRefList> xalanc::NodeListMapTypeDefinitions
Table of element keys, keyed by document node.
An instance of this class is keyed by a Document node that should be matched with the root of the current context. It contains a table of name mappings to tables that contain mappings of identifier values to nodes.
Definition at line 56 of file KeyTable.hpp.
NumberVectorTypeDecl
typedef XalanVector<double> xalanc::NumberVectorTypeDecl
Definition at line 49 of file NodeSorter.hpp.
ParamsVectorTypeDecl
typedef VariablesStack::ParamsVectorType xalanc::ParamsVectorTypeDecl
Definition at line 81 of file StylesheetExecutionContextDefault.hpp.
PatternTableVectorTypeDecl
typedef XalanVector<const XalanMatchPatternData*> xalanc::PatternTableVectorTypeDecl
Definition at line 75 of file Stylesheet.hpp.
SAXParseExceptionType
typedef xercesc::SAXParseException xalanc::SAXParseExceptionType
Definition at line 68 of file XercesParserLiaison.hpp.
size_type
typedef size_t xalanc::size_type
Definition at line 46 of file XalanMap.hpp.
StringVectorTypeDecl
typedef XalanVector<XalanDOMString> xalanc::StringVectorTypeDecl
Definition at line 55 of file NodeSorter.hpp.
TextImplType
typedef xercesc::TextImpl xalanc::TextImplType
Definition at line 85 of file XercesBridgeTypes.hpp.
XalanDOMCharVectorType
typedef XalanVector<XalanDOMChar> xalanc::XalanDOMCharVectorType
Definition at line 1124 of file XalanDOMString.hpp.
XMLSizeType
typedef XMLSize_t xalanc::XMLSizeType
Definition at line 76 of file XercesWrapperTypes.hpp.
XMLURLType
typedef xercesc::XMLURL xalanc::XMLURLType
Definition at line 48 of file URISupport.hpp.
Function Documentation
append() [1/5]
XalanDOMString& xalanc::append (XalanDOMString & theString, char theCharToAppend) inline
Concatenate a string and a character.
Deprecated:
This function is deprecated.
Parameters
theString target string
theCharToAppend the character to add to the target
Returns
string with the character appended
Definition at line 2395 of file DOMStringHelper.hpp.
append() [2/5]
XalanDOMString& xalanc::append (XalanDOMString & theString, const char * theStringToAppend, XalanDOMString::size_type theStringToAppendLength = XalanDOMString::npos) inline
Concatenate two strings.
Deprecated:
This function is deprecated.
Parameters
theString target string
theStringToAppend string to add to target
theStringToAppendLength length of the string (XalanDOMString::npos implies the string is null-terminated)
Returns
string with contents of 'theStringToAppend' added to target string
Definition at line 2348 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::append(), xalanc::XalanDOMString::getMemoryManager(), and TranscodeFromLocalCodePage().
append() [3/5]
XalanDOMString& xalanc::append (XalanDOMString & theString, const XalanDOMChar * theStringToAppend, XalanDOMString::size_type theStringToAppendLength = XalanDOMString::npos) inline
Concatenate two strings.
Deprecated:
This function is deprecated.
Parameters
theString target string
theStringToAppend string to add to target
theStringToAppendLength length of the string (XalanDOMString::npos implies the string is null-terminated)
Returns
a reference to the target string
Definition at line 2316 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::append().
append() [4/5]
XalanDOMString& xalanc::append (XalanDOMString & theString, const XalanDOMChar theCharToAppend) inline
Concatenate a string and a character.
Deprecated:
This function is deprecated.
Parameters
theString target string
theCharToAppend the character to add to the target
Returns
string with the character appended
Definition at line 2374 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::append().
append() [5/5]
XalanDOMString& xalanc::append (XalanDOMString & theString, const XalanDOMString & theStringToAppend) inline
Concatenate two strings.
Deprecated:
This function is deprecated.
Parameters
theString target string
theStringToAppend string to add to target
Returns
a reference to the target string
Definition at line 2294 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::append().
Referenced by xalanc::XalanDOMString::append(), xalanc::XalanDOMString::assign(), xalanc::XalanDOMString::operator+=(), and xalanc::XalanDOMString::push_back().
assign() [1/2]
XalanDOMString& xalanc::assign (XalanDOMString & theString, const XalanDOMChar * theStringToAssign, XalanDOMString::size_type theStringToAssignLength = XalanDOMString::npos) inline
Assign one string to another.
Deprecated:
This function is deprecated.
Parameters
theString target string
theStringToAppend string to assign
theStringToAppendLength length of the string (XalanDOMString::npos implies the string is null-terminated)
Returns
a reference to the target string
Definition at line 2265 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::assign().
assign() [2/2]
XalanDOMString& xalanc::assign (XalanDOMString & theString, const XalanDOMString & theStringToAssign) inline
Assign one string to another.
Deprecated:
This function is deprecated.
Parameters
theString target string
theStringToAppend string to assign
theStringToAppendLength length of the string (XalanDOMString::npos implies the string is null-terminated)
Returns
a reference to the target string
Definition at line 2243 of file DOMStringHelper.hpp.
Referenced by xalanc::XalanVector< XalanDOMChar >::assign(), and xalanc::XalanDOMString::operator=().
bits13to16()
char xalanc::bits13to16 (XalanUnicodeChar theChar) inline
Definition at line 47 of file XalanUTF8Writer.hpp.
bits13to18()
char xalanc::bits13to18 (XalanUnicodeChar theChar) inline
Definition at line 39 of file XalanUTF8Writer.hpp.
bits19to21()
char xalanc::bits19to21 (XalanUnicodeChar theChar) inline
Definition at line 31 of file XalanUTF8Writer.hpp.
bits1to6()
char xalanc::bits1to6 (XalanUnicodeChar theChar) inline
Definition at line 71 of file XalanUTF8Writer.hpp.
bits7to11()
char xalanc::bits7to11 (XalanUnicodeChar theChar) inline
Definition at line 63 of file XalanUTF8Writer.hpp.
bits7to12()
char xalanc::bits7to12 (XalanUnicodeChar theChar) inline
Definition at line 55 of file XalanUTF8Writer.hpp.
c_str()
const char* xalanc::c_str (const CharVectorType & theString) inline
Get the underlying representation of the target CharVectorType as a null-terminated string.
Parameters
theString target string
Returns
null-terminated string of chars
Definition at line 114 of file DOMStringHelper.hpp.
References xalanc::XalanVector< Type, ConstructionTraits >::empty(), and xalanc::XalanVector< Type, ConstructionTraits >::size().
Referenced by xalanc::XalanDOMString::data(), EnumerateDirectory(), and xalanc::XalanDOMString::hash().
c_wstr() [1/2]
const XalanDOMChar* xalanc::c_wstr (const XalanDOMChar * theString) inline
Get the underlying representation of the wide string as a UNICODE null-terminated string.
This is here simply for consistency in the code. On certain platforms, compiler- generated wide strings will not contain Unicode code points. Another macro converts those into XalanDOMStrings, which are then transcoded. In these cases, the previous defined c_sstr() function gets called.
On platforms where the compiler does generate Unicode wide strings, this function will be called instead.
Deprecated:
This function is deprecated.
Parameters
theString target string
Returns
null-terminated string of XalanDOMChar
Definition at line 150 of file DOMStringHelper.hpp.
c_wstr() [2/2]
const XalanDOMChar* xalanc::c_wstr (const XalanDOMString & theString) inline
Get the underlying representation of the target XalanDOMString as a null-terminated string.
Deprecated:
This function is deprecated.
Parameters
theString target string
Returns
null-terminated string of XalanDOMChar
Definition at line 99 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str().
charAt()
XalanDOMChar xalanc::charAt (const XalanDOMString & theString, XalanDOMString::size_type theIndex) inline
Retrieves a character at a specified index in the target string.
Deprecated:
This function is deprecated.
Parameters
theString target string
theIndex index of character
Returns
character at specified index
Definition at line 1296 of file DOMStringHelper.hpp.
clear()
void xalanc::clear (XalanDOMString & theString) inline
Remove all elements from target string.
Deprecated:
This function is deprecated.
Parameters
theString target string
Definition at line 2475 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::clear().
Referenced by xalanc::XalanVector< XalanDOMChar >::assign(), xalanc::AttributeVectorEntryExtended::clear(), and xalanc::XalanDeque< XercesBridgeNavigator >::operator=().
collationCompare() [1/5]
xalanc::collationCompare (const XalanDOMChar * theLHS, const XalanDOMChar * theRHS)
Compare the contents of two strings.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
See also
operator<()
compare()
collationCompare() [2/5]
int xalanc::collationCompare (const XalanDOMChar * theLHS, const XalanDOMString & theRHS) inline
Compare the contents of two strings.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
Definition at line 1908 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), and collationCompare().
collationCompare() [3/5]
xalanc::collationCompare (const XalanDOMChar * theLHS, XalanDOMString::size_type theLHSLength, const XalanDOMChar * theRHS, XalanDOMString::size_type theRHSLength)
Compare the contents of two character arrays.
Parameters
theLHS first array to compare
theLHSLength the length of the first array
theRHS second array to compare
theRHSLength the length of the second array
Returns
Returns 0 for equal arrays, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
collationCompare() [4/5]
int xalanc::collationCompare (const XalanDOMString & theLHS, const XalanDOMChar * theRHS) inline
Compare the contents of two strings.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
Definition at line 1926 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), xalanc::XalanDOMString::length(), and length().
Referenced by collationCompare().
collationCompare() [5/5]
int xalanc::collationCompare (const XalanDOMString & theLHS, const XalanDOMString & theRHS) inline
Compare the contents of two strings.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
See also
operator<()
compare()
Definition at line 1890 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), and collationCompare().
compare() [1/6]
xalanc::compare (const CharVectorType & theLHS, const CharVectorType & theRHS)
Compare the contents of two strings.
THIS FUNCTION DOES NOT COMPARE STRINGS LIKE strcmp() OR ANY OTHER "COLLATION" ALGORITHM.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
See also
operator<()
Referenced by xalanc::XalanDOMString::compare(), and xalanc::NodeSorter::NodeSortKeyCompare::operator()().
compare() [2/6]
int xalanc::compare (const XalanDOMChar * theLHS, const XalanDOMChar * theRHS) inline
Compare the contents of two null-terminated strings.
THIS FUNCTION DOES NOT COMPARE STRINGS LIKE strcmp() OR ANY OTHER "COLLATION" ALGORITHM.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
Definition at line 1627 of file DOMStringHelper.hpp.
References compare(), and length().
compare() [3/6]
int xalanc::compare (const XalanDOMChar * theLHS, const XalanDOMString & theRHS) inline
Compare the contents of two strings.
THIS FUNCTION DOES NOT COMPARE STRINGS LIKE strcmp() OR ANY OTHER "COLLATION" ALGORITHM.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
Definition at line 1675 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), compare(), xalanc::XalanDOMString::length(), and length().
compare() [4/6]
xalanc::compare (const XalanDOMChar * theLHS, XalanDOMString::size_type theLHSLength, const XalanDOMChar * theRHS, XalanDOMString::size_type theRHSLength)
Compare the contents of two character arrays.
THIS FUNCTION DOES NOT COMPARE STRINGS LIKE strcmp() OR ANY OTHER "COLLATION" ALGORITHM.
Parameters
theLHS first array to compare
theLHSLength the length of the first array
theRHS second array to compare
theRHSLength the length of the second array
Returns
Returns 0 for equal arrays, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
compare() [5/6]
int xalanc::compare (const XalanDOMString & theLHS, const XalanDOMChar * theRHS) inline
Compare the contents of two strings.
THIS FUNCTION DOES NOT COMPARE STRINGS LIKE strcmp() OR ANY OTHER "COLLATION" ALGORITHM.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
Definition at line 1700 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), xalanc::XalanDOMString::length(), and length().
Referenced by compare(), xalanc::DOMStringLessThanOrEqualFunction::operator()(), xalanc::DOMStringGreaterThanFunction::operator()(), xalanc::DOMStringGreaterThanOrEqualFunction::operator()(), and operator<().
compare() [6/6]
int xalanc::compare (const XalanDOMString & theLHS, const XalanDOMString & theRHS) inline
Compare the contents of two strings.
THIS FUNCTION DOES NOT COMPARE STRINGS LIKE strcmp() OR ANY OTHER "COLLATION" ALGORITHM.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
See also
operator<()
collationCompare()
Definition at line 1650 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), compare(), and xalanc::XalanDOMString::length().
compareIgnoreCaseASCII() [1/5]
int xalanc::compareIgnoreCaseASCII (const XalanDOMChar * theLHS, const XalanDOMChar * theRHS) inline
Compare the contents of two strings, in a case insensitive manner.
Only the characters a-z and A-Z are considered as characters with "case".
THIS FUNCTION DOES NOT COMPARE STRINGS LIKE strcmp() OR ANY OTHER "COLLATION" ALGORITHM.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
Definition at line 1751 of file DOMStringHelper.hpp.
References compareIgnoreCaseASCII(), and length().
compareIgnoreCaseASCII() [2/5]
int xalanc::compareIgnoreCaseASCII (const XalanDOMChar * theLHS, const XalanDOMString & theRHS) inline
Compare the contents of two strings, in a case insensitive manner.
Only the characters a-z and A-Z are considered for the comparison.
THIS FUNCTION DOES NOT COMPARE STRINGS LIKE strcmp() OR ANY OTHER "COLLATION" ALGORITHM.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
Definition at line 1830 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), xalanc::XalanDOMString::length(), and length().
Referenced by compareIgnoreCaseASCII(), xalanc::DOMStringLessThanIgnoreCaseASCIIFunction::operator()(), and xalanc::less_no_case_ascii_wide_string::operator()().
compareIgnoreCaseASCII() [3/5]
xalanc::compareIgnoreCaseASCII (const XalanDOMChar * theLHS, XalanDOMString::size_type theLHSLength, const XalanDOMChar * theRHS, XalanDOMString::size_type theRHSLength)
Compare the contents of two arrays in a case insensitive manner.
Only the characters a-z and A-Z are considered as characters with "case".
THIS FUNCTION DOES NOT COMPARE STRINGS LIKE strcmp() OR ANY OTHER "COLLATION" ALGORITHM.
Parameters
theLHS first array to compare
theLHSLength the length of the first array
theRHS second array to compare
theRHSLength the length of the second array
Returns
Returns 0 for equal arrays, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
compareIgnoreCaseASCII() [4/5]
int xalanc::compareIgnoreCaseASCII (const XalanDOMString & theLHS, const XalanDOMChar * theRHS) inline
Compare the contents of two strings, in a case insensitive manner.
Only the characters a-z and A-Z are considered as characters with "case".
THIS FUNCTION DOES NOT COMPARE STRINGS LIKE strcmp() OR ANY OTHER "COLLATION" ALGORITHM.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
Definition at line 1803 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), compareIgnoreCaseASCII(), xalanc::XalanDOMString::length(), and length().
compareIgnoreCaseASCII() [5/5]
int xalanc::compareIgnoreCaseASCII (const XalanDOMString & theLHS, const XalanDOMString & theRHS) inline
Compare the contents of two strings, in a case insensitive manner.
Only the characters a-z and A-Z are considered as characters with "case".
THIS FUNCTION DOES NOT COMPARE STRINGS LIKE strcmp() OR ANY OTHER "COLLATION" ALGORITHM.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns 0 for equal strings, less than 0 if theLHS is less than theRHS, or greater than 0 if theRHS is greater than theLHS.
See also
operator<
collationCompare
Definition at line 1776 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), compareIgnoreCaseASCII(), and xalanc::XalanDOMString::length().
CopyStringToVector()
xalanc::CopyStringToVector (const char * theString, CharVectorType & theVector)
CopyWideStringToVector()
xalanc::CopyWideStringToVector (const XalanDOMChar * theString, CharVectorType & theVector)
DOMStringToDouble()
double xalanc::DOMStringToDouble (const XalanDOMString & theString, MemoryManager & theMemoryManager) inline
Converts a XalanDOMString into a double value.
Parameters
theString target string
theMemoryManager The MemoryManager instance to use.
Returns
double value of target string
Definition at line 1025 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), and WideStringToDouble().
DOMStringToInt()
int xalanc::DOMStringToInt (const XalanDOMString & theString) inline
Converts a XalanDOMString into an integer value.
Parameters
theString target string
Returns
integer value of target string
Definition at line 982 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), and WideStringToInt().
DOMStringToLong()
long xalanc::DOMStringToLong (const XalanDOMString & theString) inline
Converts a XalanDOMString into a long value.
Parameters
theString target string
Returns
long value of target string
Definition at line 996 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), and WideStringToLong().
DOMStringToUnsignedLong()
unsigned long xalanc::DOMStringToUnsignedLong (const XalanDOMString & theString) inline
Converts a XalanDOMString into a long value.
Parameters
theString target string
Returns
unsigned long value of target string
Definition at line 1010 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), and WideStringToUnsignedLong().
endsWith() [1/3]
bool xalanc::endsWith (const XalanDOMChar * theString, const XalanDOMChar * theSubstring) inline
Simulates the java String method endsWith().
Parameters
theString target string to search
theSubstring substring searched for
Returns
true if the target string ends with the substring
Definition at line 622 of file DOMStringHelper.hpp.
References endsWith(), and length().
endsWith() [2/3]
xalanc::endsWith (const XalanDOMChar * theString, XalanDOMString::size_type theStringLength, const XalanDOMChar * theSubstring, XalanDOMString::size_type theSubstringLength)
Simulates the java String method endsWith().
Parameters
theString target string to search
theSubstring substring searched for
Returns
true if the target string ends with the substring
endsWith() [3/3]
bool xalanc::endsWith (const XalanDOMString & theString, const XalanDOMString & theSubstring) inline
Simulates the java String method endsWith().
Parameters
theString target string to search
theSubstring substring searched for
Returns
true if the target string ends with the substring
Definition at line 645 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
Referenced by endsWith().
EnumerateDirectory() [1/2]
template<class OutputIteratorType , class FilterPredicateType , class StringType , class StringConversionFunction > void xalanc::EnumerateDirectory (MemoryManager & theMemoryManager, const StringType & theDirectory, const StringType & theSearchSpec, OutputIteratorType theOutputIterator, FilterPredicateType theFilterPredicate, StringConversionFunction theConversionFunction, bool fIncludeSelfAndParent = false)
Definition at line 406 of file DirectoryEnumerator.hpp.
Referenced by xalanc::DirectoryEnumeratorFunctor< CollectionType, StringType, FilterPredicateType, StringConversionFunction >::operator()().
EnumerateDirectory() [2/2]
template<class OutputIteratorType , class FilterPredicateType , class StringType , class StringConversionFunction > void xalanc::EnumerateDirectory (MemoryManager & theMemoryManager, const StringType & theFullSearchSpec, OutputIteratorType theOutputIterator, FilterPredicateType theFilterPredicate, StringConversionFunction theConversionFunction, bool fIncludeSelfAndParent = false)
Definition at line 231 of file DirectoryEnumerator.hpp.
References xalanc::XalanVector< Type, ConstructionTraits >::back(), c_str(), xalanc::XalanDOMString::compare(), xalanc::XalanVector< Type, ConstructionTraits >::pop_back(), xalanc::XalanVector< Type, ConstructionTraits >::push_back(), xalanc::XalanDOMString::size(), xalanc::XalanVector< Type, ConstructionTraits >::size(), xalanc::XalanDOMString::substr(), and TranscodeToLocalCodePage().
equals() [1/7]
bool xalanc::equals (const XalanDOMChar * theLHS, const XalanDOMChar * theRHS) inline
Compare the contents of two strings for equality.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
true if the contents of both strings are identical
Definition at line 1984 of file DOMStringHelper.hpp.
References equals(), and length().
equals() [2/7]
xalanc::equals (const XalanDOMChar * theLHS, const XalanDOMChar * theRHS, XalanDOMString::size_type theLength)
Compare the contents of two arrays for equality.
Parameters
theLHS first array to compare
theRHS second array to compare
theLength the length of the arrays
Returns
true if the contents of both arrays are identical
Referenced by xalanc::XalanDOMString::equals(), xalanc::DOMServices::getNameOfNode(), xalanc::DOMServices::isNamespaceDeclaration(), xalanc::CollationCacheStruct::CollatorFindFunctor::operator()(), xalanc::DOMStringEqualsFunction::operator()(), xalanc::DOMStringNotEqualsFunction::operator()(), xalanc::DOMStringPointerEqualToFunction::operator()(), operator<(), xalanc::XalanNumberingResourceBundle::operator==(), xalanc::XalanNamespace::operator==(), xalanc::NameSpace::operator==(), and operator==().
equals() [3/7]
bool xalanc::equals (const XalanDOMChar * theLHS, const XalanDOMString & theRHS) inline
Compare the contents of two strings for equality.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
true if the contents of both strings are identical
Definition at line 2020 of file DOMStringHelper.hpp.
equals() [4/7]
bool xalanc::equals (const XalanDOMChar * theLHS, XalanDOMString::size_type theLHSLength, const XalanDOMChar * theRHS, XalanDOMString::size_type theRHSLength) inline
Compare the contents of two arrays for equality.
Parameters
theLHS first array to compare
theLHSLength the length of the theLHS
theRHS second array to compare
theRHSLength the length of the theRHS
Returns
true if the contents of both arrays are identical
Definition at line 1965 of file DOMStringHelper.hpp.
References equals().
equals() [5/7]
bool xalanc::equals (const XalanDOMString & theLHS, const XalanDOMChar * theRHS) inline
Compare the contents of two strings for equality.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
true if the contents of both strings are identical
Definition at line 2040 of file DOMStringHelper.hpp.
References equals().
equals() [6/7]
bool xalanc::equals (const XalanDOMString & theLHS, const XalanDOMChar * theRHS, XalanDOMString::size_type theRHSLength) inline
Compare the contents of two strings for equality.
Parameters
theLHS first string to compare
theRHS second string to compare
theRHSLength the length of the theRHS
Returns
true if the contents of both strings are identical
Definition at line 2057 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
Referenced by equals().
equals() [7/7]
bool xalanc::equals (const XalanDOMString & theLHS, const XalanDOMString & theRHS) inline
Compare the contents of two strings for equality.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
true if the contents of both strings are identical
Definition at line 2003 of file DOMStringHelper.hpp.
equalsIgnoreCaseASCII() [1/6]
bool xalanc::equalsIgnoreCaseASCII (const XalanDOMChar * theLHS, const XalanDOMChar * theRHS) inline
Compare the contents of two strings for equality, without regard for case.
Only the characters a-z and A-Z are considered characters with "case".
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
true if both strings are identical
Definition at line 2116 of file DOMStringHelper.hpp.
References equalsIgnoreCaseASCII(), and length().
equalsIgnoreCaseASCII() [2/6]
xalanc::equalsIgnoreCaseASCII (const XalanDOMChar * theLHS, const XalanDOMChar * theRHS, XalanDOMString::size_type theLength)
Compare the contents of two arrays for equality, without regard for case.
Only the characters a-z and A-Z are considered characters with "case".
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
true if the case-insensitive contents of both strings are identical
equalsIgnoreCaseASCII() [3/6]
bool xalanc::equalsIgnoreCaseASCII (const XalanDOMChar * theLHS, const XalanDOMString & theRHS) inline
Compare the contents of two strings for equality, without regard for case.
Only the characters a-z and A-Z are considered characters with "case".
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
true if the case-insensitive contents of both strings are identical
Definition at line 2161 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), equalsIgnoreCaseASCII(), xalanc::XalanDOMString::length(), and length().
equalsIgnoreCaseASCII() [4/6]
bool xalanc::equalsIgnoreCaseASCII (const XalanDOMChar * theLHS, XalanDOMString::size_type theLHSLength, const XalanDOMChar * theRHS, XalanDOMString::size_type theRHSLength) inline
Compare the contents of two strings for equality, without regard for case.
Only the characters a-z and A-Z are considered characters with "case".
Parameters
theLHS first string to compare
theLHSLength the length of the theLHS
theRHS second string to compare
theRHSLength the length of the theRHS
Returns
true if both strings are identical
Definition at line 2095 of file DOMStringHelper.hpp.
References equalsIgnoreCaseASCII().
equalsIgnoreCaseASCII() [5/6]
bool xalanc::equalsIgnoreCaseASCII (const XalanDOMString & theLHS, const XalanDOMChar * theRHS) inline
Compare the contents of two strings for equality, without regard for case.
Only the characters A-Z and a-z are considered.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
true if the case-insensitive contents of both strings are identical
Definition at line 2185 of file DOMStringHelper.hpp.
Referenced by equalsIgnoreCaseASCII().
equalsIgnoreCaseASCII() [6/6]
bool xalanc::equalsIgnoreCaseASCII (const XalanDOMString & theLHS, const XalanDOMString & theRHS) inline
Compare the contents of two strings for equality, without regard for case Only the characters A-Z and a-z are considered.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
true if the case-insensitive contents of both strings are identical
Definition at line 2137 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), equalsIgnoreCaseASCII(), and xalanc::XalanDOMString::length().
erase()
void xalanc::erase (XalanDOMString & theString) inline
Remove all elements from target string.
Deprecated:
This function is deprecated.
Parameters
theString target string
Definition at line 2490 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::erase().
Referenced by xalanc::XalanDOMString::assign(), xalanc::XalanVector< XalanDOMChar >::erase(), xalanc::XalanList< ReusableArenaBlock< string_type > * >::pop_back(), and xalanc::XalanList< ReusableArenaBlock< string_type > * >::pop_front().
flipCaseASCII()
XalanDOMChar xalanc::flipCaseASCII (XalanDOMChar theChar) inline
Flips the case to of the supplied character.
This function works only with the Unicode characters A-Z and a-z.
Parameters
theString target string
Returns
string containing lower case characters
Definition at line 1466 of file DOMStringHelper.hpp.
indexOf() [1/6]
XalanDOMString::size_type xalanc::indexOf (const XalanDOMChar * theString, const XalanDOMChar * theSubstring) inline
Simulates the java String method indexOf().
Parameters
theString string to search
theSubstring substring searched for
Returns
the index of theSubstring in theString, or length(theString) if the string is not found.
Definition at line 406 of file DOMStringHelper.hpp.
References indexOf(), and length().
indexOf() [2/6]
XalanDOMString::size_type xalanc::indexOf (const XalanDOMChar * theString, XalanDOMChar theChar) inline
Simulates the java String method indexOf().
Parameters
theString string to search
theChar character searched for
Returns
the index of theChar in theString, or length(theString) if the character is not found.
Definition at line 308 of file DOMStringHelper.hpp.
indexOf() [3/6]
xalanc::indexOf (const XalanDOMChar * theString, XalanDOMString::size_type theStringLength, const XalanDOMChar * theSubstring, XalanDOMString::size_type theSubstringLength)
Simulates the java String method indexOf().
Parameters
theString string to search
theStringLength length of the string to search
theSubstring substring searched for
theSubstringLength length of the substring searched for
Returns
the index of theSubstring in theString, or length(theString) if the string is not found.
indexOf() [4/6]
XalanDOMString::size_type xalanc::indexOf (const XalanDOMChar * theString, XalanDOMString::size_type theStringLength, XalanDOMChar theChar) inline
Simulates the java String method indexOf().
Parameters
theString string to search
theStringLength the length of theString
theChar character searched for
Returns
the index of theChar in theString, or length(theString) if the character is not found.
Definition at line 337 of file DOMStringHelper.hpp.
indexOf() [5/6]
xalanc::indexOf (const XalanDOMString & theString, const XalanDOMString & theSubstring)
Simulates the java String method indexOf().
Parameters
theString string to search
theSubstring substring searched for
Returns
the index of theSubstring in theString, or length(theString) if the string is not found.
Referenced by indexOf().
indexOf() [6/6]
XalanDOMString::size_type xalanc::indexOf (const XalanDOMString & theString, XalanDOMChar theChar) inline
Simulates the java String method indexOf().
Parameters
theString string to search
theChar character searched for
Returns
the index of theChar in theString, or length(theString) if the character is not found.
Definition at line 367 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), indexOf(), and xalanc::XalanDOMString::length().
insert() [1/2]
XalanDOMString& xalanc::insert (XalanDOMString & theString, XalanDOMString::size_type thePosition, const XalanDOMChar * theStringToInsert) inline
Insert a string into another string.
Deprecated:
This function is deprecated.
Parameters
theString target string
thePosition The position in the target string to insert
theStringToInsert The string to insert
Returns
A reference to the target string
Definition at line 2441 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::insert().
insert() [2/2]
XalanDOMString& xalanc::insert (XalanDOMString & theString, XalanDOMString::size_type thePosition, const XalanDOMString & theStringToInsert) inline
Insert a string into another string.
Deprecated:
This function is deprecated.
Parameters
theString target string
thePosition The position in the target string to insert
theStringToInsert The string to insert
Returns
A reference to the target string
Definition at line 2418 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::insert().
Referenced by xalanc::XalanVector< XalanDOMChar >::assign(), xalanc::XalanMap< const XalanDOMChar *, XalanSourceTreeElement * >::insert(), xalanc::XalanVector< XalanDOMChar >::insert(), xalanc::XalanDOMString::insert(), xalanc::XalanVector< XalanDOMChar >::operator=(), and xalanc::XalanMap< const XalanDOMChar *, XalanSourceTreeElement * >::XalanMap().
isEmpty()
bool xalanc::isEmpty (const XalanDOMString & str) inline
Determines if the target string contains any elements.
Deprecated:
This function is deprecated.
Parameters
str target string
Returns
true if the target string has a non-zero length
Definition at line 291 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::empty().
isXMLDigit()
bool xalanc::isXMLDigit (XalanDOMChar theChar) inline
Determines whether character represents a digit.
Parameters
theChar target character
Returns
true if character represents a digit
Definition at line 1326 of file DOMStringHelper.hpp.
isXMLLetterOrDigit()
bool xalanc::isXMLLetterOrDigit (XalanDOMChar theChar) inline
Determines whether character represents a letter or digit.
Parameters
theChar target character
Returns
true if character represents a letter or digit
Definition at line 1340 of file DOMStringHelper.hpp.
isXMLWhitespace() [1/4]
bool xalanc::isXMLWhitespace (const XalanDOMChar * theString) inline
Determines if a null-terminated string contains only whitespace.
Parameters
theString target string
Returns
true if the string contains only whitespace
Definition at line 2717 of file DOMStringHelper.hpp.
References length().
isXMLWhitespace() [2/4]
xalanc::isXMLWhitespace (const XalanDOMChar ch[], XalanDOMString::size_type start, XalanDOMString::size_type length)
Determines if a range in an array contains only whitespace.
Parameters
ch target array
start starting index to examine
length number of characters to examine
Returns
true if specified range contains only whitespace
isXMLWhitespace() [3/4]
xalanc::isXMLWhitespace (const XalanDOMString & string)
Determines if the string contains only whitespace.
Parameters
theString target string
Returns
true if string contains only whitespace
isXMLWhitespace() [4/4]
bool xalanc::isXMLWhitespace (XalanDOMChar theChar) inline
Determines whether character represents white space.
Parameters
theChar target character
Returns
true if character represents white space
Definition at line 1312 of file DOMStringHelper.hpp.
lastIndexOf() [1/2]
xalanc::lastIndexOf (const XalanDOMChar * theString, XalanDOMChar theChar)
Simulates the java String method lastIndexOf().
Parameters
theString string to search
theChar character searched for
Returns
the index of theChar in theString, or length(theString) if the character is not found.
lastIndexOf() [2/2]
XalanDOMString::size_type xalanc::lastIndexOf (const XalanDOMString & theString, XalanDOMChar theChar) inline
Simulates the java String method lastIndexOf().
Parameters
theString string to search
theChar character searched for
Returns
the index of theChar in theString, or length(theString) if the character is not found.
Definition at line 460 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str().
leadingByteOf2()
char xalanc::leadingByteOf2 (char theBits) inline
Definition at line 79 of file XalanUTF8Writer.hpp.
leadingByteOf3()
char xalanc::leadingByteOf3 (char theBits) inline
Definition at line 87 of file XalanUTF8Writer.hpp.
leadingByteOf4()
char xalanc::leadingByteOf4 (char theBits) inline
Definition at line 95 of file XalanUTF8Writer.hpp.
length() [1/3]
XalanDOMString::size_type xalanc::length (const char * theString) inline
Get the length of a null-terminated string.
Parameters
theString target string
Returns
the length of the target string
Definition at line 273 of file DOMStringHelper.hpp.
Referenced by collationCompare(), compare(), compareIgnoreCaseASCII(), endsWith(), equals(), equalsIgnoreCaseASCII(), indexOf(), isXMLWhitespace(), and startsWith().
length() [2/3]
XalanDOMString::size_type xalanc::length (const XalanDOMChar * theString) inline
Get the length of a null-terminated string of XalanDOMChar characters.
Parameters
theString target string
Returns
the length of the target string
Definition at line 250 of file DOMStringHelper.hpp.
length() [3/3]
XalanDOMString::size_type xalanc::length (const XalanDOMString & theString) inline
Get the length of a XalanDOMString.
Deprecated:
This function is deprecated.
Parameters
theString target string
Returns
the length of the target string
Definition at line 235 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::length().
Referenced by xalanc::FormatterToXML::accumContent(), xalanc::FormatterToXML::accumName(), xalanc::ResultNamespacesStack::addDeclaration(), xalanc::XalanNamespacesStack::addDeclaration(), xalanc::XSLTEngineImpl::addResultAttribute(), xalanc::XalanDOMString::append(), xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::charactersRaw(), xalanc::XSLException::defaultFormat(), xalanc::XalanDOMString::equals(), xalanc::URISupport::getURLStringFromString(), xalanc::XalanDOMString::hash(), xalanc::XalanDOMString::insert(), xalanc::XalanFormatterWriter::NewLineWriterFunctor< WriterType >::NewLineWriterFunctor(), xalanc::XalanFormatterWriter::NewLineWriterFunctor< WriterType >::operator()(), xalanc::XalanUTF16Writer::outputNewline(), xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::outputNewline(), xalanc::XalanUTF8Writer::outputNewline(), xalanc::XalanDOMString::substr(), xalanc::XalanOutputStream::write(), xalanc::XalanUTF16Writer::write(), xalanc::XalanUTF8Writer::write(), xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::write(), xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeCDATA(), xalanc::XalanOtherEncodingWriter< Predicate, ConstantsType >::writeCDATAChar(), xalanc::XalanUTF8Writer::writeCDATAChar(), xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeCDATAChars(), xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeCharacters(), xalanc::FormatterToXMLUnicode< UnicodeWriter, ConstantsType, CharPredicate, IndentHandler, XMLVersion >::writeNormalizedCharBig(), and xalanc::XalanFormatterWriter::XalanFormatterWriter().
makeMapValueDeleteFunctor()
template<class MapType > MapValueDeleteFunctor<MapType> xalanc::makeMapValueDeleteFunctor (MapType & theMap)
Definition at line 177 of file STLHelper.hpp.
makeXalanDestroyFunctor()
template<class Type > XalanDestroyFunctor<Type> xalanc::makeXalanDestroyFunctor (const Type *)
Definition at line 89 of file STLHelper.hpp.
Referenced by xalanc::DeleteFunctor< FormatterToTextDOMString >::operator()(), and xalanc::MapValueDeleteFunctor< T >::operator()().
MakeXalanDOMCharVector() [1/3]
xalanc::MakeXalanDOMCharVector (const char * data, XalanDOMCharVectorType & result, bool fTranscode = true)
Utility function to make a null-terminated vector of XMLChs, from a null-terminated array of chars, via transcoding, if requested.
Parameters
data array to be converted
whether or not to transcode
Returns
null-terminated vector of XalanDOMChar
MakeXalanDOMCharVector() [2/3]
xalanc::MakeXalanDOMCharVector (const XalanDOMChar * data, XalanDOMCharVectorType & result)
Utility function to make a null-terminated vector of XMLChs, from a null-terminated array of XalanDOMChar.
Parameters
data array to be converted
Returns
null-terminated vector of XalanDOMChar
MakeXalanDOMCharVector() [3/3]
XalanDOMCharVectorType& xalanc::MakeXalanDOMCharVector (const XalanDOMString & data, XalanDOMCharVectorType & result) inline
Utility function to make a null-terminated vector of XMLChs, from a XalanDOMString.
Parameters
data XalanDOMString to be converted
Returns
null-terminated vector of XalanDOMChar
Definition at line 2562 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str().
NumberToDOMString() [1/7]
xalanc::NumberToDOMString (double theValue, XalanDOMString & theResult)
Converts a double value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
Referenced by xalanc::XObject::string().
NumberToDOMString() [2/7]
XalanDOMString& xalanc::NumberToDOMString (XMLInt16 theValue, XalanDOMString & theResult) inline
Converts a 16-bit int value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
Definition at line 813 of file DOMStringHelper.hpp.
Referenced by NumberToDOMString().
NumberToDOMString() [3/7]
XalanDOMString& xalanc::NumberToDOMString (XMLInt32 theValue, XalanDOMString & theResult) inline
Converts a 32-bit int value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
Definition at line 775 of file DOMStringHelper.hpp.
References NumberToDOMString().
NumberToDOMString() [4/7]
xalanc::NumberToDOMString (XMLInt64 theValue, XalanDOMString & theResult)
Converts an 64-bit signed int value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
NumberToDOMString() [5/7]
XalanDOMString& xalanc::NumberToDOMString (XMLUInt16 theValue, XalanDOMString & theResult) inline
Converts a 16-bit unsigned int value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
Definition at line 794 of file DOMStringHelper.hpp.
References NumberToDOMString().
NumberToDOMString() [6/7]
XalanDOMString& xalanc::NumberToDOMString (XMLUInt32 theValue, XalanDOMString & theResult) inline
Converts a 32-bit unsigned int value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
Definition at line 756 of file DOMStringHelper.hpp.
References NumberToDOMString().
NumberToDOMString() [7/7]
xalanc::NumberToDOMString (XMLUInt64 theValue, XalanDOMString & theResult)
Converts an 64-bit unsigned int value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
NumberToHexDOMString() [1/6]
XalanDOMString& xalanc::NumberToHexDOMString (XMLInt16 theValue, XalanDOMString & theResult) inline
Converts a 16-bit signed int value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
Definition at line 917 of file DOMStringHelper.hpp.
Referenced by NumberToHexDOMString().
NumberToHexDOMString() [2/6]
XalanDOMString& xalanc::NumberToHexDOMString (XMLInt32 theValue, XalanDOMString & theResult) inline
Converts a 32-bit signed int value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
Definition at line 879 of file DOMStringHelper.hpp.
References NumberToHexDOMString().
NumberToHexDOMString() [3/6]
xalanc::NumberToHexDOMString (XMLInt64 theValue, XalanDOMString & theResult)
Converts an 64-bit signed int value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
NumberToHexDOMString() [4/6]
XalanDOMString& xalanc::NumberToHexDOMString (XMLUInt16 theValue, XalanDOMString & theResult) inline
Converts a 16-bit unsigned int value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
Definition at line 898 of file DOMStringHelper.hpp.
References NumberToHexDOMString().
NumberToHexDOMString() [5/6]
XalanDOMString& xalanc::NumberToHexDOMString (XMLUInt32 theValue, XalanDOMString & theResult) inline
Converts a 32-bit unsigned int value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
Definition at line 860 of file DOMStringHelper.hpp.
References NumberToHexDOMString().
NumberToHexDOMString() [6/6]
xalanc::NumberToHexDOMString (XMLUInt64 theValue, XalanDOMString & theResult)
Converts an 64-bit unsigned int value into a XalanDOMString.
Parameters
theValue number to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
Referenced by xalanc::XalanFormatterWriter::throwInvalidCharacterException(), and xalanc::XalanFormatterWriter::throwInvalidUTF16SurrogateException().
operator!=() [1/6]
bool xalanc::operator!= (const XalanDOMChar * theLHS, const XalanDOMString & theRHS) inline
Definition at line 1035 of file XalanDOMString.hpp.
operator!=() [2/6]
bool xalanc::operator!= (const XalanDOMString & theLHS, const XalanDOMChar * theRHS) inline
Definition at line 1045 of file XalanDOMString.hpp.
operator!=() [3/6]
bool xalanc::operator!= (const XalanDOMString & theLHS, const XalanDOMString & theRHS) inline
Definition at line 1025 of file XalanDOMString.hpp.
operator!=() [4/6]
bool xalanc::operator!= (const XalanQName & theLHS, const XalanQName & theRHS) inline
Definition at line 408 of file XalanQName.hpp.
operator!=() [5/6]
template<class Type > bool xalanc::operator!= (const XalanVector< Type > & theLHS, const XalanVector< Type > & theRHS) inline
Definition at line 1140 of file XalanVector.hpp.
operator!=() [6/6]
bool xalanc::operator!= (const XObjectPtr & theLHS, const XObjectPtr & theRHS) inline
Definition at line 996 of file XObject.hpp.
operator<() [1/6]
bool xalanc::operator< (const CharVectorType & theLHS, const CharVectorType & theRHS) inline
Implements operator< for CharVectorType.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns true if theLHS is lexically less than theRHS
See also
compare
Definition at line 2204 of file DOMStringHelper.hpp.
References compare().
operator<() [2/6]
bool xalanc::operator< (const ElemAttributeSet & theLHS, const ElemAttributeSet & theRHS) inline
Definition at line 121 of file ElemAttributeSet.hpp.
References xalanc::ElemAttributeSet::getQName().
operator<() [3/6]
bool xalanc::operator< (const XalanDOMString & theLHS, const XalanDOMString & theRHS) inline
Implements operator< for DOMStrings.
Parameters
theLHS first string to compare
theRHS second string to compare
Returns
Returns true if theLHS is lexically less than theRHS
See also
compare
Definition at line 2223 of file DOMStringHelper.hpp.
References compare().
operator<() [4/6]
bool xalanc::operator< (const XalanQName & theLHS, const XalanQName & theRHS) inline
Definition at line 418 of file XalanQName.hpp.
References equals(), xalanc::XalanQName::getLocalPart(), and xalanc::XalanQName::getNamespace().
operator<() [5/6]
template<class Type > bool xalanc::operator< (const XalanVector< Type > & theLHS, const XalanVector< Type > & theRHS) inline
Definition at line 1151 of file XalanVector.hpp.
References xalanc::XalanVector< Type, ConstructionTraits >::begin(), and xalanc::XalanVector< Type, ConstructionTraits >::end().
operator<() [6/6]
bool xalanc::operator< (const XObjectPtr & theLHS, const XObjectPtr & theRHS) inline
Definition at line 1006 of file XObject.hpp.
operator<<() [1/7]
std::ostream& xalanc::operator<< (std::ostream & theStream, const CharVectorType & theString) inline
Outputs the string to the specified stream.
Parameters
theStream output stream
theString the string to output
See also
OutputString
Definition at line 1166 of file DOMStringHelper.hpp.
References OutputString().
operator<<() [2/7]
std::ostream& xalanc::operator<< (std::ostream & theStream, const XalanDOMChar * theString) inline
Outputs the target string to the specified stream.
Parameters
theStream output stream
theString target string
See also
OutputString
Definition at line 1208 of file DOMStringHelper.hpp.
References OutputString().
operator<<() [3/7]
std::ostream& xalanc::operator<< (std::ostream & theStream, const XalanDOMString & theString) inline
Outputs the target string to the specified stream.
Parameters
theStream output stream
theString target string
See also
OutputString
Definition at line 1250 of file DOMStringHelper.hpp.
References OutputString().
operator<<() [4/7]
std::ostream& xalanc::operator<< (std::ostream & theStream, XalanDOMString & theString) inline
Outputs the target string to the specified stream.
Parameters
theStream output stream
theString target string
See also
OutputString
Definition at line 1272 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::getMemoryManager(), and OutputString().
operator<<() [5/7]
XalanOutputStream& xalanc::operator<< (XalanOutputStream & theStream, const CharVectorType & theString) inline
Outputs the string to the specified stream.
Parameters
theStream output stream
theString the string to output
See also
OutputString
Definition at line 1145 of file DOMStringHelper.hpp.
References OutputString().
operator<<() [6/7]
XalanOutputStream& xalanc::operator<< (XalanOutputStream & theStream, const XalanDOMChar * theString) inline
Outputs the target string to the specified stream.
Parameters
theStream output stream
theString target string
See also
OutputString
Definition at line 1187 of file DOMStringHelper.hpp.
References OutputString().
operator<<() [7/7]
XalanOutputStream& xalanc::operator<< (XalanOutputStream & theStream, const XalanDOMString & theString) inline
Outputs the target string to the specified stream.
Parameters
theStream output stream
theString target string
See also
OutputString
Definition at line 1230 of file DOMStringHelper.hpp.
References OutputString().
operator<=()
template<class Type > bool xalanc::operator<= (const XalanVector< Type > & theLHS, const XalanVector< Type > & theRHS) inline
Definition at line 1166 of file XalanVector.hpp.
operator==() [1/7]
bool xalanc::operator== (const ElemAttributeSet & theLHS, const ElemAttributeSet & theRHS) inline
Definition at line 111 of file ElemAttributeSet.hpp.
References xalanc::ElemAttributeSet::getQName().
operator==() [2/7]
bool xalanc::operator== (const XalanDOMChar * theLHS, const XalanDOMString & theRHS) inline
Definition at line 1014 of file XalanDOMString.hpp.
References equals().
operator==() [3/7]
bool xalanc::operator== (const XalanDOMString & theLHS, const XalanDOMChar * theRHS) inline
Definition at line 1004 of file XalanDOMString.hpp.
References equals().
operator==() [4/7]
bool xalanc::operator== (const XalanDOMString & theLHS, const XalanDOMString & theRHS) inline
Definition at line 994 of file XalanDOMString.hpp.
References equals().
operator==() [5/7]
bool xalanc::operator== (const XalanQName & theLHS, const XalanQName & theRHS) inline
Definition at line 398 of file XalanQName.hpp.
References xalanc::XalanQName::equals().
operator==() [6/7]
template<class Type > bool xalanc::operator== (const XalanVector< Type > & theLHS, const XalanVector< Type > & theRHS) inline
Definition at line 1118 of file XalanVector.hpp.
References xalanc::XalanVector< Type, ConstructionTraits >::begin(), xalanc::XalanVector< Type, ConstructionTraits >::end(), and xalanc::XalanVector< Type, ConstructionTraits >::size().
Referenced by xalanc::XalanListIteratorBase< XalanListTraits, Node >::operator!=(), and xalanc::XalanDecimalFormatSymbols::operator!=().
operator==() [7/7]
bool xalanc::operator== (const XObjectPtr & theLHS, const XObjectPtr & theRHS) inline
Definition at line 986 of file XObject.hpp.
operator>()
template<class Type > bool xalanc::operator> (const XalanVector< Type > & theLHS, const XalanVector< Type > & theRHS) inline
Definition at line 1177 of file XalanVector.hpp.
operator>=()
template<class Type > bool xalanc::operator>= (const XalanVector< Type > & theLHS, const XalanVector< Type > & theRHS) inline
Definition at line 1188 of file XalanVector.hpp.
OutputString() [1/6]
xalanc::OutputString (std::ostream & theStream, const CharVectorType & theString)
Outputs the target string to the specified stream.
Parameters
theStream output stream
theString target string
See also
operator<<
OutputString() [2/6]
xalanc::OutputString (std::ostream & theStream, const XalanDOMChar * theString, MemoryManager & theMemoryManager)
Outputs the target string to the specified stream.
Parameters
theStream output stream
theString target string
See also
operator<<
OutputString() [3/6]
void xalanc::OutputString (std::ostream & theStream, const XalanDOMString & theString, MemoryManager & theMemoryManager) inline
Outputs the target string to the specified stream.
Parameters
theStream output stream
theString target string
theMemoryManager The MemoryManager instance to use.
See also
operator<<
Definition at line 1124 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str().
Referenced by operator<<(), and OutputString().
OutputString() [4/6]
xalanc::OutputString (XalanOutputStream & theStream, const CharVectorType & theString)
Outputs the target string to the specified stream.
Parameters
theStream output stream
theString target string
See also
operator<<
OutputString() [5/6]
xalanc::OutputString (XalanOutputStream & theStream, const XalanDOMChar * theString)
Outputs the target string to the specified stream.
Parameters
theStream output stream
theString target string
See also
operator<<
OutputString() [6/6]
void xalanc::OutputString (XalanOutputStream & theStream, const XalanDOMString & theString) inline
Outputs the target string to the specified stream.
Parameters
theStream output stream
theString target string
See also
operator<<
Definition at line 1101 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), xalanc::XalanDOMString::empty(), and OutputString().
PointerToDOMString()
xalanc::PointerToDOMString (const void * theValue, XalanDOMString & theResult)
Converts a pointer into a XalanDOMString.
Parameters
theValue pointer to be converted
theResult the string to append with the result
Returns
a reference to the passed string result.
releaseMemory()
void xalanc::releaseMemory (XalanDOMString & theString, MemoryManager & theManager) inline
Remove all elements from target string and frees all allocated memory.
Parameters
theString target string
Definition at line 2504 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::swap().
reserve()
void xalanc::reserve (XalanDOMString & theString, XalanDOMString::size_type theCount) inline
Reserve some space in the string for more efficient concatenation...
Deprecated:
This function is deprecated.
Parameters
theString target string
theCount The amount of space to reserve
Definition at line 217 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::reserve().
Referenced by xalanc::XalanVector< XalanDOMChar >::resize().
startsWith() [1/6]
bool xalanc::startsWith (const XalanDOMChar * theString, const XalanDOMChar * theSubstring) inline
Simulates the java String method startsWith().
Parameters
theDOMString target string to search
theSubstring substring searched for
Returns
true if the target string begins with the substring
Definition at line 495 of file DOMStringHelper.hpp.
References length(), and startsWith().
startsWith() [2/6]
bool xalanc::startsWith (const XalanDOMChar * theString, const XalanDOMString & theSubstring) inline
Simulates the java String method startsWith().
Parameters
theDOMString target string to search
theSubstring substring searched for
Returns
true if the target string begins with the substring
Definition at line 514 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), xalanc::XalanDOMString::length(), length(), and startsWith().
startsWith() [3/6]
xalanc::startsWith (const XalanDOMChar * theString, XalanDOMString::size_type theStringLength, const XalanDOMChar * theSubstring, XalanDOMString::size_type theSubstringLength)
Simulates the java String method startsWith().
Parameters
theString target string to search
theStringLength the length of theString
theSubstring substring searched for
theSubstringLength the length of theSubstring
Returns
true if the target string begins with the substring
Referenced by xalanc::DOMServices::getNameOfNode(), and xalanc::DOMServices::isNamespaceDeclaration().
startsWith() [4/6]
bool xalanc::startsWith (const XalanDOMString & theString, const XalanDOMChar * theSubstring) inline
Simulates the java String method startsWith().
Parameters
theDOMString target string to search
theSubstring substring searched for
Returns
true if the target string begins with the substring
Definition at line 537 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), xalanc::XalanDOMString::length(), length(), and startsWith().
startsWith() [5/6]
bool xalanc::startsWith (const XalanDOMString & theString, const XalanDOMChar * theSubstring, XalanDOMString::size_type theSubstringLength) inline
Simulates the java String method startsWith().
Parameters
theDOMString target string to search
theSubstring substring searched for
theSubstringLength the length of theSubstring
Returns
true if the target string begins with the substring
Definition at line 561 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), xalanc::XalanDOMString::length(), and startsWith().
startsWith() [6/6]
bool xalanc::startsWith (const XalanDOMString & theString, const XalanDOMString & theSubstring) inline
Simulates the java String method startsWith().
Parameters
theDOMString target string to search
theSubstring substring searched for
Returns
true if the target string begins with the substring
Definition at line 585 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str(), and xalanc::XalanDOMString::length().
Referenced by startsWith().
substring() [1/3]
xalanc::substring (const XalanDOMChar * theString, XalanDOMString & theSubstring, XalanDOMString::size_type theStartIndex, XalanDOMString::size_type theEndIndex = XalanDOMString::npos)
Simulates the java String method substring().
Returns a new string that is a substring of this string. The substring begins at the specified theStartIndex and extends to the character at index theEndIndex - 1. Thus the length of the substring is theEndIndex - theStartIndex.
Parameters
theString source string
theSubstring target string
theStartIndex starting index, inclusive
theEndIndex ending index, exclusive
Returns
A reference to theSubstring
substring() [2/3]
xalanc::substring (const XalanDOMString & theString, XalanDOMString & theSubstring, XalanDOMString::size_type theStartIndex, XalanDOMString::size_type theEndIndex = XalanDOMString::npos)
Simulates the java String method substring().
Returns a new string that is a substring of this string. The substring begins at the specified theStartIndex and extends to the character at index theEndIndex - 1. Thus the length of the substring is theEndIndex - theStartIndex.
Parameters
theString source string
theSubstring target string
theStartIndex starting index, inclusive
theEndIndex ending index, exclusive
substring() [3/3]
xalanc::substring (const XalanDOMString & theString, XalanDOMString::size_type theStartIndex, XalanDOMString & theResult, XalanDOMString::size_type theEndIndex = XalanDOMString::npos)
Simulates the java String method substring().
Returns a new string that is a substring of this string. The substring begins at the specified theStartIndex and extends to the character at index theEndIndex - 1. Thus the length of the substring is theEndIndex-theStartIndex.
Parameters
theString source string
theStartIndex starting index, inclusive
theEndIndex ending index, exclusive
Returns
string containing the specified range of characters from target
swap()
template<class Type > void xalanc::swap (XalanVector< Type > & theLHS, XalanVector< Type > & theRHS) inline
Definition at line 1107 of file XalanVector.hpp.
References xalanc::XalanVector< Type, ConstructionTraits >::swap().
Referenced by xalanc::XalanVector< XalanDOMChar >::insert(), xalanc::XalanMap< const XalanDOMChar *, XalanSourceTreeElement * >::operator=(), xalanc::XalanVector< XalanDOMChar >::operator=(), xalanc::MutableNodeRefList::swap(), xalanc::XalanDOMString::swap(), xalanc::XalanList< ReusableArenaBlock< string_type > * >::swap(), and xalanc::XalanVector< XalanDOMChar >::XalanVector().
toCharArray() [1/3]
const char* xalanc::toCharArray (const CharVectorType & theString) inline
Get the underlying representation of the target CharVectorType as a pointer to an array of characters.
Deprecated:
This function is deprecated.
Parameters
theString target string
Returns
the pointer
Definition at line 200 of file DOMStringHelper.hpp.
References xalanc::XalanVector< Type, ConstructionTraits >::empty().
toCharArray() [2/3]
const XalanDOMChar* xalanc::toCharArray (const XalanDOMChar * theString) inline
Get the underlying representation of a XalanDOMChar.
Deprecated:
This function is deprecated.
Parameters
theString target string
Returns
array of XalanDOMChar
Definition at line 183 of file DOMStringHelper.hpp.
toCharArray() [3/3]
const XalanDOMChar* xalanc::toCharArray (const XalanDOMString & theString) inline
Get the underlying representation of the target XalanDOMString as an array of XalanDOMChar, not guaranteed to be null-terminated.
Deprecated:
This function is deprecated.
Parameters
theString target string
Returns
array of XalanDOMChar
Definition at line 167 of file DOMStringHelper.hpp.
References xalanc::XalanDOMString::c_str().
toLowerASCII()
XalanDOMChar xalanc::toLowerASCII (XalanDOMChar theChar) inline
Converts ASCII alphabetic characters from upper case to lower case.
This function works only with the Unicode characters A-Z.
Parameters
theString target string
Returns
string containing lower case characters
Definition at line 1421 of file DOMStringHelper.hpp.
toLowerCaseASCII() [1/3]
xalanc::toLowerCaseASCII (const XalanDOMChar * theString, XalanDOMString & theResult)
Converts ASCII alphabetic characters from upper case to lower case.
This function works only with the characters a-z and A-Z.
Parameters
theString The source string
theResult The target string
Returns
A reference to theResult
toLowerCaseASCII() [2/3]
xalanc::toLowerCaseASCII (const XalanDOMString & theString, XalanDOMString & theResult)
Converts ASCII alphabetic characters from upper case to lower case.
This function works only with the characters a-z and A-Z.
Parameters
theString The source string
theResult The target string
Returns
A reference to theResult
toLowerCaseASCII() [3/3]
xalanc::toLowerCaseASCII (XalanDOMString & theString)
Converts ASCII alphabetic characters from upper case to lower case.
This function works only with the characters a-z and A-Z.
Parameters
theString The string to convert
Returns
A reference to theString
toUpperASCII()
XalanDOMChar xalanc::toUpperASCII (XalanDOMChar theChar) inline
Converts ASCII alphabetic characters from lower case to upper case.
This function works only with the Unicode characters a-z.
Parameters
theString target string
Returns
string containing upper case characters
Definition at line 1444 of file DOMStringHelper.hpp.
toUpperCaseASCII() [1/3]
xalanc::toUpperCaseASCII (const XalanDOMChar * theString, XalanDOMString & theResult)
Converts ASCII alphabetic characters from lower case to upper case.
This function works only with the characters a-z and A-Z.
Parameters
theString The source string
theResult The target string
Returns
A reference to theResult
toUpperCaseASCII() [2/3]
xalanc::toUpperCaseASCII (const XalanDOMString & theString, XalanDOMString & theResult)
Converts ASCII alphabetic characters from lower case to upper case.
This function works only with the characters a-z and A-Z.
Parameters
theString The source string
theResult The target string
Returns
A reference to theResult
toUpperCaseASCII() [3/3]
xalanc::toUpperCaseASCII (XalanDOMString & theString)
Converts ASCII alphabetic characters from lower case to upper case.
This function works only with the characters a-z and A-Z.
Parameters
theString The string to convert
Returns
A reference to theString
trailingByte()
char xalanc::trailingByte (char theBits) inline
Definition at line 103 of file XalanUTF8Writer.hpp.
TranscodeFromLocalCodePage() [1/6]
xalanc::TranscodeFromLocalCodePage (const char * theSourceString, XalanDOMCharVectorType & theTargetVector, bool terminate = false)
Convert a string to a C++ standard library vector, transcoding from the default local code page.
The string must be null-terminated.
Parameters
sourceString The source string
targetVector The target string
terminate If true, the transcoded string will be null-terminated
Returns
true if successful, false if not.
TranscodeFromLocalCodePage() [2/6]
const XalanDOMString& xalanc::TranscodeFromLocalCodePage (const char * theSourceString, XalanDOMString & theResult, XalanDOMString::size_type theSourceStringLength = XalanDOMString::npos) inline
Convert a string to a XalanDOMString, transcoding from the default local code page.
Parameters
theSourceString The source string
theResult The result.
theSourceStringLength The source string length.
Returns
The new string.
Definition at line 1315 of file XalanDOMString.hpp.
References xalanc::XalanDOMString::assign().
TranscodeFromLocalCodePage() [3/6]
xalanc::TranscodeFromLocalCodePage (const char * theSourceString, XalanDOMString::size_type theSourceStringLength, bool theSourceStringIsNullTerminated, XalanDOMCharVectorType & theTargetVector, bool terminate = false)
Convert a string to a C++ standard library vector, transcoding from the default local code page.
Parameters
theSourceString The source string
theSourceStringLength The source string length.
theSourceStringIsNullTerminated true if the source string is null-terminated, otherwise false.
targetVector The target string
terminate If true, the transcoded string will be null-terminated
Returns
true if successful, false if not.
TranscodeFromLocalCodePage() [4/6]
xalanc::TranscodeFromLocalCodePage (const char * theSourceString, XalanDOMString::size_type theSourceStringLength, XalanDOMCharVectorType & theTargetVector, bool terminate = false)
Convert a string to a C++ standard library vector, transcoding from the default local code page.
Parameters
theSourceString The source string
theSourceStringLength The source string length.
targetVector The target string
terminate If true, the transcoded string will be null-terminated
Returns
true if successful, false if not.
TranscodeFromLocalCodePage() [5/6]
const XalanDOMString xalanc::TranscodeFromLocalCodePage (const char * theSourceString, XalanDOMString::size_type theSourceStringLength = XalanDOMString::npos) inline
Convert a string to a XalanDOMString, transcoding from the default local code page.
Parameters
theSourceString The source string
theSourceStringLength The source string length.
Returns
The new string.
Definition at line 1181 of file XalanDOMString.hpp.
Referenced by append().
TranscodeFromLocalCodePage() [6/6]
xalanc::TranscodeFromLocalCodePage (const CharVectorType & theSourceString, XalanDOMString & theResult)
Convert a vector of characters to a XalanDOMString, transcoding from the default local code.
Parameters
theSourceString The source vector.
theResult The result.
Returns
The transcoded string.
TranscodeToLocalCodePage() [1/8]
const CharVectorType xalanc::TranscodeToLocalCodePage (const XalanDOMChar * theSourceString) inline
Convert XalanDOMString to C++ standard library vector, transcoding to the default local code page.
Null-terminate the sttring...
Parameters
theSourceString source string
Returns
The transcoded string.
Definition at line 1232 of file XalanDOMString.hpp.
References TranscodeToLocalCodePage().
TranscodeToLocalCodePage() [2/8]
xalanc::TranscodeToLocalCodePage (const XalanDOMChar * theSourceString, CharVectorType & targetVector, bool terminate, char theSubstitutionChar)
Convert a XalanDOMChar string to C++ standard library vector, transcoding to the default local code page.
The string must be null-terminated.
Parameters
theSourceString The source string
targetVector The target string
terminate If true, the transcoded string will be null-terminated
TranscodeToLocalCodePage() [3/8]
xalanc::TranscodeToLocalCodePage (const XalanDOMChar * theSourceString, CharVectorType & targetVector, bool terminate = false)
Convert a XalanDOMChar string to C++ standard library vector, transcoding to the default local code page.
The string must be null-terminated.
Parameters
theSourceString The source string
targetVector The target string
terminate If true, the transcoded string will be null-terminated
Returns
true if successful, false if not.
TranscodeToLocalCodePage() [4/8]
xalanc::TranscodeToLocalCodePage (const XalanDOMChar * theSourceString, XalanDOMString::size_type theSourceStringLength, CharVectorType & targetVector, bool terminate, char theSubstitutionChar)
Convert a XalanDOMChar string to C++ standard library vector, transcoding to the default local code page.
If the source string contines code points, that can't be represented in the local code page, the substitution character will be used
Parameters
sourceString The source string
sourceStringLength The source string length.
targetVector The target string
terminate If true, the transcoded string will be null-terminated
theSubstitutionChar The substitution character for code points that are not presentable in the local page
TranscodeToLocalCodePage() [5/8]
xalanc::TranscodeToLocalCodePage (const XalanDOMChar * theSourceString, XalanDOMString::size_type theSourceStringLength, CharVectorType & targetVector, bool terminate = false)
Convert a XalanDOMChar string to C++ standard library vector, transcoding to the default local code page.
Parameters
sourceString The source string
sourceStringLength The source string length.
targetVector The target string
terminate If true, the transcoded string will be null-terminated
Returns
true if successful, false if not.
Referenced by EnumerateDirectory().
TranscodeToLocalCodePage() [6/8]
const CharVectorType xalanc::TranscodeToLocalCodePage (const XalanDOMString & theSourceString) inline
Convert XalanDOMString to C++ standard library vector, transcoding to the default local code page.
Parameters
thetheSourceString source string
Returns
The transcoded string.
Definition at line 1294 of file XalanDOMString.hpp.
References xalanc::XalanDOMString::c_str().
Referenced by TranscodeToLocalCodePage().
TranscodeToLocalCodePage() [7/8]
xalanc::TranscodeToLocalCodePage (const XalanDOMString & theSourceString, CharVectorType & theTargetVector, bool terminate, char theSubstitutionChar)
Convert XalanDOMString to C++ standard library vector, transcoding to the default local code page.
Parameters
theSourceString The source string
targetVector The target string
terminate If true, the transcoded string will be null-terminated
theSubstitutionChar The substitution character for code points that are not presentable in the local page
TranscodeToLocalCodePage() [8/8]
bool xalanc::TranscodeToLocalCodePage (const XalanDOMString & theSourceString, CharVectorType & theTargetVector, bool terminate = false) inline
Convert XalanDOMString to C++ standard library vector, transcoding to the default local code page.
Parameters
theSourceString The source string
theTargetVector The target string
Returns
true if successful, false if not.
Definition at line 1253 of file XalanDOMString.hpp.
References xalanc::XalanDOMString::c_str(), and TranscodeToLocalCodePage().
trim()
xalanc::trim (const XalanDOMString & theString, XalanDOMString & theResult)
Remove leading and trailing whitespace.
Parameters
theString The string to trim.
theResult The result string.
Returns
A reference to theResult.
WideStringToDouble()
xalanc::WideStringToDouble (const XalanDOMChar * theString, MemoryManager & theMemoryManager)
Converts a wide string into a double value.
Parameters
theString target string
theMemoryManager The MemoryManager instance to use.
Returns
double value of target string
Referenced by DOMStringToDouble().
WideStringToInt()
xalanc::WideStringToInt (const XalanDOMChar * theString)
Converts a wide string into an integer value.
Parameters
theString target string
Returns
integer value of target string
Referenced by DOMStringToInt().
WideStringToLong()
xalanc::WideStringToLong (const XalanDOMChar * theString)
Converts a wide string into a long value.
Parameters
theString target string
Returns
long value of target string
Referenced by DOMStringToLong().
WideStringToUnsignedLong()
xalanc::WideStringToUnsignedLong (const XalanDOMChar * theString)
Converts a wide string into an unsigned long value.
Parameters
theString target string
Returns
unsigned long value of target string
Referenced by DOMStringToUnsignedLong().
XalanConstruct() [1/9]
template<class Type > Type* xalanc::XalanConstruct (MemoryManager & theMemoryManager, Type *& theInstance)
Definition at line 200 of file XalanMemoryManagement.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
Referenced by xalanc::XalanNumberFormat::create(), xalanc::ArenaBlock< data_type >::create(), xalanc::AttributeVectorEntry::create(), xalanc::AttributeVectorEntryExtended::create(), and xalanc::ReusableArenaBlock< data_type >::create().
XalanConstruct() [2/9]
template<class Type , class Param1Type > Type* xalanc::XalanConstruct (MemoryManager & theMemoryManager, Type *& theInstance, const Param1Type & theParam1)
Definition at line 222 of file XalanMemoryManagement.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
XalanConstruct() [3/9]
template<class Type , class Param1Type , class Param2Type , class Param3Type , class Param4Type , class Param5Type , class Param6Type > Type* xalanc::XalanConstruct (MemoryManager & theMemoryManager, Type *& theInstance, const Param1Type * theParam1, const Param2Type * theParam2, const Param3Type * theParam3, const Param4Type * theParam4, const Param5Type * theParam5, Param6Type & theParam6)
Definition at line 327 of file XalanMemoryManagement.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
XalanConstruct() [4/9]
template<class Type , class Param1Type , class Param2Type , class Param3Type , class Param4Type > Type* xalanc::XalanConstruct (MemoryManager & theMemoryManager, Type *& theInstance, const Param1Type * theParam1, const Param2Type * theParam2, const Param3Type * theParam3, Param4Type & theParam4)
Definition at line 296 of file XalanMemoryManagement.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
XalanConstruct() [5/9]
template<class Type , class Param1Type > Type* xalanc::XalanConstruct (MemoryManager & theMemoryManager, Type *& theInstance, Param1Type & theParam1)
Definition at line 245 of file XalanMemoryManagement.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
XalanConstruct() [6/9]
template<class Type , class Param1Type , class Param2Type > Type* xalanc::XalanConstruct (MemoryManager & theMemoryManager, Type *& theInstance, Param1Type & theParam1, const Param2Type & theParam2)
Definition at line 269 of file XalanMemoryManagement.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
XalanConstruct() [7/9]
template<class Type , class Param1Type , class Param2Type , class Param3Type > Type* xalanc::XalanConstruct (MemoryManager & theMemoryManager, Type *& theInstance, Param1Type & theParam1, const Param2Type & theParam2, Param3Type & theParam3)
Definition at line 363 of file XalanMemoryManagement.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
XalanConstruct() [8/9]
template<class Type , class Param1Type , class Param2Type , class Param3Type , class Param4Type , class Param5Type > Type* xalanc::XalanConstruct (MemoryManager & theMemoryManager, Type *& theInstance, Param1Type & theParam1, Param2Type & theParam2, const Param3Type & theParam3, const Param4Type & theParam4, const Param5Type & theParam5)
Definition at line 392 of file XalanMemoryManagement.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
XalanConstruct() [9/9]
template<class Type , class Param1Type , class Param2Type , class Param3Type , class Param4Type , class Param5Type , class Param6Type > Type* xalanc::XalanConstruct (MemoryManager & theMemoryManager, Type *& theInstance, Param1Type & theParam1, Param2Type & theParam2, const Param3Type & theParam3, const Param4Type & theParam4, const Param5Type & theParam5, const Param6Type & theParam6)
Definition at line 424 of file XalanMemoryManagement.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
XalanCopy()
template<class InputIteratorType , class OutputIteratorType > OutputIteratorType xalanc::XalanCopy (InputIteratorType begin, InputIteratorType end, OutputIteratorType iterator) inline
Definition at line 66 of file DOMStringHelper.hpp.
XalanCopyConstruct() [1/2]
template<class Type > Type* xalanc::XalanCopyConstruct (MemoryManager & theMemoryManager, const Type & theSource)
Definition at line 450 of file XalanMemoryManagement.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
Referenced by xalanc::XalanEXSLTFunctionNodeSet::clone(), xalanc::XalanEXSLTFunctionDifference::clone(), xalanc::XalanEXSLTFunctionDateTime::clone(), xalanc::XalanEXSLTFunctionAbs::clone(), xalanc::XalanEXSLTFunctionAlign::clone(), xalanc::XalanEXSLTFunctionEvaluate::clone(), xalanc::XalanEXSLTFunctionDistinct::clone(), xalanc::XalanEXSLTFunctionRandom::clone(), xalanc::XalanEXSLTFunctionConcat::clone(), xalanc::XalanEXSLTFunctionHasSameNode::clone(), xalanc::XalanEXSLTFunctionAcos::clone(), xalanc::XalanEXSLTFunctionPadding::clone(), xalanc::XalanEXSLTFunctionIntersection::clone(), xalanc::XalanEXSLTFunctionAsin::clone(), xalanc::XalanEXSLTFunctionLeading::clone(), xalanc::XalanEXSLTFunctionAtan::clone(), xalanc::XalanEXSLTFunctionEncodeURI::clone(), xalanc::XalanEXSLTFunctionAtan2::clone(), xalanc::XalanEXSLTFunctionTrailing::clone(), xalanc::XalanEXSLTFunctionDecodeURI::clone(), xalanc::XalanEXSLTFunctionConstant::clone(), xalanc::XalanEXSLTFunctionCos::clone(), xalanc::XalanEXSLTFunctionExp::clone(), xalanc::XalanEXSLTFunctionHighest::clone(), xalanc::XalanEXSLTFunctionLog::clone(), xalanc::XalanEXSLTFunctionLowest::clone(), xalanc::XalanEXSLTFunctionMax::clone(), xalanc::XalanEXSLTFunctionMin::clone(), xalanc::XalanEXSLTFunctionPower::clone(), xalanc::XalanEXSLTFunctionSin::clone(), xalanc::XalanEXSLTFunctionSqrt::clone(), and xalanc::XalanEXSLTFunctionTan::clone().
XalanCopyConstruct() [2/2]
template<class Type , class Param1Type > Type* xalanc::XalanCopyConstruct (MemoryManager & theMemoryManager, const Type & theSource, Param1Type & theParam1)
Definition at line 472 of file XalanMemoryManagement.hpp.
References xalanc::XalanAllocationGuard::get(), and xalanc::XalanAllocationGuard::release().
XalanDestroy() [1/4]
template<class Type > void xalanc::XalanDestroy (MemoryManager & theMemoryManager, Type & theArg)
Definition at line 187 of file XalanMemoryManagement.hpp.
Referenced by XalanDestroy().
XalanDestroy() [2/4]
template<class Type > void xalanc::XalanDestroy (MemoryManager & theMemoryManager, Type * theArg)
Definition at line 171 of file XalanMemoryManagement.hpp.
References XalanDestroy().
XalanDestroy() [3/4]
template<class Type > void xalanc::XalanDestroy (Type & theArg)
Definition at line 150 of file XalanMemoryManagement.hpp.
Referenced by xalanc::ReusableArenaBlock< data_type >::destroyObject(), xalanc::XalanMessageLoader::XalanMessageLoaderDestructFunct::operator()(), xalanc::DecimalFormatCacheStruct::DecimalFormatDeleteFunctor::operator()(), and xalanc::ArenaBlock< data_type >::~ArenaBlock().
XalanDestroy() [4/4]
template<class Type > void xalanc::XalanDestroy (Type * theArg)
Definition at line 159 of file XalanMemoryManagement.hpp.
XalanScalarHash()
template<class ScalarType > size_t xalanc::XalanScalarHash (ScalarType theValue, size_t theResult) inline
Definition at line 272 of file STLHelper.hpp.
Referenced by xalanc::hash_non_terminated_array< T >::operator()(), and xalanc::hash_null_terminated_array< T >::operator()().
XalanTransform()
template<class InputIteratorType , class OutputIteratorType , class UnaryFunction > OutputIteratorType xalanc::XalanTransform (InputIteratorType begin, InputIteratorType end, OutputIteratorType iterator, UnaryFunction function) inline
Definition at line 78 of file DOMStringHelper.hpp.