Xalan-C++ API Reference: xalanc::XalanListIteratorBase< XalanListTraits, Node > Struct Template Reference
xalanc::XalanListIteratorBase< XalanListTraits, Node > Struct Template Reference
#include <xalanc/Include/XalanList.hpp>
Public Types
typedef XalanListTraits::value_type value_type
typedef XalanListTraits::reference reference
typedef XalanListTraits::pointer pointer
typedef ptrdiff_t difference_type
typedef std::bidirectional_iterator_tag iterator_category
typedef XalanListIteratorBase< XalanListIteratorTraits< value_type >, Node > iterator
Public Member Functions
XalanListIteratorBase (Node &node)
XalanListIteratorBase (const iterator &theRhs)
XalanListIteratorBase operator++ ()
XalanListIteratorBase operator++ (int)
XalanListIteratorBase operator-- ()
XalanListIteratorBase operator- (difference_type decrement) const
reference operator* () const
pointer operator-> () const
const XalanListIteratorBase & operator= (const XalanListIteratorBase &theRhs)
bool operator!= (const XalanListIteratorBase &theRhs) const
bool operator== (const XalanListIteratorBase &theRhs) const
Node & node ()
Public Attributes
Node * currentNode
Detailed Description
template<class XalanListTraits, class Node>
struct xalanc::XalanListIteratorBase< XalanListTraits, Node >
Definition at line 63 of file XalanList.hpp.
Member Typedef Documentation
difference_type
template<class XalanListTraits , class Node > typedef ptrdiff_t xalanc::XalanListIteratorBase< XalanListTraits, Node >::difference_type
Definition at line 69 of file XalanList.hpp.
iterator
template<class XalanListTraits , class Node > typedef XalanListIteratorBase<XalanListIteratorTraits<value_type>, Node> xalanc::XalanListIteratorBase< XalanListTraits, Node >::iterator
Definition at line 73 of file XalanList.hpp.
iterator_category
template<class XalanListTraits , class Node > typedef std::bidirectional_iterator_tag xalanc::XalanListIteratorBase< XalanListTraits, Node >::iterator_category
Definition at line 71 of file XalanList.hpp.
pointer
template<class XalanListTraits , class Node > typedef XalanListTraits::pointer xalanc::XalanListIteratorBase< XalanListTraits, Node >::pointer
Definition at line 67 of file XalanList.hpp.
reference
template<class XalanListTraits , class Node > typedef XalanListTraits::reference xalanc::XalanListIteratorBase< XalanListTraits, Node >::reference
Definition at line 66 of file XalanList.hpp.
value_type
template<class XalanListTraits , class Node > typedef XalanListTraits::value_type xalanc::XalanListIteratorBase< XalanListTraits, Node >::value_type
Definition at line 65 of file XalanList.hpp.
Constructor & Destructor Documentation
XalanListIteratorBase() [1/2]
template<class XalanListTraits , class Node > xalanc::XalanListIteratorBase< XalanListTraits, Node >::XalanListIteratorBase (Node & node) inline
Definition at line 75 of file XalanList.hpp.
XalanListIteratorBase() [2/2]
template<class XalanListTraits , class Node > xalanc::XalanListIteratorBase< XalanListTraits, Node >::XalanListIteratorBase (const iterator & theRhs) inline
Definition at line 80 of file XalanList.hpp.
Member Function Documentation
node()
template<class XalanListTraits , class Node > Node& xalanc::XalanListIteratorBase< XalanListTraits, Node >::node () inline
Definition at line 141 of file XalanList.hpp.
Referenced by xalanc::XalanList< ReusableArenaBlock< string_type > * >::constructNode(), xalanc::XalanList< ReusableArenaBlock< string_type > * >::erase(), and xalanc::XalanList< ReusableArenaBlock< string_type > * >::splice().
operator!=()
template<class XalanListTraits , class Node > bool xalanc::XalanListIteratorBase< XalanListTraits, Node >::operator!= (const XalanListIteratorBase< XalanListTraits, Node > & theRhs) const inline
Definition at line 131 of file XalanList.hpp.
References xalanc::operator==().
operator*()
template<class XalanListTraits , class Node > reference xalanc::XalanListIteratorBase< XalanListTraits, Node >::operator* () const inline
Definition at line 115 of file XalanList.hpp.
operator++() [1/2]
template<class XalanListTraits , class Node > XalanListIteratorBase xalanc::XalanListIteratorBase< XalanListTraits, Node >::operator++ () inline
Definition at line 85 of file XalanList.hpp.
operator++() [2/2]
template<class XalanListTraits , class Node > XalanListIteratorBase xalanc::XalanListIteratorBase< XalanListTraits, Node >::operator++ (int) inline
Definition at line 91 of file XalanList.hpp.
operator-()
template<class XalanListTraits , class Node > XalanListIteratorBase xalanc::XalanListIteratorBase< XalanListTraits, Node >::operator- (difference_type decrement) const inline
Definition at line 104 of file XalanList.hpp.
operator--()
template<class XalanListTraits , class Node > XalanListIteratorBase xalanc::XalanListIteratorBase< XalanListTraits, Node >::operator-- () inline
Definition at line 98 of file XalanList.hpp.
operator->()
template<class XalanListTraits , class Node > pointer xalanc::XalanListIteratorBase< XalanListTraits, Node >::operator-> () const inline
Definition at line 120 of file XalanList.hpp.
operator=()
template<class XalanListTraits , class Node > const XalanListIteratorBase& xalanc::XalanListIteratorBase< XalanListTraits, Node >::operator= (const XalanListIteratorBase< XalanListTraits, Node > & theRhs) inline
Definition at line 125 of file XalanList.hpp.
References xalanc::XalanListIteratorBase< XalanListTraits, Node >::currentNode.
operator==()
template<class XalanListTraits , class Node > bool xalanc::XalanListIteratorBase< XalanListTraits, Node >::operator== (const XalanListIteratorBase< XalanListTraits, Node > & theRhs) const inline
Definition at line 136 of file XalanList.hpp.
References xalanc::XalanListIteratorBase< XalanListTraits, Node >::currentNode.
Member Data Documentation
currentNode
template<class XalanListTraits , class Node > Node* xalanc::XalanListIteratorBase< XalanListTraits, Node >::currentNode
Definition at line 146 of file XalanList.hpp.
Referenced by xalanc::XalanListIteratorBase< XalanListTraits, Node >::operator=(), and xalanc::XalanListIteratorBase< XalanListTraits, Node >::operator==().
The documentation for this struct was generated from the following file:
xalanc/Include/XalanList.hpp